### ISSUE TITLE
Encoding API in c++ is missing points

### ISSUE THREAD

**Issue by jorajipo** [google/draco#1005]
I am doing a test taking the tests as reference, but when I use a pointcloud with more than 10 million points the pointcloud object is missing points, for example, ifg I use 20 million points it only takes about 18 million.

Here is my code:

#include <fstream>
#include <vector>

#include "draco/compression/encode.h"
#include "draco/compression/decode.h"
#include "draco/point_cloud/point_cloud.h"
#include "draco/io/point_cloud_io.h" //to encode to buffer
#include "draco/point_cloud/point_cloud_builder.h"
#include "draco/compression/expert_encode.h"

int main(int argc, char** argv) {
    
    //Create Point Cloud
    draco::PointCloudBuilder pc_builder;
    
    constexpr auto kNumPoints = 20000000;
    pc_builder.Start(kNumPoints);
    
    // Add position attribute.
    const int32_t pos_att_id = pc_builder.AddAttribute(
                                                       draco::GeometryAttribute::POSITION, 3, draco::DT_UINT32);
    const int32_t color_att_id = pc_builder.AddAttribute(
                                                       draco::GeometryAttribute::COLOR, 3, draco::DT_UINT8);
    
    
    // Initialize the attribute values.
    for (draco::PointIndex i(0); i < kNumPoints; ++i) {
        int32_t pos_coord = static_cast<int32_t>(i.value());
        pc_builder.SetAttributeValueForPoint(
                                             pos_att_id, i,
                                             draco::Vector3f(pos_coord, -pos_coord, pos_coord).data());
        pc_builder.SetAttributeValueForPoint(
                                             color_att_id, i, draco::Vector3f(0, 0, 0).data());
        std::cout << i << "\n";
    }
    
    std::unique_ptr<draco::PointCloud> geometry = pc_builder.Finalize(true);
    
    std::cout << "Number of points in the cloud: " << geometry->num_points();

    
    // Sequential encoding allows to use unquantized attributes in the decoder.
    /* Quantization converts floating point attributes into integer attributes (lossy operation) that are then compressed without loss.
     If integer attributes are provided, Draco treats them as pre-quantized.
   */
    
    int32_t encoding_method = draco::POINT_CLOUD_KD_TREE_ENCODING;
    
    draco::Encoder encoder;
    
    encoder.SetAttributeQuantization(draco::GeometryAttribute::POSITION, 8);
    
    encoder.SetEncodingMethod(encoding_method);
    
    encoder.SetTrackEncodedProperties(true);
    encoder.SetSpeedOptions(4,4); // speed 0 gets best compression, speed 10 is fastest
    
    draco::EncoderBuffer buffer;
    draco::Status status = encoder.EncodePointCloudToBuffer(*geometry, &buffer);
    
    if (status.ok()) {
        std::cout <<" - Encoded points: "<< encoder.num_encoded_points();
    } else {
        std::cout << "Error coding the point cloud.";
    }
    
    std::cout << " buffer.data " << buffer.data() << "buffer.size" << buffer.size();
    
    //Save Encoder Buffer in file
    std::string output_file_path = "compressed.drc";
    std::ofstream outfile(output_file_path, std::ofstream::binary);
    outfile.write(buffer.data(), buffer.size());
    outfile.close();
    std::cout << "Buffer saved in file: " << output_file_path << std::endl;
    
    
    // Create a DecoderBuffer and copy coded data
    draco::DecoderBuffer decoder_buffer;
    decoder_buffer.Init(buffer.data(), buffer.size());
    
    
    // Create a PointCloud for the decoded data
    std::unique_ptr<draco::PointCloud> dec_point_cloud;
    
    
    // Decode the data from DecoderBuffer to point_cloud
    draco::Decoder decoder;
    
    // Make sure we skip dequantization for the position attribute.
   // decoder.SetSkipAttributeTransform(draco::GeometryAttribute::POSITION);
    
    // Decode the input data into a geometry.
    dec_point_cloud = decoder.DecodePointCloudFromBuffer(&decoder_buffer).value();
    
    // Save the decoded pointcloud in a file
    std::string decoded_file_path = "decompressed.ply";
    std::ofstream output_file(decoded_file_path, std::ios::binary);
    if (!output_file) {
        std::cerr << "Could not open outfput file: " << decoded_file_path <<
        std::endl;
        return 1;
    }
    
    const draco::EncoderOptions options = draco::EncoderOptions::CreateDefaultOptions();
    

    if (!draco::WritePointCloudIntoStream(dec_point_cloud.get(), output_file,
                                          draco::POINT_CLOUD_SEQUENTIAL_ENCODING,options)) {
        
        std::cerr << "Could not save the decoded poitcloud in file:"<< decoded_file_path << std::endl;
        
    }
    
    std::cout << " points in the decoded cloud: " << dec_point_cloud->num_points();
    
    std::cout << "Decoded pointcloud saved in file: " <<
    decoded_file_path << std::endl;
    
    
    
    
    
    return 0;
    
}

**Comment by ondys** [comment]
one issue seems to be that the position attribute is created as with `DT_UINT32` type but when initialized the values are passed in as `Vector3f` including negative values. I would try to fix that first and see if the problem goes away. Most likely cause is internal deduplication of values in the `PointCloudBuilder`
