### ISSUE TITLE
ReadFileToBuffer not reading the file

### ISSUE THREAD

**Issue by jorajipo** [google/draco#1006]
I am doing an example, I take the test as reference but it could not read any file, here is my code:

#include <stdio.h>
#include <fstream>
#include <vector>

#include "draco/point_cloud/point_cloud.h"
#include "draco/io/point_cloud_io.h" //to encode to buffer
#include "draco/io/file_utils.h" //to read from stream

#include "draco/point_cloud/point_cloud.h"
#include "draco/io/point_cloud_io.h"

#include "draco/compression/decode.h"

#include <cinttypes>
#include <sstream>

#include "draco/compression/encode.h"

int main(int argc, char** argv) {
    
    const std::string file_name = argv[1];
    

    
    
    

    std::vector<char> data;
    draco::ReadFileToBuffer(file_name, &data);
    
    std::cout << "Leidos " << data.size() << " bytes del archivo: " << file_name << "\n";
    if(data.empty()){
     std::cerr << "could not read";
    }
    return 0;
}

**Comment by ondys** [comment]
Not sure what the issue is, but the code looks ok. Probably incorrect file path?
