### ISSUE TITLE
Potential GPU decoding?

### ISSUE THREAD

**Issue by s1ddok** [google/draco#1019]
I would love to know if decoding of point cloud from .drc is potentially possible to implement on GPU? i.e. is the algorithm is very sequential or it can be parallelized in a meaningful way? I'm interested in reducing bandwidth between CPU and GPU, so decoding directly on GPU would be a much preferred option

**Comment by ondys** [comment]
The algorithm wasn't really designed for GPUs. It is indeed very sequential and the performance would probably not be optimal.
