### ISSUE TITLE
FR: Add more granular "encoder.SetAttributeQuantization()" API for GeometryAttribute::GENERIC attributes

### ISSUE THREAD

**Issue by sessamekesh** [google/draco#1024]
I'd love to be able to set quantization per-attribute for generic attributes, **especially skeletal animation parameters bone_idx and bone_weight.**

## Background

I currently use a handful of custom `GeometryAttribute::GENERIC` attributes, and have been happy enough to use default quantization settings for all of them - compression rate is not a major pain point for me.

Some of my models get quite large though, even with Draco compression, and I'd love the ability to tweak the quantization level for custom properties.

## Proposal 1: Add an `Encoder::SetIndividualAttributeQuantization(GeometryAttribute::Type, int attribute_idx, int quantization_bits)` method

The three most common `GENERIC` attributes I use:
* Vertex bone index array (Uint8x4)
* Vertex bone weight array (Float32x4)
* TBN basis orientation (Float32x4 - quaternion) (in lieu of normal/tangent/bitangent)

A cursory internet search suggests that my use cases of vertex tangents and skeleton bindings are both pretty common use cases for `GeometryAttribute::GENERIC`.

I favor this approach, since it fits the common use cases and is extensible to uncommon ones as well.

## Proposal 2: Add `BONE_INDEX` and `BONE_WEIGHT` attribute types

Skeletal animation for 3D assets is a common enough use case to justify a special distinction. There isn't a lot of insanely fancy compression to be had here, but BONE_INDEX data can usually fit in 4-6 bits, and I suspect BONE_WEIGHT data can be fairly aggressively quantized as it's often a normal 4D vector.

**Comment by sessamekesh** [comment]
I'm also happy to make a PR for these, with just a touch of guidance from the Draco team 🙂

**Comment by ondys** [comment]
There is a more granular API already. See `ExpertEncoder` where you can set quantization setting for a specific attribute index (not attribute type). That should be sufficient for your requirments.
