### ISSUE TITLE
Add cmake option to enable/disable installation

### ISSUE THREAD

**Issue by ptc-tgamper** [google/draco#1029]
We pull Draco into our Cmake based project by using Cmake's FetchContent(), which more or less adds the Draco checkout directory to our project via add_subdirectory(). That in turn causes Draco's install rules to be added. Which we prefer not to happen, as we only use Draco as a dependency, but don't want it to be installes along our targets. So, in step with other Cmake based projects, simply add a Cmake option, like DRACO_INSTALL, to enable/disable Draco's install rules.

I'll post a PR shortly.

**Comment by vrabaud** [comment]
Maybe it is too intrusive and unconventional to add such an option?
If you use CMake 3.28, you should use EXCLUDE_FROM_ALL, cf https://cmake.org/cmake/help/v3.28/module/FetchContent.html#command:fetchcontent_declare
Otherwise, I see you can have a custom solution here: https://stackoverflow.com/questions/65527126/disable-install-for-fetchcontent

**Comment by ptc-tgamper** [comment]
It's not only about FetchContent. There are other ways I can do something akin to add_subdirectory(draco). Moreover, we are already doing EXCLUDE_FROM_ALL by default for everything. The latter is only about not adding the install rules to the ALL target. They are still added to the draco target itself, and any target that depends on draco will invoke them as part of its own installation.
I came up with this simple solution because I have seen it in plenty other projects, e.g. https://github.com/CLIUtils/CLI11, https://github.com/glfw/glfw, https://github.com/syoyo/tinygltf, https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator
Having this simple option gives control, one can force the desired behaviour, without having to rely on other cmake shenanigans :)
