### ISSUE TITLE
Tests fail on 32 bit systems

### ISSUE THREAD

**Issue by stoecker** [google/draco#1036]
[----------] 1 test from StlEncoderTest
[  111s] [ RUN      ] StlEncoderTest.TestStlEncoding
[  111s] /home/abuild/rpmbuild/BUILD/draco-1.5.6/src/draco/io/stl_encoder_test.cc:35: Failure
[  111s] Expected equality of these values:
[  111s]   mesh0->attribute(att_id)->size()
[  111s]     Which is: 69451
[  111s]   mesh1->attribute(att_id)->size()
[  111s]     Which is: 69442
[  111s] [  FAILED  ] StlEncoderTest.TestStlEncoding (187 ms)

See e.g. https://build.opensuse.org/package/live_build_log/graphics/draco/openSUSE_Tumbleweed/i586

**Comment by ondys** [comment]
This should be fixed in the latest release.
