### ISSUE TITLE
Severity Code Description The project file line does not display status  Error C2440 "Initialize" : Unable to transfer from "void *" to "tinygltf: : GetFileSizeFunction draco_decoder F: \ resource \ Draco - 1.5.6 \ SRC \ Draco \ IO \ gltf_decoder.cc     489 

### ISSUE THREAD

**Issue by sui0312feng** [google/draco#1051]
Severity Code Description The project file line does not display status

Error C2440 "Initialize" : Unable to transfer from "void *" to "tinygltf: : GetFileSizeFunction draco_decoder F: \ resource \ Draco - 1.5.6 \ SRC \ Draco \ IO \ gltf_decoder.cc     489

**Comment by sui0312feng** [comment]
> Severity Code Description The project file line does not display status
> 
> Error C2440 "Initialize" : Unable to transfer from "void *" to "tinygltf: : GetFileSizeFunction draco_decoder F: \ resource \ Draco - 1.5.6 \ SRC \ Draco \ IO \ gltf_decoder.cc 489

I had an error compiling with vs2019

**Comment by ondys** [comment]
I believe you are using a newer version of TinyGLTF compared to the version that is supported by Draco. 
To get the supported version, you should run the following command in your Draco git repository:
```
git submodule update --init
```
