### ISSUE TITLE
Optimizing 3D data with Draco Geometry Compression

### ISSUE THREAD

**Issue by Zhouwudexiazhou** [google/draco#1053]
I followed this example-Optimizing 3D data with Draco Geometry Compression.But step six -Render a Darco file with three.js can't work.I set up a python -m http.server and turn into it.But it can't dispaly the rendered file by buuny.drc.Where is the problem?
![1](https://github.com/google/draco/assets/141386661/3ade4cd9-c660-47b6-a524-e8b3e43d49fd)

**Comment by ondys** [comment]
The codelab has been updated to support latest three.js.
