### ISSUE TITLE
A problem about pointcloudsequentialencoder 

### ISSUE THREAD

**Issue by Rouen007** [google/draco#1056]
When I look up the comment in the point_cloud_sequential_encoder.h file, I found the following sentences: 
// This encoder preserves the order and the number of input points, but the
// mapping between point ids and attribute values may be different for the
// decoded point cloud.

And I am confused that the order of the input points does not change, **why the mapping may different in decoded point cloud**?  In my opinion, the mapping remain the initial state is all right.

**Comment by ondys** [comment]
The encoder encodes all points sequentially. It does not encode mapping from points to attribute values though. So basically for each point it encodes the values directly. The decoded point cloud will then have identity mapping between point indices and attribute value indices (at least before deduplication takes place).

A more specific example, imagine point cloud with a single attribute and 4 points that are mapped to attribute values `[2, 0, 1, 1]` (so three unique attribute values). Without deduplication, the decoded point cloud will have 4 points where the points are mapped to attribute values as: `[0, 1, 2, 3]`. The order of the points will be the same but the decoded values will be in a different order (decoded to encoded mapping will be: `(0->2, 1->0, 2->1, 3->1)`).
