### ISSUE TITLE
ReadMeshFromFile assumes file name has at least 4 characters

### ISSUE THREAD

**Issue by jwakely** [google/draco#108]
$ ./draco_encoder -i ab
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551614) > this->size() (which is 2)
Aborted (core dumped)

````
std::unique_ptr<Mesh> ReadMeshFromFile(const std::string &file_name) {
  std::unique_ptr<Mesh> mesh(new Mesh());
  // Analyze file extension.
  const std::string extension =
      parser::ToLower(file_name.substr(file_name.size() - 4));
````

**Comment by pps83** [comment]
Because they do this:
```
  const std::string extension =
      parser::ToLower(file_name.substr(file_name.size() - 4));
```
which is complete WTF. It's been months and nobody even cared to check this issue report I guess.
