### ISSUE TITLE
support mtl  file?

### ISSUE THREAD

**Issue by neuhawk** [google/draco#110]
like  test.mtl

newmtl _____46_____________________Mes
Ka 0.662745 0.662745 0.662745
Kd 0.411765 0.596078 0.486275
Ks 0.411765 0.596078 0.596078
illum 2
Ns 362.039
map_Kd 
map_bump 
bump 
map_opacity 
map_d 
refl 
map_kS 
map_kA 
map_Ns 

newmtl _______Mesh_1material
Ka 0.662745 0.662745 0.662745
Kd 1 0.282353 0
Ks 1 0.282353 0.282353
illum 2
Ns 362.039
d 0.501961
map_Kd 
map_bump 
bump 
map_opacity 
map_d 
refl 
map_kS 
map_kA 
map_Ns 

newmtl _____46_______________________M
Ka 0.662745 0.662745 0.662745
Kd 0.921569 0.921569 0.921569
Ks 0 0 0
illum 2
Ns 362.039
map_Kd 
map_bump 
bump 
map_opacity 
map_d 
refl 
map_kS 
map_kA

**Comment by ondys** [comment]
We plan to add support for generic metadata in one of our upcoming versions. This will allow users to store custom data, such as the material file, directly in the .drc file. For now the material file needs to be send and parsed separately from Draco file.

**Comment by neuhawk** [comment]
thanks.

**Comment by JiaxiangZheng** [comment]
Hi @ondys, maybe we can convert the these material info to glTF data and leave draco encode result as the bin part of glTF? I think this is more general, and draco can focus on compressing the geometry info only.

**Comment by lst61924** [comment]
@ondys  support mtl file now?

**Comment by ondys** [comment]
@lst61924 Draco now encodes material file name in metadata when decoding .obj files when `--metadata` flag is set in `draco_encoder`. The material file still needs to be parsed separately though.
