### ISSUE TITLE
why deduplicate in the end of DecodeInternal()

### ISSUE THREAD

**Issue by wanglongfromZJU** [google/draco#111]
when decode the obj file, why call the function out_point_cloud_->DeduplicateAttributeValues() and out_point_cloud_->DeduplicatePointIds() in the end of DecodeInternal()

**Comment by ondys** [comment]
We added it there because many obj files still contain duplicate positions and other attribute values (ideally this shouldn't happen as .obj file format is designed to avoid such duplicates, but in practice it's not the case). Deduplicating these values then helps compression
