### ISSUE TITLE
Windows 10 64-bit decode performance

### ISSUE THREAD

**Issue by avh** [google/draco#112]
I'm trying to use draco to encode/decode meshes in a stream.
Each frame is a simple mesh with XYZ and UV attributes.
There are about ~2000 faces and ~1000 vertices per frame
The decode performance on my MacBook Pro is ~2ms per mesh.
However, on my Windows X64 machine the decode performance is  ~25ms.

I was expecting the PC to be as fast or faster than the MacBook.
The slow performance  is causing the animation to drop frames.

I've tried setting speed options, but that seems to make very little difference. 
I've turned on code optimization and inlining, but that also had very little effect. 

Does anyone know what may be causing this performance bottleneck?

**Comment by avh** [comment]
To compare I decided to try o3dgc, and it is MUCH faster on windows.
I still puzzled why...

**Comment by ondys** [comment]
@avh We have logged the issue and we will investigate it. Thanks for the report!

**Comment by ondys** [comment]
@avh Unfortunately I was unable to reproduce this problem.Do you see the similar performance issues when you build the 32-bit version using CMake to generate visual studio project? (we don't support 64-bit build targets through that workflow yet). 

Can you post more details about your build environment/setup? Thanks

**Comment by avh** [comment]
Unfortunately I'm unable to try Win32 quickly (too many dependencies).
I was using cmake on a Razor Blade GTX 1060 with Windows 10.
cmake -G "Visual Studio 14 2015 Win64" ..
I'm statically linking the draco decoder into a DLL for a unity project.

**Comment by ondys** [comment]
My bad, I forgot about our 64-bit workflow for Win. Nevertheless I tried the 64-bit build with the same results. Can you send me the .drc file you are having problems with? Maybe it is file specific.

**Comment by ondys** [comment]
Just one more thing. Did you build the library with Release configuration? (default is Debug) I'm just asking to rule out all possibilities.

**Comment by shubhamagarwal003** [comment]
@avh Where you able to statically link the draco decoder for your Unity Project. I was trying to statically link draco encoder but was getting EntryPointNotFoundException. If you can help how you were able to use draco decoder in your Unity Project then it would be a great help. 
Thanks

**Comment by WeersProductions** [comment]
@ondys I have the exact same issue. I have the issue on both Windows x64 as UWP x86. Draco is really fast on Macbook Pro, Android and IOS though, using the same Draco file. 
The library is built with the Debug configuration and I am using commit: 02272a65c72673432a67815d7ba499e6954066ef  (version 1.3.0). 

The function `DecodeMeshFromBuffer` is the slow one.

I have tested this with multiple Draco files, there does not seem to be a performance difference between them.

Thanks!

**Comment by WeersProductions** [comment]
Solved the issue, building it in 'Release' configuration did the job. In 'Debug' configurations, the Vector run-time checks slow down the encoding and decoding a lot.
