### ISSUE TITLE
Mesh round-trip encode/decode produces artifacts

### ISSUE THREAD

**Issue by nyue** [google/draco#115]
Hi,

  I downloaded the Armadillo mesh from the [Stanford](https://graphics.stanford.edu/data/3Dscanrep/)

  I converted it to ASCII using MeshLab

  I encoded the Armadillo_ascii_ply file to Armadillo.drc using the draco_encoder

  I decoded the Armadillo.drc to Armadillo.obj using the draco_decoder

  When I viewed the Armadillo.obj file, I see strips of polygonal faces missing.

  The input files, output files and screen capture of my viewer are all [here](https://www.dropbox.com/sh/92ayhl1nabmurdx/AABU8tAkVSaHsBGG9uPLpx7Ua?dl=0)

Cheers

**Comment by ondys** [comment]
I'm having trouble reproducing the problem. I've used the attached .drc file and I decoded it to both .ply and to .obj and in both cases the output model looked ok (no visible artifacts).

When you decode the model and open it in MeshLab, does it show the same problem you see in your viewer?

**Comment by nyue** [comment]
Thank you @ondys , MeshLab is fine, the viewer I have seems to be the problem. Thank you for the suggestion.
