### ISSUE TITLE
Steps in creating a simple draco file ?

### ISSUE THREAD

**Issue by nyue** [google/draco#116]
Hi,

  I am trying to understand the API calls required to create a mesh in Draco.

  There is pointcloud and mesh.

  The ply and obj example are not easy to follow.

  Given

  // Tetrahedron
  float pts[4][3]; // positions;
  float normals[4][3]; //normals;
  int indices[4][3];

  How do I create a mesh ? Do I create a pointcloud separately from the mesh ? or do I create the mesh and add attributes ?

Cheers

**Comment by ondys** [comment]
There are essentially two ways to do it:

1. You can do this fairly easily using for example `TriangleSoupMeshBuilder` class ([link](https://github.com/google/draco/blob/master/mesh/triangle_soup_mesh_builder.h)). You just create one attribute for positions, one for normals and then add the attribute values directly for all four faces (you can find examples in the accompanied [test](https://github.com/google/draco/blob/master/mesh/triangle_soup_mesh_builder_test.cc)).

2. If can build it "directly" by creating attributes for positions and normals and adding faces to the mesh:

```
    std::unique_ptr<Mesh> mesh(new Mesh());
    mesh->set_num_points(num_vertices);   // 4 in your case
    // Create position and normal attributes.
    GeometryAttribute pa;
    va.Init(GeometryAttribute::POSITION, nullptr, 3, DT_FLOAT32, false, sizeof(float) * 3, 0);
    int32_t pos_att_id = mesh->AddAttribute(pa, true, num_vertices);

    GeometryAttribute na;
    na.Init(GeometryAttribute::NORMAL, nullptr, 3, DT_FLOAT32, false, sizeof(float) * 3, 0);
    int32_t norm_att_id = mesh->AddAttribute(na, true, num_vertices);

    // Set attribute values.
    for (int i = 0; i < num_vertices; ++i) {
      mesh->attribute(pos_att_id)->SetAttributeValue(AttributeValueIndex(i), pts[i]);
      mesh->attribute(norm_att_id)->SetAttributeValue(AttributeValueIndex(i), normals[i]);
    }

    // Add faces
   for (int i = 0; i < num_faces; ++i) {
     mesh->AddFace({{indices[i][0], indices[i][1], indices[i][2]});
   }
```

It would get slightly more complicated when attribute seams are present (e.g. when you have more than one normal vector on a single vertex). Let me know if this helped, I haven't actually tested the code above, so it may need some tweaking but the relevant API should be there.

**Comment by nyue** [comment]
Thank you.

Yes, I have to support attribute seams, one example being UVs

If attribute seams is a requirement, should I invest time learning the second approach ? or is there a different approach if attribute seams are a requirement ?

Cheers

**Comment by ondys** [comment]
> If attribute seams is a requirement, should I invest time learning the second approach ?

You can certainly use the second approach for attribute seams as well, that's what our file format loaders are doing.

The key thing to understand is that in Draco, geometry is represented by n-dimensional points that are mapped to attribute values. For example when you have a mesh with 3 position coordinates (x,y,z) and 2 texture coordinates (u,v), each point is essentially a 5 dimensional point that is mapped to a single position value and a single uv value. For meshes without attribute seams, each point is equivalent to a vertex, but when attribute seams are present, there may be more points on a single vertex (e.g. two points mapped to the same position value but with different normals). What this means is that in case of attribute seams, there may be more points mapped to the same attribute value and therefore we need to specify an explicit map between point indices and attribute value indices.

The simplest way how to initialize a mesh with attribute seams manually is to first define one virtual point for every corner of the mesh (3 corners per face) and then deduplicate the point indices (I'll just generalize the example I gave above):

```
    int32_t num_corners = num_faces * 3;
    std::unique_ptr<Mesh> mesh(new Mesh());
    mesh->set_num_points(num_corners);   // 4 in your case
    // Create position and normal attributes.
    GeometryAttribute pa;
    va.Init(GeometryAttribute::POSITION, nullptr, 3, DT_FLOAT32, false, sizeof(float) * 3, 0);

    // NOTICE the "false" arugment - indicating attribute needs explicit mapping
    int32_t pos_att_id = mesh->AddAttribute(pa, false, num_positions);

    GeometryAttribute na;
    na.Init(GeometryAttribute::NORMAL, nullptr, 3, DT_FLOAT32, false, sizeof(float) * 3, 0);
    int32_t norm_att_id = mesh->AddAttribute(na, false, num_normals);

    // Set attribute values.
    for (int i = 0; i < num_positions; ++i) {
      mesh->attribute(pos_att_id)->SetAttributeValue(AttributeValueIndex(i), pts[i]);
    }
    for (int i = 0; i < num_normals; ++i) {
      mesh->attribute(norm_att_id)->SetAttributeValue(AttributeValueIndex(i), normals[i]);
    }

    // Add faces
   for (int i = 0; i < num_faces; ++i) {
     // Create dummy face mapped to point indices equivalent to corner indices.
     Mesh::Face face;   
     for (int c = 0; c < 3; ++c)
        face[c] = 3 * i + c;
     mesh_->AddFace(face);
 
     // Map the dummy point indices to attribute values (assuming we have obj style indices for each corner)
     for (int c = 0; c < 3; ++c) {
        mesh->attribute(pos_att_id)->SetPointMapEntry(face[c], position_indices[i][c]);
        mesh->attribute(norm_att_id)->SetPointMapEntry(face[c], normal_indices[i][c]);
     }
   }
   // Deduplicate point indices
   mesh->DeduplicatePointIds();
```

the deduplication step ensures that all similar points are merged together (where similar means points that are mapped to the equivalent attribute values).
