### ISSUE TITLE
Draco loading failed in IOS 9 iphone

### ISSUE THREAD

**Issue by jungleowl** [google/draco#117]
Loading failed on IOS 9 and lower versions with safari and any other browsers such as chrome, firefox, etc. The mentioned IOS versions in fact supports webgl and can load non-draco-compressed models such as .obj and .ply and so on. Example can be found as below: https://storage.googleapis.com/demos.webmproject.org/draco/draco_loader_throw.html. 
Loading succeeded on IOS 10 and above. 

Android  phone can also load the website with android version higher than 5, lower versions haven't been tested due to absence of relevant devices.

Considering many iphone users are still using IOS 8&9 who fears to slow down the operation by the higher IOS version, it could be an issue when spreading the application with draco.

**Comment by ondys** [comment]
Thanks for the report, we will investigate it.

**Comment by hccampos** [comment]
Running into several similar issues as well, but haven't been able to identify the real cause of the problem. At the moment it looks like decompressing some larger models sometimes ends up using too much memory and causes the browser to crash/reload.

**Comment by jungleowl** [comment]
I think crash/reload problem might differ from this case. As my understanding, when the model is too large, the browser can decompress the model but fail to render it due to the size eats resources (we have encountered the same situation as well), yet the decompressing procedure works fine in the case. But in the case above, we observed that the browser seemed not even decompress the model, not mention to draw it.

**Comment by FrankGalligan** [comment]
So I agree with jungleowl that the crash/reload problem might be a different issue. So please file another issue with steps to reproduce.

The ios9 issue is that in our example code and our loader code we are using let and const, which are not supported on ios until 10. draco_decoder.js works fine on ios9.

We are going to do some more testing and discuss about changing the example and loader code. 

In the meantime if you want your code to work on ios9 just change all 'let' and 'const' to 'var' in your Javascript code.

**Comment by jungleowl** [comment]
Hi, Frank, the modification has been done on my side, workflow is just fine, thanks a lot! But honestly, I do feel the loading efficience is little bit slower than when the original one works on IOS 10. I assume we can look forward to the release of the new version which is expected to be optimized on this.
