### ISSUE TITLE
Store multiple meshes in one drc file.

### ISSUE THREAD

**Issue by scashews** [google/draco#118]
Is there any way to store multiple meshes in a DRC file, and retrieve them by ID? I have meshes for each of the characters of the alphabet, uppercase and lowercase, and don't want 52 DRC files to upload. I don't see an ID in the point cloud base clase, but maybe I'm missing something? Thanks,

**Comment by ondys** [comment]
Currently Draco can store only a single mesh per one .drc file. If you are using C++ api, you can theoretically create a generic attribute that would store the mesh id for every point and use it to separate the sub-meshes on the decoder.

Alternatively you should still be able to concatenate the 52 .drc files into a single file and split them on the decoder. E.g. something similar that three.js provided script for OpenCTM files (https://github.com/mrdoob/three.js/blob/6c7f000734f8579da37fb39e5c2e9e5e2dfb14f8/utils/converters/ctm/join_ctm.py)
