### ISSUE TITLE
How can I encode multiple UVs into a drc file?

### ISSUE THREAD

**Issue by pastelsky** [google/draco#119]
Say I'm trying to encode an object like this which has multiple different textures and uvs- 

<img width="406" alt="screen shot 2017-06-05 at 9 51 22 am" src="https://cloud.githubusercontent.com/assets/8946207/26770451/a2f6a5d2-49d4-11e7-8471-755b28393902.png">

When I try to convert my blender design to a OBJ, I don't think it's able to export all the uv maps since OBJ only supports  a single UV map. As  a result, I have only only one material applied throught this object (including the legs) when I try to use it in three js. 

Is there any way to overcome this limitation with the OBJ format (and hence drc) ? 
You can find the sample blender file, obj file and textures here - 
https://www.dropbox.com/s/g7cffam8guv0m16/LowPoly%20%283%29%203.zip?dl=0

**Comment by ondys** [comment]
Draco format can store any number of texture coordinate attributes, but to do you would have to use our C++ API, e.g., by writing an export plugin for Blender.

**Comment by pastelsky** [comment]
Thanks! My C++ is a little rusty. Could you point me to a starting point in draco's code that would interface with blender's python export API ?

Also I'd imagine this is a pretty common use case and it could be useful for others as well. Are there any plans to enable encoding of multiple uv models by supporting Blender / Maya / Sketchup files directly ?

**Comment by ondys** [comment]
I've actually posted some examples recently in this issue: https://github.com/google/draco/issues/116

Other good sources would be our loaders for .obj and .ply files that are located under `io/` subfolder in our repo.

I'm not really familiar with Blender exporters and their APIs so I can't provide any general advice but definitely feel free to ask specific questions if you encounter any problems.

As for us adding support for more file formats; it's definitely on our roadmap but I can't give you any specifics as to when is that going to happen or what formats are going to be supported first.

**Comment by pastelsky** [comment]
@ondys the easiest workround I could think of is to tweak blender's OBJ exporter to export multiple UV'S instead of just the active UV.

I got the exporter to export UV  data like -
```obj
vt0 1.666 2.888
vt0 ...  ....
....
vt1 2.566 4.667
vt1 ...  ...
....
vt2 3.777 5.555
vt2 ... ...
...
```
This is not a valid OBJ file, but the plan is to tweak draco's OBJ encoder to understand this intermediary format.

In the OBJ to DRC encoder, I see this function encodes UV attributes to draco's binary format. Could you help me figure out how I can change this encoder to recognise `vt0`,  `vt1` ... etc and encode those as multiple uv channels in the drc file?

**Comment by ondys** [comment]
@pastelsky To read your custom .obj file you would need to modify OBJ decoder (encoder is for outputing OBJ files from Draco).

Apart from adding `vt0` and `vt1`, you will also have to modify the face declaration to add one more index for the new texture coordinates , e.g.:
`f 1/1/1/1 2/2/2/2 3/3/3/3`

As for changes to the decoder, you can start by modifying function `ObjDecoder::ParseTexCoord()` to accept two different texture coordinates (don't forget to update `num_tex_coords_` separately for each UV set.

After that you can add one more texture coordinate attribute in `DecodeInternal()` function (see code:
```
 if (num_tex_coords_ > 0) {
    GeometryAttribute va;
    va.Init(GeometryAttribute::TEX_COORD, nullptr, 2, DT_FLOAT32, false,
            sizeof(float) * 2, 0);
    tex_att_id_ = out_point_cloud_->AddAttribute(va, false, num_tex_coords_);
  }
```

You will also need to modify function `ObjDecoder::ParseFace()` to properly parse uv indices for the new uv set and also change `ObjDecoder:MapPointToVertexIndices()` to include the new uv set.

I can provide more details as you progress with the implementation
