### ISSUE TITLE
any tech details of draco?

### ISSUE THREAD

**Issue by JiaxiangZheng** [google/draco#120]
Hi, I am wondering is there any tech details of the draco lib? 

The [OpenCTM](http://openctm.sourceforge.net/) also encode/decode the triangle meshes, what's the mainly difference about them?

**Comment by ondys** [comment]
@JiaxiangZheng We haven't published any official technical details about methods in Draco yet.

In general Draco provides significantly better compression compared to OpenCTM and faster encoding and decoding (especially for Javascript through WebAssembly). One advantage that OpenCTM currently has over Draco is smaller javascript decoder size which may be important for some applications (we are working on making our decoder smaller as well).

There are other more technical differences, such as Draco's support for geometry attributes of arbitrary types (e.g. native support for generic integer attributes or pre-quantized positions, etc...).

The latest external benchmark that I'm aware one is the one published by box.com here: https://developer.box.com/v2.0/blog/showdown-3d-model-compression-at-scale-draco-vs-open3dgc 

It's comparing Draco against O3DGC compression library. Note that it was using an older version of Draco and not the best compression level possible. The latest version with max compression level can result in about 10-15% better compression for Draco compared to the reported numbers.

With regards to OpenCTM, you can check some rough comparison of O3DGC with OpenCTM done by Khronos here: https://github.com/KhronosGroup/glTF/wiki/Open-3D-Graphics-Compression

**Comment by JiaxiangZheng** [comment]
Thanks for your reply, it really helps me 👍 . @ondys
