### ISSUE TITLE
How to support LOD?

### ISSUE THREAD

**Issue by JiaxiangZheng** [google/draco#121]
Hi, the draco lib does really good job in compressing the models, but I am wondering does it support  LOD mesh?  Since rendering the original detailed mesh all the time is a burden for browser.

Currently, one way I can think of is to combine the draco with pop-buffer, with draco to transfer the compressed raw mesh, and with pop-buffer to transfer the level info of faces. But after decoding the compressed data in frontend, does the vertice/face index info still corresponding to the original one?

**Comment by ondys** [comment]
@JiaxiangZheng In general, LODs are often represented by completely different meshes with distinct connectivity and vertex attributes. In such case you can simply encode each LOD separately as a different .drc file.

Saying that, we may add some more native support for LODs or even progressive meshes in future, but I don't have any more details to share at this time.
