### ISSUE TITLE
Add encoding methods to a command line tool

### ISSUE THREAD

**Issue by gldan** [google/draco#123]
.ply source------------------------------------------
ply
format ascii 1.0
comment VCGLIB generated
element vertex 22
property float x
property float y
property float z
end_header
-14.939299583435059 0 17.519500732421875
-14.939299583435059 0 -14.001399993896484
17.38520050048828 0 -14.001399993896484
17.38520050048828 0 17.519500732421875
-14.939299583435059 25.5802001953125 17.519500732421875
17.38520050048828 25.5802001953125 17.519500732421875
17.38520050048828 25.5802001953125 -14.001399993896484
-14.939299583435059 25.5802001953125 -14.001399993896484
0 -1 0
0 1 0
0 0 1
1 0 0
0 0 -1
-1 0 0
32.324501037597656 0 0
32.324501037597656 31.52090072631836 0
0 31.52090072631836 0
0 0 0
32.324501037597656 25.5802001953125 0
0 25.5802001953125 0
31.52090072631836 0 0
31.52090072631836 25.5802001953125 0
.ply source------------------------------------------end

cmd:
draco -i file.ply -o output.drc -point_cloud

code-------------------------------------------------
       const numPoints = outputGeometry.num_points() ;
       var numVertexCoordinates = numPoints * 3;
      const posAttId = wrapper.GetAttributeId(outputGeometry, dracoDecoder.POINT_CLOUD);
      const posAttribute = wrapper.GetAttribute(outputGeometry, posAttId);
      const posAttributeData = new dracoDecoder.DracoFloat32Array();
       wrapper.GetAttributeFloatForAllPoints( outputGeometry, posAttribute, posAttributeData);
       var points = new Float32Array(numVertexCoordinates);
       for (let i = 0; i < numVertexCoordinates; i ++ ) {
                points[i] = posAttributeData.GetValue(i);
        };
       console.log(points)
code-------------------------------------------------end
output：
17.38455581665039,25.580610275268555,17.518722534179688
32.324501037597656,31.521467208862305,0
32.324501037597656,25.580610275268555,0
31.521467208862305,25.580610275268555,0
17.38455581665039,25.580610275268555,-14.000772476196289
17.38455581665039,0,17.518722534179688
32.324501037597656,0,0
31.521467208862305,0,0
17.38455581665039,0,-14.000772476196289
1.00033700466156,0,0
-14.93994426727295,25.580610275268555,17.518722534179688
0,31.521467208862305,0
0,25.580610275268555,0
-14.93994426727295,25.580610275268555,-14.000772476196289
0,1.00033700466156,0
0,0,1.00033700466156
-14.93994426727295,0,17.518722534179688
0,0,0
0,0,-1.00033700466156
0,-1.00033700466156,0
-1.00033700466156,0,0
-14.93994426727295,0,-14.000772476196289

**Comment by ondys** [comment]
@gldan The default point cloud compression algorithm in Draco is not order preserving. You may try to encode the geometry with `-cl 0` flag which is currently the only order preserving method we have exposed in the `draco_encoder` tool. Unfortunately, looking at the code, it will also disable any prediction so the compression rate will most likely be quite bad.

If you are using C++ API for encoding you can force the compression to be order preserving by setting an option:
`SetEncodingMethod(options, POINT_CLOUD_SEQUENTIAL_ENCODING);`

(you would also need to set quantization manually if you go this route.

**Comment by edankwan** [comment]
Is it possible to expose more parameters like this one into the command-line tool?

**Comment by FrankGalligan** [comment]
Closing as this was done.

**Comment by sg2nq** [comment]
@FrankGalligan I don't see the ability to select encoding method in the CLI tool, could you link to the PR/Commit for when this was done?
