### ISSUE TITLE
How can I name a generic attribute ?

### ISSUE THREAD

**Issue by nyue** [google/draco#124]
Hi,

  I am attempting to store custom attributes (non-named) in Draco.

  GeometryAttribute::Init() does not have a parameter for naming the attribute.

  When I read back the *.drc file, how can I get back the original name of that custom/generic attribute ?

Cheers

**Comment by ondys** [comment]
@nyue The only way how to identify custom/generic attributes in the current version of Draco is to use custom ids (`GeometryAttribute::set_custom_id()`).

We are working on support for metadata in Draco that will allow you to specify the name or any other custom data for a given attribute.

**Comment by nyue** [comment]
Thank you for the heads up @ondys do you have a ETA on the the metadata support ? This will allow me to schedule my development plans or switch to other development in the mean time.

Cheers

**Comment by ondys** [comment]
@nyue We are targeting late July/August time frame. Obviously things can change so I can't promise anything.

**Comment by nyue** [comment]
I see a 1.0.0 release but was not able to determine from the release notes if metadata support is included ? Any update on that ?

**Comment by fanzhanggoogle** [comment]
Hi @nyue, I believe this issue is solved.
