### ISSUE TITLE
consider support material name?

### ISSUE THREAD

**Issue by JiaxiangZheng** [google/draco#125]
It seems when encoding the obj file to drc, the code will parse material and assign each vertex to a material id without storing the material file name. When decoding the drc, we are hard to restore the corresponding material name back because the mtl filename is missing.

Why not storing the material file name but store the material id for each vertex?

**Comment by ondys** [comment]
@JiaxiangZheng The current workflow for this case is to send the .mtl file separately and use the id to index the materials stored within the .mtl file (material ids correspond to the order of materials in the .mtl file).

For the next release, we plan to add support for metadata that is going to allow users to store more data within the .drc file, including, for example, the file name of the material file

**Comment by FrankGalligan** [comment]
duplicate of #364
