### ISSUE TITLE
why draco is faster and more efficient than others like Open3DGC ? 

### ISSUE THREAD

**Issue by fndysf** [google/draco#127]
Because draco uses new algorithms ? As far as I know, algorithms like edgebreaker have existed for a long time.

**Comment by ondys** [comment]
Geometry compression consists of many different blocks that all affect the final compression ratio and the performance such as predictors for geometry attributes or the entropy coder used for the actual compression. Draco uses a unique combination of novel algorithms combined with existing state of the art research to deliver a good balance between the compression ratio and the performance.

**Comment by fndysf** [comment]
@ondys  Thank you for your detailed reply.
