### ISSUE TITLE
what controls Lossless and lossy compression ?

### ISSUE THREAD

**Issue by fndysf** [google/draco#128]
mesh_edgebreaker is lossy compression ? mesh_sequential is lossless compression ？

**Comment by ondys** [comment]
mesh_edgebreaker and mesh_sequential are used to differentiate two different algorithms for connectivity compression. Edgebreaker based compression is lossy in the sense that it does not preserve order of vertices or faces while the sequential method is order preserving.

Both methods can be either lossy or lossless in terms of attribute value compression (lossy when the attributes are quantized, lossless when not).

**Comment by fndysf** [comment]
@ondys OK. Thank you. I understand it now.
