### ISSUE TITLE
What compression algorithm does mesh_sequential use ?

### ISSUE THREAD

**Issue by fndysf** [google/draco#132]
Does it also use edgebreaker algorithm ? the only difference is sequential preserves original order ?
Is it  compression level  that determines what compression algorithm to use ?
Is connectivity compression algorithm totally independent of pointAtrribute compression algorithm ?
what is the relationship among these four algorithms: mesh_sequential_ebcoder, mesh_edgebreaker_encoder, pointAttributeKdTreeEncoder and pointAttributeKdTreeEncoder ?

**Comment by ondys** [comment]
mesh_sequential encoding stores triplets of point indices for every face in the order they are defined in the provided draco::Mesh. The indices are delta coded + entropy coded for better compression but even then, the final compression ratio is usually much worse compared to the edgebreaker method.

In general connectivity compression is separate from the point attribute compression, but in our current implementation, the mesh sequential method doesn't use some of the more advanced algorithms for point attribute compression (such as parallelogram prediction, etc..). This may change in future if there is demand for it.

mesh_sequential_encoder  is for the order preserving connectivity encoding of meshes
mesh_edgebreaker_encoder is for connectivity encoding using the edgebreaker method
pointAttributeKdTreeEncoder  is a method for encoding attributes of point clouds using kD-tree method (not applicable to meshes in its current form).

**Comment by fndysf** [comment]
So after encoding connectivity, both mesh_edgebreaker and mesh_sequential use sequentialAttributeEncoder to encode PointAttributes ? That is, sequentialAttributeEncoder use vector<PointIndex> which is produced by connectivity compression algorithms ( mesh_edgebreaker and mesh_sequential ), to encode PointAttribute ?

**Comment by ondys** [comment]
@fndysf Yes they both use the same sequential attribute encoders. But as mentioned earlier, the main difference is that sequential encoding method currently doesn't use some more advanced prediction schemes such as parallelogram prediction (again as said before, this can be changed if there is demand).
