### ISSUE TITLE
Applying materials to encoded .obj

### ISSUE THREAD

**Issue by shubhamagarwal003** [google/draco#143]
From a similar issue https://github.com/google/draco/issues/52, I understand that mesh faces are encoded with material ids. But I don't understand how can I access these material ids and assign material parsed from .mtl file? Is there any function in draco_decoder.js to get this material ids?

**Comment by ondys** [comment]
The material ids are stored in a generic attribute. If you use our latest 1.0.0 release and encode the .obj with metadata (`--metadata` flag), you can get the material id generic attribute for example like this:
```
const mat_att_id = decoder.GetAttributeIdByName(mesh, "material");
const mat_att = decoder.GetAttribute(mesh, mat_att_id);
```

Note that if you have multiple material ids you have to split the decoded geometry into multiple meshes manually on the javascript decoder. The code to do that would be something similar as shown at this example (where you would replace `subObjId` with `matId`:

https://github.com/google/draco/issues/89#issuecomment-291056720
