### ISSUE TITLE
Macro expansion issue on Windows VS2015

### ISSUE THREAD

**Issue by nyue** [google/draco#149]
In the following example snippet from decode.cc, line 90-107

Visual Studio 2015 complains about the expansion of the macros
(1) DRACO_ASSIGN_OR_RETURN
(2) DRACO_RETURN_IF_ERROR

Anyone else encountering this error when building with VS 2015 ?

`
Status Decoder::DecodeBufferToGeometry(DecoderBuffer *in_buffer,
                                       PointCloud *out_geometry) {
#ifdef DRACO_POINT_CLOUD_COMPRESSION_SUPPORTED
  DecoderBuffer temp_buffer(*in_buffer);
  DracoHeader header;
  DRACO_RETURN_IF_ERROR(PointCloudDecoder::DecodeHeader(&temp_buffer, &header))
  if (header.encoder_type != POINT_CLOUD) {
    return Status(Status::ERROR, "Input is not a point cloud.");
  }
  DRACO_ASSIGN_OR_RETURN(std::unique_ptr<PointCloudDecoder> decoder,
                         CreatePointCloudDecoder(header.encoder_method))

  DRACO_RETURN_IF_ERROR(decoder->Decode(options_, in_buffer, out_geometry))
  return OkStatus();
#else
  return Status(Status::ERROR, "Unsupported geometry type.");
#endif
}
`

**Comment by ondys** [comment]
Thanks for the report. We will investigate it.

**Comment by ondys** [comment]
A fix for the issue has been submitted. Please let us know if you still experience any problems. Thanks!
