### ISSUE TITLE
Support for standard game-oriented triangle mesh data?

### ISSUE THREAD

**Issue by bhouston** [google/draco#15]
Very interesting.  I am a little active in this space.... and created a mesh compression format for https://Clara.io (which has different needs than a game engine).  Was thinking of creating a Three.JS specific mesh compression algorithm as described here: https://github.com/mrdoob/three.js/issues/8851

So the main parts of a game quality triangle mesh are:
- vertex positions
- optional vertex normals
- optional vertex colors (vec3) sets, either numbered or preferrably named.
- optional vertex uv (vec2) sets, either numbered or preferrably named.
- optional per face material ids or face groups.
- optional vertex skin weights (4 usually for games)
- optional vertex skin done indicies (4 usually for games)
- optional named blendshape/morph vertex positions (3 x float)
- optional named blendshape/morph vertex normals (3 x float)

What does this tool support?

**Comment by ondys** [comment]
Our library can support any per-vertex or per-face data so all of the listed are theoretically supported. Saying that, we currently don't have a loader for any file format that would provide all these attributes. We have direct support for positions, normals, colors, and uvs. Other attributes can be added with type draco::GeometryAttribute::GENERIC that can be further identified by providing a custom id.

The easiest way to build a mesh with these attributes would be through our [draco::TriangleSoupMeshBuilder](https://github.com/google/draco/blob/master/mesh/triangle_soup_mesh_builder.h) . It can be used for example like this:

```
TriangleSoupMeshBuilder mb;
mb.Start(num_faces);
const int pos_att_id = mb.AddAttribute(GeometryAttribute::POSITION, 3, DT_FLOAT32);

// Add a generic attribute (e.g., vertex skin weights).
const int vertex_skin_weights_att_id =  mb.AddAttribute(GeometryAttribute::GENERIC, 4, DT_FLOAT32);

// Add a per face material id.
const int material_att_id = mb.AddAttribute(GeometryAttribute::GENERIC, 1, DT_INT32);

for (int i = 0; i < num_faces; ++i) {
  const int vert_id_0 = mesh->Face(i).VertexId(0);
  const int vert_id_1 = mesh->Face(i).VertexId(1);
  const int vert_id_2 = mesh->Face(i).VertexId(2);
  mb.SetAttributeValuesForFace(pos_att_id, FaceIndex(i),
                               &vertex_data[vert_id_0].pos,
                               &vertex_data[vert_id_1].pos,
                               &vertex_data[vert_id_2].pos);

  // Set vertex skin weight.
  mb.SetAttributeValuesForFace(vertex_skin_weights_att_id, FaceIndex(i),
                               &vertex_data[vert_id_0].skin_weights,
                               &vertex_data[vert_id_1].skin_weights,
                               &vertex_data[vert_id_2].skin_weights);

  // Set material id.
  mb.SetPerFaceAttributeValueForFace(material_att_id, FaceIndex(i),
                                     &mesh->Face(i).material_id);
}

// Create a draco::Mesh from the builder.
std::unique_ptr<Mesh> mesh = mb.Finalize();
```

Also note that to efficiently compress such mesh, you will have to manually set quantization options for each added attribute, e.g.,:

```
EncoderOptions encoder_options;

Options *vertex_skin_weight_options = encoder_options.GetAttributeOptions(vertex_skin_weights_att_id);

// Set 10 bit precision for vertex skin weights.
SetAttributeQuantization(vertex_skin_weight_options, 10);

// ...
EncoderBuffer out_buffer;
EncodeMeshToBuffer(mesh, encoder_options, &out_buffer);
```

**Comment by FrankGalligan** [comment]
We just added [mesh/triangle_soup_mesh_builder_test.cc](https://github.com/google/draco/blob/master/mesh/triangle_soup_mesh_builder_test.cc) which shows basically what is written above.

**Comment by bhouston** [comment]
Does this support indexed triangles?  Does one get optimal compression via the triangle soup?  (I worry about the work triangle soup as it sounds like it doesn't infer an coherent connected surface from the triangles that often leads to good compression.)

**Comment by bhouston** [comment]
This is great that you can support the main game mesh data.  I could see this getting usage in the non-web games industry. :)

**Comment by bhouston** [comment]
> Does this support indexed triangles? 

I see the Mesh.h is different than the triangle soup builder.  so yes you have indexed triangles.

>  Does one get optimal compression via the triangle soup?

I notice the MeshAttributeElementType.  That makes sense and smart. :)
