### ISSUE TITLE
Failed loading the input mesh from MagicaVoxel baked PLY export

### ISSUE THREAD

**Issue by kfarr** [google/draco#16]
`./draco_encoder -i ../aframe-city-builder/assets/ply/alien_egg2.bake.ply -o ./alien_egg2_bake.drc`
returns
`Failed loading the input mesh.`

You can see some other examples of source files here:
`https://github.com/kfarr/aframe-city-builder/tree/master/assets/ply`

**Comment by ondys** [comment]
I've added support for "vertex_index" property field that is generated by MagicaVoxel. Till now we supported only the more common "vertex_indices" property name. Unfortunately, there is no proper standard for PLY files so both are acceptable.

**Comment by kfarr** [comment]
Confirmed, works, looks great!
