### ISSUE TITLE
Microsoft VS 2015 - Install error

### ISSUE THREAD

**Issue by nyue** [google/draco#160]
After successfully building draco, attempt to build the INSTALL target resulted in the follow series of errors
[I have pasted one sample here]

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "setlocal
F:\nyue\software\cmake\cmake-3.7.2-win64-x64\bin\cmake.exe -DBUILD_TYPE=Release -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	INSTALL	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	133

**Comment by francois-keith** [comment]
It's due to the fact that the file cmake/FindDraco.cmake is missing, thus the following install instruction crashes (on ubuntu systems as well) :
https://github.com/google/draco/blob/master/CMakeLists.txt#L833-L834
Remove it you should be fine.

**Comment by tomfinegan** [comment]
Thanks for reporting this-- the new file didn't get included in the snapshot that gets pushed out to github.

**Comment by tomfinegan** [comment]
This should be fixed now that FindDraco.cmake has been pushed.
