### ISSUE TITLE
maybe a bug ? : version 1.0.0 file not supported by draco_decoder.js

### ISSUE THREAD

**Issue by zhilinyue** [google/draco#161]
dracoDecoder.isVersionSupported('1.0.0')
false

I use latest code to build draco_encoder.exe, convert a obj file,but something goes wrong.

wasm decode is ok,but draco_decoder.js is blocked when running funtion DecodeBufferToMesh.

Is this a bug or?

**Comment by ondys** [comment]
Yes I believe there is a problem with isVersionSupported function. The decoder itself should work for 1.0.0 files though. I'll update the javascript decoder.

**Comment by ondys** [comment]
javascript decoder has been updated. Please re-open the issue if you still encounter the problem.
