### ISSUE TITLE
Unittests failing

### ISSUE THREAD

**Issue by nyue** [google/draco#166]
Running the "draco_tests --update_golden_files" resulted in the following output

I can understand the missing files can be due to missing commits but not with the --update_golden_files flag already enabled for the other errors.

`
[==========] Running 95 tests from 28 test cases.
[----------] Global test environment set-up.
[----------] 1 test from PointAttributeTest
[ RUN      ] PointAttributeTest.TestCopy
[       OK ] PointAttributeTest.TestCopy (0 ms)
[----------] 1 test from PointAttributeTest (0 ms total)

[----------] 6 tests from PredictionSchemeNormalOctahedronCanonicalizedTransformTest
[ RUN      ] PredictionSchemeNormalOctahedronCanonicalizedTransformTest.Init
[       OK ] PredictionSchemeNormalOctahedronCanonicalizedTransformTest.Init (0 ms)
[ RUN      ] PredictionSchemeNormalOctahedronCanonicalizedTransformTest.IsInBottomLeft
[       OK ] PredictionSchemeNormalOctahedronCanonicalizedTransformTest.IsInBottomLeft (0 ms)
[ RUN      ] PredictionSchemeNormalOctahedronCanonicalizedTransformTest.GetRotationCount
[       OK ] PredictionSchemeNormalOctahedronCanonicalizedTransformTest.GetRotationCount (0 ms)
[ RUN      ] PredictionSchemeNormalOctahedronCanonicalizedTransformTest.RotateRepresentation
[       OK ] PredictionSchemeNormalOctahedronCanonicalizedTransformTest.RotateRepresentation (0 ms)
[ RUN      ] PredictionSchemeNormalOctahedronCanonicalizedTransformTest.ComputeCorrection
[       OK ] PredictionSchemeNormalOctahedronCanonicalizedTransformTest.ComputeCorrection (0 ms)
[ RUN      ] PredictionSchemeNormalOctahedronCanonicalizedTransformTest.Interface
[       OK ] PredictionSchemeNormalOctahedronCanonicalizedTransformTest.Interface (0 ms)
[----------] 6 tests from PredictionSchemeNormalOctahedronCanonicalizedTransformTest (0 ms total)

[----------] 3 tests from PredictionSchemeNormalOctahedronTransformTest
[ RUN      ] PredictionSchemeNormalOctahedronTransformTest.Init
[       OK ] PredictionSchemeNormalOctahedronTransformTest.Init (0 ms)
[ RUN      ] PredictionSchemeNormalOctahedronTransformTest.ComputeCorrections
[       OK ] PredictionSchemeNormalOctahedronTransformTest.ComputeCorrections (0 ms)
[ RUN      ] PredictionSchemeNormalOctahedronTransformTest.Interface
[       OK ] PredictionSchemeNormalOctahedronTransformTest.Interface (0 ms)
[----------] 3 tests from PredictionSchemeNormalOctahedronTransformTest (0 ms total)

[----------] 1 test from SequentialIntegerAttributeEncodingTest
[ RUN      ] SequentialIntegerAttributeEncodingTest.DoesCompress
[       OK ] SequentialIntegerAttributeEncodingTest.DoesCompress (1 ms)
[----------] 1 test from SequentialIntegerAttributeEncodingTest (1 ms total)

[----------] 1 test from DecodeTest
[ RUN      ] DecodeTest.TestSkipAttributeTransform
[       OK ] DecodeTest.TestSkipAttributeTransform (0 ms)
[----------] 1 test from DecodeTest (0 ms total)

[----------] 2 tests from EncodeTest
[ RUN      ] EncodeTest.TestExpertEncoderQuantization
[       OK ] EncodeTest.TestExpertEncoderQuantization (0 ms)
[ RUN      ] EncodeTest.TestEncoderQuantization
[       OK ] EncodeTest.TestEncoderQuantization (0 ms)
[----------] 2 tests from EncodeTest (0 ms total)

[----------] 6 tests from MeshEdgebreakerEncodingTest
[ RUN      ] MeshEdgebreakerEncodingTest.TestNmOBJ
[       OK ] MeshEdgebreakerEncodingTest.TestNmOBJ (2 ms)
[ RUN      ] MeshEdgebreakerEncodingTest.ThreeFacesOBJ
[       OK ] MeshEdgebreakerEncodingTest.ThreeFacesOBJ (0 ms)
[ RUN      ] MeshEdgebreakerEncodingTest.TestPly
[       OK ] MeshEdgebreakerEncodingTest.TestPly (2 ms)
[ RUN      ] MeshEdgebreakerEncodingTest.TestMultiAttributes
[       OK ] MeshEdgebreakerEncodingTest.TestMultiAttributes (1 ms)
[ RUN      ] MeshEdgebreakerEncodingTest.TestEncoderReuse
[       OK ] MeshEdgebreakerEncodingTest.TestEncoderReuse (1 ms)
[ RUN      ] MeshEdgebreakerEncodingTest.TestDecoderReuse
[       OK ] MeshEdgebreakerEncodingTest.TestDecoderReuse (2 ms)
[----------] 6 tests from MeshEdgebreakerEncodingTest (8 ms total)

[----------] 2 tests from PointCloudKdTreeEncodingTest
[ RUN      ] PointCloudKdTreeEncodingTest.TestFloatKdTreeEncoding
[       OK ] PointCloudKdTreeEncodingTest.TestFloatKdTreeEncoding (9 ms)
[ RUN      ] PointCloudKdTreeEncodingTest.TestIntKdTreeEncoding
[       OK ] PointCloudKdTreeEncodingTest.TestIntKdTreeEncoding (0 ms)
[----------] 2 tests from PointCloudKdTreeEncodingTest (9 ms total)

[----------] 2 tests from PointCloudSequentialEncodingTest
[ RUN      ] PointCloudSequentialEncodingTest.DoesEncodeAndDecode
[       OK ] PointCloudSequentialEncodingTest.DoesEncodeAndDecode (1 ms)
[ RUN      ] PointCloudSequentialEncodingTest.EncodingPointCloudWithMetadata
[       OK ] PointCloudSequentialEncodingTest.EncodingPointCloudWithMetadata (1 ms)
[----------] 2 tests from PointCloudSequentialEncodingTest (2 ms total)

[----------] 1 test from RansCodingTest
[ RUN      ] RansCodingTest.LinkerTest
[       OK ] RansCodingTest.LinkerTest (0 ms)
[----------] 1 test from RansCodingTest (0 ms total)

[----------] 4 tests from BufferBitCodingTest
[ RUN      ] BufferBitCodingTest.TestBitCodersByteAligned
[       OK ] BufferBitCodingTest.TestBitCodersByteAligned (0 ms)
[ RUN      ] BufferBitCodingTest.TestBitCodersNonByte
[       OK ] BufferBitCodingTest.TestBitCodersNonByte (0 ms)
[ RUN      ] BufferBitCodingTest.TestSingleBits
[       OK ] BufferBitCodingTest.TestSingleBits (0 ms)
[ RUN      ] BufferBitCodingTest.TestMultipleBits
[       OK ] BufferBitCodingTest.TestMultipleBits (0 ms)
[----------] 4 tests from BufferBitCodingTest (0 ms total)

[----------] 2 tests from MathUtils
[ RUN      ] MathUtils.Mod
[       OK ] MathUtils.Mod (0 ms)
[ RUN      ] MathUtils.IntSqrt
[       OK ] MathUtils.IntSqrt (3 ms)
[----------] 2 tests from MathUtils (3 ms total)

[----------] 2 tests from QuantizationUtilsTest
[ RUN      ] QuantizationUtilsTest.TestQuantizer
[       OK ] QuantizationUtilsTest.TestQuantizer (0 ms)
[ RUN      ] QuantizationUtilsTest.TestDequantizer
[       OK ] QuantizationUtilsTest.TestDequantizer (0 ms)
[----------] 2 tests from QuantizationUtilsTest (0 ms total)

[----------] 1 test from StatusTest
[ RUN      ] StatusTest.TestStatusOutput
[       OK ] StatusTest.TestStatusOutput (0 ms)
[----------] 1 test from StatusTest (0 ms total)

[----------] 7 tests from SymbolCodingTest
[ RUN      ] SymbolCodingTest.TestLargeNumbers
[       OK ] SymbolCodingTest.TestLargeNumbers (47 ms)
[ RUN      ] SymbolCodingTest.TestManyNumbers
[       OK ] SymbolCodingTest.TestManyNumbers (2 ms)
[ RUN      ] SymbolCodingTest.TestEmpty
[       OK ] SymbolCodingTest.TestEmpty (0 ms)
[ RUN      ] SymbolCodingTest.TestOneSymbol
[       OK ] SymbolCodingTest.TestOneSymbol (0 ms)
[ RUN      ] SymbolCodingTest.TestBitLengths
[       OK ] SymbolCodingTest.TestBitLengths (1 ms)
[ RUN      ] SymbolCodingTest.TestLargeNumberCondition
[       OK ] SymbolCodingTest.TestLargeNumberCondition (243 ms)
[ RUN      ] SymbolCodingTest.TestConversionFullRange
[       OK ] SymbolCodingTest.TestConversionFullRange (0 ms)
[----------] 7 tests from SymbolCodingTest (293 ms total)

[----------] 5 tests from VectorDTest
[ RUN      ] VectorDTest.TestOperators
[       OK ] VectorDTest.TestOperators (0 ms)
[ RUN      ] VectorDTest.TestSquaredDistance
[       OK ] VectorDTest.TestSquaredDistance (0 ms)
[ RUN      ] VectorDTest.TestCrossProduct3D
[       OK ] VectorDTest.TestCrossProduct3D (0 ms)
[ RUN      ] VectorDTest.TestAbsSum
[       OK ] VectorDTest.TestAbsSum (0 ms)
[ RUN      ] VectorDTest.TestOstream
[       OK ] VectorDTest.TestOstream (0 ms)
[----------] 5 tests from VectorDTest (0 ms total)

[----------] 7 tests from ObjDecoderTest
[ RUN      ] ObjDecoderTest.ExtraVertexOBJ
[       OK ] ObjDecoderTest.ExtraVertexOBJ (0 ms)
[ RUN      ] ObjDecoderTest.PartialAttributesOBJ
[       OK ] ObjDecoderTest.PartialAttributesOBJ (1 ms)
[ RUN      ] ObjDecoderTest.SubObjects
[       OK ] ObjDecoderTest.SubObjects (0 ms)
[ RUN      ] ObjDecoderTest.SubObjectsWithMetadata
[       OK ] ObjDecoderTest.SubObjectsWithMetadata (0 ms)
[ RUN      ] ObjDecoderTest.QuadOBJ
[       OK ] ObjDecoderTest.QuadOBJ (0 ms)
[ RUN      ] ObjDecoderTest.ComplexPolyOBJ
[       OK ] ObjDecoderTest.ComplexPolyOBJ (0 ms)
[ RUN      ] ObjDecoderTest.TestObjDecodingAll
F:\nyue\projects\draco\draco_git\src\draco\io\obj_decoder_test.cc(49): error: Expected: (mesh) != (nullptr), actual: 8-byte object <00-00 00-00 00-00 00-00> vs 8-byte object <00-00 00-00 00-00 00-00>
Failed to load test model bunny_norm.obj
F:\nyue\projects\draco\draco_git\src\draco\io\obj_decoder_test.cc(49): error: Expected: (mesh) != (nullptr), actual: 8-byte object <00-00 00-00 00-00 00-00> vs 8-byte object <00-00 00-00 00-00 00-00>
Failed to load test model mat_test.obj
F:\nyue\projects\draco\draco_git\src\draco\io\obj_decoder_test.cc(49): error: Expected: (mesh) != (nullptr), actual: 8-byte object <00-00 00-00 00-00 00-00> vs 8-byte object <00-00 00-00 00-00 00-00>
Failed to load test model test_city_atts.obj
F:\nyue\projects\draco\draco_git\src\draco\io\obj_decoder_test.cc(49): error: Expected: (mesh) != (nullptr), actual: 8-byte object <00-00 00-00 00-00 00-00> vs 8-byte object <00-00 00-00 00-00 00-00>
Failed to load test model test_nm_trans.obj
F:\nyue\projects\draco\draco_git\src\draco\io\obj_decoder_test.cc(49): error: Expected: (mesh) != (nullptr), actual: 8-byte object <00-00 00-00 00-00 00-00> vs 8-byte object <00-00 00-00 00-00 00-00>
Failed to load test model test_sphere.obj
[  FAILED  ] ObjDecoderTest.TestObjDecodingAll (18 ms)
[----------] 7 tests from ObjDecoderTest (19 ms total)

[----------] 3 tests from PlyDecoderTest
[ RUN      ] PlyDecoderTest.TestPlyDecoding
[       OK ] PlyDecoderTest.TestPlyDecoding (0 ms)
[ RUN      ] PlyDecoderTest.TestPlyNormals
[       OK ] PlyDecoderTest.TestPlyNormals (0 ms)
[ RUN      ] PlyDecoderTest.TestPlyDecodingAll
[       OK ] PlyDecoderTest.TestPlyDecodingAll (111 ms)
[----------] 3 tests from PlyDecoderTest (113 ms total)

[----------] 4 tests from PlyReaderTest
[ RUN      ] PlyReaderTest.TestReader
[       OK ] PlyReaderTest.TestReader (0 ms)
[ RUN      ] PlyReaderTest.TestReaderAscii
[       OK ] PlyReaderTest.TestReaderAscii (0 ms)
[ RUN      ] PlyReaderTest.TestReaderExtraWhitespace
[       OK ] PlyReaderTest.TestReaderExtraWhitespace (0 ms)
[ RUN      ] PlyReaderTest.TestReaderMoreDataTypes
[       OK ] PlyReaderTest.TestReaderMoreDataTypes (1 ms)
[----------] 4 tests from PlyReaderTest (1 ms total)

[----------] 2 tests from IoPointCloudIoTest
[ RUN      ] IoPointCloudIoTest.EncodeWithBinary
[       OK ] IoPointCloudIoTest.EncodeWithBinary (1 ms)
[ RUN      ] IoPointCloudIoTest.ObjFileInput
[       OK ] IoPointCloudIoTest.ObjFileInput (0 ms)
[----------] 2 tests from IoPointCloudIoTest (1 ms total)

[----------] 5 tests from MeshAreEquivalentTest
[ RUN      ] MeshAreEquivalentTest.TestOnIndenticalMesh
[       OK ] MeshAreEquivalentTest.TestOnIndenticalMesh (1 ms)
[ RUN      ] MeshAreEquivalentTest.TestPermutedOneFace
[       OK ] MeshAreEquivalentTest.TestPermutedOneFace (0 ms)
[ RUN      ] MeshAreEquivalentTest.TestPermutedTwoFaces
[       OK ] MeshAreEquivalentTest.TestPermutedTwoFaces (0 ms)
[ RUN      ] MeshAreEquivalentTest.TestPermutedThreeFaces
[       OK ] MeshAreEquivalentTest.TestPermutedThreeFaces (1 ms)
[ RUN      ] MeshAreEquivalentTest.TestOnBigMesh
[       OK ] MeshAreEquivalentTest.TestOnBigMesh (1 ms)
[----------] 5 tests from MeshAreEquivalentTest (4 ms total)

[----------] 3 tests from MeshCleanupTest
[ RUN      ] MeshCleanupTest.TestDegneratedFaces
[       OK ] MeshCleanupTest.TestDegneratedFaces (0 ms)
[ RUN      ] MeshCleanupTest.TestDegneratedFacesAndIsolatedVertices
[       OK ] MeshCleanupTest.TestDegneratedFacesAndIsolatedVertices (0 ms)
[ RUN      ] MeshCleanupTest.TestAttributes
[       OK ] MeshCleanupTest.TestAttributes (0 ms)
[----------] 3 tests from MeshCleanupTest (0 ms total)

[----------] 2 tests from TriangleSoupMeshBuilderTest
[ RUN      ] TriangleSoupMeshBuilderTest.CubeTest
[       OK ] TriangleSoupMeshBuilderTest.CubeTest (0 ms)
[ RUN      ] TriangleSoupMeshBuilderTest.TestPerFaceAttribs
[       OK ] TriangleSoupMeshBuilderTest.TestPerFaceAttribs (0 ms)
[----------] 2 tests from TriangleSoupMeshBuilderTest (0 ms total)

[----------] 6 tests from MetadataEncoderTest
[ RUN      ] MetadataEncoderTest.TestSingleEntry
[       OK ] MetadataEncoderTest.TestSingleEntry (0 ms)
[ RUN      ] MetadataEncoderTest.TestMultipleEntries
[       OK ] MetadataEncoderTest.TestMultipleEntries (0 ms)
[ RUN      ] MetadataEncoderTest.TestEncodingArrayEntries
[       OK ] MetadataEncoderTest.TestEncodingArrayEntries (0 ms)
[ RUN      ] MetadataEncoderTest.TestEncodingBinaryEntry
[       OK ] MetadataEncoderTest.TestEncodingBinaryEntry (0 ms)
[ RUN      ] MetadataEncoderTest.TestEncodingNestedMetadata
[       OK ] MetadataEncoderTest.TestEncodingNestedMetadata (0 ms)
[ RUN      ] MetadataEncoderTest.TestEncodingGeometryMetadata
[       OK ] MetadataEncoderTest.TestEncodingGeometryMetadata (0 ms)
[----------] 6 tests from MetadataEncoderTest (0 ms total)

[----------] 9 tests from MetadataTest
[ RUN      ] MetadataTest.TestRemoveEntry
[       OK ] MetadataTest.TestRemoveEntry (0 ms)
[ RUN      ] MetadataTest.TestSingleEntry
[       OK ] MetadataTest.TestSingleEntry (0 ms)
[ RUN      ] MetadataTest.TestWriteOverEntry
[       OK ] MetadataTest.TestWriteOverEntry (0 ms)
[ RUN      ] MetadataTest.TestArrayEntry
[       OK ] MetadataTest.TestArrayEntry (0 ms)
[ RUN      ] MetadataTest.TestStringEntry
[       OK ] MetadataTest.TestStringEntry (0 ms)
[ RUN      ] MetadataTest.TestBinaryEntry
[       OK ] MetadataTest.TestBinaryEntry (0 ms)
[ RUN      ] MetadataTest.TestNestedMetadata
[       OK ] MetadataTest.TestNestedMetadata (0 ms)
[ RUN      ] MetadataTest.TestHardCopyMetadata
[       OK ] MetadataTest.TestHardCopyMetadata (0 ms)
[ RUN      ] MetadataTest.TestGeometryMetadata
[       OK ] MetadataTest.TestGeometryMetadata (0 ms)
[----------] 9 tests from MetadataTest (0 ms total)

[----------] 4 tests from PointCloudBuilderTest
[ RUN      ] PointCloudBuilderTest.IndividualTest_NoDedup
[       OK ] PointCloudBuilderTest.IndividualTest_NoDedup (0 ms)
[ RUN      ] PointCloudBuilderTest.IndividualTest_Dedup
[       OK ] PointCloudBuilderTest.IndividualTest_Dedup (0 ms)
[ RUN      ] PointCloudBuilderTest.BatchTest
[       OK ] PointCloudBuilderTest.BatchTest (0 ms)
[ RUN      ] PointCloudBuilderTest.MultiUse
[       OK ] PointCloudBuilderTest.MultiUse (0 ms)
[----------] 4 tests from PointCloudBuilderTest (0 ms total)

[----------] 2 tests from PointCloudTest
[ RUN      ] PointCloudTest.TestAttributeDeletion
[       OK ] PointCloudTest.TestAttributeDeletion (1 ms)
[ RUN      ] PointCloudTest.TestPointCloudWithMetadata
[       OK ] PointCloudTest.TestPointCloudWithMetadata (0 ms)
[----------] 2 tests from PointCloudTest (1 ms total)

[----------] 2 tests from MeshEncoderTests/MeshEncoderTest
[ RUN      ] MeshEncoderTests/MeshEncoderTest.EncodeGoldenMesh/0
F:\nyue\projects\draco\draco_git\src\draco\compression\mesh\mesh_encoder_test.cc(85): error: Value of: CompareGoldenFile(golden_file_name, buffer.data(), buffer.size())
  Actual: false
Expected: true
Encoded data is different from the golden file. Please verify that the encoding works as expected and update the golden file if necessary (run the test with --update_golden_files flag).
[  FAILED  ] MeshEncoderTests/MeshEncoderTest.EncodeGoldenMesh/0, where GetParam() = "sequential" (0 ms)
[ RUN      ] MeshEncoderTests/MeshEncoderTest.EncodeGoldenMesh/1
F:\nyue\projects\draco\draco_git\src\draco\compression\mesh\mesh_encoder_test.cc(85): error: Value of: CompareGoldenFile(golden_file_name, buffer.data(), buffer.size())
  Actual: false
Expected: true
Encoded data is different from the golden file. Please verify that the encoding works as expected and update the golden file if necessary (run the test with --update_golden_files flag).
[  FAILED  ] MeshEncoderTests/MeshEncoderTest.EncodeGoldenMesh/1, where GetParam() = "edgebreaker" (1 ms)
[----------] 2 tests from MeshEncoderTests/MeshEncoderTest (1 ms total)

[----------] Global test environment tear-down
[==========] 95 tests from 28 test cases ran. (457 ms total)
[  PASSED  ] 92 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] ObjDecoderTest.TestObjDecodingAll
[  FAILED  ] MeshEncoderTests/MeshEncoderTest.EncodeGoldenMesh/0, where GetParam() = "sequential"
[  FAILED  ] MeshEncoderTests/MeshEncoderTest.EncodeGoldenMesh/1, where GetParam() = "edgebreaker"

 3 FAILED TESTS
`

Cheers

**Comment by fanzhanggoogle** [comment]
Thanks for the report.
This [PR](https://github.com/google/draco/pull/175) should fix it.
