### ISSUE TITLE
Metadata : custom attributes for particles and meshes - examples ?

### ISSUE THREAD

**Issue by nyue** [google/draco#167]
Hi,

  I wish to write and read-back custom point/vertex attributes to particles and meshes.

  Example of those attributes are e.g. velocities (float vector), densities (float scalar), particle_id (integer scalar)

  When reading those information back from a draco file, I need to know their original attribute name rather than "generic"

  I hope with the Metadata feature, I can do the above.

Cheers

**Comment by fanzhanggoogle** [comment]
Hi,

That's definitely possible with the new metadata feature. 
To achieve what you want, you could do something like:
```
draco::PointCloud pc;
std::unique_ptr<draco::GeometryMetadata> metadata =
    std::unique_ptr<draco::GeometryMetadata>(new draco::GeometryMetadata());
draco::GeometryAttribute your_custom_attribute;
your_custom_attribute.Init(draco::GeometryAttribute::GENERIC, nullptr, 3,
                                           draco::DT_FLOAT32, false, 12, 0);
const uint32_t attribute_id = pc.AddAttribute(your_custom_attribute, false, 0);
std::unique_ptr<draco::AttributeMetadata> attribute_metadata =
    std::unique_ptr<draco::AttributeMetadata>(
          new draco::AttributeMetadata(attribute_id));
attribute_metadata->AddEntryString("name", "velocities");
pc.AddAttributeMetadata(std::move(attribute_metadata));
```
To access metadata after decoding the geometry:
```
const draco::GeometryMetadata *pc_metadata = pc.GetMetadata();
const draco::AttributeMetadata *attribute_metadata =
    pc_metadata->GetAttributeMetadata(attribute_id);
```
For more details, you could maybe look at this [test](https://github.com/google/draco/blob/master/src/draco/point_cloud/point_cloud_test.cc)
