### ISSUE TITLE
Getting "Building from within the Draco source tree is not supported"

### ISSUE THREAD

**Issue by pps83** [google/draco#168]
```
C:\work-cdn\draco-build>cmake ../draco-git -G "Visual Studio 14 2015"
CMake Error at CMakeLists.txt:9 (message):
  Building from within the Draco source tree is not supported.

  Hint: mkdir -p ../draco_build && cd ../draco_build

  Run cmake from there.


-- Configuring incomplete, errors occurred!
See also "C:/work-cdn/draco-git/CMakeFiles/CMakeOutput.log".
```

I guess it's clear that I'm not building from draco git?.. I wish cmake never existed, each time it's a pain to use it.

**Comment by FrankGalligan** [comment]
Can you try creating a build directory as a subdirectory of Draco root?

**Comment by pps83** [comment]
In my case I had to delete whatever cmake cache that it creates and after that it was ok. Once I got into visual studio everything was ok. Draco does work well and I got impressive results.

**Comment by zwcloud** [comment]
This error message is a little misleading: create a build directory outside the draco source directory and the error still occurs.  It would be better to say *creating a build directory as a subdirectory of Draco root*.
