### ISSUE TITLE
How to load basic face-vertex mesh

### ISSUE THREAD

**Issue by pps83** [google/draco#169]
I'm trying to use draco c++ code to load and compress my custom [face-vertex mesh](https://en.wikipedia.org/wiki/Polygon_mesh#Face-vertex_meshes) represented basically by this data structure:

```
struct vertex
{
    float v[3];
    float n[3];
    float t[3];
};
typedef unsigned face[3];
struct mesh
{
    vector<vertex> v;
    vector<face> f;
};
```

I'm looking into draco::Mesh and as if I was totally blind I don't see how to do that.
I also tried to save my mesh into .obj file and process it with draco_encoder, but after processing I get smaller number of vertices and faces have non-matching values for normals texture coordinates.

v 0.000611 -0.525000 -0.208333
v -0.208333 -0.525000 0.000611
v -0.147239 -0.525000 -0.147239

**Comment by FrankGalligan** [comment]
You can use https://github.com/google/draco/blob/master/src/draco/mesh/triangle_soup_mesh_builder.h

Check out https://github.com/google/draco/blob/master/src/draco/mesh/triangle_soup_mesh_builder_test.cc#L24, which shows how to use TriangleSoupMeshBuilder by building a cube.

**Comment by pps83** [comment]
Hi Franc,

I was able to import my custom mesh into draco::Mesh by building wavefront obj and then importing it into draco::Mesh. This part works. The problem I'm having is that after I compress and uncompress with draco my mesh becomes broken/unusable. At first I'd like to figure out if I can use draco at all, and then I'll sure use that triangle soup mesh builder.
I wanted to disable detail loss to verify that my mesh was identical and used `-qp 0` but after that draco decoder [crashes and cannot even open its own file](https://github.com/google/draco/issues/171). With default settings encode and then decoder work.

I took one of my custom meshes, wrote some quick code to [save it as a wavefront](https://www.pastiebin.com/59876c0224767) obj and then tried to experiment with that exported mesh and draco. As you can see all faces in obj have to have identical triplets because in my mesh format each vertex has a tu,tv,tw and nx,ny,nz attached to it. That's why faces (look like this](https://www.pastiebin.com/59876c0224767):


    f 2/2/2 2/2/2 1/1/1
    f 1/1/1 2/2/2 3/3/3
    f 1/1/1 3/3/3 4/4/4
    ...

After I compress that mesh to .drc and uncompress back to obj I get a [mesh that is unusable](https://www.pastiebin.com/59876a3d3ff48). It's unusable because it has non-matching triplets for faces which cannot be imported into my custom meshes:

```
f 3/3/3 1/1/1 2/2/2
f 2/2/2 1/1/1 6/12/6
f 6/12/6 1/1/1 7/6/7
...
```

How can I make draco to 1) compress and uncompress to identical mesh, 2) produce faces with matching v/t/n triplets? Is that even possible?

**Comment by pps83** [comment]
By trial and error I think I got it working. I had relevant [stackoverflow post](https://stackoverflow.com/questions/45535967/) on how to convert such wavefront obj into my custom representation. In short, I treated all triplets like unique values and and new and reshuffled vertices to match these new face triplets. I have no experience with all that stuff, just wanted to confirm that the approach is correct one.

**Comment by FrankGalligan** [comment]
Hi Pavel,

First off we will look into fixing #171.

I think what you are doing is correct to get the mesh into the format you want. I.e. treat each different triplet as unique and then you can use that as a universal index.

As for Draco, I don't think there are any options currently that will give you the behavior you want as we perform a deduplication on the attributes.

**Comment by pps83** [comment]
Yes, I agree #171 should have a proper fix. Looking quickly into that, seems that it's taking wrong code path and calls stuff that shouldn't be called as if .drc file was corrupted. But... code shouldn't assume correctness of a file that it tries to uncompress and shouldn't crash in any case.
In general, how performant is draco? By changing qp values for all attributes I've seen that it takes sometimes long time for small meshes with approximately 200 vertices. Also by changing qp and compression level I got very strange results: sometime reducing compression I got way smaller output, and when I increased to 10 I got worse results. Is it in the same ballpark of slow compressors like guetzly or it shouldn't be that slow, because I'm trying to use it on a server that serves lots of meshes realtime; or this compressor is better to be used for one time compression when creating meshes?

**Comment by ondys** [comment]
@pps83 In general, for meshes with 200 vertices I would expect the encoding to be <1 ms  no matter what compression options you select. The differences in performance may be related to run-time overhead such as cache misses and memory reallocations. If you have some specific model where you encounter performance problems, please send it to us and we will profile it.

**Comment by pps83** [comment]
So, far I don't have any performance issues, I use it on a desktop pc, and all I can say that I get compression results that are beyond my expectations. It works extremely well, the only issue is that I cannot get it to work with lossless compression (I reported [the bug](https://github.com/google/draco/issues/171)). Once I'll move it live on a mobile I'll see if there are any performance issues loading large meshes.

In general, draco uses floating point compression, in which files can I see that code, to learn how it works?
