### ISSUE TITLE
Adding support for vtk-js

### ISSUE THREAD

**Issue by jourdain** [google/draco#17]
That seems interesting and I would like to play with it but I'm guessing the JavaScript implementation is only for decoding and I will have to use the C++ one to encode my data.

Although, I'd rather use the command line interface to compress my various files.

Generally speaking a VTK dataset has 3 types of arrays:
- vtkPoints which would correspond to the coordinates of the geometry
- vtkCellArray which is the index mapping to create various cells. 
- And then any data associated to the points or cells (float32/64, int...)

In my JavaScript representation, I have a JSON file that describe the dataset and a binary representation for each arrays. So far, I've been bundling the set of files into a zip file.
Some example could be downloaded here: https://data.kitware.com/#collection/586fef9f8d777f05f44a5c86
And you can download a viewer from here: http://kitware.github.io/vtk-js/examples/StandaloneSceneLoader.html

So I was thinking it would be nice if your command line tools could compress a file on the disk that represent any of those binary array with additional informations such as the type of the numbers and which type of array they are.

Then I was hoping to use your decoder to convert those buffer on the fly to the corresponding typed array when reading them back.

Anyway, any help or guidance would be awesome and I'm really curious how much improvement we could get from it. 

Thanks,

Seb

**Comment by ondys** [comment]
1. Based on your description, compressing VTK data should be possible as long as vtkCellArray represent connectivity of triangular meshes (Draco doesn't support general polygons). Currently we have importers only for .OBJ and .PLY, but we plan to add support for more formats in future. In case you don't want to wait for us, we always welcome any pull requests that would add support for additional formats. An example how to create a mesh from generic data has been shown in this issue: [https://github.com/google/draco/issues/15](https://github.com/google/draco/issues/15) . Additional examples would be our OBJ and PLY decoders.

2. As for the javascript, it is true that our current javascript API is for the decoder only, but it can be extended for the encoder too if there is sufficient demand.

**Comment by jourdain** [comment]
Thanks for your feedback. 

For vtkCellArray, it is definitely a connectivity map but it does not need to be a set of triangles.
In fact we have a vtkCellArray per type of cells (verts, lines, polys, strip). On top of that the layout is [numberOfPoints, idx_0, ids_1, ... idx_n, numberOfPoints, idx_0, idx_1, numberOfPoints, ...]

And for the polys, the number of points can be more than 3 which means they can be quad, or even bigger. And I'm just talking about the vtkPolyData which are our surface mesh. The full set of dataset types can be found here in case you are interested. http://www.vtk.org/wp-content/uploads/2015/04/file-formats.pdf

For the JavaScript I was just asking in case I could skip some build time. But no big deal here. Thx.

I'm going to look closer to the issue #15. 

Otherwise do you think having a command line tool that can be used to compress files that are binary arrays could make sense? Or did I miss understood the library as all the arrays should be written in the same compressed file?

Anyway, thanks again for your feedback.

**Comment by FrankGalligan** [comment]
I'm closing this issue. If you think we should talk more about it please re-open.
