### ISSUE TITLE
About sequential attribute encoder 

### ISSUE THREAD

**Issue by fndysf** [google/draco#174]
Now I know mesh_edgebreaker and mesh_squential compress connectivity information, then sequentialAttributeEncoder is called to compress Point Attributes. My question is what algorithm is uesd to compress Point Attributes like position, normal and texture coordinate. Quatitization and Prediction Scheme ? Is there any advanced algorithm used to compress point attributes ? I looked into the source code, but I did not find the answer.

**Comment by ondys** [comment]
@fndysf Draco uses various algorithms to compress point attributes based on the attribute type. In general all attributes can be quantized (see `SequentialQuantizationAttributeEncoder`) and a prediction scheme is applied on the resulting integer values (e.g. constrained multi parallelogram for positions, specialized predictors for texture coordinates and normals that use positions of the underlying geometry, etc..). Once prediction schemes are applies all data is compressed using rANS entropy coding.
