### ISSUE TITLE
Metadata Example: Javascript decoder.

### ISSUE THREAD

**Issue by shubhamagarwal003** [google/draco#178]
I've an .obj file with multiple sub-objects and an associated .mtl file with texture information. I want to encode it into draco format and then decode again using Javascript decoder (preserving the textures on each component). I assume that with the metadata support in version 1.0.0 this is possible. Can someone provide me an example on how to do this? Or if there are some pointers to make my own DracoLoader to achieve this?

**Comment by ondys** [comment]
@shubhamagarwal003 Do you use a different .mtl file for each sub-object or does each sub-object uses a different material from the same .mtl file? Our `ObjDecoder` currently supports only one .mtl file per .obj file so in case you need the former you would have to modify the obj decoder + write your own DracoLoader. We are planning to provide examples for using metadata in Javascript in the near future.

**Comment by shubhamagarwal003** [comment]
In my case  each sub-object uses a different material from the same .mtl file. But I didn't got any example where I can provide the .mtl file to load texture from it. If you can provide some pointers on how to proceed with it?

**Comment by himanshu999** [comment]
Hi Ondys, 

Can you please answer my question related to this thread. I am using the --metadata flag to geenrate material generic attribute and I am able to successfully retreive it through javascript decoder. But the other generic flag, viz. the subObjAttribute Id is being generated but the value if same for all points, though i clearly have multiple subobjects (starting with 'o') in my .obj file.

**Comment by himanshu999** [comment]
@shubhamagarwal003 , you may use the following code to get the material attribute for each point in mesh. 

//materials attribute
		 var materialAttrId =
            decoder.GetAttributeIdByName(dracoGeometry, "material");
		
        var materialAttributeData;
        if (materialAttrId != -1) {
          if (this.verbosity > 0) {
            console.log('Loaded material attribute.');
          }
		 
          var materialAttribute = decoder.GetAttribute(dracoGeometry,
                                                         materialAttrId);
          materialAttributeData = new dracoDecoder.DracoFloat32Array();
          decoder.GetAttributeFloatForAllPoints(dracoGeometry,
                                                materialAttribute,
                                                materialAttributeData);


and then you can loop through this materialAttributeData array and then you need to split the mesh based on material ids and apply the required material on them. 

To split the geometry into sub objects , have a look at [#89](https://github.com/google/draco/issues/89)

**Comment by ondys** [comment]
@himanshu999 
> Can you please answer my question related to this thread. I am using the --metadata flag to generate material generic attribute and I am able to successfully retreive it through javascript decoder. But the other generic flag, viz. the subObjAttribute Id is being generated but the value is same for all points, though i clearly have multiple subobjects (starting with 'o') in my .obj file.

Can you please send us the .obj file so we can investigate it? Thanks!

**Comment by himanshu999** [comment]
Hi @ondys , 
Here is my simple test obj file which has a cube and a sphere. No UV Mapping. 
https://we.tl/XbMYITur8O

**Comment by fanzhanggoogle** [comment]
Hi @himanshu999 
Thank you for reporting the bug. I wasn't able to open your file but [this PR](https://github.com/google/draco/pull/186) should fix the bug.

**Comment by shubhamagarwal003** [comment]
@fanzhanggoogle Hi I tried the latest commit but getting the error 
`
Failed to encode the mesh.
Failed to encode point attributes.
`
The same obj file was being encoded earlier.

**Comment by fanzhanggoogle** [comment]
Hi @himanshu999, thanks for trying out. Would you be able to send us the model that fails the encoding? The latest change added some restriction on the usage of material library in obj file. I could help locating the problem.

**Comment by shubhamagarwal003** [comment]
@fanzhanggoogle you can find the model .obj and associated .mtl file here https://drive.google.com/drive/u/1/folders/0B5ZnEve9BlcVODViakVqcEJpb2M. Thanks for the help.

**Comment by orient0254y** [comment]
@himanshu999 I have write a small tool to decomposition an obj file to small pieces,and it's working good.The tool is [here](https://github.com/orient0254y/objFileDecomposition).You can add these pieces to scene easy by reading "README.md" file.
     If these files compression to drc file,there will be much works to us to compression these by hands(or cmd command like this:./draco_encoder -i xxx.obj -o xxx.drc),it's bothered.So I'm tring to find a method to encoder an obj file to a drc file width "javascript",I tried many times but failed.example is [here](https://github.com/orient0254y/dracoEncoderTest).
    If you have any ideas will be appreciated.

**Comment by fanzhanggoogle** [comment]
Hi @shubhamagarwal003, sorry for the late reply. We have improved loading obj file with .mtl file internally and will push to the repo this week or early next week. That should fix the problem of loading your files.

**Comment by fanzhanggoogle** [comment]
Hi, @orient0254y. Thanks for trying out the Javascript encoder. I took a quick look at your example, I noticed that you are using the draco_encoder_nodejs.js which is built for NPM package. We actually have a standalone Javascript version draco_encoder ( is used in the same way as draco_decoder.js ) which should suit your requirement. It's not in the public repo yet, we will push it shortly.

**Comment by shubhamagarwal003** [comment]
@fanzhanggoogle I am not sure my problem is with loading. With the latest commit I was getting an error when I tried to encode a particular .obj. 
`Failed to encode the mesh. Failed to encode point attributes.`
The same obj was encoded properly in previous commits. The link to .obj is https://drive.google.com/drive/u/1/folders/0B5ZnEve9BlcVODViakVqcEJpb2M

**Comment by fanzhanggoogle** [comment]
Hi @shubhamagarwal003 , I tried your files and it could encoded and decoded with the latest release. Just to note that you need to change your City.mtl to Abhishek_Created.mtl because that's the mtl file name specified in the City.obj file.

**Comment by fanzhanggoogle** [comment]
Hi @orient0254y , we have uploaded [Javascript version of draco_encoder](https://github.com/google/draco/tree/master/javascript). You can try it out!

**Comment by orient0254y** [comment]
@fanzhanggoogle I have tried draco_encoder.js of version 1.1.0,but I got new Error:THREE.DRACOLoader: No position attribute found.maybe I have got some wrong lines some where in my code,my code is here:[https://github.com/orient0254y/dracoEncoderTest](url);
If you can give one demo like "webgl_loader_draco.html" with using javascript method to compress an obj file to a drc file,it will be very helpful, thanks!

**Comment by fanzhanggoogle** [comment]
Hi @orient0254y , thanks for trying the js encoder. I took a quick look at your code and found one issue. I made a comment there. Let me know if it works now and I can help further.

**Comment by orient0254y** [comment]
@fanzhanggoogle sorry about that I don't find your comment,where is it!Should you give a link.

**Comment by orient0254y** [comment]
@fanzhanggoogle 你在杭州工作吗？咱都中国的用啥英文聊，那么用js压缩obj文件怎么弄的？有没有例子啊。

**Comment by orient0254y** [comment]
@shubhamagarwal003 Have you solve this problem?

**Comment by fanzhanggoogle** [comment]
@orient0254y Hi, sorry for the late reply. I'm actually on the Draco team so it's better for me to use English so that others could understand the questions and get help as well.
To encode .obj using JS, one way is to use the OBJLoader of ThreeJS and convert to Draco format. We have internally a simple obj loader to directly load .obj and compress but it's not mature yet. We'll make a n announcement once we publish that. If you could open a new issue on this request, we can track it from there since this issue is resolved and closed. Thanks!

**Comment by prabhatmishra33** [comment]
@fanzhanggoogle  Can you please tell me do we have something now which will help to convert .obj to .drc with javascript ? ,I actually tried with:
 `node draco_encoder.js -i ./bugatti.obj -o bugatti.drc`  
[ node version : v10.15.3]
no errors were thrown and no output file was created.
draco_encoder.js is this file https://github.com/google/draco/blob/master/javascript/draco_encoder.js
