### ISSUE TITLE
model disappeared sometimes

### ISSUE THREAD

**Issue by meiwhu** [google/draco#183]
I encode the obj model into drc in windows, and load  it in the example in `draco/javascript/example/webgl_loader_draco.html`, 
the model disappear when the camera rotate somewhere.
This is the obj file
[test.zip](https://github.com/google/draco/files/1237702/test.zip).
please help!

**Comment by Ben-Mack** [comment]
I have the same problem, my model is randomly disappear and appear when loaded into webgl_loader_draco.html  
Default bunny model working good.

After sometime playing with it, I found out that if you comment out 2 line at 141 and 151 then viewer working good, these lines are used to "dequantization on the GPU", I think this is a bug.

**Comment by meiwhu** [comment]
@Ben-Mack  it works! thank you^_^
