### ISSUE TITLE
Cannot build Draco with JS decoder: draco requires support for CXX flag: -std=c++11.

### ISSUE THREAD

**Issue by Ben-Mack** [google/draco#188]
I can build Draco using  `cmake .`  without a problem. But I want to edit javascript decoder so I have to build it, I'm still trying for days without success. 
Please give me some direction on how to solve this issue, any idea is much appreciated.

Here is what I use to build Draco with JS decoder:

```
cd C:\Users\Ben\Desktop\draco-master
SET EMSCRIPTEN="C:\Users\Ben\Desktop\Emscripten\emscripten\1.37.1"
cmake . -DCMAKE_TOOLCHAIN_FILE="C:\Users\Ben\Desktop\Emscripten\emscripten\1.37.1\cmake\Modules\Platform\Emscripten.cmake"
```

And this is the error report:

```
 -- Building for: Visual Studio 15 2017
CMake Warning at C:/Users/Ben/Desktop/Emscripten/emscripten/1.37.1/cmake/Modules/Platform/Emscripten.cmake:121 (message):
  CMAKE_C_COMPILER version looks too old.  Was 3.7.0, should be at least
  3.9.0.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:2 (project)


Checking CXX compiler flag support for: -std=c++11
-- Performing Test HAVE_CXX_FLAG
CMake Warning at C:/Users/Ben/Desktop/Emscripten/emscripten/1.37.1/cmake/Modules/Platform/Emscripten.cmake:121 (message):
  CMAKE_C_COMPILER version looks too old.  Was 3.7.0, should be at least
  3.9.0.
Call Stack (most recent call first):
  C:/Users/Ben/Desktop/draco-master/CMakeFiles/3.9.1/CMakeSystem.cmake:6 (include)
  C:/Users/Ben/Desktop/draco-master/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project)


-- Performing Test HAVE_CXX_FLAG - Failed
CMake Error at cmake/compiler_flags.cmake:95 (message):
  draco requires support for CXX flag: -std=c++11.
Call Stack (most recent call first):
  cmake/compiler_flags.cmake:124 (require_cxx_flag)
  CMakeLists.txt:15 (require_cxx_flag_nomsvc)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Ben/Desktop/draco-master/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Ben/Desktop/draco-master/CMakeFiles/CMakeError.log".
```

I already tried to upgrade cmake, mingw gcc g++, Visual Studio.
> cmake version 3.9.1
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
Visual Studio 2017
Windows 10 64bit

 thank a lot!

**Comment by Ben-Mack** [comment]
@ondys @fanzhanggoogle @FrankGalligan  Sorry for tag you guys, I know that you're all busy but I'm close to my deadline, can you take a quick look? 
I've already reinstall everything on a new pc: MinGW, Cmake, Visual Studio 2017, Emscripten but still facing the same error: 
```
-- Performing Test HAVE_CXX_FLAG - Failed
CMake Error at cmake/compiler_flags.cmake:95 (message):
  draco requires support for CXX flag: -std=c++11.
```

**Comment by FrankGalligan** [comment]
Hey Ben. Can you paste these:
See also "C:/Users/Ben/Desktop/draco-master/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Ben/Desktop/draco-master/CMakeFiles/CMakeError.log".

**Comment by Ben-Mack** [comment]
Here it is

CMakeOutput.log
```
The target system is: Emscripten - 1 - x86
The host system is: Windows - 10.0.14393 - AMD64

```

CMakeError.log

```
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG failed with the following output:
Change Dir: C:/Users/Ben/Desktop/draco-master/build/CMakeFiles/CMakeTmp

Run Build Command:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community/MSBuild/15.0/Bin/MSBuild.exe" "cmTC_0b39c.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=15.0"
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.



Build started 8/25/2017 3:17:04 PM.

Project "C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\cmTC_0b39c.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_0b39c.dir\Debug\".

  Creating directory "C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_0b39c.dir\Debug\cmTC_0b39c.tlog\".

InitializeBuildStatus:

  Creating "cmTC_0b39c.dir\Debug\cmTC_0b39c.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\CL.exe /c /W1 /WX- /diagnostics:classic /O2 /Oy- /D HAVE_CXX_FLAG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_0b39c.dir\Debug\\" /Fd"cmTC_0b39c.dir\Debug\vc141.pdb" /Gd /TP /analyze- /errorReport:queue  -s ERROR_ON_UNDEFINED_SYMBOLS=1 -g "C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\src.cxx"

  Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25507.1 for x86

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /W1 /WX- /diagnostics:classic /O2 /Oy- /D HAVE_CXX_FLAG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_0b39c.dir\Debug\\" /Fd"cmTC_0b39c.dir\Debug\vc141.pdb" /Gd /TP /analyze- /errorReport:queue  -s ERROR_ON_UNDEFINED_SYMBOLS=1 -g "C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\src.cxx"

  ERROR_ON_UNDEFINED_SYMBOLS=1

  

cl : Command line warning D9002: ignoring unknown option '-s' [C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\cmTC_0b39c.vcxproj]

cl : Command line warning D9002: ignoring unknown option '-g' [C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\cmTC_0b39c.vcxproj]

c1xx : fatal error C1083: Cannot open source file: 'ERROR_ON_UNDEFINED_SYMBOLS=1': No such file or directory [C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\cmTC_0b39c.vcxproj]

  src.cxx

  Generating Code...

Done Building Project "C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\cmTC_0b39c.vcxproj" (default targets) -- FAILED.



Build FAILED.



"C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\cmTC_0b39c.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  cl : Command line warning D9002: ignoring unknown option '-s' [C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\cmTC_0b39c.vcxproj]

  cl : Command line warning D9002: ignoring unknown option '-g' [C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\cmTC_0b39c.vcxproj]





"C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\cmTC_0b39c.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  c1xx : fatal error C1083: Cannot open source file: 'ERROR_ON_UNDEFINED_SYMBOLS=1': No such file or directory [C:\Users\Ben\Desktop\draco-master\build\CMakeFiles\CMakeTmp\cmTC_0b39c.vcxproj]



    2 Warning(s)

    1 Error(s)



Time Elapsed 00:00:01.09


Source file was:
int main() { return 0; }

```

**Comment by Ben-Mack** [comment]
I've successfully built Draco with JS decoder on Ubuntu virtual machine, so maybe this error is Windows-specific?

**Comment by tomfinegan** [comment]
Looking into this now, but a couple things are jumping out at me as odd right away:

```
cd C:\Users\Ben\Desktop\draco-master
SET EMSCRIPTEN="C:\Users\Ben\Desktop\Emscripten\emscripten\1.37.1"
cmake . -DCMAKE_TOOLCHAIN_FILE="C:\Users\Ben\Desktop\Emscripten\emscripten\1.37.1\cmake\Modules\Platform\Emscripten.cmake"
```

First thing:
This CMake command should fail without modifications to Draco's CMake file:
https://github.com/google/draco/blob/master/CMakeLists.txt#L8

There should be a complaint about building within the source tree being unsupported if "." is the Draco path.

Second thing:
Why are you using `SET EMSCRIPTEN=...` instead of using emsdk_env.bat?

I'm not certain how Visual Studio is getting involved here, but it might be related to setting only the EMSCRIPTEN environment variable instead of using the provided batch file. I don't know that it's even possible to build for emscripten from within MSVC (it might work; I have no idea). The portable emsdk includes the compilers and tools required to build the JS decoder-- afaik you should not need MSVC at all.

**Comment by Ben-Mack** [comment]
1. I know that and already create and build in seperate folder in later build (but still got the same error)
2. I followed instruction on Readme file (https://github.com/google/draco#javascript-encoderdecoder) 
I've just tried to run `emsdk_env.bat` before `cmake` but no luck.

I'm still very new to build from source. So for example, with a clean windows 10, what I have to install to build Draco with JS decoder?

```
MinGW
CMake
Emscripten
```
Are these enough? Do I have to check any custom option in MinGW?

**Comment by tomfinegan** [comment]
Ok, got this to work. There's an odd problem that can be worked around manually (more on this below) but things appear to work with the following installed:

- [Portable EMSDK](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html)
- For Make: [MSYS2](http://www.msys2.org/). You can probably use any old version of Make-- just noting the one that I actually used.

For the portable EMSDK make sure you follow all of the instructions for installation. After running emsdk_env.bat, do this:

1) Add the path to MSYS2's usr/bin to your PATH. For example, mine is `C:\src\msys64\usr\bin`, so I ran `PATH=%PATH%;C:\src\msys64\usr\bin` in my command prompt (cmd.exe in this case).
2) In a directory that's not the root of the draco repository run:
`cmake path\to\draco -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=path\to\Emscripten.cmake`
    - Get a coffee, take a nap, something-- this takes a **long time** the first time it works.
3) There will be a couple of error messages about IOErrors while trying to open glue_decoder.cpp glue_encoder.cpp, run these two commands to generate the files:

```
python path\to\emsdk-portable\emscripten\1.37.20\tools\webidl_binder.py path\to\draco\src\draco\javascript\emscripten\draco_web_decoder.idl .\glue_decoder

python path\to\emsdk-portable\emscripten\1.37.20\tools\webidl_binder.py path\to\draco\src\draco\javascript\emscripten\draco_web_encoder.idl .\glue_encoder
```
I'll file an issue about the IOErrors and look into that some time next week since it can be worked around.

4) Run make -j

That should get you a javascript build of Draco.

**Comment by tomfinegan** [comment]
dc28e6a2eae53d48b22c668b6e8cad1c582a11ce fixes this.
