### ISSUE TITLE
Error compiling draco_decoder.js

### ISSUE THREAD

**Issue by haeric** [google/draco#19]
I'm trying to compile draco_decoder.js with some parameters in Makefile.emcc changed, [as described in the README](https://github.com/google/draco/blob/master/README.md#javascript-decoder-performance). `make -f Makefile.emcc` runs normally at first, printing only warnings about an optimization it can't do:
```
make -f Makefile.emcc
python /usr/local/opt/emscripten/libexec/tools/webidl_binder.py javascript/emscripten/draco_web.idl glue
em++ -MMD -MP -DDRACO_STANDARD_EDGEBREAKER_SUPPORTED -DDRACO_PREDICTIVE_EDGEBREAKER_SUPPORTED -I../../ -I./ -std=c++11 -O3 -s ALLOW_MEMORY_GROWTH=1 --memory-init-file 0 -Wno-sign-compare -fno-omit-frame-pointer javascript/emscripten/draco_glue_wrapper.cc -o obj/javascript/emscripten/draco_glue_wrapper.o
WARNING:root:not all asm.js optimizations are possible with ALLOW_MEMORY_GROWTH, disabling those
em++ -MMD -MP -DDRACO_STANDARD_EDGEBREAKER_SUPPORTED -DDRACO_PREDICTIVE_EDGEBREAKER_SUPPORTED -I../../ -I./ -std=c++11 -O3 -s ALLOW_MEMORY_GROWTH=1 --memory-init-file 0 -Wno-sign-compare -fno-omit-frame-pointer javascript/emscripten/webidl_wrapper.cc -o obj/javascript/emscripten/webidl_wrapper.o
WARNING:root:not all asm.js optimizations are possible with ALLOW_MEMORY_GROWTH, disabling those
em++ -MMD -MP -DDRACO_STANDARD_EDGEBREAKER_SUPPORTED -DDRACO_PREDICTIVE_EDGEBREAKER_SUPPORTED -I../../ -I./ -std=c++11 -O3 -s ALLOW_MEMORY_GROWTH=1 --memory-init-file 0 -Wno-sign-compare -fno-omit-frame-pointer core/draco_types.cc -o obj/core/draco_types_a.o
WARNING:root:not all asm.js optimizations are possible with ALLOW_MEMORY_GROWTH, disabling those
...
```

But then eventually crashes with the following error:
```
make: *** No rule to make target `obj/compression/attributes/mesh_normal_attribute_decoder_a.o', needed by `draco_decoder'.  Stop.
```

Is using Makefile.emcc still supported, or is the only compile path now `cmake . -DCMAKE_TOOLCHAIN_FILE=... && make`?

Running: OSX 10.11.6 (El Capitan)
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.0
clang version 3.9.0  (emscripten 1.37.0 : 1.37.0)
Target: x86_64-apple-darwin15.6.0

**Comment by martinlindhe** [comment]
The Makefile.emcc says you should run this command first, did you?

    make target DRACO_CONFIG=full        # or limited

https://github.com/google/draco/blob/master/Makefile.emcc#L9

**Comment by ondys** [comment]
using Makefile.emcc directly is still supported. There was a bug in the Makefile that has been fixed now. Thank you for reporting it!

**Comment by haeric** [comment]
Excellent, works great now! 👍
