### ISSUE TITLE
how to encode obj file to drc file with draco

### ISSUE THREAD

**Issue by lst61924** [google/draco#192]
I can't use nodeJs. so how can I use this tool to encode an obj file!!!thanks.
some piece of code like:
`objLoader.load( file.name,function ( object ) {
                console.log(object);
                // return;
                var indices = [];
                var vertices = [];
                var normals = [];
                object.traverse(function(mesh) {
                    if (mesh instanceof THREE.Mesh) {
                        if (mesh.geometry) {
                            mesh.geometry.attributes.normal.array.forEach(function(n){
                                normals.push(n);
                            });
                            mesh.geometry.attributes.uv.array.forEach(function(u){
                                indices.push(u);
                            });
                            mesh.geometry.attributes.position.array.forEach(function(p){
                                vertices.push(p);
                            });
                        }
                    }
                });
                var mesh = {
                    indices : new Uint32Array(indices),
                    vertices : new Float32Array(vertices),
                    normals : new Float32Array(normals)
                };
                console.log(mesh);
                var encoderModule = DracoEncoderModule();
                console.log(encoderModule);
                var encoder = new encoderModule.Encoder();
                var meshBuilder = new encoderModule.MeshBuilder();
                var dracoMesh = new encoderModule.Mesh();

                var numFaces = mesh.indices.length / 3;
                var numPoints = mesh.vertices.length;
                meshBuilder.AddFacesToMesh(dracoMesh, numFaces, mesh.indices);

                meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.POSITION,numPoints, 3, mesh.vertices);
                if (mesh.hasOwnProperty('normals')) {
                    meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.NORMAL, numPoints, 3, mesh.normals);
                }
                if (mesh.hasOwnProperty('colors')) {
                    meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.COLOR, numPoints, 3, mesh.colors);
                }
                if (mesh.hasOwnProperty('texcoords')) {
                    meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.TEX_COORD, numPoints, 3, mesh.texcoords);
                }
                console.log(meshBuilder);
                var encodedData = new encoderModule.DracoInt8Array();
                console.log(encodedData);
                // if (method === "edgebreaker") {
                  encoder.SetEncodingMethod(encoderModule.MESH_EDGEBREAKER_ENCODING);
                // } else if (method === "sequential") {
                  // encoder.SetEncodingMethod(encoderModule.MESH_SEQUENTIAL_ENCODING);
                // }

                // Use default encoding setting.
                var encodedLen = encoder.EncodeMeshToDracoBuffer(dracoMesh,encodedData);
                console.log(encodedLen);
                console.log(dracoMesh);

                var outputBuffer = new ArrayBuffer(encodedLen);
                var outputData = new Int8Array(outputBuffer);
                for (var i = 0; i < encodedLen; ++i) {
                    outputData[i] = encodedData.GetValue(i);
                }
                encoderModule.destroy(encodedData);
                encoderModule.destroy(encoder);
                encoderModule.destroy(meshBuilder);
                // Write to file. You can view the the file using webgl_loader_draco.html
                // example.
                console.log(outputBuffer);
                console.log(outputData);
                dracoLoader.setVerbosity(1);`

**Comment by lst61924** [comment]
通过draco_encode 压缩的drc文件只能贴一张贴图怎么解决多张贴图的问题呢

**Comment by fanzhanggoogle** [comment]
Hi @lst61924 , could you restate the question so that everyone on the team could understand your question and help. Thanks!
