### ISSUE TITLE
draco_decoder generate a big single mesh? how to avoid it?

### ISSUE THREAD

**Issue by maskerman** [google/draco#195]
Hello, I try to encoder a obj with multi sub mesh. It works; 
draco_encoder -i d:\render.obj -o d:\1.drc --metadata
then when I decoder it, I find the result obj is a big-single-mesh, This is not the result I want. How to avoid it? I use the follow command line:
draco_decoder -i d:\1.drc -o d:\js\1.obj
And I can't find any addition argument to avoid this problem.
How to solve this question? 
Although I can split this obj file to many sub obj file,then encoder them. But it seems not good.

**Comment by ondys** [comment]
Currently, you would have to either separate the mesh into multiple meshes before sending them to Draco or you can separate them after decoding. The decoded mesh stores sub object ids in a generic attribute attribute that can be used to query mapping between points and sub-objects
