### ISSUE TITLE
Recommended lossless compression pass on top of Draco encoded output

### ISSUE THREAD

**Issue by birarda** [google/draco#198]
We've noticed that an additional LZ4 pass on top of the Draco output provides quite an additional gain in compression.

For context, we have content that Draco compresses to ~40% of the original, and the LZ4 pass gets us to ~22% of the original.

Is a lossless compression pass on top of Draco's output recommended or are we missing some configuration of the encoder that would net us additional gains without the LZ4 pass?

We're currently using the default quantization and 0 for both encode and decode speed.

**Comment by birarda** [comment]
Worth noting that we have a bit of a unique use currently. We take FBX files and pull out their geometry  data before re-inserting a custom "DracoMesh" node with the Draco compressed geometry into the FBX.

I can investigate more to determine exactly how much of the savings given by LZ4 is on the Draco encoded data, but am curious to hear your thoughts on a lossless pass on top of Draco data.

**Comment by ondys** [comment]
@birarda In general, some additional compression gain from a lossless compression pass is expected, but from what I observed it was usually in order of a few percent (usually about 1-2%, although I was using gzip and I haven't tried LZ4 which may be better).

It would be certainly interesting to see what portion of this gain is related to Draco and what to the rest of the FBX file.

**Comment by birarda** [comment]
I'll do some tests next week writing the Draco buffer to a file and then running the LZ4 compression on that to see specifically what gains we get on top of the Draco data only.
