### ISSUE TITLE
Questions about compression level

### ISSUE THREAD

**Issue by Saievo** [google/draco#199]
Hi,
After using draco for a while, I found that different compression levels (-cl) were not as described above as README.
README above write:
"In general, the highest setting, 10, will have the most compression but worst decompression speed. 0 will have the least compression, but best decompression speed. The default setting is 5."

This means that the decompression speed of 0 is the fastest, and the size will be the largest, while the decompression speed of 10 is the slowest, but the smallest size.
But with the description does not match, the following is my test data.
 (Decode by HUAWEI mate8, native c ++ decoder)
![image](https://user-images.githubusercontent.com/7145702/30421347-13c1f9ee-996f-11e7-8e51-fb869f788837.png)

cl_level | size | decode_time
0 | 6038979 | 202
1 | 994186 | 346
2 | 994186 | 348
3 | 950992 | 423
4 | 950992 | 439
5 | 853011 | 639
6 | 816817 | 659
7 | 1099512 | 831
8 | 1099512 | 839
9 | 1045419 | 922
10 | 1046828 | 957

There are several questions:
1. The default level is actually 7. (the largest size, poor decompression speed)
2. -cl = 6, size minimum.
3. -cl level is different, but the result is exactly the same? (1 = 2,3 = 4,7 = 8)
4. In this case, why not level 6 as the default level (the smallest size), or level 1 (great speed, relatively small size)
5. Is the test data above the same as your expectations, or is there a problem with my test method?
6. Do I use cl = 1 when is quality lossless compression?

I am asking more questions, very sorry.
But these questions are I am eager to get the answer, very grateful.

**Comment by ondys** [comment]
@Saievo The difference between compression levels is mostly in the algorithms that are selected to compress a mesh. In the current version, the mapping between compression level and used features is pretty much hard-coded and it is entirely possible to find models where higher compression levels result in a poorer compression. Overall, we have observed better compression for higher compression levels for the vast majority of our test models (over thousand meshes).

Could you share your model with us to see if we can use it to tweak our feature selection for different compression levels? Thanks

**Comment by Saievo** [comment]
@ondys  
of course.
I downloaded the .obj file on this site.
https://www.turbosquid.com/FullPreview/Index.cfm/ID/535504
May need to be registered, but the model is free.
When downloading, remember to select .obj format.
![image](https://user-images.githubusercontent.com/7145702/30462840-ea40c500-99fa-11e7-8965-f7a69a1382ee.png)

**Comment by FrankGalligan** [comment]
I think the compression levels for most models have gotten better. I just tested the model above and the size gets smaller as the cl goes up.


Compression Level | Encoded Size
0 | 244535
1 | 125869
2 | 125869
3 | 107705
4 | 107189
5 | 83297
6 | 80464
7 | 77514
8 | 77610
9 | 73807
10 | 72959
