### ISSUE TITLE
Support for streaming mesh compression

### ISSUE THREAD

**Issue by Pombal** [google/draco#20]
Any plans to support progressive encoding of a mesh where the indices only need to be sent once and the attributes can be sent incrementally or with an increased LOD, over time?

If not, could you please provide some guidance on how this would be best achieved in draco?

**Comment by bhouston** [comment]
The easiest solution to using Darco this way would be for you to create your LOD levels and then encode each one as a separate Darco resource.  You can then pick which LOD to load and thus just load a different Darco resource.  If you want to progressively refine, load a low LOD darco resource and then request a high complexity one and upgrade the resource in real-time.

True streaming progressive mesh formats are very different in design than Darco.

**Comment by FrankGalligan** [comment]
I'm closing this issue. If you think this is a feature we should really look at, please re-open.
