### ISSUE TITLE
Texture coordinate verification : javascript/example

### ISSUE THREAD

**Issue by nyue** [google/draco#201]
Hi,

  I am writing out *.drc files via the c++ API

  I am using the javascript/example webpage to load the files to verify that it is written correctly.

  Do you have a way to verify (directly/indirectly) that the texture coordinates are also write correctly. I know the API will always package the data correctly, I want to verify that I am supplying the data correctly to the API for writing.

  On that note, what about attribute of type draco::GENERIC ? Is there a way to view them (e.g. in a spreadsheet)

![attributedataspreadsheet](https://user-images.githubusercontent.com/486172/30602086-6a764d92-9d18-11e7-86bd-942531414e0a.png)

Cheers

**Comment by ondys** [comment]
For texture coordinates, you can modify the example to attach a texture to the created material.

We don't have any simple way to verify the other attributes at this point (apart from manual debugging).
