### ISSUE TITLE
how to build file that use Javascript Encoder API?

### ISSUE THREAD

**Issue by Frankling** [google/draco#203]
when I step to 
const encodedLen = encoder.EncodeMeshToDracoBuffer(dracoMesh,encodedData);
then how I produce the file that like the c++ encoder API did?

**Comment by fanzhanggoogle** [comment]
Hi,

You can take a look at the [NodeJS example](https://github.com/google/draco/blob/1c7e96cba17e1fcbba370b8ec36525aaa839f856/javascript/npm/draco3d/draco_nodejs_example.js#L125). It outputs the buffer of encoded data to a binary file.
