### ISSUE TITLE
Inconsistent types and sizes

### ISSUE THREAD

**Issue by novacrazy** [google/draco#22]
I've noticed in multiple places that `size_t`, `int32_t` and `int64_t` are used interchangeably for indexes and sizes.

For example, in `mesh/mesh.h`:

```cpp
void SetNumFaces(int64_t num_faces);
```

while literally right below that:

```cpp
FaceIndex::ValueType num_faces() const;
const Face &face(FaceIndex face_id);
```

Where `FaceIndex::ValueType` is defined as `int32_t` in `mesh/mesh_indices.h`

`int64_t` is not only signed, but may be larger than `size_t`, which is what all STL containers use for sizes and indexing, and `size_t` is always bigger than `int32_t`. These mean it's possible to overflow `size_t` when calling `SetNumFaces`, and it's possible to overflow `int32_t` when accessing faces or even getting the number of faces.

Likewise, in `point_cloud/point_cloud.h`, and probably other places, `num_points` returns `size_t`, while the internal `_num_points` value is a signed `int32_t`, which doesn't make any sense, unless it's possible to have negative number of points.

In fact, why even choose signed types for sizes and index values at all? Why have "strongly-typed" (as worded in `core/draco_index_type_vector.h`) index types at all, when everything should just be `size_t`?

Additionally, there probably shouldn't be a wrapper for `std::vector` at all.

Edit: Just found this:

```cpp
inline int num_vertices() const { return vertex_corners_.size(); }
inline int num_corners() const { return faces_.size() * 3; }
inline int num_faces() const { return faces_.size(); }
```

which is incredibly dangerous as `faces_.size()` approaches even a THIRD of the max value of a signed `int`

I'm going to start trying to fix these, but I don't know how deep they go.

**Comment by novacrazy** [comment]
I can kind of see why some types are limited to 32-bits if the idea was to maintain decent integer precision with the JavaScript target, and I must admit 3D data with that many points is unlikely, (even the [Lucy](https://graphics.stanford.edu/data/3Dscanrep/lucy-vray_28_mil_poly_hdri_gi.jpg) model is only ~58M points), but still it's probably a good idea to match the STL.

And I see now that negative indices are used as markers for invalid values, I think. Not sure if there is a better way to do that.

**Comment by novacrazy** [comment]
Actually, 32-bit signed integers for the index types are fine for actual geometry data, even OpenGL mostly uses 32-bit types. I was thinking too much about how it's being used in the library in conjunction with the STL containers.

Even still, the fact remains it's possible to add or allocate more points or faces to a point cloud / mesh than the index type supports. I mean, still kind of unlikely, but possible.

**Comment by bhouston** [comment]
I think for web-based graphics 32 integers are fine for the number of vertices, faces, uvs, etc.  As you said OpenGL doesn't support 64 bit indices at this time.  Just for storing 2^32 4byte integers you need 16GB of memory.  And that doesn't include vertices and other data.  In 5 to 10 years sure, if GPU progress continues on its current trend, but I think this isn't a near term requirement.  UInt32 for array lengths and uint16 and uin32 for triangle indices is what I would recommend is sufficient for the next 5 to 10 years except at the ultra high end that doesn't even exist today.

**Comment by novacrazy** [comment]
I agree, but simple consistency with all the types would still be preferred despite what hardware actually supports.

That or actual documentation explaining why some seemingly arbitrary integer types were chosen...

**Comment by ondys** [comment]
We are currently in a process of cleaning up type inconsistencies across Draco library but it may take some time to track them all down. In any case we appreciate any reported problems.

As for using the strongly typed indices, the decision was mostly for coding safety. Draco uses a lot of different types of indices and it is easy to mix them up, especially when the indices are used as function arguments. Strongly typed indices proved to be useful and we were able to catch a lot of bugs thanks to them.
