### ISSUE TITLE
draco_decoder.js 1.1.0 refuses to decode 1.1.0-encoded data

### ISSUE THREAD

**Issue by zellski** [google/draco#220]
Greetings Draco gurus,

For the 1.1.0 release, src/draco/javascript/emscripten/version.js was correctly updated to accept a version string of "1.1.0":
```
  if (version[0] == 1 && version[1] >= 0 && version[1] <= 1)
    return true;
```
 However, in the sprawling chaos that is draco_decoder.js, we still see the older: `if(version[0]==1&&version[1]==0)return true;`

In other words, it looks to me like JS decoder 1.1.0 currently can't cope with data encoded with version 1.1.0. Any chance of getting an official full recompilation of draco_decoder.js?

**Comment by ondys** [comment]
Thanks for the report, we will update the draco_decoder.js with the correct `isVersionSupported()` function. That being said, you should be able to decode .drc files encoded with 1.1.0 files just fine. The decoder itself does not use this function to verify the version.

**Comment by zellski** [comment]
Ahh, I missed the origin of the call. It's being explicitly checked by `DRACOLoader.js`, committed to the three.js library:
```
        THREE.DRACOLoader.getDecoder(this,
            function(decoder) {
              callback(decoder.isVersionSupported(version));
            });
```

Easy enough to hack past, sure. Still, we live in hope that by the time the next formal three.js release comes around, it will include stable Draco support out of the box. It looks like all the pieces are moving into place reliably.
