### ISSUE TITLE
Statically Linking draco encoder for unity

### ISSUE THREAD

**Issue by shubhamagarwal003** [google/draco#221]
I am fairly new to C++. I want to use draco encoder to compress .obj model obtained from Unity. In Unity we can create native plugins by creating a statically linked DLL. So can someone help me how we can create a statically linked DLL for draco encoder?

**Comment by fanzhanggoogle** [comment]
Hi,

Could you give us more details on your use case? Are you working on iOS? As far as I know, on Windows, the native plugin should be a shared library (dynamically linked). And when you build Draco you should be able to get the .so in the build directory.

**Comment by shubhamagarwal003** [comment]
Hi,
I want to do it for both Windows and iOS. But currently I am working on Windows. I created Visual Studio project using  "cmake path/to/draco -G "Visual Studio 14 2015". But when I build it from Visual Studio I didn't got any ".so" in the build directory. Further as far as I know (correct me if I am wrong), ".so" are for Linux and ".dll" are its equivalent in windows.

**Comment by dyangrun** [comment]
Hi,
I just add new function to Draco unity plugin,fix some issues like you happen.
You can try step by this:
1. change draco_unity_plugin project
2. change CMakeLists, fix itme in add_library(dracodec_unity).
3.build  dracodec_unity project, get dll to use

**Comment by FrankGalligan** [comment]
Please [using Draco in Unity](https://github.com/google/draco/tree/master/unity)
