### ISSUE TITLE
can 'draco' encode 3Dmaterial(.obj) by javascript encoder?

### ISSUE THREAD

**Issue by theothersideofgod** [google/draco#227]
can 'draco' encode 3Dmaterial(.obj) by javascript encoder?

I check the example that java-script parts, I only get .drc encoder to .drc , but  i do not get .obj encoder to .drc , thanks

**Comment by fanzhanggoogle** [comment]
Hi @theothersideofgod , currently we don't have direct API to do that, but you can achieve that by writing some obj loading code yourself. e.g:
~~~
function loadObjFile(text) {
  const lines = text.split('\n');
  const vertexRegex =
      /^v\s+([\d|\.|\+|\-|e|E]+)\s+([\d|\.|\+|\-|e|E]+)\s+([\d|\.|\+|\-|e|E]+)/;
  const normalRegex =
      /^vn\s+([\d|\.|\+|\-|e|E]+)\s+([\d|\.|\+|\-|e|E]+)\s+([\d|\.|\+|\-|e|E]+)/;
  const faceRegex =
      /^f\s+(-?\d+)\/\/(-?\d+)\s+(-?\d+)\/\/(-?\d+)\s+(-?\d+)\/\/(-?\d+)(?:\s+(-?\d+)\/\/(-?\d+))?/; 
  const indices = [];
  const vertices = [];
  const normals = [];
  // Go through each line of obj file.
  for (let i = 0; i < lines.length; ++i) {
    const line = lines[i];
    const firstChar = line.charAt(0);
    if (firstChar === 'f') {
      // Parse faces
      // The format is :
      // f vertex/texcoord/normal vertex/texcoord/normal vertex/texcoord normal
      const result = faceRegex.exec(line);
      indices.push(parseInt(result[1]), parseInt(result[3]),
          parseInt(result[5]));
    } else if (firstChar === 'v' && line.charAt(1) === ' ') {
      // Parse vertices
      // The format of a vertex line is:
      // v x y z
      const result = vertexRegex.exec(line);
      vertices.push(parseFloat(result[1]),
          parseFloat(result[2]), parseFloat(result[3]));
    } else if (firstChar === 'v' && line.charAt(1) === 'n') {
      // Parse normals
      // The format is :
      // vn n1 n2 n3
      const result = normalRegex.exec(line);
      normals.push(parseFloat(result[1]),
          parseFloat(result[2]), parseFloat(result[3]));
    }
  }

  const mesh = {
    indices : new Uint32Array(indices),
    vertices : new Float32Array(vertices),
    normals : new Float32Array(normals)
  };
  return mesh;
}

~~~

And then you could compress the mesh using the `MeshBuilder` as in the example.

**Comment by theothersideofgod** [comment]
Thank you so much! fanzhanggoogle,  we will try your solution, thanks a lot

**Comment by a5507203** [comment]
Hi, I found the 
const faceRegex =
      /^f\s+(-?\d+)\/\/(-?\d+)\s+(-?\d+)\/\/(-?\d+)\s+(-?\d+)\/\/(-?\d+)(?:\s+(-?\d+)\/\/(-?\d+))?/; 
has some error, my face format likes this
f 1/1/1 2/2/2 3/3/3
Thank you in advance.

**Comment by ondys** [comment]
The .obj decoder posted above is just a simple tool we use for internal testing of hand-selected .obj files and it is not suitable to be used in production for generic .obj files. For your purposes you may consider using for example [three.js obj loader](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/OBJLoader2.js) that can handle much wider variety of inputs

**Comment by a5507203** [comment]
@fanzhanggoogle
Hi why the
const result = vertexRegex.exec(line);
gives me null, the line looks like this
f 1/1/1 2/2/2 3/3/3
Thank you in advance.

**Comment by zhongmin2015** [comment]
Hi，i will do this yet，can you tell me your email？so we can discuss together。

**Comment by nomercy0** [comment]
hi @fanzhanggoogle  faceRegex is not working ,it is returning null

**Comment by FrankGalligan** [comment]
The code @fanzhanggoogle posted is just an example. Please use [three.js obj loader](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/OBJLoader2.js) if you want to load an obj file.
