### ISSUE TITLE
Crash on obj with texture

### ISSUE THREAD

**Issue by gag** [google/draco#23]
I encounter encoder being crashing on objs with texture(s).

Below is the command output:

> ./draco_encoder -cl 10 -i ~/Desktop/e.obj -o ~/Desktop/e.draco
> Encoder options:
>   Compression level = 10
>   Positions: Quantization = 14 bits
>   Texture coordinates: Quantization = 12 bits
>   Normals: Quantization = 10 bits'
> 
> [1]    39524 segmentation fault  ./draco_encoder -cl 10 -i ~/Desktop/e.obj -o ~/Desktop/e.draco

File that can be used to reproduce the problem: [model.zip](https://github.com/google/draco/files/707630/model.zip)

**Comment by ondys** [comment]
Thank you for the report.

We have fixed the crashing issue, but note that the input file contains several non-triangular faces that are currently not processed correctly by Draco OBJ loader. Also the encoded material ids are encoded but not exported.

**Comment by gag** [comment]
Thank you, @ondys! I suppose the issue is closed by 27cf67cd0f78c17bbcbd0981209566c73ef779cf commit?

**Comment by ondys** [comment]
Yes, it is closed with the caveats listed in my previous post (no support for non-triangular faces and materials are not preserved on obj export). Feel free to open new issues for these.
