### ISSUE TITLE
ply loses vertex property

### ISSUE THREAD

**Issue by maruncz** [google/draco#24]
hi

when i compress and decompress my test file

```ply
format ascii 1.0
comment Author: CloudCompare (TELECOM PARISTECH/EDF R&D)
obj_info Generated by CloudCompare!
element vertex 1410581
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property float scalar_Scalar_field
end_header
```

the `property float scalar_Scalar_field` is not present in decompressed file

**Comment by ondys** [comment]
Hi,

our PLY reader and writer is currently limited to built-in attributes only (positions, colors, ..). Any custom attributes are ignored on load. At this moment, generic attributes can be compressed only when the draco::Mesh is constructed through our API directly, but we plan to add support for more attributes to our PLY decoder in near future.

**Comment by ataber** [comment]
Is this an area where contributions would be welcome?

**Comment by ondys** [comment]
@ataber We always welcome contributions, but depending on what you are planning to do, this project may benefit from a closer cooperation with us.

What we are planning to do is to add support for generic metadata for meshes and attributes. This metadata can be then used to hold for example a property name that could be then preserved during the decoding step.

Adding support for metadata would be certainly a relatively big change to our framework which would require some input from our team.

On the other hand, if the scope would be more narrow.. let's say you would be interested in extending our PlyDecoder to support loading of arbitrary PLY properties as GENERIC attributes, then we would definitely welcome this contribution and it would most likely not require our oversight.

**Comment by ataber** [comment]
I think the more narrow change would fit my application's needs. What do GENERIC attributes look like when decoded in JS? I assume they're exposed as a map from attribute name -> list of values?

**Comment by ondys** [comment]
They are just like any other attribute .. just an array of values for all points of the mesh.
But as I mentioned earlier, we currently don't store attribute names... that's why we cannot preserve general attributes that can be found in ply files (and that's what we want to solve with the added metadata).

What you can do to differentiate GENERIC attributes is to use different custom_ids for each attribute (see `GeometryAttribute::set_custom_id()` method). Custom id is preserved during encoding and it can be used by the javascript client app .. e.g.:

```
for (let i = 0; i < dracoGeometry.num_attributes(); i++) {
    const attribute = wrapper.GetAttribute(dracoGeometry, i)
    if (attribute.attribute_type() === Module.GENERIC) {
      if (attribute.custom_id() === 0) { 
        // attribute is X (e.g. material ids)
      }
      if (attribute.custom_id() === 1) { 
        // attribute is Y (e.g. vertex weights)
      }
      ...
    }
}
```

**Comment by ataber** [comment]
Okay, thanks for the hint :) 

Looking through the code it looks like it would require another large change to store face properties - is that assessment correct?

**Comment by ondys** [comment]
Not necessarily. We already do have support for storing per-face attributes. You can check our `TriangleSoupMeshBuilder` class for an example. It has a method `SetAttributeValuesForFace()` that can be used to set per-face attribute values. The similar approach can be applied in the `PlyDecoder` as well.

**Comment by FrankGalligan** [comment]
I'm closing this issue. If you are still having problems please re-open.

**Comment by GumpXiaoli** [comment]
This issue seems not be fixed yet in the latest master branch. 
Is there any plan recently?

**Comment by sg2nq** [comment]
Hi @ondys @FrankGalligan I'm trying to do something similar, in that I also need to encode other properties like property `float scalar_Scalar_field`. Is there any support for this kind of situation now?
