### ISSUE TITLE
does not compile a draco library for Android

### ISSUE THREAD

**Issue by kaizer1** [google/draco#241]
Here's how to attach a library to my cmake:
add_subdirectory(draco-master ${CMAKE_BINARY_DIR}/draco_build)   
include_directories("${CMAKE_BINARY_DIR}"/) 

Here are the errors I get when compiling:
 
![screen shot 2017-10-17 at 01 57 37](https://user-images.githubusercontent.com/5073933/31638911-b5da0f22-b2de-11e7-8565-42726843e618.png)
 
Android Studio, project API > 18 
  In what I was mistaken. I will be grateful for the help

**Comment by fanzhanggoogle** [comment]
Hi, @kaizer1 what os are you using?

**Comment by kaizer1** [comment]
Hi @fanzhanggoogle os - macOS High Sierra 10.13

**Comment by fanzhanggoogle** [comment]
Thanks for the report. We are aware of this issue and have fixes coming. For temporary fix:
1) Add #include "draco/compression/point_cloud/point_cloud_decoder.h" to decode.h
2) Change "std::log2" to just "log2"
These should make it compile. The fix will go to master soon. 

Let me know if it works for you.

**Comment by kaizer1** [comment]
I did this and did not help. And you do not have an assembled sample library for android?

**Comment by fanzhanggoogle** [comment]
Currently we don't. If you could report your error, I might be able to help further.

**Comment by kaizer1** [comment]
Sorry, very long compile library. It seems all works well, thank you. I made changes to what you said and now everything is ok. And such a question, if possible, I read that it is now possible to download not only the obj format file,  but also the format of gltf, but nowhere can I find more information, you do not know where you can read about it more. Or download a library with this option. Thank you

**Comment by fanzhanggoogle** [comment]
Good to know. Sorry I forgot one more thing you need to enable mesh decoding:
Add `#define DRACO_MESH_COMPRESSION_SUPPORTED` to decode.h.

Regarding the GLTF draco extension, it's WIP. We are working with the community to have support for various loader and exporter. You could start from the Spec here:
https://github.com/KhronosGroup/glTF/pull/874
