### ISSUE TITLE
Adding material Indices to the DracoMesh in Javascript

### ISSUE THREAD

**Issue by syed-usman** [google/draco#242]
Hi, 
I am trying to convert a **THREE.Geometry** Object into a **DracoMesh**

Using the MeshBuilder to add data to **dracoMesh**, how do I add the material indices of the faces to **dracoMesh** using the **MeshBuilder** ? 
 
```

let materialAttrId = meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.GENERIC, numPoints, 1, materialIndices);
meshBuilder.SetMetadataForAttribute(dracoMesh, materialAttrId, "material");

```
If I do it like this I get float values in the GENERIC data, while uncompressing.

Any help will be appreciated :)

**Comment by usmanshah** [comment]
@fanzhanggoogle 
In a comment on [Issue 178](https://github.com/google/draco/issues/178), you mentioned 

> We have internally a simple obj loader to directly load .obj and compress but it's not mature yet. We'll make a n announcement once we publish that.

I am trying to do the exact same thing here and need some help regarding compressing the material IDs. 
**PS** Is there a time frame when this could be released ?

**Comment by ondys** [comment]
only floating point attributes are currently supported by the Javascript API.. you can still store the material ids as floats but the compression is most likely going to be worse and you will have to handle it on the decoder.

We plan to add support for integer attributes in future releases.

**Comment by ondys** [comment]
support for integer attributes has been added in 1.2.4
