### ISSUE TITLE
PLY files issues at reading and writing

### ISSUE THREAD

**Issue by PatOnyx** [google/draco#25]
Hello,

The decoded PLY files generated by the DRACO decoder cannot be read by the famous MeshLab  (http://www.meshlab.net/) viewer.

In addition, some PLY files that can be displayed by meshLab is not supported by rthe DRACO encoder, generating the following messages:
> [patonyx]: ./draco_encoder -i DATA/PLY/horse.ply -o horse.drc -qp 20
> Failed loading the input mesh.

Regards,

PatOnyx

**Comment by PatOnyx** [comment]
1) Please find attached "head1.ply" in the ZIP container which corresponds to one PLY file which is not supported by the DRACO encoder but that can be loaded/diplayed by Meshlab without issue.
[head1.zip](https://github.com/google/draco/files/710282/head1.zip)

2) At the decoder side and according to the command lines below, the "bun_zipper_rec.ply" cannot be read by Meshlab by using you own "bun_zipper.ply" as input mesh. The "bunzipper.ply" file is the one stored in the "testdata" directory provided in the DRACO package.
> ./draco_encoder.exe -i ../../testdata/bun_zipper.ply -o bun_zipper.drc
> ./draco_decoder/exe -i  bun_zipper.drc -o bun_zipper_rec.ply

**Comment by PatOnyx** [comment]
1) Please find attached "head1.ply" in the ZIP container which corresponds to one PLY file which is not supported by the DRACO encoder but that can be loaded/diplayed by Meshlab ([64 bits / v1.3.4] or [64 bits / v2016.12])  without issue.
[head1.zip](https://github.com/google/draco/files/710282/head1.zip)

2) At the decoder side and according to the command lines below, the "bun_zipper_rec.ply" cannot be read by Meshlab ([64 bits / v1.3.4] or [64 bits / v2016.12]) by using your own "bun_zipper.ply" as input mesh. The "bunzipper.ply" file is the one located in the "testdata" directory provided in the DRACO package.
> ./draco_encoder.exe -i ../../testdata/bun_zipper.ply -o bun_zipper.drc
> ./draco_decoder/exe -i  bun_zipper.drc -o bun_zipper_rec.ply

**Comment by Codersadis** [comment]
I‘ve met the same issue. 
It seems that the decoded .ply file has different file size with the input .ply file.

**Comment by ondys** [comment]
We found a problem with .ply encoding on windows builds. It has been fixed and the decoded files should now be readable by Meshlab. Thanks for the report!

As for decoding the "head1.ply". The file is encoded in "format binary_big_endian" which is not supported by Draco. Currently, Draco supports only "format binary_little_endian" and "format ascii". You can probably convert your mesh to the little endian format in Meshlab. We plan to add support for the big endian format in future.
