### ISSUE TITLE
Encoding a .obj along with its associated .mtl

### ISSUE THREAD

**Issue by farzaa** [google/draco#256]
Hey there all. I'm a bit new to the world of 3D models so sorry if I say something grossly incorrect :)!

Currently I'm using the command line tool like so to encode
`./draco_encoder -i testdata/in_model.obj -o out.drc`

And than to decode I do
`./draco_decoder -i out.drc -o out_model.obj`

in_model.obj is a custom model I created using AutoDesk ReMake which basically allows me to take a bunch of pictures of an object, run it through their software, and it will output a .obj, .mtl, and .jpg with the textures. 

I run draco on in_model.obj and then decode the .drc to get out_model.obj. All the information related to the .mtl references on in_model.obj are gone when I open out_model.obj in a text editor. 

I mean lines such as
`mtllib untitled.mtl` or `usemtl Material_0` or `usemtl Material` 

Disappear when viewing the decoded .obj in a text editor. 

Is this behavior intended? If so, is there some solution where I can preserve the .mtl references? 

Also, if there is any solution for the .jpg associated with the .mtl file to also be encoded in the .drc, that'd be cool! Let me know and thanks all.

Thanks!

**Comment by ondys** [comment]
@farzaa You can try encoding the model with `--metadata` flag. In that case the reference to the material names should be preserved. There is no simple way how to store the .jpg in the encoded .drc at this time.

**Comment by farzaa** [comment]
Thanks!! :)

**Comment by Rakiah** [comment]
@ondys how would this get retrieved in the Unity plugin ?

**Comment by aruni445** [comment]
> Thanks!! :)

Hi @farzaa ,  I hope you are doing well. I am facing the same issue which you have encountered a long back. If you have the answer please help me out.

I have converted the .obj file to .drc. While loading the .drc file in threejs, I am unable to get the material(.mtl). Is there any way to get the material(.mtl file which is present in the row .obj)

**Have you succeeded to get the .mtl info in .drc file as suggested by @ondys** 

Thanks
