### ISSUE TITLE
compress THREE.BufferGeometry  to DracoMesh and back?

### ISSUE THREAD

**Issue by Frankling** [google/draco#267]
@fanzhanggoogle  I have tried to compress THREE.BufferGeometry that just including attributes, then get the outputdata. However when I decode this outputdata I got dracoGeometry that have 0 attributes?  Is there something mistake ?
`<pre>var mesh = {normals:obj.attributes.normal.array,vertices:obj.attributes.position.array,uv:obj.attributes.uv.array}
var encoderModule = DracoEncoderModule();

var encoder = new encoderModule.Encoder();
var meshBuilder = new encoderModule.MeshBuilder();
var dracoMesh = new encoderModule.Mesh();
var numPoints = mesh.vertices.length;
meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.POSITION,
  numPoints, 3, mesh.vertices);
meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.NORMAL, numPoints, 3, mesh.normals);
meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.TEX_COORD, numPoints, 2, mesh.uv);
var encodedData = new encoderModule.DracoInt8Array();
encoder.SetAttributeQuantization(encoderModule.POSITION, 10);
encoder.SetEncodingMethod(encoderModule.MESH_EDGEBREAKER_ENCODING);

var encodedLen = encoder.EncodeMeshToDracoBuffer(dracoMesh,encodedData);
var outputBuffer = new ArrayBuffer(encodedLen);
var outputData = new Int8Array(outputBuffer);
for (let i = 0; i < encodedLen; ++i) {
    outputData[i] = encodedData.GetValue(i);
}

//decode here
var dracoDecoder=new DracoDecoderModule();
var buffer = new dracoDecoder.DecoderBuffer();
var rawBuffer=outputData.buffer
buffer.Init(new Int8Array(rawBuffer), rawBuffer.byteLength);
var decoder = new dracoDecoder.Decoder();
var geometryType = decoder.GetEncodedGeometryType(buffer);
var dracoGeometry = new dracoDecoder.Mesh();
var decodingStatus = decoder.DecodeBufferToMesh(buffer, dracoGeometry);</pre>`

**Comment by fanzhanggoogle** [comment]
Hi @Frankling , sorry for the late reply. Have you solved your issue?

**Comment by Frankling** [comment]
@fanzhanggoogle  not yet, still working on it.

**Comment by fanzhanggoogle** [comment]
@Frankling I realized that you are actually compressing a point cloud. We don't currently expose the point cloud encoding API in Javascript, e.g. EncodePointToDracoBuffer(). But if you only want to decode a point cloud, you should be able to get by for example:
~~~
var dracoGeometry = new decoderModule.PointCloud();
status = decoder.DecodeBufferToPointCloud(buffer, dracoGeometry);
~~~

**Comment by Frankling** [comment]
![qq 20171117103606](https://user-images.githubusercontent.com/5674121/32926669-60cea232-cb83-11e7-8bbd-403fc37b06f5.jpg)
