### ISSUE TITLE
Properties missed after decoded from .drc

### ISSUE THREAD

**Issue by chenkandewang** [google/draco#290]
I  tried to encode the bun_zipper.ply using encode tool. When I recovering the .ply file from .drc using decode tool, I found that following properties were missed: 
property float confidence
property float intensity

I just followed the guideline as:
./draco_encoder -i testdata/bun_zipper.ply -o out.drc
&
./draco_decoder -i out.drc -o bun_zi_rec.ply

Anybody know what's the reason? Thanks!

**Comment by ondys** [comment]
our .ply decoder currently does not process custom properties. We plan to add support for this in future releases.

**Comment by chenkandewang** [comment]
Got it. Thanks.
