### ISSUE TITLE
draco_encoder_nodejs.js didnt get updated during 1.2 build process.

### ISSUE THREAD

**Issue by zynga-jpetersen** [google/draco#291]
It doesnt look like draco_encoder_nodejs.js got updated during these changes, even though draco_encoder.js did get updated (and it looks like the c++ for encoding it got updated as well).

From reading draco_encoder_nodejs.js it doesnt look like it uses draco_encoder.js, so it looks like it needs to get updated separately?

Thanks and great project.

**Comment by fanzhanggoogle** [comment]
Hi @zynga-jpetersen , thanks for reporting the issue. The npm package has been updated. You can checkout [here](https://www.npmjs.com/package/draco3d).

I'll close this issue then.

**Comment by zynga-jpetersen** [comment]
Thanks!
