### ISSUE TITLE
Inconsistently seeing THREE.DRACOLoader: Decoding failed: Not a Draco file.

### ISSUE THREAD

**Issue by zynga-jpetersen** [google/draco#292]
Its followed up with error "THREE.DRACOLoader: Unknown geometry type." 

My draco compressed gltf model generally loads, so I'm not sure what might be triggering this race condition.

I do load multiple models around the same time, so I'm now as I write this wondering if depending on those network conditions how at the same time they are.

For each of those scenes I am using separate GLTFLoaders and DRACOLoader, so provided there arent any statics, that should be fine.

	let loader = new THREE.GLTFLoader();
	loader.setDRACOLoader(new THREE.DRACOLoader(undefined, { type: 'js' }));

And I'm using the GLTFLoader from:
https://github.com/donmccurdy/three.js/blob/feat-gltf-draco-extension-v4/examples/js/loaders/GLTFLoader.js

This is in Chrome.

Thanks.

**Comment by zynga-jpetersen** [comment]
I'm pretty sure this is actually a result of the https://github.com/fanzhanggoogle/gltf-pipeline/tree/draco_compression_extension renaming the .bin file to 0.bin and me not correctly handling the fact that depending on how long some stuff takes to load I've got 2 things named 0.bin . That tool doesnt seem to produce a valid glb any more, so I'll look at renaming the binary file to its original name and update the reference in the gltf.

**Comment by zynga-jpetersen** [comment]
Yeah its an issue with the way I'm loading the assets from a tar file. Thanks!

**Comment by tomermesser** [comment]
Just wanted to mention here that I a, using the draco compression as well with draco. 
My solution for that error was to produce just 1 file (.gltf) and not 2 as before (.gltf + .bin).
I converted + compressed it from GLB to GLTF using those parameres:

```
    const gltfPipelineExecutable = path.join(
      __dirname,
      "node_modules",
      "gltf-pipeline",
      "bin",
      "gltf-pipeline.js"
    );
    const gltfPipeline = spawn("node", [
      gltfPipelineExecutable,
      "-i",
      intermediateFilePath,
      "-o",
      outputFilePath,
      "-d",
      "--keepUnusedElements",
      "--draco.compressionLevel",
      compressionLevel.toString(),
      "--embed", // Ensure everything remains embedded in the .gltf
    ]);
```
