### ISSUE TITLE
use of open GL in visual studio with the help of cmake.

### ISSUE THREAD

**Issue by Abhi-1725** [google/draco#296]
Hello team,

Actually i want to measure depth of a 3d image using a ZED camera. also i want to use other features like spatial mapping , positional tracking. I have installed visual studio 2017 community.  I want to use open GL window so that i can show coordinates and 3d images.  To use Open GL i need cmake GUI so that its easier to convert .cpp files to mex files / other  files. 
 the snap shot of the error that i have got after configuring CMake application is below 

![cmake output log](https://user-images.githubusercontent.com/33417745/32848872-3e6e7f08-ca36-11e7-9d80-c9efd384f383.JPG)

I am using Visual studio , CMake and open GL for the first time. I will be happy to use any one of them Open CV /  Open GL /  point cloud library for the above senario.  
I have changed the versions and other specifications in the existing CMakeLists.txt file that is supposed to be there in the project folder.

ERROR:

"C:\Users\ada24\source\repos\Depth\Depth\Depth\build\CMakeFiles\3.10.0-rc4\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(Link target) -> 
  LINK : fatal error LNK1181: cannot open input file 'gdi32.lib' [C:\Users\ada24\source\repos\Depth\Depth\Depth\build\CMakeFiles\3.10.0-rc4\CompilerIdC\CompilerIdC.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.75

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: 
[CMakeError.log](https://github.com/google/draco/files/1475602/CMakeError.log)
[CMakeOutput.log](https://github.com/google/draco/files/1475604/CMakeOutput.log)
[CMakeLists.txt](https://github.com/google/draco/files/1475607/CMakeLists.txt)

Id flags:  

The output was:

**Comment by tomfinegan** [comment]
C compiler test failure:

> Build FAILED.
> 
> "C:\Users\ada24\source\repos\Depth\Depth\Depth\build\CMakeFiles\3.10.0-rc4\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
> (Link target) -> 
>   LINK : fatal error LNK1181: cannot open input file 'gdi32.lib' [C:\Users\ada24\source\repos\Depth\Depth\Depth\build\CMakeFiles\3.10.0-rc4\CompilerIdC\CompilerIdC.vcxproj]
> 
>     0 Warning(s)
>     1 Error(s)

C++ compiler test failure:

Build FAILED.

> "C:\Users\ada24\source\repos\Depth\Depth\Depth\build\CMakeFiles\3.10.0-rc4\CompilerIdCXX\CompilerIdCXX.vcxproj" (default target) (1) ->
> (Link target) -> 
>   LINK : fatal error LNK1181: cannot open input file 'gdi32.lib' [C:\Users\ada24\source\repos\Depth\Depth\Depth\build\CMakeFiles\3.10.0-rc4\CompilerIdCXX\CompilerIdCXX.vcxproj]
> 
>     0 Warning(s)
>     1 Error(s)

Probable fix:
https://stackoverflow.com/questions/33599723/fatal-error-lnk1104-cannot-open-file-gdi32-lib

This is not a draco bug. Your environment is not correctly configured.

**Comment by Abhi-1725** [comment]
hello team,

i have configured as per your suggestion. still i am getting the same error. Kindly assist.
![cmake output](https://user-images.githubusercontent.com/33417745/32853273-6cd3c8dc-ca43-11e7-8cd3-fccd07d2020d.JPG)
[CMakeOutput.log](https://github.com/google/draco/files/1475874/CMakeOutput.log)
[CMakeError.log](https://github.com/google/draco/files/1475875/CMakeError.log)

**Comment by tomfinegan** [comment]
CMakeError.log still contains the same link errors for gdi32.lib. This is not a Visual Studio support forum, but this [page](https://developercommunity.visualstudio.com/content/problem/59748/visual-studio-2017-v152-264306-still-missing-gdi32.html) from the Visual Studio support forum suggests the following work around:

1. Launch Visual Studio Installer
2. Go to Individual Components
3. Make sure Windows 10 SDK (10.0.15063.0) for Desktop C++ or whatever SDK you want to target is installed
4. Go to your project properties page and make sure the correct Windows SDK is targeted.

**Comment by Abhi-1725** [comment]
Hello team,

thanks a lot for the previous help. 
i have another issue 
 which says : 

Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Using Win32 for window creation

![cmake 1](https://user-images.githubusercontent.com/33417745/32978143-deb1e206-cc44-11e7-8a2d-057075b53f98.JPG)

could you please assist.

**Comment by Abhi-1725** [comment]
Hello team,

i have another issue
which says :

Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE
Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
Using Win32 for window creation

I am using windows 10, visual studio 2017 and glfw 3.2.1

![image](https://user-images.githubusercontent.com/33417745/32980977-09e6cbec-cc79-11e7-8235-3be076b63928.png)

[CMakeOutput.log](https://github.com/google/draco/files/1484622/CMakeOutput.log)
[CMakeError.log](https://github.com/google/draco/files/1484623/CMakeError.log)

could you please assist.
