### ISSUE TITLE
How to Render Mesh in Native Android App?

### ISSUE THREAD

**Issue by mekya** [google/draco#298]
Hi,

How can it be possible to render [Mesh](https://github.com/google/draco/blob/master/src/draco/mesh/mesh.h) on OpenGL Surface in native Android app?

Is there anyone that can give a clue about that?

Regards,
A. Oguz

**Comment by Zephyrox** [comment]
Decode the draco file with the API, using draco::Decoder class. The create vertices and indices buffers from the extracted Meshes.

**Comment by mekya** [comment]
Thank you for the answer,

In which platform or surface we can show the mesh, do you know any sample app for that?

**Comment by Zephyrox** [comment]
Check any opengl tutorial on native android, example:
http://www.learnopengles.com/calling-opengl-from-android-using-the-ndk/
After you have a basic rendering working you should be able to create vertices and indices buffers from the draco Mesh object.

**Comment by mekya** [comment]
Yeah doing something like that. Also playing ply files in order.

Looking for some easy tools to do that

thank you for feedbacks.

![screenshot_2017-12-28-08-14-11](https://user-images.githubusercontent.com/3456251/34400924-63d72ff0-eba7-11e7-980f-fbc34a3221c2.png)
