### ISSUE TITLE
Cmake not finding vulkan

### ISSUE THREAD

**Issue by Abhi-1725** [google/draco#299]
Hello team,

its urgent. kindly do the needful ASAP

i have another issue
which says :

Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE
Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
Using Win32 for window creation

I am using windows 10, visual studio 2017 and glfw 3.2.1

image

CMakeOutput.log
CMakeError.log

could you please assist.

**Comment by tomfinegan** [comment]
@Abhi-1725 

This is not a general support forum. If you are having problems using Vulkan with CMake I suggest looking at Vulkan and CMake documentation to determine the cause of your issue.
