### ISSUE TITLE
Linking error with VS2017

### ISSUE THREAD

**Issue by eddiz** [google/draco#300]
Hello, 

the current master branch does not link with the default settings on Windows 10, Visual Studio 2017

CMake (ok)
Compiling (ok)
Linking (see below:)

./draco/compression/attributes/prediction_schemes/prediction_scheme_decoder_factory.h(107): error C2535: 'std::unique_ptr<draco::PredictionSchemeDecoder<DataTypeT,TransformT>,std::default_delete<_Ty>> draco::MeshPredictionSchemeDecoderFactory<DataTypeT>::operator ()(draco::PredictionSchemeMethod,const draco::PointAttribute *,const TransformT &,const MeshDataT &,uint16_t)': member function already defined or declared
        with
        [
            _Ty=draco::PredictionSchemeDecoder<DataTypeT,TransformT>
        ]
./draco/compression/attributes/prediction_schemes/prediction_scheme_decoder_factory.h(47): note: see declaration of 'draco::MeshPredictionSchemeDecoderFactory<DataTypeT>::operator ()'
./draco/compression/attributes/prediction_schemes/prediction_scheme_decoder_factory.h(116): note: see reference to class template instantiation 'draco::MeshPredictionSchemeDecoderFactory<DataTypeT>' being compiled
./draco/mesh/corner_table_indices.h(33): note: see reference to class template instantiation 'draco::IndexType<int32_t,draco::CornerIndex_tag_type_>' being compiled
./draco/mesh/corner_table_indices.h(31): note: see reference to class template instantiation 'draco::IndexType<int32_t,draco::VertexIndex_tag_type_>' being compiled
./draco/mesh/mesh_indices.h(27): note: see reference to class template instantiation 'draco::IndexType<int32_t,draco::FaceIndex_tag_type_>' being compiled
./draco/attributes/geometry_indices.h(34): note: see reference to class template instantiation 'draco::IndexType<int32_t,draco::AttributeValueIndex_tag_type_>' being compiled

**Comment by robertlong** [comment]
I'm seeing the same thing in `1.2.2` and `1.2.1`. Version `1.2.0` compiles correctly.

**Comment by FrankGalligan** [comment]
We can reproduce this.
