### ISSUE TITLE
Getting segmentation fault for some .obj files with the latest draco build

### ISSUE THREAD

**Issue by Dharnidharka** [google/draco#304]
I an getting a segmentation fault while trying to convert an object file to draco. I rebuilt draco today, so it's not related to https://github.com/google/draco/issues/57

The output after running the draco_encoder is:
Encoder options:
  Compression level = 7
  Positions: Quantization = 14 bits

Segmentation fault: 11

Attached is one file which is giving the error. I got this error in 6 files out of 100 that I tried to convert. (Added .txt extension to be able to upload)

[test.obj.txt](https://github.com/google/draco/files/1499208/test.obj.txt)

**Comment by Ni55aN** [comment]
The same problem on Ubuntu 16 x64. Outputs an error

> Іegmentation fault (core dumped)

**Comment by ondys** [comment]
@Dharnidharka Thanks for the report. The input file you attached contains line segments and no faces and the current Draco version cannot process it. It should still not crash, which will be fixed, but even after the fix, all the line segments are going to be ignored.

@Ni55aN Thanks, I'll look into this case as well (in this case I believe we can simply ignore the unused normal indices)

**Comment by ondys** [comment]
These issues should be fixed in the latest release (1.2.4)
