### ISSUE TITLE
Per-face attributes

### ISSUE THREAD

**Issue by spootsy** [google/draco#311]
Hi,

I'm trying to create Draco meshes which have per-face attributes, but I can't find any good examples of how to do this.

The only example I can see is in the triangle_soup_mesh_builder class, which creates a unique set of positions for each face, and then assigns the same value to each of the points for the face attribute. In my use case, faces are sharing points, so this doesn't work, because the point attribute values are overwritten by different faces.

Is there any other way I can achieve this? I tried just encoding a series of unmapped attribute values, making sure the attribute indices matched the face indices, but I couldn't get it working.

Any suggestions or pointers would be great

**Comment by spootsy** [comment]
Sorry for the bump, but are there any suggestions/advice on how to do per-face attributes?

I can try denormalizing all the points for each face if there's no other way to include a face-attribute association, but is reading the values back in then just like for any other point attribute?

**Comment by ondys** [comment]
At this moment, the only way to do that is using the same approach as the TriangleSoupMeshBuilder. Note that it doesn't prevent you from sharing attribute values between points. In Draco, all attributes contain a map between Point indices and Attribute Value indices and multiple points can be mapped to the same attribute values. This will happen automatically when you use TrangleSoupMeshBuilder (input values will get deduplicated used to compute mapping between the point indices and attribute values). 

See for example this simple [case](https://github.com/google/draco/blob/451b56f4c98b3725d052afce4d97436c36eabc42/src/draco/mesh/triangle_soup_mesh_builder_test.cc#L99) where a cube is created with per-face attribute that has a different value for each of the cube's face. This will construct a mesh with 24 points (3 points for each vertex of the cube), but the mesh will still have only 8 position attribute values where 3 points are always mapped to a single attribute value.
