### ISSUE TITLE
The difference of compression ratio via javascript encoder and the linux tools 

### ISSUE THREAD

**Issue by Frankling** [google/draco#313]
|-----------------|----------------|
 |         file           |       size          |
 |-----------------|----------------| 
 |        original    |      11.2 MB     |
 |-----------------|----------------| 
 |    js encoder    |       7.02 MB    |
 |-----------------|----------------| 
 |    linux cmd tools  |     290 KB |
 |-----------------|----------------| 
The difference of compression ratio via javascript encoder and the linux command is so big?
how to reduce the compress rate via javascript encoder API
[file.zip](https://github.com/google/draco/files/1546468/file.zip)

**Comment by slertness** [comment]
why close？
