### ISSUE TITLE
Unity decoder missing uvs and normals

### ISSUE THREAD

**Issue by usefulslug** [google/draco#314]
The Unity decoder is missing decoding for uvs and normals. Normals are being calculated instead of decoded, which does not yield the same results as the normals may have been modified per vertex.

**Comment by fanzhanggoogle** [comment]
Hi, we are updating the loader to support texture coordinates and normals. Hopefully we can get it in by next week.

**Comment by RomainMilbert** [comment]
Is there anything new with this issue? Unity crashes whenever I try to import a mesh with texcoords in it (OBJ format). Removing them works fine though.

**Comment by ondys** [comment]
support for texture coordinates and normals has been added in the 1.2.5 release. Can you send us a test model with steps to reproduce your issue? Thanks

**Comment by RomainMilbert** [comment]
[Encoded Bunny](https://drive.google.com/file/d/1eav4UodHZfGsB1RiOogyUlZ_ZbtsHYVk/view?usp=sharing) on Windows with the command `draco_encoder.exe -i bunny.obj -o bunny.drc -cl 10 --metadata` (this fails with other compression levels and without metadata as well anyway). 

Draco has been built statically in Release/x64 with the last version available here on GitHub.

Basic example code:
```cs
using System.Collections.Generic;
using System.IO;
using UnityEngine;

public class UncompressTest : MonoBehaviour {

  private void Start() {
    var meshData = File.ReadAllBytes("bunny.drc");

    var meshes = new List<Mesh>();
    var loader = new DracoMeshLoader();
    var faceCount = loader.DecodeMesh(meshData, ref meshes);

    if (faceCount > 0) {
      foreach (var mesh in meshes) {
        var newGameObj = new GameObject("bunny" + mesh.GetInstanceID());
        newGameObj.AddComponent<MeshFilter>().mesh = mesh;
        newGameObj.AddComponent<MeshRenderer>().material.color = Color.gray;
      }

      Debug.Log("Mesh imported!");
    } else {
      Debug.LogWarning("Wrong data received (no face available)");
    }
  }
}
```
Doesn't go past the `DecodeMesh()` line when debugging (`Unity has stopped working`, no log output in this case).

When importing then exporting back the [OBJ without UVs](https://drive.google.com/file/d/12O5RjdBDcp6ud21M01HOc73jjrs_D2c_/view?usp=sharing) (in Blender or MeshLab), Draco has no problem decoding it.
