### ISSUE TITLE
Unity3D bunny.bytes on Resources folder doesn't load

### ISSUE THREAD

**Issue by AnaRhisT94** [google/draco#316]
Hey there,
I imported the unity folder into a new project, places the bunny.drc file into Resources folder under Assets.
Renamed **bunny** to **bunny.bytes**

And I'm getting the **error**:
```
Didn't load file!
UnityEngine.Debug:Log(Object)
DracoMeshLoader:LoadMeshFromAsset(String, List`1&) (at Assets/unity/DracoMeshLoader.cs:119)
DracoDecodingObject:Start() (at Assets/unity/DracoDecodingObject.cs:35)
```

**Comment by fanzhanggoogle** [comment]
Hi, could you try putting DracoMeshLoader.cs and DracoDecodingObject.cs under Assets/ instead of Assets/unity? Not sure if that's the issue, but worth a try.

**Comment by AnaRhisT94** [comment]
I just did. same result.
```
Didn't load file!
UnityEngine.Debug:Log(Object)
DracoMeshLoader:LoadMeshFromAsset(String, List`1&) (at Assets/DracoMeshLoader.cs:119)
DracoDecodingObject:Start() (at Assets/DracoDecodingObject.cs:35)
```

**Comment by FrankGalligan** [comment]
Hi,

Could you list the files in the Resources folder and paste the output?

**Comment by AnaRhisT94** [comment]
Hey Frank, I just have the bunny.drc file in my Resources folder. When I changed it to bunny.bytes, it appears now as bunny.drc.bytes in the Explorer, and as bunny.drc at the Resources folder inside Unity Editor.

**Comment by FrankGalligan** [comment]
Can you change the name to "bunny.bytes" in the explorer, which should
change the name to bunny inside Unity editor. Then try again?

**Comment by AnaRhisT94** [comment]
I've changed "bunny" to "bunny.bytes" in the explorer, it's now "bunny.bytes.drc" there. It doesn't work.

**Comment by AnaRhisT94** [comment]
[bunny.zip](https://github.com/google/draco/files/1577403/bunny.zip)
This is the file I'm using.

**Comment by FrankGalligan** [comment]
OK I just tried with your file and it worked for me.

For this to work the file should be named "bunny.bytes" in the Resources
folder in explorer window.

Can you delete the files in Resources folder from explorer? Then run:
cp bunny.drc <Link to your project>/Assets/Resources/bunny.bytes

Then try and render in Unity?

**Comment by AnaRhisT94** [comment]
Deleted everything in the Resources folder.
CMD -> Run -> copy bunny.drc C:\Users\ii\Documents\Draco\Assets\Resources\bunny.bytes (Using Windows 10).
Error:
The system cannot find the file specified.

Can you upload your project as .unitypackage in a .zip file please?

**Comment by fanzhanggoogle** [comment]
Hi, does the error "The system cannot find the file specified." comes from CMD or in Unity?

**Comment by AnaRhisT94** [comment]
CMD

בתאריך 21 בדצמ׳ 2017 02:29,‏ "FanZhang" <notifications@github.com> כתב:

**Comment by fanzhanggoogle** [comment]
I guess you need to make sure both bunny.drc and C:\Users\ii\Documents\Draco\Assets\Resources\ exists where you do the copy command?

**Comment by AnaRhisT94** [comment]
I did that, still doesn't fix.

**Comment by AnaRhisT94** [comment]
I dragged and dropped 'unity' folder into my project. and didn't do anything except attaching the DracoDecodingObject.cs to an empty gameobject.

Then grabbed the bunny.drc from <My path>\draco-master\javascript\npm\draco3dgltf\draco.drc
into the Resources folder which is inside Assets. and after that I change draco to draco.bytes which is now draco.bytes.drc in the Resources folder. Resulted in an error 'Didn't load file'..

**Comment by AnaRhisT94** [comment]
Update:
I renamed bunny.drc to bunny.drc.bytes and there's bunny.prefab appeared in my resources. and bunny asset. But it still doesn't load them in run-time.

**Comment by AnaRhisT94** [comment]
Update:
I tried again, in Resources folder, changed bunny.drc to bunny.bytes and it worked now.

**Comment by FrankGalligan** [comment]
Awesome!

Sorry about the confusion. We are going to redo the readme to make it less
confusing.

Frank
