### ISSUE TITLE
Make it possible for API users to determine which Draco features are enabled.

### ISSUE THREAD

**Issue by pps83** [google/draco#323]
For more details see [this comment.](https://github.com/google/draco/commit/a7c0d80a71ce08f51d2e6b6aabf30778d76e4c9a#diff-4da73ff69f68c7e79d812c7615d8dfbaR98)

In short, all the defines that control code inclusion in public darco headers must be set in a config header file, so that when these darco headers are used from some other project the other project would have the same defines as the darco lib.

**Comment by tomfinegan** [comment]
This is in progress: Should be available for next release. Note: name will be draco_features.h.
