### ISSUE TITLE
In the DRACOLoader.js file, how can i assign the value of posAttributeData to geometryBuffer.vertices one time

### ISSUE THREAD

**Issue by baozeyang2016** [google/draco#327]
not use for many times, in order to save time

**Comment by ondys** [comment]
I'm not sure if I understand the question. Values from attributeData are copied to geometryBuffer using GetValue() method, one by one. What problem are you trying to solve?

**Comment by baozeyang2016** [comment]
First of all, very thanks your reply, my question is the time that Values from attributeData are copied to geometryBuffer using GetValue() method one by one is too large, i want to decrease the time, if there is a function  realize this？please help @ondys

**Comment by ondys** [comment]
No there is currently no other way to copy the data. Are you sure it is the bottleneck though? Based on our internal measurements this was usually low on the list compared to other parts of the code.

**Comment by baozeyang2016** [comment]
My application scene is following: browser and version is firefox 57.0.4(64bit), computer system is win10(64bit), ply data num 29k vertex 54k face. the part of indices decoding is 
for (let i = 0; i < numFaces; ++i)
          {
                  wrapper.GetFaceFromMesh(dracoGeometry, i, ia);
                  index = i * 3;
                  geometryBuffer.indices[index] = ia.GetValue(0);
                  geometryBuffer.indices[index + 1] = ia.GetValue(1);
                  geometryBuffer.indices[index + 2] = ia.GetValue(2);
          }
and the time of this part wasting is 40-50ms, it is too long for real-time playing. I use geometryBuffer.indices.fill、 geometryBuffer.indices.push and geometryBuffer.indices.set to accerate, but that not work. Are there any other improvements, please guide me.

**Comment by baozeyang2016** [comment]
My application scene is following: browser and version is firefox 57.0.4(64bit), computer system is win10(64bit), ply data num 29k vertex 54k face. the part of indices decoding is
for (let i = 0; i < numFaces; ++i)
{
wrapper.GetFaceFromMesh(dracoGeometry, i, ia);
index = i * 3;
geometryBuffer.indices[index] = ia.GetValue(0);
geometryBuffer.indices[index + 1] = ia.GetValue(1);
geometryBuffer.indices[index + 2] = ia.GetValue(2);
}
and the time of this part wasting is 40-50ms, it is too long for real-time playing. I use geometryBuffer.indices.fill、 geometryBuffer.indices.push and geometryBuffer.indices.set to accerate, but that not work. Are there any other improvements, guide me please .

**Comment by baozeyang2016** [comment]
There is another problem i want to ask for,  Whether the number of faces is larger than the number of vertices It means that the ply model is redundant

**Comment by baozeyang2016** [comment]
how much is the your test time about this part ? can you tell me? please...

**Comment by FrankGalligan** [comment]
Added GetAttribute<type>ForAllPoints() functions.

See https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/draco_web_decoder.idl#L212
