### ISSUE TITLE
Can i  ues draco.js  Compress  .obj file ?

### ISSUE THREAD

**Issue by zhongmin2015** [google/draco#339]

**Comment by ondys** [comment]
we do provide a javascript version of draco encoder but it currently does not provide any capabilities related to loading third party file formats such as .obj. I.e., you would have to use your own .obj parsing library and convert the output to a draco mesh that can be handled by the javascript encoder API.

On the other hand, for C++,  we have a build-in obj decoder that can convert .obj files into draco meshes (we may create a javascript version in future but it is currently not on our roadmap).

**Comment by prabhatmishra33** [comment]
@ondys  now do we have any feature with javascript which converts .obj file to .drc ?
