### ISSUE TITLE
Expose separate indices to JavaScript decoder

### ISSUE THREAD

**Issue by syed-usman** [google/draco#343]
Question: 
When decoding, is there a flag we can provide to DRACO to make it output an indexed geometry instead of a non-indexed Geometry?

Does Draco perform any conversions between indexed/ non-indexed geometry when processing(both while encoding and decoding) the geometry data?

I have created an Angular5 service to compress/uncompress/export a THREE.Group using Draco. The problem is that when I convert the file back to an OBj I get three times as much vertices (non-indexed geometry).

Here is the service: https://gist.github.com/syed-usman/652839619e54a93d46d770c49631db95

**Comment by ondys** [comment]
Draco always uses indexed geometry (both internally and as an output). I.e., the output geometry attributes are indexed by the indices defined on mesh faces (`GetFaceFromMesh` function).

One difference between what Draco and .obj (at least in Javascript) is that .obj uses multiple indices for each vertex (one for positions, another for normals and texture coordinates) while Draco outputs only one index for all attributes (which is the way how the geometry is handled by GPU APIs or three.js). This may cause number of vertices (indices) to grow in case the mesh contains a lot of attribute seams on the non-position attributes.

Internally (and using the C++ API) Draco actually represents the mesh the same way as .obj by having separate indices for all attributes. We can potentially expose this in the Javascript API as well if that's what you need.

**Comment by DrJohnDale** [comment]
Hello, I am working on this issue with Syed.

I am not sure exactly what you mean by multiple indices or one index per attribute.  By one index per attribute do you mean that in the faces section a vertex will have the same numbers for the v/vn/vt. E.G. Draco will give out after decompression 1/1/1 but never 1/2/3? This would also imply that a vertex index is never used more than once, i.e. each face has unique vertices, normals and textures.

I am also correct that in understanding that internally Draco holds the faces in the structure 1/2/3 i.e. without the vertices being duplicated?  If we could access the data in this structure it would be useful for us.

**Comment by ondys** [comment]
our javascript decoder always provides the same index for all attributes on any given face corner. That can be interpreted in the obj format as `f a/a/a b/b/b c/c/c`  (as explained above, this is the format used by GPU APIs or three.js). Note that that does not imply that a vertex index is never used more than once. If multiple face corners connected to a single vertex share the same attribute values, they will have the same vertex index. E.g. look at the simple case below:
```
0----2
|   /|
| /  |
1----4
```
If normals and texture coordinates are shared between both corners on vertices 2 and 4 respectively, the above mesh can be described in obj (and in Draco javascript output) as:
f 0/0/0 1/1/1 2/2/2
f 1/1/1 4/4/4 2/2/2

Vertices 1 and 2 are shared between two faces.

 Internally, Draco stores data to format more similar to .obj but that format is not currently exposed in Javascript (you can still get it through C++ API though). I'll create internal feature request to add it to our Javascript API as well.

**Comment by FrankGalligan** [comment]
We will not add this to our current JavaScript/WASM decoders as it will make the libraries bigger. Someone could create a new JavaScript/WASM decoder that exposes these functions.
