### ISSUE TITLE
Normals problem

### ISSUE THREAD

**Issue by Aeros** [google/draco#348]
Hi,
I have been testing draco since a month, it's a good product, we like speed and compression size. I use DracoLoader for ThreeJs.

I still have one problem.
I'm exporting obj file without normals to keep small file size for uncompression and decoding speed. Almost all meshes are rendered correctly, the normals are well computed. 
But I have problem with some meshes, as you can see in the screenshots (smooth, flat, wireframe).

<div style="display: flex; flex-direction: row;">
<img src="https://user-images.githubusercontent.com/36449080/36157221-9ab734a0-10d9-11e8-915c-24f8325522c5.PNG" height="128" title="smooth"/>
<img src="https://user-images.githubusercontent.com/36449080/36157219-9aa0297c-10d9-11e8-8788-f1bc2a7e5283.PNG" height="128" title="flat"/>
<img src="https://user-images.githubusercontent.com/36449080/36157222-9ae05ca4-10d9-11e8-9f07-cef9f3d84aed.PNG" height="128" title="wireframe"/>
</div>

Rendering without modification (smooth) causes normals problems, when I set 'flatShading' to true on the material the mesh is correctly rendered.

I tested OBJLoader2 from ThreeJs with the option 'useIndices' and the mesh was correctly rendered.

I found this issue [Indexed Geometry when decoding #343](https://github.com/google/draco/issues/343) that will be interesting and getting closer to my problem.

Do you have an explanation, or are thinking of correcting this normals compute?

Does Draco decoder support per-vertex normals? If that is the case, are the normals computed by vertex or are they computed by face and copied for each vertex?

Best regards,

**Comment by ondys** [comment]
The image on the left looks like it is averaging normals across all faces which creates the undesired effect. What you probably want is to specify some crease angle that will average normals only from relatively flat areas. 

Note that if the input encoded model does not have normals, Draco doesn't generate them either. If that's the case, the normals are most likely generated later on by three.js

**Comment by ondys** [comment]
Draco does not compute normals. If the input model that you compress contains normals, Draco is going to preserve them. If the input model has no normals, the decoded model will have no normals as well. In our example viewer we use THREE.js function |computeVertexNormals()| that is called on the decoded geometry.. there is a chance you may be using it in your code as well.

**Comment by Aeros** [comment]
Thank you.
The problem seems to come from threejs smooth normals computation. I assume that it implements something similar to this: https://stackoverflow.com/a/45496726

**Comment by supermoos** [comment]
@Aeros did you find a way to solve this? Encode normals to file before draco compression? Or is there a way to get the geometery.computeVertexNormals() from three.js to work with the draco compressed file similar to a non-draco compressed file?

**Comment by Aeros** [comment]
Sorry for the late reply, a skiing accident...
 We decided finally  to embedded the normals, we did not have time anymore to find another solution...
It take more physical space (the double), the dowloading time is a little more longer, but the loading time remains very correct.
If someone finds another way, it will be with pleasure...

**Comment by FrankGalligan** [comment]
Closing as this is an issue with three.js normal calculation.
