### ISSUE TITLE
How to generate draco_decoder. Exe?

### ISSUE THREAD

**Issue by jk601220272** [google/draco#350]
How to generate draco_decoder. Exe?

**Comment by FrankGalligan** [comment]
I'm assuming you are on Windows.

Follow these directions:
https://github.com/google/draco#windows

This will generate a Microsoft Visual Studio project file. Then you need to open the project file in visual studio and build the draco_decoder target. This will create draco_decoder.exe.

**Comment by FrankGalligan** [comment]
Closing if you are still having problems please re-open with new data.
