### ISSUE TITLE
draco_encoder crashes with -qp 31

### ISSUE THREAD

**Issue by Jiloc** [google/draco#352]
Draco Version: 1.25
Platform: Windows 10

When I try to use `./draco_encoder.exe -qp 31 -i whatever.obj` the encoder crashes without any info

But if I use `./draco_encoder.exe -cl 10 -qp 31 -i whatever.obj` it returns a segmentation fault (with a `cl < 10` it just crashes)

using a `qp < 31` everyting works just fine

**Comment by ondys** [comment]
thanks for the report, I've added the issue to our internal bug-tracker

**Comment by FrankGalligan** [comment]
A while ago we changed the api to require <= 30 quantization.
