### ISSUE TITLE
configuration for lossless compression

### ISSUE THREAD

**Issue by Jiloc** [google/draco#353]
Can draco achieve a lossless compression for .obj/.stl?Is there a suggested configuration? So far I've got the best result from -qp 30 -cl 0 (-qp 31 doesn't work as I pointed out in #352), but there decompressed mesh is not equal yet.

**Comment by ondys** [comment]
You can set -qp to 0 in which case the quantization will be disabled. The input values will be then encoded losslessly but the compression ratio will be probably rather bad as Draco doesn't currently have a specialized encoder for floating point values.

**Comment by FarhadG** [comment]
After setting `qp` to `0`, I ran into an issue when trying to render it in `THREE`. I don't get this error when I set the value to anything other than `0`.
![screen shot 2018-03-19 at 2 14 32 pm](https://user-images.githubusercontent.com/1647596/37597549-08ebf7b0-2b80-11e8-850a-9b29da7d4413.png)

**Comment by ondys** [comment]
thanks for the report. I was able to reproduce the issue and we will investigate it. It seems to be isolated to Javascript & wasm decoding (c++ decoder seems to work fine).

**Comment by FrankGalligan** [comment]
This currently works.
