### ISSUE TITLE
How to get mapping new faces onto old faces

### ISSUE THREAD

**Issue by nbcong** [google/draco#359]
Hi,

Firstly; thanks for creating the very helpful and powerful draco lib. The lib is very important for our mesh data transportation phase.

Secondly; I'm using c++ and sticking closely to MeshEdgeBreakerEncoder. I would like to know that after finishing mesh compression; is there any way to get mapping new faces onto the origin mesh faces immediately?

Any suggestions would be great to me. Thanks!

**Comment by ondys** [comment]
The mapping is lost (which allows the method to achieve better compression). You could theoretically store the mapping in a separate integer attribute. For every face, all corners would be always mapped to the same value that would correspond to the face index in the input mesh.
