### ISSUE TITLE
Encoder fails for `double` or `float64` ply vertex properties

### ISSUE THREAD

**Issue by ataber** [google/draco#360]
Hello,

I am trying to compress the following PLY file with the CLI encoder on latest master:
```
ply
format ascii 1.0
element vertex 8
property float64 x
property float64 y
property float64 z
element material 0
element face 12
property list uint8 int32 vertex_indices
end_header
0 0 0 
10 0 0 
10 0 30 
0 0 30 
10 20 0 
10 20 30 
0 20 0 
0 20 30 
3 0 1 2 
3 0 2 3 
3 1 4 5 
3 1 5 2 
3 4 6 7 
3 4 7 5 
3 6 0 3 
3 6 3 7 
3 1 0 6 
3 6 4 1 
3 2 7 3 
3 7 2 5 
```

but I get the following error: `Failed loading the input mesh: Unknown error..`

When I change the `x`, `y`, and `z` attributes to be `float` or `float32`, the encoding succeeds, but it fails when they are either `float64` or `double`. Am I missing something obvious? The encoder does support doubles right? Thank you!

**Comment by ataber** [comment]
Indeed, it looks like [position values must be float32 for the CLI](https://github.com/google/draco/blob/master/src/draco/io/ply_decoder.cc#L136).

**Comment by ataber** [comment]
I made some changes to [my fork](https://github.com/intact-solutions/draco) to support doubles (for posterity looking at this issue). Does your comment about float64 mean that Draco basically truncates internally to 32 bits and then quantizes/compresses?

**Comment by ondys** [comment]
No, if you supply float64 (DT_FLOAT64)  attribute to Draco, it will preserve the values as 64 bit floats. What I was trying to say is that you should truncate it to DT_FLOAT32 before compressing it with Draco, because quantization wouldn't work for DT_FLOAT64 and the compression would be very bad.

**Comment by ataber** [comment]
Gotcha, thanks for the tip!
