### ISSUE TITLE
I met a trouble

### ISSUE THREAD

**Issue by aiyouBug** [google/draco#362]
1. I can't find the.Drc file of.Fbx in the sample. Look at Readme in support of.Fbx.But I can't get the.Drc file through draco_encoder.exe
2. I can use a file in.Obj format, but I don't know how to merge the.Mtl file with the format of the read.Obj file. At present, I can only be naive to cut the model according to the array average.

**Comment by ondys** [comment]
1. draco_encoder does not currently support .fbx file format. I checked our main README.me and we do not mention .fbx at all there.

2. .mtl file needs to be send separately. draco_encoder can encode material indices and names when used with the `--metadata` flag but it does not encode the material definitions.
