### ISSUE TITLE
Is the order of vertices in the Draco output reproducible?

### ISSUE THREAD

**Issue by BerndGe** [google/draco#363]
Hi all,

the question is: can the order of vertices in the output change if I:
* add/remove a generic attribute
* change the compression level
?

Reason for the question: As the Draco library doesn't provide a way to find out the mapping from original vertices to encoded vertices, I envision the following (as a workaround, really):
* Encode a mesh (i. e. geometrical information) with an additional attribute that enumerates a vertex index 1..n
* Decode the Draco file. Use the index attribute to extract the mapping from old to encoded vertex indices and store that somewhere
* Encode the mesh again without the additional attribute (This resulting Draco file has a much better compression ratio than the one created in the first step)
=> the extracted mapping is only useful if it can be used for second encoded mesh

My use case: I want to transfer mesh data from a server to a web client. The mesh consists of geometrical information and an additional float value for each vertex. This additional channel exists once "per stage", (you can think of the stage as an additional time coordinate). When the client switches from one stage to the other, the geometrical information stays the same, but the additional channel is new. A good argument can be made that only the additional channel is transmitted from server to client on a stage switch, whereas the geometrical information only has to be transmitted once. The additional channel needs to have some precision, so just transmitting the whole information (geometry plus additional channel) for each stage switch with a broadly quantized channel isn't a good alternative. However, when separating the information per-vertex for each stage switch, I have to be able to map this information to the correct vertices.

**Comment by ondys** [comment]
In general, Draco does not provide any guarantees in terms of vertex or face order

That being said, the face order should be consistent when the compression level remains the same (at least for compression level >= 5).  Adding additional attributes may affect mapping between points and attribute values (adding new attributes often introduces new points unless the attributes don't have any attribute seams). Attribute values should be decoded the same way however (e.g. position attribute should always have the coordinates stored in the same order even when additional attributes are added). 

Summary:
What you are trying to do is most likely doable, but you will have to be careful. Assuming the new attribute storing the vertex indices mapping is defined without any attribute seams, there should be 1:1 correspondence between points on both meshes.

**Comment by donmccurdy** [comment]
Is it safe to say that after the vertex data is compressed, decoding order is then deterministic? I.e. decoding on two different devices, or with two different versions of the Draco library, should give the same vertex order?
