### ISSUE TITLE
encoder error: Failed loading the input mesh: Failed to parse vertex indices.

### ISSUE THREAD

**Issue by zwcloud** [google/draco#365]
> PS D:\> .\draco_encoder.exe -i L20.obj -o L20.drc
> Failed loading the input mesh: Failed to parse vertex indices.

L20.obj: [L20.zip](https://github.com/google/draco/files/1870439/L20.zip)

This obj file is generated by osgconv tool from [OpenSceneGraph](http://www.openscenegraph.com/).

__Environment:__
* Win10 x64, VS2017, Debug

* draco_version.cc
    ```cpp
    static const char kDracoGitHash[] = "3b3cab31e5e75de851cd2eb588cd7ba8eec70f27";
    static const char kDracoGitDesc[] = "unreleased";
    ```

**Comment by zwcloud** [comment]
I just debugged the encoder. And it turned out that the app runs into `obj_decoder.DecodeFromFile` which  `return DecodeFromFile(file_name, static_cast<PointCloud *>(out_mesh));`.

**https://github.com/google/draco/blob/3b3cab31e5e75de851cd2eb588cd7ba8eec70f27/src/draco/io/obj_decoder.cc#L48**

The obj file is NOT a point cloud. Is that the cause of the error?

**Comment by FrankGalligan** [comment]
The issue is the obj file is not written correctly. If you look at the face line:
`f 1/1/ 2/2/ 3/3/`

Obj parsers would expect normal values.
