### ISSUE TITLE
Complete Application crash when loading bunny.drc 

### ISSUE THREAD

**Issue by nomercy0** [google/draco#368]
I have been working on my start up since 5 months based on augmented reality .I have completed building my app logic and got stuck in remote loading of high poly assets at runtime in unity
since 1 month. I have checked all the things from my side I cant  find a solution to load 3d object faster after downloading it  .
I completely rely on draco
I tried Implementing google draco on **Unity 2107.3** and the app  crashes  with decompression failure and I don't receive any error and not even the bunny.drc model is getting loaded
Refer Link--https://github.com/google/draco/issues/357(Created by my colleage)

bunny.drc gets properly loaded but crashes at laoder.DecodeMesh .

I would appreciate any help from you in order to sort this issue  
Please help me 
```
`using System.Collections.Generic;
using System.IO;
using UnityEngine;

public class UncompressTest : MonoBehaviour {

  private void Start() {
    var meshData = File.ReadAllBytes("bunny.drc");

    var meshes = new List<Mesh>();
    var loader = new DracoMeshLoader();
    var faceCount = loader.DecodeMesh(meshData, ref meshes);

    if (faceCount > 0) {
      foreach (var mesh in meshes) {
        var newGameObj = new GameObject("bunny" + mesh.GetInstanceID());
        newGameObj.AddComponent<MeshFilter>().mesh = mesh;
        newGameObj.AddComponent<MeshRenderer>().material.color = Color.gray;
      }

      Debug.Log("Mesh imported!");
    } else {
      Debug.LogWarning("Wrong data received (no face available)");
    }
  }
}`
```

**Comment by farzaa** [comment]
Hey dude! So, I haven't worked with Unity, but I had a very similar problem on Android and it mostly had to do with the fact that I wasn't using C++11 as my compiler. Check out my example [here](https://github.com/farzaa/DracoPortedToAndroid) if it helps :)

**Comment by FrankGalligan** [comment]
@nomercy0 Did you get this to work?

**Comment by nomercy0** [comment]
@FrankGalligan  I was able to load bunny.drc from unity **2018.1**  however   unity crashes when I load command line generated custom drc file with default setting (I was able to load the same drc file with webgl loader of javascript)
I am here attaching the obj file and along with generated drc with command line application of draco
[106.zip](https://github.com/google/draco/files/2280218/106.zip)
I have tested all of it with latest release of draco

**Comment by nomercy0** [comment]
@FrankGalligan  Any solution for this

**Comment by FrankGalligan** [comment]
@nomercy0 I tried out your file. It did not crash. We have fixed a few things in the past couple of days. #446 might be the issue you are seeing. We are going to try and make a new release this week.

**Comment by nomercy0** [comment]
@FrankGalligan  for your information obj encoded with tex_coord dont get loaded in unity windows however obj encoded without tex_coord gets loaded without a problem.
Hoping you will fix it on next release

**Comment by FrankGalligan** [comment]
@nomercy0 Please try again with the latest release 1.3.4

**Comment by nomercy0** [comment]
Works perfectly fine
