### ISSUE TITLE
glTF export?

### ISSUE THREAD

**Issue by dVurpillot** [google/draco#369]
I see that Draco compression is now officially supported by Khronos/glTF.
I enabled gltf related vars from the cmake file but I really don't get what is the pipeline to go from .obj/.ply to a glTF file with the correct data structure and the -h proves to be not very helpful on this matter.

Am I overlooking something?

**Comment by ondys** [comment]
Draco currently does not have a native exporter to gltf . Our current recommendation is to convert the file to a regular gltf using one of the available glTF tools and then use gltf-pipeline with our pull request [here](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/353).

**Comment by my2iu** [comment]
Can you put that information somewhere prominent, possibly on the front readme.md? I spent a lot of time going through a lot of gltf and draco documentation looking for the draco gltf encoder. I did not realize that there wasn't an encoder yet.

**Comment by my2iu** [comment]
Or maybe you can also provide an encoder binary that people can download now, or a branch to the encoder that people can compile, or some documentation on how you created the compressed gltf sample files so that other people can start creating their own compressed gltf files too? It just seems weird to have a compression standard with no implementation.

**Comment by ondys** [comment]
just a quick update: Draco is now fully integrated with the gltf pipeline 2.0 branch (https://github.com/AnalyticalGraphicsInc/gltf-pipeline/tree/2.0)

We are still working on a proper documentation

**Comment by FrankGalligan** [comment]
We are not currently planning to support this in draco_encoder or draco_decoder.

There are a lot of other solutions that support this:
https://github.com/CesiumGS/gltf-pipeline
https://github.com/KhronosGroup/glTF-Blender-IO

If someone adds a pull request to add this support to draco_encoder or draco_decoder, then please reopen this issue.
