### ISSUE TITLE
Draco uwp-x86 support

### ISSUE THREAD

**Issue by WeersProductions** [google/draco#373]
Hi all,

I was wondering whether Draco has x86-uwp support?

I'm having trouble getting it to work, see [here](https://github.com/Microsoft/vcpkg/issues/3276). 
If you need more information, don't hesitate to send me a message!

Thank you in advance!

**Comment by ondys** [comment]
if there are any specific build issues you can always create a pull request to fix them. We currently do not provide an official support for uwp so unless there is a sufficient demand it may take a while for the Draco team to fix that.

**Comment by WeersProductions** [comment]
Hey,
Thanks for your message. Draco seems to be fully compatible with UWP. I did not yet do any extensive testing, but I think it 'simply' works. 
Disabling a few compiler warnings/errors allowed me to compile it 😀.

**Comment by FrankGalligan** [comment]
Closing as it looks like it works.
