### ISSUE TITLE
please offer an option for encryption

### ISSUE THREAD

**Issue by guzuomuse** [google/draco#376]
i want to protect my 3d assets like .obj and .gltf with draco
i can convert these files to .drc format
but we can easily reverse them using `draco_decoder`  command 
so if we can add an option when we encode someobj.file
like `draco_encoder myfile.obj --password **** `
i don't know if this is a right thought,any idea? thanks

**Comment by FrankGalligan** [comment]
Adding encryption is currently out of our scope. But if there is big enough demand I'm sure someone could create a post process tool that encrypts .drc files, much like how media files are encrypted today.

I'm not sure of your use use case, but something that could be done easily is just use zip and encrypt the files with that.

**Comment by guzuomuse** [comment]
@FrankGalligan 
i know zip can encrypt these file.
but i want to prevent my drc file converting to obj file without the "password";
for example:
1: i convert my obj file to drc.
2: on client side show the 3d scence by decode the drc with javascript(this process not required the password)
3:someone download the drc file,but can't convert the drc file to obj without the password
in this case we can protect my source obj file isn't it?

**Comment by FrankGalligan** [comment]
@guzuomuse 

I understand what you want, but talking from experience on with video encryption, it is actually a very big and difficult task to do correctly.

That being said, I reopened the issue and marked it as an enhancement. So maybe someone can take this issue and implement it.

**Comment by zwcloud** [comment]
@guzuomuse 

>on client side load the drc file and show the 3d scence by decoding the drc with javascript(this process not required the password)

I should say this is logically impossible.

**Comment by guzuomuse** [comment]
@zwcloud ,hmmmmm....i think you are right.
