### ISSUE TITLE
Point cloud decode error

### ISSUE THREAD

**Issue by lilleyse** [google/draco#381]
I have a point cloud that has two attributes: position and color. When I apply the quantization transform to the positions the color values are returned as 0.

Here's some sample data and code example: [draco-bug.zip](https://github.com/google/draco/files/1961701/draco-bug.zip). In the folder run `npm install` and `npm start`. Go to localhost:8003 and look at the console. I’m using the 1.3.0 wasm binary.

**Comment by ondys** [comment]
thanks for the report. fixed in 1.3.1

**Comment by danem** [comment]
I'm experiencing the same issue with version 1.5
