### ISSUE TITLE
Less faces after compression

### ISSUE THREAD

**Issue by DrJohnDale** [google/draco#384]
Hi,

With some compression settings (encoder.SetSpeedOptions(5, 5)) we get less faces out than we put in. Is this expected behavior? How does draco decide which faces will be removed?

Which settings give the best compression without removing faces.

Cheers

**Comment by DrJohnDale** [comment]
We found the issue and it appears to be with our meshes. The mesh has some very small faces in it, so that when the obj file is created and the vertices are rounded they all have the same location.

It appears that Draco ignores these faces. Is this the expected behavior of Draco?

**Comment by FrankGalligan** [comment]
Hi,

So yes by default Draco will de-duplicate vertices.
