### ISSUE TITLE
Running the WebAssembly version of Draco in a web worker

### ISSUE THREAD

**Issue by tastnt** [google/draco#386]
Hey All,

I am trying to run the WebAssembly version of Draco in a web worker. I have created the following worker code based on [this example](https://github.com/google/draco/blob/master/javascript/time_draco_decode.html):

```JavaScript
importScripts("draco_wasm_wrapper.js");
var decoderModule = {};
var dracoDecoderType = {};

onmessage = function (e) {
    var compressedMeshBlob = e.data;
    var fileReader = new FileReader();

    loadWebAssemblyDecoder(function decoderReady() {
        console.log("Decoder is ready.");
        fileReader.onload = function () {
            var arrayBuffer = fileReader.result;
            var geometryData = decodeMesh(arrayBuffer);
            postMessage(geometryData);
            geometryData = undefined;
            close();
        };
        fileReader.readAsArrayBuffer(compressedMeshBlob);
    });
};

function loadWebAssemblyDecoder(decoderReadyCallback) {
    dracoDecoderType['wasmBinaryFile'] = 'draco_decoder.wasm';

    const xhr = new XMLHttpRequest();
    xhr.open('GET', 'draco_decoder.wasm', true);
    xhr.responseType = 'arraybuffer';

    xhr.onload = function () {
        dracoDecoderType['wasmBinary'] = xhr.response;
        decoderModule = DracoDecoderModule(dracoDecoderType);
        decoderReadyCallback();
    };

    xhr.send(null)
}

function decodeMesh(arrayBuffer) {
    const byteArray = new Uint8Array(arrayBuffer);
    const buffer = new decoderModule.DecoderBuffer();
    buffer.Init(byteArray, byteArray.length);
    const decoder = new decoderModule.Decoder();

    const geometryType = decoder.GetEncodedGeometryType(buffer);
    var dracoGeometry;
    if (geometryType === decoderModule.TRIANGULAR_MESH) {
        dracoGeometry = new decoderModule.Mesh();
    } else {
        throw Error("Only triangular meshes are supported.");
    }

    decoderModule.destroy(decoder);
    decoderModule.destroy(buffer);
    return dracoGeometry;
}
```
The `compressedMeshBlob` is a compressed Draco mesh which is loaded as a [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) by the main thread and passed to the web worker through `postMessage()`. I am using the [draco_decoder.wasm](https://github.com/google/draco/blob/master/javascript/draco_decoder.wasm) and [draco_wasm_wrapper.js](https://github.com/google/draco/blob/master/javascript/draco_wasm_wrapper.js) from the respository. I am getting the following error message:

![image](https://user-images.githubusercontent.com/4266299/39691950-80fddf54-51df-11e8-98dc-a12a1e4d39b1.png)

I am not sure if I am doing something incorrectly or if it is fundamentally not possible to run the WebAssembly version of Draco in a web worker. Using the JavaScript decoder works fine.

Thank you very much for your help in advance!

**Comment by simonbourne** [comment]
I also experience this same issue with the WebAssembly version of DracoDecoderModule not being fully initialised and raising the same exception when I try to initialise a DecoderBuffer object:

`draco_wasm_wrapper.js:60 Uncaught TypeError: Cannot read property 'apply' of undefined
    at DracoDecoderModule.a._emscripten_bind_DecoderBuffer_DecoderBuffer_0 (draco_wasm_wrapper.js:60)
    at new R (draco_wasm_wrapper.js:25)`

I am not using web workers, so do not feel the problem just relates to them, it seems to be a timing issue as if I wait longer between creating the DracoDecoderModule and initialising the DecoderBuffer object, then the DracoDecoderModule internal member variable asm will include all the emscripten wrapped functions and the decoder will work correctly (however they seem to be missing initially). As stated previously using the much slower Javascript version does not suffer this issue.

Is this a bug or is there a signal/callback we can use to tell when the DracoDecoderModule is fully initialised?

This is using Draco 1.3.3, and any help would be greatly appreciated.

**Comment by trox667** [comment]
Maybe you just need to wait for the wasm module to be ready. There is a callback available added to the draco_wasm_wrapper. It's also used in the [example](https://github.com/google/draco/blob/master/javascript/time_draco_decode.html)
```
this.dracoModule = DracoDecoderModule();
dracoDecoderType['onModuleLoaded'] = () => {
    // Create the decoder instance
    this.dracoDecoder = new this.dracoModule.Decoder();
};
```
Waiting for this callback before starting the decoder should help.

**Comment by donmccurdy** [comment]
We have a functional example here, fyi: https://github.com/mrdoob/three.js/pull/15249.

**Comment by SoylentGraham** [comment]
Am I correct in thinking, there still isn't a non-three.js webworker example?

**Comment by donmccurdy** [comment]
Babylon.js also has an open source implementation with web workers, for another example. I think use of web workers is outside the scope of what a JS library would usually want to provide in examples, since that's often dependent on the build system (e.g. webpack).
