### ISSUE TITLE
about obj  encoder error 

### ISSUE THREAD

**Issue by openforus** [google/draco#39]
when i encoder the obj model with  point 237522 and face 712566 crash,
the debug repot: vector subscript out of range

**Comment by ondys** [comment]
Can you please provide a link for the model that caused the crash? We need it in order to reproduce and fix the issue. Thanks.

**Comment by openforus** [comment]
ok，Maybe The model is too big . Thank you ,the model  link :
[http://pan.baidu.com/s/1pKMPsE3]

**Comment by ondys** [comment]
Thanks for the model. The model itself isn't that big. We have been successfully testing it on models with tens of millions faces. But in the end it also depends on the specs of your computer.

I tested the attached model and it worked for me. What OS / computer specs did you use to test it?

**Comment by openforus** [comment]
I've found the reason. , I  compile the source code with debug mode，When use  the application which build in release mode it is OK，thanks ondys
