### ISSUE TITLE
SIGABRT in draco::IndexTypeVector<draco::IndexType<unsigned int, draco::VertexIndex_tag_type_>, int>::operator[]

### ISSUE THREAD

**Issue by najadojo** [google/draco#398]
Using american fuzzy lop 2.49b on draco_decoder I found crashes at stacks like:

```
#0  __GI_raise (sig=...) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  __GI_abort () at abort.c:90
#2  __gnu_debug::_Error_formatter::_M_error() const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  std::__debug::vector<int, std::allocator<int> >::operator[] (this=..., __n=...) at /usr/include/c++/7/debug/vector:417
#4  draco::IndexTypeVector<draco::IndexType<unsigned int, draco::VertexIndex_tag_type_>, int>::operator[] (this=..., index=...) at /home/jamie/draco/src/draco/core/draco_index_type_vector.h:58
#5  draco::MeshEdgeBreakerTraversalValenceDecoder::NewActiveCornerReached (this=..., corner=...) at /home/jamie/draco/src/draco/compression/mesh/mesh_edgebreaker_traversal_valence_decoder.h:159
#6  draco::MeshEdgeBreakerDecoderImpl<draco::MeshEdgeBreakerTraversalValenceDecoder>::DecodeConnectivity (this=..., num_symbols=...) at /home/jamie/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:654
#7  draco::MeshEdgeBreakerDecoderImpl<draco::MeshEdgeBreakerTraversalValenceDecoder>::DecodeConnectivity (this=...) at /home/jamie/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:373
#8  draco::MeshEdgeBreakerDecoder::DecodeConnectivity (this=...) at /home/jamie/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder.cc:60
#9  draco::MeshDecoder::DecodeGeometryData (this=...) at /home/jamie/draco/src/draco/compression/mesh/mesh_decoder.cc:30
#10 draco::PointCloudDecoder::Decode (this=..., options=..., in_buffer=..., out_point_cloud=...) at /home/jamie/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:97
#11 draco::MeshDecoder::Decode (this=..., options=..., in_buffer=..., out_mesh=...) at /home/jamie/draco/src/draco/compression/mesh/mesh_decoder.cc:24
#12 draco::Decoder::DecodeBufferToGeometry (this=..., in_buffer=..., out_geometry=...) at /home/jamie/draco/src/draco/compression/decode.cc:121
#13 draco::Decoder::DecodeMeshFromBuffer (this=..., in_buffer=...) at /home/jamie/draco/src/draco/compression/decode.cc:86
```
There are multiple input files that have this bounds check problem.
[id:000009,sig:06,src:000002,op:int32,pos:42,val:+0.gz](https://github.com/google/draco/files/2028605/id.000009.sig.06.src.000002.op.int32.pos.42.val.0.gz)
[id:000188,sig:06,src:000248,op:havoc,rep:2.gz](https://github.com/google/draco/files/2028607/id.000188.sig.06.src.000248.op.havoc.rep.2.gz)
[id:000248,sig:06,src:000907,op:int32,pos:41,val:+128.gz](https://github.com/google/draco/files/2028609/id.000248.sig.06.src.000907.op.int32.pos.41.val.128.gz)
[id:000151,sig:11,src:000024,op:flip1,pos:29.gz](https://github.com/google/draco/files/2028613/id.000151.sig.11.src.000024.op.flip1.pos.29.gz)
[id:000088,sig:06,src:000009,op:flip1,pos:13.gz](https://github.com/google/draco/files/2028617/id.000088.sig.06.src.000009.op.flip1.pos.13.gz)
[id:000018,sig:11,src:000003,op:arith16,pos:47,val:-1.gz](https://github.com/google/draco/files/2028619/id.000018.sig.11.src.000003.op.arith16.pos.47.val.-1.gz)
[id:000021,sig:11,src:000003,op:int32,pos:41,val:be:+1024.gz](https://github.com/google/draco/files/2028627/id.000021.sig.11.src.000003.op.int32.pos.41.val.be.1024.gz)
[id:000321,sig:06,src:001538,op:arith8,pos:22,val:+33.gz](https://github.com/google/draco/files/2028631/id.000321.sig.06.src.001538.op.arith8.pos.22.val.33.gz)

**Comment by ondys** [comment]
fixed in 1.3.2
