### ISSUE TITLE
Unity windows builds are crashing

### ISSUE THREAD

**Issue by kiwipxl** [google/draco#404]
Has anyone been able to build a working unity build in Visual Studio 2017 Community? Whenever the dll function is called (DecodeMeshForUnity), Unity will crash. I've looked at the EventViewer and there doesn't seem to be any useful information I can show here, but I've uploaded the built dll I have (x64) in case anyone wants to try it.

This is the cmake command I used:
`cmake ../ -G "Visual Studio 15 Win64" -DBUILD_UNITY_PLUGIN=ON`
I then opened ALL_BUILD project and built from there. The outputted dll was in /Debug.
I also tried going back to when windows support was first added and building then, but same issue.
Note: I've also tried a 32 bit build but Unity won't recognise it (even if I change the CPU to only x86_64)

Also, the original dll (~400kb) works fine in Unity, while the built one I have is ~4mb, any ideas why that might be? Does that have anything to do with this?

[dracodec_unity.dll.zip](https://github.com/google/draco/files/2038200/dracodec_unity.dll.zip)

**Comment by kiwipxl** [comment]
This seems to only happen when freeing memory inside `DracoMeshLoader.cs`.
Might be good to call the plugin's release instead of marshal release?

**Comment by SergeyNewcastle** [comment]
Have the same problem

**Comment by FrankGalligan** [comment]
I was able to reproduce the issue. This will be fixed in the next release.

**Comment by FrankGalligan** [comment]
@kiwipxl This should be fixed now in 1.3.4
