### ISSUE TITLE
Compilation error with GCC 4.8

### ISSUE THREAD

**Issue by zellski** [google/draco#406]
Is this a known problem? Is there a workaround, or is the GCC simply too old? ~~It seems to happen for 4.9.2 as well.~~ Edit: 4.9.2 is good.

```
/build/draco/src/Draco/src/draco/compression/attributes/kd_tree_attributes_decoder.cc: In member function 'virtual bool draco::KdTreeAttributesDecoder::DecodePortableAttributes(draco::DecoderBuffer*)':
/build/draco/src/Draco/src/draco/compression/attributes/kd_tree_attributes_decoder.cc:198:50: error: call of overloaded 'DecodePoints(draco::DecoderBuffer*&, draco::PointAttributeVectorOutputIterator<unsigned int>&)' is ambiguous
       if (!decoder.DecodePoints(in_buffer, out_it))
                                                  ^
/build/draco/src/Draco/src/draco/compression/attributes/kd_tree_attributes_decoder.cc:198:50: note: candidates are:
In file included from /build/draco/src/Draco/src/draco/compression/attributes/kd_tree_attributes_decoder.cc:17:0:
/build/draco/src/Draco/src/draco/compression/point_cloud/algorithms/dynamic_integer_points_kd_tree_decoder.h:148:6: note: bool draco::DynamicIntegerPointsKdTreeDecoder<compression_level_t>::DecodePoints(draco::DecoderBuffer*, OutputIteratorT&) [with OutputIteratorT = draco::PointAttributeVectorOutputIterator<unsigned int>; int compression_level_t = 0]
 bool DynamicIntegerPointsKdTreeDecoder<compression_level_t>::DecodePoints(
      ^
/build/draco/src/Draco/src/draco/compression/point_cloud/algorithms/dynamic_integer_points_kd_tree_decoder.h:140:6: note: bool draco::DynamicIntegerPointsKdTreeDecoder<compression_level_t>::DecodePoints(draco::DecoderBuffer*, OutputIteratorT&&) [with OutputIteratorT = draco::PointAttributeVectorOutputIterator<unsigned int>&; int compression_level_t = 0]
 bool DynamicIntegerPointsKdTreeDecoder<compression_level_t>::DecodePoints(
      ^

```

**Comment by FrankGalligan** [comment]
It is a known issue. Do you need 4.8?

**Comment by zellski** [comment]
There have been requests to run FBX2glTF on the AmazonLinux distributions that are based on CentOS 6, and sometime goes wrong there -- at least with the way I've been compiling it. A sample report is here: https://github.com/facebookincubator/FBX2glTF/issues/104

Let me see what I can do with a simplified compilation approach; using GCC 4.9.2 on the exact target distribution. I'll get back to you. :)

**Comment by qweas120** [comment]
Hi @zellski. I run into this issue too. I also tried GCC 4.9(4.9.4) but it didn't work. Is there any suggestion?

**Comment by qweas120** [comment]
Well, I compiled it successfully.
The error is about the override functions.
``` CPP
// In file draco/src/draco/compression/point_cloud/algorithms/float_points_tree_decoder.h
bool DecodePointCloud(DecoderBuffer *buffer, OutputIteratorT &out);
bool DecodePointCloud(DecoderBuffer *buffer, OutputIteratorT &&out);
```
``` CPP
// In file draco/src/draco/compression/point_cloud/algorithms/dynamic_integer_points_kd_tree_decoder.h
bool DecodePoints(DecoderBuffer *buffer, OutputIteratorT &oit);
bool DecodePoints(DecoderBuffer *buffer, OutputIteratorT &&oit);
```

It seems that the right value reference function can consume both left value reference and right value reference. Thus I rename the left value reference function to avoid the ambiguity and it works finally.

``` CPP
// In file draco/src/draco/compression/point_cloud/algorithms/float_points_tree_decoder.h
bool DecodePointCloud_(DecoderBuffer *buffer, OutputIteratorT &out);
bool DecodePointCloud(DecoderBuffer *buffer, OutputIteratorT &&out);
```
``` CPP
// In file draco/src/draco/compression/point_cloud/algorithms/dynamic_integer_points_kd_tree_decoder.h
bool DecodePoints_(DecoderBuffer *buffer, OutputIteratorT &oit);
bool DecodePoints(DecoderBuffer *buffer, OutputIteratorT &&oit);
```

**Comment by meenalpatil-2007** [comment]
@qweas120 This solution partially worked for me. It resolved all "error: call of overloaded ...  is ambiguous" errors.
But there are few more as below. Any help with this would be very much helpful:

`In file included from /home/ec2-user/draco/src/draco/compression/attributes/kd_tree_attributes_decoder.cc:17:0:
/home/ec2-user/draco/src/draco/compression/point_cloud/algorithms/dynamic_integer_points_kd_tree_decoder.h:151:6: error: prototype for ‘bool draco::DynamicIntegerPointsKdTreeDecoder<compression_level_t>::DecodePoints(draco::DecoderBuffer*, OutputIteratorT&)’ does not match any in class ‘draco::DynamicIntegerPointsKdTreeDecoder<compression_level_t>’
 bool DynamicIntegerPointsKdTreeDecoder<compression_level_t>::DecodePoints(
      ^
/home/ec2-user/draco/src/draco/compression/point_cloud/algorithms/dynamic_integer_points_kd_tree_decoder.h:99:8: error: candidate is: template<int compression_level_t> template<class OutputIteratorT> bool draco::DynamicIntegerPointsKdTreeDecoder<compression_level_t>::DecodePoints(draco::DecoderBuffer*, OutputIteratorT&&)
   bool DecodePoints(DecoderBuffer *buffer, OutputIteratorT &&oit);
        ^
In file included from /home/ec2-user/draco/src/draco/compression/attributes/kd_tree_attributes_decoder.cc:18:0:
/home/ec2-user/draco/src/draco/compression/point_cloud/algorithms/float_points_tree_decoder.h:83:6: error: prototype for ‘bool draco::FloatPointsTreeDecoder::DecodePointCloud(draco::DecoderBuffer*, OutputIteratorT&)’ does not match any in class ‘draco::FloatPointsTreeDecoder’
 bool FloatPointsTreeDecoder::DecodePointCloud(DecoderBuffer *buffer,
      ^
/home/ec2-user/draco/src/draco/compression/point_cloud/algorithms/float_points_tree_decoder.h:40:8: error: candidates are: template<class OutputIteratorT> bool draco::FloatPointsTreeDecoder::DecodePointCloud(const char*, size_t, OutputIteratorT)
   bool DecodePointCloud(const char *data, size_t data_size,
        ^
/home/ec2-user/draco/src/draco/compression/point_cloud/algorithms/float_points_tree_decoder.h:37:8: error:                 template<class OutputIteratorT> bool draco::FloatPointsTreeDecoder::DecodePointCloud(draco::DecoderBuffer*, OutputIteratorT&&)
   bool DecodePointCloud(DecoderBuffer *buffer, OutputIteratorT &&out);
        ^
`

**Comment by tomfinegan** [comment]
Closing. Please try using a newer compiler release. The most recent release of gcc 4.8 is June 2015, and the most recent release of gcc 4.9 is August 2016. Newer compilers should be available for target platforms.

**Comment by lczong** [comment]
Hi! I used gcc 7.3.1, but still got the same problem.
