### ISSUE TITLE
CMake flag to build draco webassembly libraries which can be linked to WASM at a later build stage.

### ISSUE THREAD

**Issue by DrJohnDale** [google/draco#407]
We are using draco in out cpp side and our web side and have recently started to use webassembly with emscripten to to build our cpp so we can use it in the browser.

For this we need to link to the draco libraries but the default emscripten build does not produce the libdraco, libdracodec and libdracoenc libraries.  We currently edit the CMakeList.txt entry at line 607 from:
```
#
# Draco targets.
#
if (EMSCRIPTEN)
```
to 
```
#
# Draco targets.
#
if (NO)
```

So that the emscripten build produces the libraries the same way the cpp build does.

What would be really useful for us would be a CMake flag that if it were set and  emscripten was being used we could build only the three library files.

Cheers

**Comment by DrJohnDale** [comment]
Hi,

I tested the branch and it works perfectly.

Cheers.

**Comment by tomfinegan** [comment]
Thanks for testing! Closing.
