### ISSUE TITLE
I cannot cmake in centos, who can help me? 

### ISSUE THREAD

**Issue by arvinhu2017** [google/draco#41]
/data/arvinhu/draco-master]# cmake /data/arvinhu/draco-master -DCMAKE_BUILD_TYPE=release
-- The C compiler identification is unknown
-- The CXX compiler identification is GNU 4.4.6
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/local/share/cmake-3.7/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /data/arvinhu/draco-master/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/gmake" "cmTC_01fd7/fast"

  /usr/bin/gmake -f CMakeFiles/cmTC_01fd7.dir/build.make
  CMakeFiles/cmTC_01fd7.dir/build

  gmake[1]: Entering directory
  `/data/arvinhu/draco-master/CMakeFiles/CMakeTmp'

  Building C object CMakeFiles/cmTC_01fd7.dir/testCCompiler.c.o

  /usr/bin/cc -o CMakeFiles/cmTC_01fd7.dir/testCCompiler.c.o -c
  /data/arvinhu/draco-master/CMakeFiles/CMakeTmp/testCCompiler.c

  cc1: error: unrecognized command line option '-quiet'

  cc1: error: unrecognized command line option '-quiet'

  cc1: error: unrecognized command line option '-auxbase-strip
  CMakeFiles/cmTC_01fd7.dir/testCCompiler.c.o'

  gmake[1]: *** [CMakeFiles/cmTC_01fd7.dir/testCCompiler.c.o] Error 1

  gmake[1]: Leaving directory
  `/data/arvinhu/draco-master/CMakeFiles/CMakeTmp'

  gmake: *** [cmTC_01fd7/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "/data/arvinhu/draco-master/CMakeFiles/CMakeOutput.log".
See also "/data/arvinhu/draco-master/CMakeFiles/CMakeError.log".

**Comment by tomfinegan** [comment]
@arvinhu2017: A newer compiler is required. From the output CMake appears not to support GCC v4.4.6. Upgrading the compiler should solve the problem.

Ignoring the CMake issue with GCC v4.4.6: You need a C++ compiler with C++11 support to compile Draco. Specifically, the compiler you use must support the flag "-std=c++11".

**Comment by FrankGalligan** [comment]
I'm closing this issue. If you are still having problems please re-open.
