### ISSUE TITLE
C++ Decoder API Returns Broken Mesh

### ISSUE THREAD

**Issue by FreddyFunk** [google/draco#413]
Hi,

I have written the compressed bytes into a binary file and was able to get a valid .obj file with the draco_decoder.exe using the follwoing command:
`draco_decoder.exe -i test.drc -o test.obj`

My code for decompression is based discription of the C++ Decoder API here on github.
```
void Decompress(const std::vector<char>& vecCompressedData,
                                       std::vector<uint32_t>*   vecVertexIndices,
                                       std::vector<float>*      vecVertices,
                                       std::vector<float>*      vecNormals)
{
    draco::DecoderBuffer buffer;
    buffer.Init(vecCompressedData.data(), vecCompressedData.size());

    draco::Decoder                   DracoDecoder;
    draco::Mesh*                     pMesh;
    const draco::EncodedGeometryType geom_type = DracoDecoder.GetEncodedGeometryType(&buffer).value();
    if (geom_type == draco::TRIANGULAR_MESH)
    {
        pMesh = DracoDecoder.DecodeMeshFromBuffer(&buffer).value().get();
    }

   // ----------------------------------------------------------------
   // pMesh is empty. And how to get back the raw vertices, indices, normals and other attributes?
   // ----------------------------------------------------------------

}
```

Sadly, following this discribtion the decompressed mesh _attribute_data__ and _faces__ are empty, so it seems to be broken...

Also I am trying to understand the API calls required to properly get the _get the verticies, indicies and normals back_ out of raw byte form from a Draco EncoderBuffer, but I have no clue. As a final result I need something like a std::vector<unsigned int> filled with indices and a std::vector<float> filled with the vertices and so on.

I would be very thankful if you could help me! :-)

Cheers

**Comment by ondys** [comment]
for the decoder, the return type needs to be of type `std::unique_ptr<draco::Mesh>`, not `draco::Mesh*`. 

if you call:
```
pMesh = DracoDecoder.DecodeMeshFromBuffer(&buffer).value().get();
```

the returned mesh would get deleted right after the function returns (the pointer is owned by the unique ptr that you don't assign anywhere).

**Comment by FreddyFunk** [comment]
Thanks for pointing this out. I managed to get it working.
