### ISSUE TITLE
APPLICATION_FAULT_NULL_POINTER_WRITE_INVALID_POINTER_WRITE_draco_decoder!draco::DynamicIntegerPointsKdTreeDecoder_6_::DecodeInternal_draco::PointAttributeVectorOutputIterator_unsigned_int___+642

### ISSUE THREAD

**Issue by najadojo** [google/draco#414]
Using american fuzzy lop 2.49b on draco_decoder 1.3.2 I found crashes at stacks like:

draco_decoder!draco::DynamicIntegerPointsKdTreeDecoder<6>::DecodeInternal<draco::PointAttributeVectorOutputIterator<unsigned int> >+0x642
draco_decoder!draco::DynamicIntegerPointsKdTreeDecoder<6>::DecodePoints<draco::PointAttributeVectorOutputIterator<unsigned int> >+0xb5
draco_decoder!draco::KdTreeAttributesDecoder::DecodePortableAttributes+0x4c8
draco_decoder!draco::AttributesDecoder::DecodeAttributes+0x16
draco_decoder!draco::PointCloudDecoder::DecodeAllAttributes+0x2d
draco_decoder!draco::PointCloudDecoder::DecodePointAttributes+0x17c
draco_decoder!draco::PointCloudDecoder::Decode+0x311
draco_decoder!draco::Decoder::DecodeBufferToGeometry+0x252
draco_decoder!draco::Decoder::DecodePointCloudFromBuffer+0x15f
draco_decoder!main+0x9c2

Input [example.zip](https://github.com/google/draco/files/2078345/example.zip) demonstrates the failure.

**Comment by ondys** [comment]
fixed in 1.3.3
