### ISSUE TITLE
Draco loader fails to work on IE11

### ISSUE THREAD

**Issue by SebastienHo** [google/draco#415]
Hi team,

Thanks for prodvided draco, we found it extremely good compared to normal three js loader.

We found out that draco loader does not work on IE11 (either windows 10 or 7) : 
 see https://threejs.org/examples/webgl_loader_draco.html

It looks like WebAssembly is not supported by IE11, therefore it falls into the .js script load : doing so it doesn't load the rabbit model.

Could you help us to solve the issue?

Regards,

Sebastien

**Comment by tomfinegan** [comment]
Does patching in the changes from https://github.com/google/draco/pull/405, and enabling IE_COMPATIBLE when you run CMake fix the issue?

**Comment by SebastienHo** [comment]
I have tried the cmake command  
_cmake ..\draco-master -DCMAKE_TOOLCHAIN_FILE="C:\Users\sho\Downloads\emsdk-master\emsdk-master\emscripten\1.38.5\cmake\Modules\Platform\Emscripten.cmake" -DIE_COMPATIBLE=true_

I get the following outputs

C:\Users\sho\Downloads\draco-master\draco_build>cmake ..\draco-master -DCMAKE_TOOLCHAIN_FILE="C:\Users\sho\Downloads\emsdk-master\emsdk-master\emscripten\1.38.5\cmake\Modules\Platform\Emscripten.cmake" -DIE_COMPATIBLE=true
-- Building for: Visual Studio 15 2017
Checking CXX compiler flag support for: -std=c++11
-- Performing Test HAVE_CXX_FLAG
-- Performing Test HAVE_CXX_FLAG - Failed
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.14.1.windows.1")
-- Found PythonInterp: C:/Users/sho/Downloads/emsdk-master/emsdk-master/python/2.7.13.1_64bit/python-2.7.13.amd64/python.exe (found version "2.7.13")
Checking C compiler flag support for: -s ALLOW_MEMORY_GROWTH=1
-- Performing Test HAVE_C_FLAG
-- Performing Test HAVE_C_FLAG - Failed
Checking CXX compiler flag support for: -s ALLOW_MEMORY_GROWTH=1
-- Performing Test HAVE_CXX_FLAG
-- Performing Test HAVE_CXX_FLAG - Failed
Checking C compiler flag support for: -s LEGACY_VM_SUPPORT=1
-- Performing Test HAVE_C_FLAG
-- Performing Test HAVE_C_FLAG - Failed
Checking CXX compiler flag support for: -s LEGACY_VM_SUPPORT=1
-- Performing Test HAVE_CXX_FLAG
-- Performing Test HAVE_CXX_FLAG - Failed
Checking C compiler flag support for: -Wno-almost-asm
-- Performing Test HAVE_C_FLAG
-- Performing Test HAVE_C_FLAG - Failed
Checking CXX compiler flag support for: -Wno-almost-asm
-- Performing Test HAVE_CXX_FLAG
-- Performing Test HAVE_CXX_FLAG - Failed
Checking C compiler flag support for: --memory-init-file 0
-- Performing Test HAVE_C_FLAG
-- Performing Test HAVE_C_FLAG - Failed
Checking CXX compiler flag support for: --memory-init-file 0
-- Performing Test HAVE_CXX_FLAG
-- Performing Test HAVE_CXX_FLAG - Failed
Checking C compiler flag support for: -fno-omit-frame-pointer
-- Performing Test HAVE_C_FLAG
-- Performing Test HAVE_C_FLAG - Failed
Checking CXX compiler flag support for: -fno-omit-frame-pointer
-- Performing Test HAVE_CXX_FLAG
-- Performing Test HAVE_CXX_FLAG - Failed
Checking C compiler flag support for: -s MODULARIZE=1
-- Performing Test HAVE_C_FLAG
-- Performing Test HAVE_C_FLAG - Failed
Checking CXX compiler flag support for: -s MODULARIZE=1
-- Performing Test HAVE_CXX_FLAG
-- Performing Test HAVE_CXX_FLAG - Failed
Checking C compiler flag support for: -s NO_FILESYSTEM=1
-- Performing Test HAVE_C_FLAG
-- Performing Test HAVE_C_FLAG - Failed
Checking CXX compiler flag support for: -s NO_FILESYSTEM=1
-- Performing Test HAVE_CXX_FLAG
-- Performing Test HAVE_CXX_FLAG - Failed
Checking C compiler flag support for: -s EXPORTED_RUNTIME_METHODS=[]
-- Performing Test HAVE_C_FLAG
-- Performing Test HAVE_C_FLAG - Failed
Checking CXX compiler flag support for: -s EXPORTED_RUNTIME_METHODS=[]
-- Performing Test HAVE_CXX_FLAG
-- Performing Test HAVE_CXX_FLAG - Failed
Checking C compiler flag support for: -s PRECISE_F32=1
-- Performing Test HAVE_C_FLAG
-- Performing Test HAVE_C_FLAG - Failed
Checking CXX compiler flag support for: -s PRECISE_F32=1
-- Performing Test HAVE_CXX_FLAG
-- Performing Test HAVE_CXX_FLAG - Failed
Checking C compiler flag support for: -s ELIMINATE_DUPLICATE_FUNCTIONS=1
-- Performing Test HAVE_C_FLAG
-- Performing Test HAVE_C_FLAG - Failed
Checking CXX compiler flag support for: -s ELIMINATE_DUPLICATE_FUNCTIONS=1
-- Performing Test HAVE_CXX_FLAG
-- Performing Test HAVE_CXX_FLAG - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/sho/Downloads/draco-master/draco_build

None of the tests succeeded, thus I have the solution available. When I try to compile everything with VS 2017, I get the following error :

Severity Code Description Project File Line Deletion Status
Error D8021 invalid numeric argument '/ Wno-almost-asm' draco_decoder_1_glue_decoder_js C: \ Users \ sho \ Downloads \ draco-master \ draco_build \ cl 1
Error D8021 invalid numeric argument '/ Wno-almost-asm' draco_encoder_2_version_js C: \ Users \ sho \ Downloads \ draco-master \ draco_build \ cl 1
Error D8021 invalid numeric argument '/ Wno-almost-asm' draco_decoder_1_prepareCallbacks_js C: \ Users \ sho \ Downloads \ draco-master \ draco_build \ cl 1
Error D8021 invalid numeric argument '/ Wno-almost-asm' draco_decoder_2_finalize_js C: \ Users \ sho \ Downloads \ draco-master \ draco_build \ cl 1
Error D8021 invalid numeric argument '/ Wno-almost-asm' draco_decoder_2_version_js C: \ Users \ sho \ Downloads \ draco-master \ draco_build \ cl 1
Error D8021 invalid numeric argument '/ Wno-almost-asm' draco_encoder_1_glue_encoder_js C: \ Users \ sho \ Downloads \ draco-master \ draco_build \ cl 1
Error D8021 Invalid Numeric Argument '/ Wno-almost-asm' draco_encoder_1_prepareCallbacks_js C: \ Users \ sho \ Downloads \ draco-master \ draco_build \ cl 1
Error D8021 invalid numeric argument '/ Wno-almost-asm' draco_decoder C: \ Users \ sho \ Downloads \ draco-master \ draco_build \ cl 1
Error D8021 invalid numeric argument '/ Wno-almost-asm' draco_encoder_2_finalize_js C: \ Users \ sho \ Downloads \ draco-master \ draco_build \ cl 1
Error D8021 invalid numeric argument '/ Wno-almost-asm' draco_encoder C: \ Users \ sho \ Downloads \ draco-master \ draco_build \ cl 1

Could you tell me what is wrong?

**Comment by tomfinegan** [comment]
@SebastienHo Can you try using the makefile generator? I don't think you're going to be able to get an Emscripten build to work from within Visual Studio.

**Comment by FrankGalligan** [comment]
@SebastienHo The issue is that IE does not support JavaScript Promise. three.js uses Promises in their code.

See Promise compatibility here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility#Browser_compatibility

You should be able to use the Draco JavaScript decoder in IE11, but just not through three.js.

**Comment by aothms** [comment]
I actually got a bit further with this by inserting a promise polyfill in the blob content of the worker URL here https://github.com/mrdoob/three.js/blob/21c1cb2/examples/js/loaders/DRACOLoader.js#L301

Now I get an `abort("Assertion failed: this is a legacy browser, build with LEGACY_VM_SUPPORT")`, probably from emscriptem, which is all perfectly reasonable, and likely solvable, but at this point it's easier for me to just pass the non-compressed gltf to IE users.
