### ISSUE TITLE
APPLICATION_FAULT_INVALID_POINTER_READ_draco_decoder!draco::MeshTraversalSequencer_draco::EdgeBreakerTraverser_draco::CornerTableTraversalProcessor_draco::MeshAttributeCornerTable_,draco::MeshAttributeIndicesEncodingObserver_draco::MeshAttributeCornerTable_,d

### ISSUE THREAD

**Issue by najadojo** [google/draco#416]
Using american fuzzy lop 2.49b on draco_decoder 1.3.2 I found crashes at stacks like:

draco_decoder!draco::MeshTraversalSequencer<draco::EdgeBreakerTraverser<draco::CornerTableTraversalProcessor<draco::MeshAttributeCornerTable>,draco::MeshAttributeIndicesEncodingObserver<draco::MeshAttributeCornerTable>,draco::EdgeBreakerObserver> >::UpdatePointToAttributeIndexMapping+0xe3
draco_decoder!draco::SequentialAttributeDecodersController::DecodeAttributes+0x86
draco_decoder!draco::PointCloudDecoder::DecodeAllAttributes+0x2d
draco_decoder!draco::PointCloudDecoder::DecodePointAttributes+0x17c
draco_decoder!draco::PointCloudDecoder::Decode+0x311
draco_decoder!draco::MeshDecoder::Decode+0x1c
draco_decoder!draco::Decoder::DecodeBufferToGeometry+0x252
draco_decoder!draco::Decoder::DecodeMeshFromBuffer+0x6c
draco_decoder!main+0x6eb

Input [example.zip](https://github.com/google/draco/files/2081835/example.zip) demonstrates the failure.

**Comment by ondys** [comment]
fixed in 1.3.3
