### ISSUE TITLE
Assertion failed: (normal.AbsSum()) <= (upper_bound) 

### ISSUE THREAD

**Issue by chipweinberger** [google/draco#419]
I've been documenting this issue over here:https://github.com/donmccurdy/three-gltf-viewer/issues/99

I have a mesh with positions and normals only. It encodes without error, but fails on decode.

**Comment by ondys** [comment]
I believe this problem is already fixed in the latest version of draco decoder. It seems the decoders at Don's repo are somehow out of date and need to be updated (https://github.com/donmccurdy/three-gltf-viewer/tree/master/lib/draco)

**Comment by chipweinberger** [comment]
Great! I'll forward this to him and see if it fixes it!

**Comment by donmccurdy** [comment]
Just to confirm, is this a decoder bug that has been fixed, or something in the newer encoder that is not backward-compatible?

**Comment by ondys** [comment]
It was a decoder bug and bitstream wasn't changed (a couple of wrong asserts sneaked in to the javascript / wasm decoder).

**Comment by donmccurdy** [comment]
Ok, thanks!
