### ISSUE TITLE
2 issues I met when try the javascript sample

### ISSUE THREAD

**Issue by philxia** [google/draco#42]
1.  Get 2 errors in chrome console for files - DRACOLoader.js and webgl_loader_draco.html.
>>
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode.
<<
Add the "use strict" at the beginning of these 2 files can fix it.

2. Get 1 object undefined error when value the cameraTarget in webgl_loader_draco.html file.
>>
function init() {
        container = document.createElement('div');
        document.body.appendChild(container);

        camera = new THREE.PerspectiveCamera(35, window.innerWidth / window.innerHeight, 1, 15);
        camera.position.set(3, 0.15, 3);
        cameraTarget = new THREE.Vector3(0, 0, 0);
<<
declare it with camera can fix it.
>>
      let camera, cameraTarget, scene, renderer;
<<

**Comment by FrankGalligan** [comment]
Thanks philxia.

Made the changes in this commit: https://github.com/google/draco/commit/3682ca28018e77f330c29327cea6f244d53fad78
