### ISSUE TITLE
Getting td::bad_alloc error while decoding drc file as obj

### ISSUE THREAD

**Issue by Rafidheen** [google/draco#420]
Unhandled exception at 0x769DC41F in draco_decoder.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x001CECB8.
![error](https://user-images.githubusercontent.com/9413194/41164716-77868b72-6b59-11e8-8e1d-41d1599942ea.png)

Please let me know if any other details required.

**Comment by ondys** [comment]
Hi,
Can you share with us the .drc file that causes this issue? Thanks

**Comment by FrankGalligan** [comment]
I'm closing this issue. If you are still having problems please re-open.
