### ISSUE TITLE
Some labels can't resolved in the 0.9.1 version of Draco.

### ISSUE THREAD

**Issue by yazhouzheng** [google/draco#422]
Hi Developers,

I have a legacy code which using Draco initial version's interfaces. but when I add the related Draco code to my project, there still has some labels can't resolved, such as draco::BasicIndexType, draco::FixedDataBuffer and PointAttribute's setBuffer method mesh's method SetFaces, I want to know whether there has earlier Draco version can solve this problem? Anyone could help me with this problem? Thanks.

Best Regards
Asher

**Comment by ondys** [comment]
you may try using older version of draco from here: https://github.com/google/draco/releases/tag/0.9.1

**Comment by yazhouzheng** [comment]
Thanks for providing the advice, but I have tested the version 0.9.0 and version 0.9.1, it still can't work around. And I found the ResetBuffer method of point_cloud/point_attribute.cc in the source code , but no setBuffer found, can you give some hint about it?

Best Regards
Asher

**Comment by yazhouzheng** [comment]
And here is my search history:
/draco-0.9.1
$ grep -irn "setBuffer" *
point_cloud/geometry_attribute.cc:68:void GeometryAttribute::ResetBuffer(const DataBuffer *buffer,
point_cloud/geometry_attribute.h:183:  void ResetBuffer(const DataBuffer *buffer, int64_t byte_stride,
point_cloud/point_attribute.cc:43:  ResetBuffer(attribute_buffer_.get(), entry_size, 0);

And I have a question, Since there has no setBuffer method, why there has a method called ResetBuffer?
