### ISSUE TITLE
How to encode triangle strips?

### ISSUE THREAD

**Issue by FreddyFunk** [google/draco#423]
Hello,

I saw the file "_mesh_stripifier.h_" and am courious, how to initialize a Draco Mesh with triangle strips and if the C++ Encoder and Decoder could handle triangle strips with primitive restart or with degenerated triangles in a Mesh as input. 

Kind Regards

**Comment by ondys** [comment]
mesh stripifier is used only to generate triangle strips out of an existing `draco::Mesh` but `draco::Mesh` itself does not support triangle strip representation. If you want to encode triangle strips with draco, you need to "unroll" the strips to regular tri-list representation and then stripify the decoded mesh (but the strips will be most likely different compared to the input mesh)

**Comment by FreddyFunk** [comment]
Ok, thank you for this information. Do you know which algorithms have constraints that prevent the draco encoder to work directly on triangle strips?

**Comment by ondys** [comment]
The main algorithm used by Draco is based on the Edgebreaker method that encodes the connectivity in a specific pattern that does not follow triangle strips. Strips could be theoretically encoded directly with the sequential encoding method, but we currently don't have a support for that

**Comment by guanprco** [comment]
Hi @ondys,

Draco implementation has references to mesh sequential encoding in a few places: 
* class MeshSequentialEncoder cf src/draco/compression/mesh/mesh_sequential_encoder.h
* class MeshSequentialDecoder cf src/draco/compression/mesh/mesh_sequential_decoder.h

Is sequential encoding now supported, meaning it should be possible to use Draco to exchange triangle strip? 

Regards,
