### ISSUE TITLE
Is there technical papers or algorithm documents which explain basic and deep details of draco?

### ISSUE THREAD

**Issue by ShaoyuanLi** [google/draco#425]
Hello,

I have learned corto(vclab) and other mesh compression library.I have read some papers such as _Edgebreaker: Connectivity compression for triangle meshes_ and _Edge breaker on a Corner Table : A simple technique for representing and compressing triangulated surfaces_.However draco code seems more complexity than below projects and papers.Is there technical papers or algorithm documents which explain basic and deep details of draco ?

Kind Regards

**Comment by imhuwq** [comment]
I'm searching for this too, and I find this wikipedia page about [ANS algoritm](https://en.wikipedia.org/wiki/Asymmetric_numeral_systems):

> Among others, ANS is used in the Facebook Zstandard compressor[5] (also used e.g. in Linux kernel,[6] there is ongoing standardization for MIME[7]), in the Apple LZFSE compressor,[8] Google Draco 3D compressor[9] and PIK image compressor,[10] in CRAM DNA compressor[11] from SAMtools utilities, Dropbox DivANS compressor,[12] and it is being considered for the AV1 open video coding format[13] from the Alliance for Open Media.

**Comment by FrankGalligan** [comment]
Probably the best is the bitstream spec.
https://google.github.io/draco/spec/

**Comment by expenses** [comment]
> Probably the best is the bitstream spec. https://google.github.io/draco/spec/

No offence, but this isn't a spec. It's just a list of C-like pseudocode functions. The KTX spec (http://github.khronos.org/KTX-Specification/) is a good example of what a specification should look like and I'd love to see something like this for draco.
