### ISSUE TITLE
Failed loading the input mesh: Failed to parse a float number

### ISSUE THREAD

**Issue by CC1027CC** [google/draco#426]
I'm getting errors encoding.
[test.zip](https://github.com/google/draco/files/2122855/test.zip)
This obj file is generated by Rhino tool.

**Comment by ondys** [comment]
I believe the problem is caused by having split lines with `\` symbol such as 
```
vn -0.06065036356449127 3.663852112367749e-05 \
 -0.9981590509414673
```

It seems pretty non-standard to me, but I'll add it to our internal issue tracker and hopefully we will add support for this into the Draco OBJ loader

**Comment by FrankGalligan** [comment]
Closing due to low priority.
