### ISSUE TITLE
sub_obj attribute points less than actual points?

### ISSUE THREAD

**Issue by merxim** [google/draco#429]
Hello,

I am trying to use the method described in https://github.com/google/draco/issues/89 by @ondys  and @NumaNumaNuma, and I managed to make changes both to the decoder plugin and in Unity using the code samples.
While the vertices seem to be in order(can't see them yet, but it doesn't throw any errors) and the logic with the faces seems to be fine as well, There is an index error when I m trying to assign the faces to sub meshes I ve created. 
What happens:  
-Num vertices: 460371
-Num Faces: 452244
-Decoded mesh has 389233 points (sub_obj_id's length) with 924 sub objects (sub_obj_id's value range).
ERROR happens when assigning faces and they start referencing points with id bigger than 389233. 
Why would I be missing 60k thousand points from the sub objects attribute? 
I have not modified how the attribute is gotten, so there is a problem in my case there to begin with.
P.S.: Model gets completely normally rendered as one mesh when using the default code. 

Are the points in subobj non-consecutive or something else? Thanks!

**Comment by NumaNumaNuma** [comment]
I haven't used draco in a while, but your 60k points missing reminded me that Unity silently splits models with more than 63k vertices. Maybe that has something to do with it?

**Comment by merxim** [comment]
I 'm running draco_decoder in visual studio in debug mode with breakpoints and it still has the same behaviour: 
http://prntscr.com/jzufsg

**Comment by merxim** [comment]
For other people that might come across this: I was accessing the values for sub_obj_names  through the Attribute->buffer->data(). everything was resolved (and i didn't have to manually pass the index mapping to Unity) when I stored the values in the same way as the other attributes in the draco_unity_plugin.cc:  "if (!subojb_att->ConvertValue<int, 1>(val_index, unity_mesh->sub_objs + i.value())) "
