### ISSUE TITLE
How to decode GENERIC Attributes?

### ISSUE THREAD

**Issue by adishavit** [google/draco#43]
How do I decode an attribute of type `GENERIC`?

The function:
```
int32_t PointCloud::NumNamedAttributes(GeometryAttribute::Type type) const {
  if (type == GeometryAttribute::INVALID ||
      type >= GeometryAttribute::NAMED_ATTRIBUTES_COUNT) // == GeometryAttribute::GENERIC
    return 0;
  return named_attribute_index_[type].size();
}
```

always returns 0.

I saw an issue mentioning custom IDs, but I don't understand how to make these work either.

**Comment by ondys** [comment]
One way to get generic attribute data on the decoder side is to first assign a unique custom id to the encoded attribute and then after the point cloud/mesh is decoded you can go over all attributes and get the one with the matching custom id. Example:

```
// Encoder:
const int generic_attribute_id = mesh->AddAttribute(...) ; // Create your custom attribute attribute
mesh->attribute(generic_attribute_id)->set_custom_id(unique_id);
...

// Decoder:
PointAttribute *generic_attribute = nullptr;
for (int i = 0; i < decoded_mesh->num_attributes(); ++i) {
  if (decoded_mesh->attribute(i)->custom_id() == unique_id) {
    generic_attribute = decoded_mesh->attribute(i);
    break;
  }
}

```

We will probably add more API functions to simplify this process in future.

**Comment by swomack** [comment]
@ondys 

Is it possible to iterate over the attributes in javascript? I cant find any function to access the attribute using the index.

**Comment by FrankGalligan** [comment]
I'm closing this issue. If you are still having problems please re-open.
