### ISSUE TITLE
After compress, the obj's texture coordinate changed 

### ISSUE THREAD

**Issue by maskerman** [google/draco#437]
I try draco 1.3.2 ,and find a problem :After endcode and decoder, some obj's texture coordinate changed.
      Please see attached test.

zip. I use the following command line:
      draco_encoder.exe -i vrtest.obj -o vrtest -qt 14
      then I run the following command line:
      draco_decoder.exe -i vrtest -o vrtest1.obj
      and import the two obj to 3dsmax. then I find the texture-coord is change. please see attached image(14.jpg)
[test.zip](https://github.com/google/draco/files/2205128/test.zip)
 the left is orgin obj file, and the right is the new obj file(vrtest1.obj). 
      How to solve this problem?

**Comment by maskerman** [comment]
attached screen capture 14.jpg.
[14.zip](https://github.com/google/draco/files/2205149/14.zip)

**Comment by FrankGalligan** [comment]
I think this is because of the precise nature of the texture coordinates and the quantization. E.g. If you run:
draco_encoder.exe -i vrtest.obj -o vrtest-qt20.drc -qt 20
draco_decoder.exe -i vrtest-qt20.drc -o vrtest2.obj

vtrtest2.obj will have texcoords that look correct.

**Comment by maskerman** [comment]
thanks! I try and find it's ok
