### ISSUE TITLE
Could Not Found ./draco_encoder

### ISSUE THREAD

**Issue by qiangzi7723** [google/draco#439]
Arter I run `cmake ../ -G Xcode`, I could not found draco_encoder or draco_decoder. So I don't know how to compress my obj.

Where are they?My system is Mac Serria 10.12.2. Thanks.

By the way, `cmake ../ -G Xcode` work successful but no draco_encoder and draco_decoder.

**Comment by FrankGalligan** [comment]
Hello,

`cmake ../ -G Xcode` will build the Xcode project. Then you need to open the Xcode project in Xcode to build draco_encoder and draco_decoder.


If you have the command line tools installed on your mac you can just build form the command line.  

`cmake ../`
`make`
