### ISSUE TITLE
Add build support for VS2013

### ISSUE THREAD

**Issue by cheneyfan** [google/draco#44]
error C4430 for vs2013 debug x64

**Comment by tomfinegan** [comment]
Hi @cheneyfan! Please post the full build output. I suspect this is an issue with C++11 support in vs2013, but knowing all of the details would help here. Thanks!

**Comment by minimoog** [comment]
Most of the C4430 are because constexpr is not supported in vs2013:

draco_index_type.h(67): error C2146: syntax error : missing ';' before identifier 'IndexType'

**Comment by FrankGalligan** [comment]
Currently VS2015 is required to build.

**Comment by FrankGalligan** [comment]
I'm closing this issue. If you are still having problems please re-open.
