### ISSUE TITLE
If you want people to use that library, you need to make that documentation accessible

### ISSUE THREAD

**Issue by jokoon** [google/draco#441]
I just wanted to read about the internals of draco, looking at its doc.

I landed here https://github.com/google/draco/tree/master/docs/spec

You should provide a HTML doc, or a simpler way to generate the doc, like plain markdown. This is wirth's law at play here.

From what I gather you require 5 (!?!) things to generate that doc: ruby, rbenv, markdown, bundle, kramdown, jekyll. Apparently it starts a server. I stopped trying to find out how to generate that doc because fixing an error brought another one.

Do you realize I'm posting an issue about generating a documentation?

This library seems interesting, but honestly if it's a hurdle to build the doc, is that a bad sign? What's the point of open sourcing it if you inadvertently make it hard to read about it?

**Comment by louquillio** [comment]
There is no need to build the document. The rendered document (HTML) is automatically published by GitHub Pages, here:

https://google.github.io/draco/spec/

The document build steps essentially describe the GitHub Pages pipeline. They are only needed if one had a special need to build it locally.
