### ISSUE TITLE
Fatal error in draco_unity_plugin.cc

### ISSUE THREAD

**Issue by ToniFF** [google/draco#446]
The codes about getting uv are wrong and Unity crash would be caused. They should be:

if (!texcoord_att->ConvertValue<float, 2>(
              val_index, unity_mesh->texcoord + i.value() * 2)) {
        ReleaseUnityMesh(&unity_mesh);
        return -8;
}

**Comment by FrankGalligan** [comment]
This will be fixed in the next release

**Comment by FrankGalligan** [comment]
Should be fixed in 1.3.4
