### ISSUE TITLE
There is some way to convert a gltf file to a drc file?

### ISSUE THREAD

**Issue by lucasdeoliveiragomes** [google/draco#449]
I'm trying to convert a 3d file to drc, but it's neither obj nor ply, so I've seen the compatibility of Draco with gltf. I would like to know if there is anything ready to convert a gltf file to a Draco file.

**Comment by donmccurdy** [comment]
@lucasdeoliveiragomes glTF supports many features like materials, animation, and node hierarchies, so converting from `.gltf` to `.drc` would lose a lot of information. If you're just trying to add Draco compression to an existing model, you can do that while keeping it in `.gltf` format. Refer to the [2.0 branch of glTF-Pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/tree/2.0).

If you really need the result to be a `.drc` file, I think you'll need to convert from glTF to OBJ to DRC.

**Comment by lucasdeoliveiragomes** [comment]
My goal was to able to convert other file types(stl for example) to drc, and when saw the gltf compatibility with draco I think that could convert a file to gltf and after to drc

**Comment by donmccurdy** [comment]
Probably what you saw mentioned about "gltf compatibility with draco" is that the glTF format uses the Draco compression technique inside its own (`.gltf` or `.glb`) files. If you want highly compressed files that contain both meshes and materials, then glTF (with Draco) is probably the right thing to use, there are many more tools that can open glTF files than `.drc` files.

I do not think there are any tools that can convert directly from glTF to `.drc`. You can convert from glTF to OBJ using a [Blender importer](https://github.com/julienduroure/gltf2-blender-importer), then convert to `.drc`. But you will lose the color/material of the model.

**Comment by lucasdeoliveiragomes** [comment]
The [draco3dgltf](https://github.com/google/draco/tree/master/javascript/npm/draco3dgltf) don't do that?

**Comment by donmccurdy** [comment]
No, the `draco3dgltf` module does not have any features for reading a glTF file. Typically it would be used for encoding geometry "in place" in a glTF file, or decoding Draco data in a glTF file at runtime.

Even if a converter existed, it would never be possible to convert _everything_ in a glTF file to a `.drc` file. Materials, textures, animation, etc. will be lost.

**Comment by lucasdeoliveiragomes** [comment]
Ok, thanks very much!
