### ISSUE TITLE
vector subscript out of range error,

### ISSUE THREAD

**Issue by dyangrun** [google/draco#451]
`int64_t ComputeShannonEntropy(const uint32_t *symbols, int num_symbols,
                              int max_value, int *out_num_unique_symbols) {
  // First find frequency of all unique symbols in the input array.
  int num_unique_symbols = 0;
  std::vector<int> symbol_frequencies(max_value + 1, 0);
  for (int i = 0; i < num_symbols; ++i) {
    ++symbol_frequencies[symbols[i]];
  }`

this max_value is -1，because in EncodeSymbols function ComputeBitLengths function get max_value is
4294967295， MAX of Uint~

i think this value type is inconsistent
` 	dracodec_unity.dll!std::vector<int,std::allocator<int> >::operator[](unsigned __int64 _Pos)  行 1235	C++
>	dracodec_unity.dll!draco::ComputeShannonEntropy(const unsigned int * symbols, int num_symbols, int max_value, int * out_num_unique_symbols)  行 16 + 0x1c 字节	C++
 	dracodec_unity.dll!draco::ApproximateRawSchemeBits(const unsigned int * symbols, int num_symbols, unsigned int max_value, int * out_num_unique_symbols)  行 94 + 0x18 字节	C++
 	dracodec_unity.dll!draco::EncodeSymbols(const unsigned int * symbols, int num_values, int num_components, const draco::Options * options, draco::EncoderBuffer * target_buffer)  行 134 + 0x21 字节	C++
 	dracodec_unity.dll!draco::SequentialIntegerAttributeEncoder::EncodeValues(const std::vector<draco::IndexType<unsigned int,draco::PointIndex_tag_type_>,std::allocator<draco::IndexType<unsigned int,draco::PointIndex_tag_type_> > > & point_ids, draco::EncoderBuffer * out_buffer)  行 154 + 0x4e 字节	C++
 	dracodec_unity.dll!draco::SequentialAttributeEncoder::EncodePortableAttribute(const std::vector<draco::IndexType<unsigned int,draco::PointIndex_tag_type_>,std::allocator<draco::IndexType<unsigned int,draco::PointIndex_tag_type_> > > & point_ids, draco::EncoderBuffer * out_buffer)  行 49 + 0x1a 字节	C++
 	dracodec_unity.dll!draco::SequentialAttributeEncodersController::EncodePortableAttributes(draco::EncoderBuffer * out_buffer)  行 76 + 0x4e 字节	C++
 	dracodec_unity.dll!draco::AttributesEncoder::EncodeAttributes(draco::EncoderBuffer * out_buffer)  行 53 + 0x15 字节	C++
 	dracodec_unity.dll!draco::SequentialAttributeEncodersController::EncodeAttributes(draco::EncoderBuffer * buffer)  行 61	C++
 	dracodec_unity.dll!draco::PointCloudEncoder::EncodeAllAttributes()  行 150 + 0x4e 字节	C++
 	dracodec_unity.dll!draco::PointCloudEncoder::EncodePointAttributes()  行 129 + 0x16 字节	C++
 	dracodec_unity.dll!draco::PointCloudEncoder::Encode(const draco::EncoderOptionsBase<int> & options, draco::EncoderBuffer * out_buffer)  行 48 + 0x16 字节	C++
 	dracodec_unity.dll!draco::ExpertEncoder::EncodeMeshToBuffer(const draco::Mesh & m, draco::EncoderBuffer * out_buffer)  行 111 + 0x3f 字节	C++
 	dracodec_unity.dll!draco::ExpertEncoder::EncodeToBuffer(draco::EncoderBuffer * out_buffer)  行 36 + 0x29 字节	C++
 	dracodec_unity.dll!draco::Encoder::EncodeMeshToBuffer(const draco::Mesh & m, draco::EncoderBuffer * out_buffer)  行 33 + 0x1a 字节	C++
 	dracodec_unity.dll!EncodeMeshForUnity(char * * data, draco::DracoToUnityMesh * * tmp_mesh)  行 191	C++
`
Maybe we should add a conditional judgment for max_value

**Comment by dyangrun** [comment]
i check my data,found that my data was missing very large vertices.is error，fix it error disappears。
but if i real have very large vertices，is right value~
this issue can to happen,should be avoided

**Comment by FrankGalligan** [comment]
@dyangrun Can you post the old file that exhibited the issue? It is nice to have to check that the bug is fixed.

**Comment by dyangrun** [comment]
@FrankGalligan Sorry for so long to reply, i check my data for a long time, because the NaN value appeared in .obj file，so is not issues.

**Comment by dyangrun** [comment]
@FrankGalligan Sorry for so long to reply, i check my data for a long time, because the NaN value appeared in .obj file，so is not issues.
