### ISSUE TITLE
Mesh is not getting loaded properly unity android

### ISSUE THREAD

**Issue by nomercy0** [google/draco#453]
1. I tried loading encoded  drc files (**with** --skip TEX_COORD ) with  unity android the mesh loads perfectly fine
2.  Again I tried loading encoded drc files (**without** --skip TEX_COORD which is default setting)  in unity android mesh got weird very weird and by applying material it does not show as expected.

I am attaching drc file for both along with screenshot of decoded mesh and original obj file

[101.zip](https://github.com/google/draco/files/2293050/101.zip)

**Comment by FrankGalligan** [comment]
@nomercy0 Can you try again with release 1.3.4?

**Comment by nomercy0** [comment]
Working now
