### ISSUE TITLE
out of bounds memory access on IOS 11.2.6

### ISSUE THREAD

**Issue by riematrix** [google/draco#456]
**ios safari crashed** when loading .drc model/material, and after several refresh action the console reports an error: "out of bounds memory access".

**test data/code**
[example.zip](https://github.com/google/draco/files/2316919/example.zip)

I added texture load to the example code. Draco compression config is default.
browser: ios safari 11.2.6

**stack trace**
[Error] Unhandled Promise Rejection: Error: Out of bounds memory access (evaluating 'a.asm._emscripten_bind_Decoder_Decoder_0.apply(null,arguments)')
	wasm function: 616 (draco_wasm_wrapper.js:54:274)
	wasm function: 658
	wasm function: 83
	wasm function
	_emscripten_bind_Decoder_Decoder_0
	_emscripten_bind_Decoder_Decoder_0 (draco_wasm_wrapper.js:54:274)
	g (draco_wasm_wrapper.js:24)
	decodeDracoFileInternal (DRACOLoader.js:120)
	（匿名函数） (DRACOLoader.js:108)
	promiseReactionJob

PS: Seems that on mobile safari the total time of rendering a .drc file(from page load to mesh display) is longer than the original .obj file.
Do you have any suggestions?

**Comment by FrankGalligan** [comment]
Draco has been working on ios now.
