### ISSUE TITLE
How to use animations?

### ISSUE THREAD

**Issue by jeckgit** [google/draco#457]
Hi. I'm trying to figure out how the animation code works right now. Can you publish a sample file where the keyframe animations are stored? How are the keyframe information stored in obj and ply files?

**Comment by FrankGalligan** [comment]
Hi @jeckgit,

I put up some sample glTF files encoded with Draco animation here:
https://github.com/FrankGalligan/glTF-Sample-Models/tree/add_draco_animation

The files will be in the "glTF-Draco-Mesh-Anim" folders.

As for animation in OBJ and PLY, we currently do not have support for animation in those file formats. We currently only have support for glTF.


Code to create glTF Draco animation files using gltf-pipeline:
https://github.com/FrankGalligan/gltf-pipeline/tree/add_draco_animation_compression

Code to render glTF Draco animation files using three.js
https://github.com/FrankGalligan/three.js/tree/add_draco_animation_compression

glTF extension spec draft for Draco animation:
https://github.com/FrankGalligan/glTF/tree/draco_animation_extension_draft/extensions/2.0/Vendor/DRACO_animation_compression

**Comment by jeckgit** [comment]
Now that I have some input, I will close the issue for now. TY
