### ISSUE TITLE
Error: "Invalid number of indices on a face."

### ISSUE THREAD

**Issue by JohnnyPosi** [google/draco#458]
I'm getting this error when I'm trying to decode my `.obj` model. Is there any way to fix it?

**Comment by JohnnyPosi** [comment]
Solved it: when export the model in Blender, just enable "Triangulate Faces" option. It increased the object size though.

**Comment by jeromeetienne** [comment]
Just for logging, the same happened to me and the same solution worked. What about appending this message with 'Maybe try to triangulate your model?"

**Comment by awong1900** [comment]
why do not support the Quad ?

**Comment by FrankGalligan** [comment]
Closing as we added support to triangulate quads a while ago. See https://github.com/google/draco/blob/master/src/draco/io/obj_decoder.cc#L404
