### ISSUE TITLE
How n-polygons are compressed and why only triangle meshes are created during decompression

### ISSUE THREAD

**Issue by jeckgit** [google/draco#459]
Hello,
I was wondering how the compression algorithm and the decompression algorithm work. With Draco, n-polygonal meshes can be compressed. However, only triangle meshes are created during decompression.
I assumed that the algorithm ["Geometry Prediction for High Degree Polygons"](https://www.cs.unc.edu/~isenburg/gphdp/) presented by Isenburg was used for compressing, because I repeatedly came across the parallelogram prediction inside the source code.
From the source code I also found that the ["Edgebreaker" ](https://www.cc.gatech.edu/~jarek/papers/CornerTableSMI.pdf) algorithm was used, which in turn can only compress triangle meshes.

My question is, how are n-polygonal meshes compressed or how are the triangle meshes finally created by decompression?

**Comment by imhuwq** [comment]
I think there are two layers of compression in the Draco lib:
- mesh compression using ParallelogramPrediction etc.
- data compression using ANS algorithm

**Comment by ondys** [comment]
Draco works only on triangular meshes. For some cases (e.g. obj files) the n-polygons are triangulated during mesh loading, but they are not preserved during compression. One way to preserve general polygons is to use generic attributes that store what edges are "internal". To see how that could be used check code used in the Draco USD plugin:
https://github.com/PixarAnimationStudios/USD/pull/761
