### ISSUE TITLE
codelab compilation step seems obsolete

### ISSUE THREAD

**Issue by jeromeetienne** [google/draco#462]
the compilation step for draco in the codelab seems to be obsolete. https://codelabs.developers.google.com/codelabs/draco-3d/index.html#2

doing ```cmake .``` in draco repository is reporting the following message.

```
  Building from within the Draco source tree is not supported.

  Hint: Run these commands

  $ rm -rf CMakeCache.txt CMakeFiles

  $ mkdir -p ../draco_build

  $ cd ../draco_build

  And re-run CMake from the draco_build directory.
```

Those instructions worked for me

**Comment by FrankGalligan** [comment]
The codelab has been updated so the compilation step works with the latest version. Thanks for the report.
