### ISSUE TITLE
How to create Draco_animation_compression

### ISSUE THREAD

**Issue by jeckgit** [google/draco#465]
Hello,

I am trying to create the Draco_animation_compression, with the gltf-pipeline. 
[https://github.com/FrankGalligan/gltf-pipeline/tree/add_draco_animation_compression](https://github.com/FrankGalligan/gltf-pipeline/tree/add_draco_animation_compression)

I wanted to compress the AnimatedMorphCube Example.
[https://github.com/FrankGalligan/glTF-Sample-Models/tree/add_draco_animation/2.0/AnimatedMorphCube](https://github.com/FrankGalligan/glTF-Sample-Models/tree/add_draco_animation/2.0/AnimatedMorphCube)

I am using the following comand:

`node bin/gltf-pipeline.js -i test_gltf/GoogleDracoCube/AnimatedMorphCube/glTF/AnimatedMorphCube.gltf -d -s -o test_gltf/GoogleDracoCube/AnimatedMorphCube/gltf-animated-Draco/AnimatedMorphCube.gltf`

What I expected was a compressed file with "extensionsRequired " and the "Draco_animation_compression" property inside and the "extensions" object also with the "Draco_animation_compression" proberty, like 
[https://github.com/FrankGalligan/glTF-Sample-Models/blob/add_draco_animation/2.0/AnimatedMorphCube/glTF-Draco-Mesh-Anim/AnimatedMorphCube.gltf](https://github.com/FrankGalligan/glTF-Sample-Models/blob/add_draco_animation/2.0/AnimatedMorphCube/glTF-Draco-Mesh-Anim/AnimatedMorphCube.gltf) .

I only got a nearly uncompressed file with the "KHR_draco_mesh_compression" as "extensionsRequired" and no describtion.

What do I have to do to get a draco compressed gltf-morph-animation like in the example that was provided? 

I hope you can help

**Comment by FrankGalligan** [comment]
you need to add the "-a" option on the command line.
