### ISSUE TITLE
decoded mesh with texture looks worse with cl=0 vs. the default cl=5

### ISSUE THREAD

**Issue by davegirdy** [google/draco#47]
I'm having an issue with a particular mesh where the encoded & decoded mesh shows black spots on the texture. I found out that materials are not yet preserved on OBJ export... so I manually added the line "mtllib ./mesh.obj.mtl" to the OBJ file after I decoded it. What was weirder is that the black spots became more prevalent when I set cl=0. I attached some screenshots of before and after, and also the original model. Also, the decoded mesh file size is bigger than the original. I think it might be because the decoded mesh has a blank line after every entry. (I'm using default cmake settings with VS 2015 Community, x64 Release build of encoder & decoder). Any idea why this mesh in particular doesn't encode & decode well? Thanks! 

![cl_eq_0](https://cloud.githubusercontent.com/assets/3012561/22274191/d269dcb8-e259-11e6-8451-fc3947ab6414.png)
![default_cl_eq_5](https://cloud.githubusercontent.com/assets/3012561/22274192/d26d9966-e259-11e6-8457-529f1ab38327.png)
[mesh.zip](https://github.com/google/draco/files/728388/mesh.zip)

**Comment by ondys** [comment]
Thanks for the report. Can you please also attach the encoded .drc file and the decoded .obj file? (for -cl 0 would be sufficient). 

I tried to reproduce it on our end and I it worked as expected (no artifacts for either -cl 0 or -cl 5 (default)). It was on Linux though so it is possible, there is some windows specific bug, I'll investigate more.

**Comment by davegirdy** [comment]
Sure, no problem. See below! Thanks for looking into it.
[mesh_decoded.zip](https://github.com/google/draco/files/731035/mesh_decoded.zip)

**Comment by davegirdy** [comment]
I also tried on Linux and confirm that this is a Windows specific bug. Linux results looks good on my end.

**Comment by FrankGalligan** [comment]
Hi Dave,

Sorry it took so long. We were setting up a windows development machine. So we figured out what the issue is.

For some reason in your mesh_decoded.obj file the first line got messed up. Here are the first two lines:
`mtllib ./mesh.obj.mtl usemtl material_0v -62.325630 -129.229721 -69.757767
v -61.428375 -129.248032 -71.479034`

The problem is you only have a CR between `material_0v -62.325630`. If you add a windows line ending (LF) then your file works great. E.g.
`mtllib ./mesh.obj.mtl usemtl material_0
v -62.325630 -129.229721 -69.757767
v -61.428375 -129.248032 -71.479034`

**Comment by davegirdy** [comment]
No problem on the delay! Thank you for looking into this. I confirm the problem is indeed with line endings.  

I was using Notepad++ on the decoded OBJ file so I could add back in the MTL lines. The file was bieng opened in "Macintosh" mode.

If I copy/paste all the lines into a new Notepad++ file (default is Dos\Windows format) and save the file... everything works again. 

Thanks again for Draco! I am getting really good results with it so far.
