### ISSUE TITLE
Executing with g++ 4.8.4 possible? 

### ISSUE THREAD

**Issue by briar-smith** [google/draco#472]
g++ is required to execute Draco (likely due to std lib dependencies?). It looks like g++ 4.9 executes Draco but the servers I'm trying to run on are Ubuntu 14.04, g++ 4.8.4. Is there anyway to execute it with this version of g++?? Help would really be appreciated.

**Comment by FrankGalligan** [comment]
This would be difficult to go back through the code and make sure it works with gcc 4.8.
