### ISSUE TITLE
CMake configure fails with c++_static.props not found

### ISSUE THREAD

**Issue by dletozeun** [google/draco#475]
Hello,

On following build host system configuration:
Windows 10
VS 2017 15.8.1
CMake 3.12.3
Nsight Tegra for VS 3.5

The CMake build configuration fails for at least arm and arm64 architectures with the following error:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\Tegra-Android\PlatformToolsets\Stl.props(7,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\Tegra-Android\PlatformToolsets\Stl\c++_static.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The c++_static.props file does not exist at least in my VS install and replacing with llvm-libc++.props worked. To do so I replaced in the toolchain cmake file of each architecture the following:

> set_variable_if_unset(CMAKE_ANDROID_STL_TYPE c++_static)

by

> set_variable_if_unset(CMAKE_ANDROID_STL_TYPE llvm-libc++_static)

Did I misconfigure something? Thanks!

**Comment by tomfinegan** [comment]
What NDK version are you using?

**Comment by dletozeun** [comment]
Hi Tom,

I uses the latest version supported by VS 2017: r15c

**Comment by tomfinegan** [comment]
> I uses the latest version supported by VS 2017: r15c

Interesting. Nvidia [docs](https://docs.nvidia.com/gameworks/content/developertools/mobile/nsight_tegra/nsight_tegra_v3_5.htm) claim r14 is the latest, but perhaps that page is out of date. TBH, I'm not sure that matters here. It was the only missing piece for a repro attempt if it comes down to that.

This problem is somewhat confusing since the CMake [docs](https://cmake.org/cmake/help/latest/variable/CMAKE_ANDROID_STL_TYPE.html) state that c++_static means LLVM libc++ static

Anyway, you should be able to set CMAKE_ANDROID_STL_TYPE when running CMake and without touching the toolchain file. Try adding `-DCMAKE_ANDROID_STL_TYPE=llvm-libc++_static` to your CMake command line.

**Comment by ToniFF** [comment]
With Draco 1.3.4, NDK r12b, and Visual Studio 2017, I met the same issue too and "-DCMAKE_ANDROID_STL_TYPE=llvm-libc++_static" doesn't work. I have to modify the toolchain cmake files. Thank you for sharing the solution.

**Comment by Tostifrosti** [comment]
I came across this error as well (Draco 1.3.5, VS2017, NDK r16b, CMake 3.13.0-rc1). Adding this line `-DCMAKE_ANDROID_STL_TYPE=llvm-libc++_static"` doesn't fix the problem. It seems to be ignored by Visual Studio (maybe it's a setting within Visual Studios). 

I found a small workaround:

1. Use your cmake command to create the cache files.
2. Go to that folder /CMakeFiles/(your cmake version)/CMakeSystem.cmake
3. Edit the file by adding line `set(CMAKE_ANDROID_STL_TYPE llvm-libc++_static)` below `CMAKE_CROSSCOMPILING`.
4. Rerun your cmake command without deleting any cache files.

This doesn't fix the problem, so the developers still needs to fix this (maybe adding this option in CMakeLists). 
Hopefully this will help some ppl.

**Comment by kizjig** [comment]
I too am seeing the same issue when trying to build ARM7 architecture.

Windows 10
VS 2017 version 15.9.28307.222
Nsight Tegra for VS 3.5
CMake v3.14.5

I modified the toolchain cmake files as suggested by @ToniFF as the `DCMAKE_ANDROID_STL_TYPE=llvm-libc++_static ` also didn't work for me, but now I get a new issue with the linker flags. 

`$ cmake C:/repos/draco -DCMAKE_TOOLCHAIN_FILE=c:/repos/draco/cmake/toolchains/armv7-android-ndk-libcpp.cmake
-- The C compiler identification is Clang 3.8.275480
-- The CXX compiler identification is Clang 3.8.275480
-- Check for working C compiler: C:/NVPACK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/NVPACK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/NVPACK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/repos/draco/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_a29a4.vcxproj /p:Configuration=Debug /p:Platform=Tegra-Android /p:VisualStudioVersion=15.0 /v:m
    Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

      testCCompiler.c
    clang++.exe : error : invalid linker name in argument '-fuse-ld=bfd' [C:\repos\draco\CMakeFiles\CMakeTmp\cmTC_a29a4.vcxproj]




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:16 (project)


-- Configuring incomplete, errors occurred!
See also "C:/repos/draco/CMakeFiles/CMakeOutput.log".
See also "C:/repos/draco/CMakeFiles/CMakeError.log".
`

Any ideas on how I can get past this @tomfinegan ?

**Comment by kizjig** [comment]
So with a little bit more digging and research I've managed to get past this problem by specifying the linker flags in the toolchain file,

I modified the armv7-android-ndk-libcpp.cmake file again to also contain `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fuse-ld=bfd.exe")`

**Comment by tomfinegan** [comment]
> With Draco 1.3.4, NDK r12b, and Visual Studio 2017, I met the same issue too and "-DCMAKE_ANDROID_STL_TYPE=llvm-libc++_static" doesn't work. I have to modify the toolchain cmake files. Thank you for sharing the solution.

This is a bug. #533 fixes misbehavior of set_variable_if_unset().

> clang++.exe : error : invalid linker name in argument '-fuse-ld=bfd'

I can't reproduce this problem using the same version of the NDK in your log (r14b), or with newer NDKs. I'm not certain why CMake is using the wrong LD flag-- is it possible something is coming from your environment that is influencing CMake?

Anyway, the workaround you've used is reasonable, but I do not believe it needs to be in the toolchain file. Specifying `-DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=bfd.exe` in the CMake command line should be enough.
