### ISSUE TITLE
gltf encode with c++

### ISSUE THREAD

**Issue by ymb27** [google/draco#476]
is here some sample about gltf encode with c++? I complie the project, it can work with .obj, but it can't encode the gltf directly. I want some sample about gltf encode with c++.

**Comment by ondys** [comment]
Draco currently does not have encoder for GLTF files. One way to make draco encoded gltf files would be to convert your input model to a gltf (without Draco) and then run the file through a gltf pipeline (https://github.com/AnalyticalGraphicsInc/gltf-pipeline)
