### ISSUE TITLE
`ReleaseUnityMesh` not found

### ISSUE THREAD

**Issue by Tostifrosti** [google/draco#477]
I'm trying to include the Draco Importer for Unity but i keep getting this error that the `ReleaseUnityMesh` method can not be found. I've followed every step on the readme page. It feels like that the `dracodec_unity.dll` doesn't contain the code for `ReleaseUnityMesh`. I've tried to build the source of draco and use that DLL in Unity, but that has unfortunately no effect.

Unity: 2018.2.13f1
Platform: Window 10
Building for Android/iOS

Error in Unity: `Assets\Draco\DracoMeshLoader.cs(282,3): error CS0103: The name 'ReleaseUnityMesh' does not exist in the current context`

**Comment by NumaNumaNuma** [comment]
Same here on Mac OS, is that method missing from the compiled plugin?

**Comment by NumaNumaNuma** [comment]
Found the problem, the script was missing a declaration. just add this after line 48 in DracoMeshLoader.cs:
`[DllImport("dracodec_unity")]
    private static extern int ReleaseUnityMesh(DracoToUnityMesh** tmpMesh);`

Also in DracoDecodingObject.cs, it automatically loads "bunny" but it should be "bunny.drc", as the test file is called bunny.drc.bytes and unity trims the last extension only, not both of them.

Also the Readme file says to just drop a game obejct with the script on it as a test, the obejct needs a mesh filter and a mesh renderer with a material assigned to it.

**Comment by Stephengower** [comment]
I just experienced this same issue.  It looks like nearly a year has passed.  Seems like quite a long time for a problem preventing compiling to remain.  ??

**Comment by FrankGalligan** [comment]
Sorry this will be fixed in the next release.
