### ISSUE TITLE
Positional Quantization parameter in draco_encoder Utility takes values >31 bit and gives strange results. 

### ISSUE THREAD

**Issue by aurelw** [google/draco#48]
I use the draco_encoder utility to encode a mesh and change the positional quantization parameter.

`./draco_encoder   -qp 10 -i ~/my_file.ply -o test.draco && du -hs test.draco`

If I increase the value, the file size increases constantly, which works as expected. However, with 32 bit I get a small file, with 33 an even smaller one and with 34 a slightly larger and so on.

**Comment by ondys** [comment]
Thanks for the report. The maximum allowed value for quantization is currently 31 bits. The behavior for larger values is undefined. We are going to add error reporting to the encoder app when the input parameters are out of supported range.

**Comment by ondys** [comment]
Fixed in the master branch
