### ISSUE TITLE
Triangles sharing only one vertex with others get disconnected after encoding

### ISSUE THREAD

**Issue by EvgenyRodygin** [google/draco#481]
Meshes which have triangles sharing only one vertex with others get those triangles completely disconnected from the rest of the mesh. I.e. they have their own unique vertex set.

I've attached a very simple **example**. Please note that the sufficient number of vertices to describe this mesh is **11** (which it is in "ply"). But it gets **12** after converting **with draco**. For my use case, this is quite crucial. Tested with draco versions **1.2.5**, **1.3.1-1.3.5**.

[example](https://github.com/google/draco/files/2518599/test.zip)

**Comment by ondys** [comment]
related to https://github.com/google/draco/issues/503

By default, draco splits all non-manifold vertices/edges (when a two surfaces meet in one vertex, the vertex is non-manifold). The only solution for this would be to explicitly set encoding method to `MESH_SEQUENTIAL_ENCODING` (c++ api only)
