### ISSUE TITLE
Duplicate object name will be ignored

### ISSUE THREAD

**Issue by YouYue123** [google/draco#482]
Hi,

I have an obj file as below with duplicated object name, so far I found draco will just merge the object with same name into same one. It actually changed the original OBJ model structure. Is this an expected behaviour by design?

> o name1
> v ....
> v ....
> f ....
> o name 2
> v ...
> v ...
> f ...
> f ...
> o name 1
> v ...
> v ...
> f ...
> f ...

**Comment by YouYue123** [comment]
The relavant  code piece as below in obj_decoder.cc

```c++
auto it = obj_name_to_id_.find(obj_name);

 if (it == obj_name_to_id_.end()) {
    const int num_obj = static_cast<int>(obj_name_to_id_.size());
    obj_name_to_id_[obj_name] = num_obj;
    last_sub_obj_id_ = num_obj;
  } else {
    last_sub_obj_id_ = it->second;
  }
```

**Comment by ondys** [comment]
yes it is by design. it can be changed if a different behavior is different from the spec (or expectation of the majority of developers)
