### ISSUE TITLE
can point cloud encoder do not remove duplicate points?

### ISSUE THREAD

**Issue by Leehomwang** [google/draco#483]
I have a obj file `1.obj` with 5 points:
```
v 0 0 0
v 0 1 0
v 0 0 1
v 0 1 1
v 0 0 0
```
where the first point and the last point is the same one.
then I encode it with `draco_encoder.exe -i 1.obj -o 1.drc`.
and then I decode 1.drc with Javascript Decoder API THREE.DRACOLoader, I only get 4 points. 
how can I get the original 5 points?

My operating system is windows 10 x64.

**Comment by ondys** [comment]
Our obj loader by default deduplicate all points
     - this can be turned off by calling `obj_decoder.set_deduplicate_input_values(false)` (C++ api only)
There is no way to do this directly from the draco_encoder.exe app though.
