### ISSUE TITLE
use draco in androidstudio

### ISSUE THREAD

**Issue by Amoryan** [google/draco#484]
**CMakeLists**
cmake_minimum_required(VERSION 3.4.1)

add_subdirectory(../draco
                 ${CMAKE_BINARY_DIR}/draco_build)
include_directories("${CMAKE_BINARY_DIR}" ../draco)

add_library( 
             native-lib

             SHARED

             src/main/cpp/native-lib.cpp)

find_library(
              log-lib

              log )

target_link_libraries( # Specifies the target library.
                       native-lib

                       draco

                       ${log-lib} )

compile success!

my native-lib.cpp 

#include <jni.h>
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <src/draco/compression/decode.h>
#include <src/draco/core/decoder_buffer.h>
#include <src/draco/mesh/mesh.h>
#include <src/draco/point_cloud/point_cloud.h>
#include <src/draco/compression/config/compression_shared.h>

extern "C" JNIEXPORT void JNICALL
Java_com_threed_jpark_homemodel_viewmodel_Product3DDetailVM_decodeDrc(JNIEnv *jniEnv, jobject,
                                                                      jstring fileName) {
    const char *cs = jniEnv->GetStringUTFChars(fileName, 0);

    std::ifstream input_file(cs, std::ios::binary);

    // not found
    if (!input_file) {
        return;
    }

    // Read the file stream into a buffer.
    std::streampos file_size = 0;
    input_file.seekg(0, std::ios::end);
    file_size = input_file.tellg() - file_size;
    input_file.seekg(0, std::ios::beg);
    std::vector<char> data(file_size);
    input_file.read(data.data(), file_size);

    // file is empty
    if (data.empty()) {
        return;
    }

    draco::DecoderBuffer buffer;
    buffer.Init(data.data(), data.size());

    // Decode the input data into a geometry.
    std::unique_ptr<draco::PointCloud> pc;
    draco::Mesh *mesh = nullptr;
    auto type_statusor = draco::Decoder::GetEncodedGeometryType(&buffer);
    if (!type_statusor.ok()) {
        return;
    }

    const draco::EncodedGeometryType geom_type = type_statusor.value();
    if (geom_type == draco::TRIANGULAR_MESH) {

        draco::Decoder decoder;
        auto statusor = decoder.DecodeMeshFromBuffer(&buffer);
        if (!statusor.ok()) {
            return;
        }

        std::unique_ptr<draco::Mesh> in_mesh = std::move(statusor).value();

        if (in_mesh) {
            mesh = in_mesh.get();
            pc = std::move(in_mesh);
        }
    } else if (geom_type == draco::POINT_CLOUD) {
        // Failed to decode it as mesh, so let's try to decode it as a point cloud.
        draco::Decoder decoder;
        auto statusor = decoder.DecodePointCloudFromBuffer(&buffer);
        if (!statusor.ok()) {
            return;
        }
        pc = std::move(statusor).value();

    }

    if (pc == nullptr) {
        std::cout << "decode failed !" << std::endl;
    } else {
        std::cout << "decode success !" << std::endl;
    }
}

run failed !

i don't know how to fix it 

Build command failed.
Error while executing process E:\yanfangxiong\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build E:\yanfangxiong\jpark-android\app\.externalNativeBuild\cmake\debug\arm64-v8a --target native-lib}
[1/2] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o
FAILED: E:\yanfangxiong\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=aarch64-none-linux-android21 --gcc-toolchain=E:/yanfangxiong/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 --sysroot=E:/yanfangxiong/sdk/ndk-bundle/sysroot  -Dnative_lib_EXPORTS -I. -I../../../../../draco -isystem E:/yanfangxiong/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem E:/yanfangxiong/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem E:/yanfangxiong/sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++11 -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -MF CMakeFiles\native-lib.dir\src\main\cpp\native-lib.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -c E:\yanfangxiong\jpark-android\app\src\main\cpp\native-lib.cpp
In file included from E:\yanfangxiong\jpark-android\app\src\main\cpp\native-lib.cpp:6:
../../../../../draco\src/draco/compression/decode.h:20:10: fatal error: 'draco/compression/config/compression_shared.h' file not found
#include "draco/compression/config/compression_shared.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

**Comment by FrankGalligan** [comment]
Please see this section in BUILDING.md:
https://github.com/google/draco/blob/master/BUILDING.md#draco---static-library
