### ISSUE TITLE
Error when encoding triangulated line object

### ISSUE THREAD

**Issue by mingweiLIU** [google/draco#485]
Hi, I hava a obj model in which contains a line, the line is triangulated, while there is an error when I encode the model with the draco_encoder.exe, the infomation is "Out of range" as shown in the image below:
![2](https://user-images.githubusercontent.com/11702952/49523166-2910d100-f8e4-11e8-9138-f99fff5c1302.png)
The platform I tested is windows10, vs2015 x64; and the attached file is the tested model.
[DPobj.zip](https://github.com/google/draco/files/2649407/DPobj.zip)

**Comment by ondys** [comment]
The main issue is that all triangles are degenerate which the encoder does not currently handle properly.

One way to fix this would be to set encoding method to use sequential encoding that would work with degenerate triangles (`SetEncodingMethod(MESH_SEQUENTIAL_ENCODING)`) .. this is currently possible only via the C++ api though.

**Comment by mingweiLIU** [comment]
Thanks a lot.
