### ISSUE TITLE
Smaller JavaScript decoder

### ISSUE THREAD

**Issue by ikerr** [google/draco#49]
The Draco encoder / decoder performs really well in my tests (compared to Open3DGC), both from a compression ratio standpoint and from a speed standpoint; however, the current encoder is nearly 900 KB in size and gzips to about 150 KB, which is likely too large to deliver with our web app.

It would be useful to have a more streamlined (size-wise) version of the JavaScript decoder, perhaps one that is not built with Emscripten. Are there any plans for this?

**Comment by ondys** [comment]
We actually did write a javascript decoder manually some time ago, but it is now rather outdated and not compatible with the current bitstream. If there is a strong demand we may look into that again.

Saying that, what we plan to do in the near future is to add an option to add/remove features that are included in the decoder. For example if you know that your input files are only meshes, you will be able to exclude all functionality specific to point clouding, which would reduce the decoder size quite a bit. We actually already have a limited support for this in the Empscripten makefile (look for `DRACO_CONFIG_DEFINES`), but on a very few features can be disabled at this time.

**Comment by openforus** [comment]
when I run "make -f Makefile.emcc" in os x EI Capitan to compile generated draco_decoder.js code 
get  the following compile errors:

In file included from javascript/emscripten/draco_glue_wrapper.cc:26:
./glue.cpp:148:14: error: cannot initialize a parameter of type 'const char *'
      with an lvalue of type 'char'
  self->Init(arg0, arg1);
             ^~~~
./core/decoder_buffer.h:38:25: note: passing argument to parameter 'data' here
  void Init(const char *data, size_t data_size);
                        ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
make: *** [obj/javascript/emscripten/draco_glue_wrapper.o] Error 1

So how to resolve this problem？

**Comment by hccampos** [comment]
Being able to remove unnecessary features is indeed a great idea, so I would like so second that.

**Comment by ondys** [comment]
@openforus Thanks for the report. I was able to repro the problem. As far as I can tell this is a MacOS specific issue. We will post an update when we have a fix.  Also, in future, please consider opening a new issue when reporting problems. It makes things easier to track.

**Comment by ondys** [comment]
We did our first pass on the javascript decoder size, which included separating mesh and point cloud decoders into two .js files + turning on extra flags that reduced the javascript size without hurting the performance (the performance should be actually slightly better now).

From the previous draco_decoder.js (878 KB) we are now down to 585 KB for draco_mesh_decoder.js  .. so about 33% reduction. Still far from perfect, but getting better.

Note that we now include 3 different javascripts:
draco_decoder.js  - still contains both mesh and point cloud decoders
draco_mesh_decoder.js - only mesh decoding
draco_point_cloud_decoder.js - only point cloud decoding

We will still keep working on this so I'm going to keep the issue open

**Comment by marklundin** [comment]
Would a WebAssembly Decoder make sense in this instance?

**Comment by ondys** [comment]
@marklundin Yes, WebAssembly is going to make the decoder smaller as well.
