### ISSUE TITLE
Non-standard "build" directory installed in top-level CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by hobu** [google/draco#490]
A typical installation unexpectedly creates a "build" directory that gets installed in CMAKE_INSTALL_PREFIX that has a `draco_version.h` and a `draco_test_config.h` file in it on both windows and OSX builds with current master. Is this an expected behavior? I was working to make a Draco package for [conda-forge](https://github.com/conda-forge/staged-recipes/pull/7286), but this particular behavior is a stumbling block. Can this build directory be controlled? Is there a reason such information is not simply in the include path?

![screen shot 2018-12-14 at 4 18 48 pm](https://user-images.githubusercontent.com/87751/50032899-f76ec880-ffbb-11e8-90b4-960a9e963b60.png)

**Comment by tomfinegan** [comment]
Fixed in upcoming release.
