### ISSUE TITLE
How can i use this lib to code Point-Cloud stream in real-time

### ISSUE THREAD

**Issue by cucrui** [google/draco#497]
just as title

**Comment by ondys** [comment]
can you elaborate more about your use case?

**Comment by cucrui** [comment]
> can you elaborate more about your use case?

Im using IntelRealsense Depth camera to obtain PointCloud stream, and i want to transmit stream from one pc to another by wifi,before transimission, i need to compress stream to bit stream. so i wanna know whether this lib work out for compression. thx dude

**Comment by ondys** [comment]
it really depends on the amount of points per second, your machine specs and structure of your point cloud data. Draco is not doing any temporal compression so every frame would have to be compressed independently. In general, encoding speed may be an issue unless you use compression level 0 or explicitly specify the encoding method as `POINT_CLOUD_SEQUENTIAL_ENCODING`.

**Comment by Falken42** [comment]
@cucrui We recently had a project where we also streamed depth data from an Intel RealSense D415 over wifi, although we decided to compress the depth map itself (as an F32 image) using [zfp](https://github.com/LLNL/zfp), then reconstruct the point cloud data on the client from that.  This might be more feasible to do in realtime than attempting to compress/transmit/decompress the point cloud itself.

**Comment by cucrui** [comment]
> @cucrui We recently had a project where we also streamed depth data from an Intel RealSense D415 over wifi, although we decided to compress the depth map itself (as an F32 image) using [zfp](https://github.com/LLNL/zfp), then reconstruct the point cloud data on the client from that. This might be more feasible to do in realtime than attempting to compress/transmit/decompress the point cloud itself.
Thanks for your recommendation, I'll try this lib.Keep in touch.

**Comment by cucrui** [comment]
> @cucrui We recently had a project where we also streamed depth data from an Intel RealSense D415 over wifi, although we decided to compress the depth map itself (as an F32 image) using [zfp](https://github.com/LLNL/zfp), then reconstruct the point cloud data on the client from that. This might be more feasible to do in realtime than attempting to compress/transmit/decompress the point cloud itself.

hey dude, whats your project going on, recently I also try to compress depth and rgb information with zfp, but result make me disappointing, the compression ratio were 1.4, would you mind give me more details about how you use zfp on your project.
Really thanks for your reply!

**Comment by Falken42** [comment]
If you're not getting good results with zfp then you've probably set the [tolerance level](https://zfp.readthedocs.io/en/release0.5.4/modes.html) too high.

Also, zfp shouldn't be used for RGB data, only depth.  We used libjpeg-turbo for the RGB data.

**Comment by cucrui** [comment]
> If you're not getting good results with zfp then you've probably set the [tolerance level](https://zfp.readthedocs.io/en/release0.5.4/modes.html) too high.
> 
> Also, zfp shouldn't be used for RGB data, only depth. We used libjpeg-turbo for the RGB data.

Got it, but after I compressed depth data, what should I transmit for another end point to recieve for decompressing.
I guess `buffer(from simple.c)` should to be transmit , but in another end point I can't decompress from this recieved buffer. Would you mind give some suggestions.

**Comment by Falken42** [comment]
Are you writing the full ZFP header with `zfp_write_header()` before compressing?  The decompression side needs to know the exact field parameters to use (which are stored in the header) in order for it to work properly.

I'd suggest getting compression and decompression working locally first before attempting to handle transmission of the data.

**Comment by cucrui** [comment]
> Are you writing the full ZFP header with `zfp_write_header()` before compressing? The decompression side needs to know the exact field parameters to use (which are stored in the header) in order for it to work properly.
> 
> I'd suggest getting compression and decompression working locally first before attempting to handle transmission of the data.

That is to say if I writing the full ZFP header,  the compressed buffer contain all parameters that decompression side needs?

But when I use `zfp_read_header()`, this function's parameters is `zfp_stream* stream, zfp_field* field, unit mask`.With the only bytes stream `buffer`, It seems that I can't get parameters such as dimension, data type etc before I use zfp_read_header() to get full header information.That makes me so confused.

**Comment by Falken42** [comment]
Call `stream_open()` on your buffer first, then use `zfp_stream_set_bit_stream()` to assign the bit stream to a zfp object.  After that, you can allocate an empty field with `zfp_field_alloc()` and call `zfp_read_header()` which will read and populate the field with the decompression parameters.

Look at [this example](https://github.com/LLNL/zfp/blob/master/examples/simple.c) for some code.  If you're still stuck, you should probably open an issue over there rather than here at draco.

**Comment by cucrui** [comment]
> Call `stream_open()` on your buffer first, then use `zfp_stream_set_bit_stream()` to assign the bit stream to a zfp object. After that, you can allocate an empty field with `zfp_field_alloc()` and call `zfp_read_header()` which will read and populate the field with the decompression parameters.
> 
> Look at [this example](https://github.com/LLNL/zfp/blob/master/examples/simple.c) for some code. If you're still stuck, you should probably open an issue over there rather than here at draco.

I'll try. Really thanks for your reply, you are so kind to patiently answer my question.
Best wishes!

**Comment by cucrui** [comment]
> Call `stream_open()` on your buffer first, then use `zfp_stream_set_bit_stream()` to assign the bit stream to a zfp object. After that, you can allocate an empty field with `zfp_field_alloc()` and call `zfp_read_header()` which will read and populate the field with the decompression parameters.
> 
> Look at [this example](https://github.com/LLNL/zfp/blob/master/examples/simple.c) for some code. If you're still stuck, you should probably open an issue over there rather than here at draco.

Sorry to bother you, Now I'm trying to compress RGB data using libjpeg-turbo.But my point cloud data is too large, about 1000000 points, so if I use jpeg, width and Height are also too large.
with below code, I get  wrong result.
```cpp
tjhandle _jpegCompressor = tjInitCompress();

    tjCompress2(_jpegCompressor, (unsigned char *)image, ImgWidth, 0, ImgHeight, TJPF_RGB,
                (unsigned char **)buffer, _jpegSize, TJSAMP_444, JPEG_QUALITY,
                TJFLAG_FASTDCT);

    int width, height, jpegSubsamp;
    tjhandle _jpegDecompressor = tjInitDecompress();
    tjDecompressHeader2(_jpegDecompressor, (unsigned char *)buffer,*_jpegSize, &width, &height, &jpegSubsamp);
    cout << "debug : " << width << " " << height << endl;

    tjDestroy(_jpegCompressor);
``` 
the original width = height = 529905, but after decompress header, width and heigth become another value.How can I fix it.

**Comment by whatisor** [comment]
I think from his comment, this is not suitable for online stream:
"Draco is not doing any temporal compression"
