### ISSUE TITLE
Error enum in status.h collides with error define on Windows in wingdi.h

### ISSUE THREAD

**Issue by SaschaWillems** [google/draco#499]
The ```status.h``` includes an enum that defines a value for ```errror``´:

![image](https://user-images.githubusercontent.com/10283127/51799242-8a3b8d80-221f-11e9-82f3-b7f0e7ad33fa.png)

If you're using Draco in a Windows application that creates a window, this may collide with an error define in ```wingdi.h```.

While this is a minor problem that can be handled at application level, by manually checking and undefining this error constant, if not required, it would be nice if this could be fixed in ```status.h``` instead, e.g. by renaming.

**Comment by FrankGalligan** [comment]
This was changed to DRACO_ERROR.
