### ISSUE TITLE
simple application crashes compiled with vs2015 x64, but with x86 is ok

### ISSUE THREAD

**Issue by abushinov** [google/draco#50]
hi, i try to create draco point cloud programmatically, and write to file.

the problem is, then i compile an app in x64 mode, both release and debug builds, are crashes, but in x86 it work's fine in release and debug builds. you can try precompiled app in the file below in "bin" folder.
https://dl.dropbox.com/s/ov3rpburwc972sd/TestDraco.zip?dl=0

My specs: Windows 7 x64, Visual Studio 2015 SP3

**Comment by ondys** [comment]
Try changing following line in your main.cpp:
```
out_point_cloud_->AddAttribute(va, false, num_vert);
```
to:
```
out_point_cloud_->AddAttribute(va, true, num_vert);
```

The second parameter determines whether the attribute uses identity mapping for map between point indices and attribute value indices. If it is set to `false`, an explicit mapping is used and you would have to set it using the following function:
```
out_point_cloud_->attribute(att_id_)->SetPointMapEntry(..., ...);
```

**Comment by abushinov** [comment]
cool, works great. thank you!
