### ISSUE TITLE
Unity Plugin builds are in debug mode

### ISSUE THREAD

**Issue by Tostifrosti** [google/draco#502]
The draco plugins for unity (Android) in the latest version (1.3.5) are in build in debug mode. The plugins in this repo are around ~25.3 MB for ARMv7 and ~28.4 MB for ARM64 which is quite a lot. After building the project for myself using the release command, the plugins became much smaller and run much smoother: ~5.5 MB for ARMv7 and 7.8 MB for ARM64.

So far, I was only able to test for Android, so I'm not sure about the plugin for other platforms. 
Please replace the current plugin files with release mode files.

**Comment by FrankGalligan** [comment]
Fixed in next release
