### ISSUE TITLE
Compression level >6 yields larger file

### ISSUE THREAD

**Issue by UX3D-schmithuesen** [google/draco#504]
When testing the command line encoder with a very simple example object, I noticed that any compression level above 6 yields in file sizes **larger** than 6. 
[monkey.zip](https://github.com/google/draco/files/2884523/monkey.zip)

**NOTE**: When inspecting all the possible levels, I also noted a huge gap between 4 and 5. So as far as compression goes, 5 and 6 are the best options by far while any number lower **or higher** has larger results.

**Comment by ondys** [comment]
Thank you for reporting this. This is a known issue. The compression levels are defined by a (mostly hard-coded) set of compression features that should usually result in better compression / slower speed as the compression level increases. That being said, there are models where the features enabled for lower compression levels result in better compression compared to higher compression levels. We periodically re-evaluate what features to use for different compression levels and hopefully we will get to more predictable compression performance in future.
