### ISSUE TITLE
Fastest way to get decoded mesh into JavaScript Float32Array/Uint32Array?

### ISSUE THREAD

**Issue by manuel-castro** [google/draco#505]
First of all, just wanted to say, draco is a great achievement. I have MB level meshes and am seeing compression levels of 5-6x better than gzipped ply.

I am trying to optimize the time from having downloaded the compressed mesh to populating a JS Float32Array with vertex coordinates and a Uint32Array with vertex indices (for faces). The way I am doing it right now, I basically copied from the examples in the repo. After decoding the mesh, I am retrieving the vertex indices by looping and using GetFaceFromMesh: 

```
const indices = new Uint32Array(numFaces * 3);
const ia = new decoderModule.DracoInt32Array();
for (let i = 0; i < numFaces; ++i) {
    decoder.GetFaceFromMesh(mesh, i, ia);
    const index = i * 3;
    indices[index] = ia.GetValue(0);
    indices[index + 1] = ia.GetValue(1);
    indices[index + 2] = ia.GetValue(2);
}
```

Then for retrieving the vertex coordinates, it's similar:

```
const numValues = numPoints * 3;
const decoderAttr = decoderModule.POSITION;
const attrId = decoder.GetAttributeId(mesh, decoderModule.POSITION);
const attribute = decoder.GetAttribute(mesh, attrId);
const attributeData = new decoderModule.DracoFloat32Array();
decoder.GetAttributeFloatForAllPoints(mesh, attribute, attributeData);
const attributeDataArray = new Float32Array(numValues);
for (let i = 0; i < numValues; ++i) {
  attributeDataArray[i] = attributeData.GetValue(i);
}
```

For a 1.5MB draco mesh with 1.1 million faces and 580k vertices, getting the faces takes ~100ms, and getting the vertices takes ~50ms. Maybe there is no other possible way of doing the above at the moment, but if there is a faster way to copy the DracoFloat32Array data and DracoInt32Array data into JS, that would be helpful.

I also want to make the decompression as fast as possible. I am already using the WebAssembly decoder and compression level = 1 (at this level, it's already very effective for my meshes). For this 1.5MB draco mesh, decoding takes ~270ms. I am using the pre-built wasm decoder in the repo, but if there are CMake settings for building the wasm decoder that would make it faster, then I would switch to building it. I see the note in the README about the JavaScript decoder using dynamic memory, and the speed-up when using static instead, is that relevant for the wasm decoder as well?

I'd much appreciate any help anyone is willing to give.

**Comment by ondys** [comment]
It is unfortunately necessary to copy the data from the emscriten memory pool to Javascript. It may be possible to do that more efficiently than shown on the examples but it would probably require to update the WebIDL bindings to provide a more direct access to the underlying emscripten memory that would then allow to wrap it in Javascript Array objects that can be copied more efficiently. We currently don't have plans to add this feature, but any community contributions are always welcome.

As for the decoding performance. I believe, the build was tuned toward performance so I wouldn't expect any significant gains by tweaking the CMake settings. One thing to consider is that the decoding usually takes significantly longer the first time the Draco decoding module is initialized. If you can reuse the same decoder across multiple meshes/point_clouds, the performance should get better over time.

**Comment by manuel-castro** [comment]
I see. Thank you! Your tip about reusing the same decoder will be helpful.

**Comment by eile** [comment]
#530 implements some of this.
