### ISSUE TITLE
How can I use lossless compression?

### ISSUE THREAD

**Issue by simon2077** [google/draco#514]
Hi,I want to use lossless compression in my project, but I don't know how to do it. If I use parameters -qp 0 -cl 0, will draco do lossless compression  on an obj file ? If not ,then how can I use lossless compression? Thank you very much .

**Comment by ondys** [comment]
Yes, Draco should be truly lossless in terms of data for -qp 0 and -cl 0 . That is, points and faces should be exactly the same before and after compression. But note that this does not mean that the .obj file will be exactly similar. Draco for example deduplicates values when loading .obj files which may change some things.

**Comment by bigeyesung** [comment]
Hey, just wanted to follow up this question, does Draco supports lossless compression? 
I build the latest and draco-1.3.5 version and the output file size is not as same as the input's. The command are shown as below,
./draco_encoder -qp 0 -cl 0 -i bun_zipper.ply -o Encode.drc 
./draco_decoder -i Encode.drc -o bun_zipper_Draco.ply

**Comment by ChaturvediShilpa** [comment]
Hi, 

I faced similar issue. I encoded the sample file named  present under test data folder using command line and then tried decoding it back using command line.  I expected that I will regain the original file but the decoded file is not readable. Please help

**Comment by FrankGalligan** [comment]
So in general Some file -> encode -> decode -> file, will usually have minor differences. In this case:
./draco_encoder -i bun_zipper.ply -o Encode.drc -qp 0 -cl 0
./draco_decoder -i Encode.drc -o bun_zipper_Draco.ply

bun_zipper.ply is an ascii PLY file and bun_zipper_Draco.ply is a binary PLY file. So bun_zipper.ply will be much bigger than bun_zipper_Draco.ply.

Both files render fine for me.
