### ISSUE TITLE
Can I use other people draco_encoder.exe ?

### ISSUE THREAD

**Issue by steveyang331** [google/draco#516]
I don't think cmake file on my compute .

Can I use draco_encoder.exe from other people ? 

Or it have to cmake on every specific compute , can't use other compute of draco_encoder.exe file ?

**Comment by jiangmingwen** [comment]
Yes, I have tested others using my computer to compile drac.exe is completely normal

**Comment by kangland** [comment]
> Yes, I have tested others using my computer to compile drac.exe is completely normal

Thanks reply. I got it and it works.

**Comment by ua4192** [comment]
Hi

Could anybody send me the draco_encoder.exe to my mail?

alejandro.insua@gmail.com

I am not familiar with cmake.

Best regards

**Comment by tomfinegan** [comment]
Basic user instructions for CMake are here:
https://cmake.org/cmake/help/latest/guide/user-interaction/index.html

The Draco build instructions are here:
https://github.com/google/draco/blob/master/BUILDING.md

Running untrusted binary executables from strangers on the internet is a _BAD_ idea. I strongly recommend taking some time to familiarize yourself with the above before doing something that could compromise your system.
