### ISSUE TITLE
About the memory footprint during the decompression process

### ISSUE THREAD

**Issue by verybigzhouhai** [google/draco#517]
Hi,
     I have a problem, I use draco_decoder.js to extract an 11M glb(gltf) file. 
     In the chrome browser, a total of more than 900M of memory will be applied. The file includes 4.1 million triangle faces and 3 million vertices. The data after decompression takes up only 150M. 
     Why is there so much memory used in the decompression process, is this necessary?
thanks.

**Comment by FrankGalligan** [comment]
So I'm sure the amount of memory used by the decoder could be cut down. How much is the question. Also when cutting down memory you have to be careful as performance as well. As for where the specific memory is being used, someone would have to go through and see what allocations are using what memory.
