### ISSUE TITLE
Compilation warning (implicit conversion loses integer precision) in options.h

### ISSUE THREAD

**Issue by amaes** [google/draco#518]
Hello!

This is very extremely minor, but compiling this code for iOS (arm64) with Xcode's default build settings generate a warning here: 
https://github.com/google/draco/blob/master/src/draco/core/options.h#L122
`const int val = std::strtol(act_str, &next_str, 10);`

```
../draco/src/draco/core/options.h:117:23: warning: implicit conversion loses integer precision: 'long' to 'const int' [-Wshorten-64-to-32]
      const int val = std::strtol(act_str, &next_str, 10);
```

**Comment by FrankGalligan** [comment]
This should be fixed in the next release.
