### ISSUE TITLE
Npm draco3d package usage as command line tool

### ISSUE THREAD

**Issue by khelkun** [google/draco#519]
I wish I could use draco3d npm package to simply encode an .obj or .ply file to a .drc file, and decode a .drc file to to .obj or .ply file

In other words I wish to use the npm package as the [command line tool](https://github.com/google/draco#command-line-applications). I could call the command line tool from my NodeJS service (e.g without using the draco3d npm package at all) but since the service is in an alpine linux docker container, that would suppose to build the command line tool in my docker container, so it would be easier if I could use the draco3d npm package.

Is this possible at present?

**Comment by FrankGalligan** [comment]
This is currently not possible. Someone could add build rules to [CMakeLists.txt](https://github.com/google/draco/blob/master/CMakeLists.txt) to build draco_encoder and draco_decoder command line apps to emscripten.
