### ISSUE TITLE
obj_decoder: Possible to maintain/export 'usemtl' definitions or group names?

### ISSUE THREAD

**Issue by johnwquarles** [google/draco#52]
Quick question about the OBJ decoder:

Is it possible to maintain `usemtl` definitions within the draco-encoded file (specifically for eventual use in `THREE.js`)?

Similarly, is this possible with polygon groups?

From what I can gather neither is currently supported. Any plans to do so in the future?

Thank you for Draco!

**Comment by ondys** [comment]
We currently don't preserve `usemtl` on export for obj files. The mesh faces are actually encoded with proper material ids, but at this time Draco can't store any extra info about the material name and we therefore can't preserve the materials on .obj export.  We plan to add support for mesh and attribute metadata that would allow us to preserve information such as this. I can't tell when it is going to be released though.

A side note, if you load the model directly into three.js (i.e., without converting it back to .obj .. for example as shown in our [here](https://github.com/google/draco/blob/master/javascript/example/DRACOLoader.js)), you should still be able to get the material id for a given face that can be used to query materials in the appropriate .mtl file.

**Comment by johnwquarles** [comment]
Hi ondys, thanks so much for your reply.

I gather we're talking about (in `THREE.js`) each face's `materialIndex`?

I don't know of any way to specify a material for a given group or face within an OBJ file other than `usemtl` statements. Is there another way to specify the material id within an OBJ, or is this supposed to be parsed from `usemtl` statements when converting to `drc`?

When I convert my resultant THREE.js `bufferGeometry` into a `geometry` and iterate over all of its faces, I get a `materialIndex` of 0 for all of them, in any event.

**Comment by ondys** [comment]
1. For obj's you can first specify the material library `mtllib file_name.mtl` that can contain more than one material that can be assigned to faces using the `usemtl` function. What Draco stores, is the index of the material in the parent .mtl file. Draco currently doesn't support .OBJs with more then one material libraries (i.e., all the materials need to be stored in one .mtl file). 

2. For the THREE.js , I think the material would go to `materialIndex` but we currently don't fill it in our Draco->THREE.js example, but it is possible to add it. I'll add an internal issue tracker to add support for it, but pull requests are also welcomed.

**Comment by kyewong** [comment]
I tried to process obj/ply models with an external image file as its texture, while failed to restore the texture of the decoded draco file. This will limit the use of draco in many applications, since only models with simple colors can be compressed/decompressed. Will draco support complex materials in the next update?

**Comment by kappa-gooner** [comment]
@ondys: 
I followed the code used in subObjects, set the filter to look for `custom_id() === 0` and got the point to material map.

Do I have to read the `mtl` file myself to get hold of the material information? What's the relationship between the material name and the material ID that's decoded from Draco?

**Comment by ondys** [comment]
@kappa-gooner Yes, you will have to read/parse the material file yourself. Material ids stored in the generic attribute correspond to the position of the material in the .mtl file (e.g., first material in the .mtl file has id 0, second 1, and so on).

**Comment by customlogic** [comment]
How would one access the material index from the Javascript decoder? Is it something DRACOLoader should be able to access, or does the draco_decoder.js first need to be altered to expose this data?

**Comment by usmanshah** [comment]
@ondys 
>  The mesh faces are actually encoded with proper material ids

Do you know how to encode these material ids when using the MeshBuilder to build a Draco Mesh in Javascript ? I have already asked a question [here](https://github.com/google/draco/issues/242)

**Comment by FrankGalligan** [comment]
@syed-usman You can see how Draco does it in our obj parser here:
https://github.com/google/draco/blob/master/src/draco/io/obj_decoder.cc#L187
