### ISSUE TITLE
Type mismatch in AddKeyframes

### ISSUE THREAD

**Issue by MotivaCG** [google/draco#520]
Notice that the header uses:
`int32_t AddKeyframes(DataType data_type, uint32_t num_components,  const std::vector<T> data);``

but it calls to
`temp_att->Init(GeometryAttribute::GENERIC, nullptr, num_components, data_type, false, DataTypeLength(data_type), 0);`

Where num_components is casted to int8_t

So the size of the buffer is cropped if it is bigger than 255.

How should I deal with vertex animation? creating one animation per vertex? notice that I can only animate 255/3 vertex in a single animation, it looks pretty in efficient.

**Comment by FrankGalligan** [comment]
No the num_components is the number of elements in the glTF type. Scalar is 1 Vec2 is 2, vec 3 is 3,  vec4 is 4, up to matrix which is 16. 

The size of the vector in data determines how many animations you have. So lets say you have 1000 animations with made up each of 3 values. Your function would look like this:
num_components = 3;
std::vector<X> data = {your 1000 animations};
//data.size() should equal 1000 * num_components * sizeof(data_type). If your data_type is float then data.size() would equal = 1000 * 3 * 4 = 7000.

AddKeyframes({ data_type}, 3, data);
