### ISSUE TITLE
draco js loader can not get the material?

### ISSUE THREAD

**Issue by caxieyou** [google/draco#526]
When I use  the C++ version to compress the obj file to drc file or decompress the drc file back to obj file.
If I use  the --metadata flag then there will be materials showing in the obj file.

But when I use the drc file compressed with the --metadata flag. how can i get the material info back?

THX

**Comment by FrankGalligan** [comment]
The material info is encoded into the Draco mesh as metadata. You can how to get the materiel info back by looking at the code in obj_encoder. https://github.com/google/draco/blob/master/src/draco/io/obj_encoder.cc#L130
