### ISSUE TITLE
Missing decoding to gltf?

### ISSUE THREAD

**Issue by tprochazka** [google/draco#528]
I'm calling this:
./draco_decoder -i ROH.bin -o ROH.gltf

And it still write:
Invalid extension of the output file. Use either .ply, .obj, or .gltf
When I change .gltf to ply or obj it works correctly.

It looks that implementation for gltf is missing here
https://github.com/google/draco/blob/785c9c4aa2b952236c29ad639901dbbaf216da38/src/draco/tools/draco_decoder.cc#L171

**Comment by atteneder** [comment]
Ran into the same issue right now. It definitely is missing :D

**Comment by FrankGalligan** [comment]
That is an error as it does not support gltf files. We will fix that in the next release. 

Please see [gltf-pipeline](https://github.com/CesiumGS/gltf-pipeline) for a tool that supports Draco compressed glTF files.
