### ISSUE TITLE
the qp -0 can not been decompressed correct

### ISSUE THREAD

**Issue by caxieyou** [google/draco#529]
I am using the draco_encoder to compress the obj file, and use the default cl-7.

Also I added the qp -0 which means no quantinization, then it compressed successfully.

Then I use the drc file in the js part to decode, I got the error 

"Decoding failed: Failed to decode point attributes."

 Any Ideas?

Thx

**Comment by boucaud** [comment]
I'm having the same issue. Compressing this simple file with no quantization, and compression level >= 7 will lead to a decoder failure.

[bunny.obj.zip](https://github.com/google/draco/files/3621238/bunny.obj.zip)

**Comment by FrankGalligan** [comment]
I'm having trouble reproducing this. Can I get some more detailed steps thanks.

**Comment by boucaud** [comment]
I remember being able to find a workaround for this, but here was the issue (still present on master):

Encoding the attached bunny.obj model with these parameters:

`./draco_encoder -i ./bunny.obj -o out.drc -cl 10 -qp 0 `

Then trying to decode the output like this:

`./draco_decoder -i out.drc -o out.obj`

Results in the following error message:

> Decoding failed: Failed to decode point attributes.

This does work:

`./draco_encoder -i ./bunny.obj -o out.drc -cl 10 -qp 0 -qn 0`

**Comment by FrankGalligan** [comment]
Fixed in 1.4.0
