### ISSUE TITLE
draco_encoder: crash in draco::PointAttribute::DeduplicateFormattedValues<float, 2>(...)

### ISSUE THREAD

**Issue by alexeygroshev** [google/draco#53]
Hi,

Was running draco_encoder on different objects and on some of them faced a segfault with the same  stacktrace:

> #0  0x000000010041e287 in draco::PointAttribute::DeduplicateFormattedValues<float, 2> (
    this=0x60007d4b0, in_att=..., in_att_offset=...)
    at /home/User/Work/draco/point_cloud/point_attribute.cc:174
#1  0x0000000100417307 in draco::PointAttribute::DeduplicateTypedValues<float> (in_att_offset=...,
    in_att=..., this=<optimized out>) at /home/User/Work/draco/point_cloud/point_attribute.cc:98
#2  draco::PointAttribute::DeduplicateValues (this=<optimized out>, in_att=..., in_att_offset=...,
    in_att_offset@entry=...) at /home/User/Work/draco/point_cloud/point_attribute.cc:57
#3  0x000000010041737c in draco::PointAttribute::DeduplicateValues (this=<optimized out>, in_att=...)
    at /home/User/Work/draco/point_cloud/point_attribute.cc:48
#4  0x000000010040f136 in draco::PointCloud::DeduplicateAttributeValues (this=0x60007cb00)
    at /home/User/Work/draco/point_cloud/point_cloud.cc:175
#5  0x0000000100406ead in draco::ObjDecoder::DecodeInternal (this=this@entry=0xffffc580)
    at /home/User/Work/draco/io/obj_decoder.cc:162
#6  0x00000001004071b0 in draco::ObjDecoder::DecodeFromFile (this=this@entry=0xffffc580,
    file_name=..., out_point_cloud=0x60007cb00) at /home/User/Work/draco/io/obj_decoder.cc:66
#7  0x000000010040724c in draco::ObjDecoder::DecodeFromFile (this=this@entry=0xffffc580,
    file_name=..., out_mesh=<optimized out>) at /home/User/Work/draco/io/obj_decoder.cc:44
#8  0x00000001004054bc in draco::ReadMeshFromFile (file_name=...)
    at /home/User/Work/draco/io/mesh_io.cc:33
#9  0x00000001004943a7 in main (argc=7, argv=0xffffcbb0)
    at /home/User/Work/draco/tools/draco_encoder.cc:189

The crash is here, see line 174:
> (gdb) l
169         for (int i = 0; i < num_unique_entries_; ++i) {
170           SetPointMapEntry(PointIndex(i), value_map[AttributeValueIndex(i)]);
171         }
172       } else {
173         // Update point to value map using the mapping between old and new values.
174         for (PointIndex i(0); i < indices_map_.size(); ++i) {
175           SetPointMapEntry(i, value_map[indices_map_[i]]);
176         }
177       }
178       num_unique_entries_ = unique_vals.value();

Command line:
> draco_encoder.exe -cl 5 -i objname.obj -o objname.drc.

Thanks in advance for your help

**Comment by ondys** [comment]
Thanks for the report. Can you please attach an .obj that causes this crash?

**Comment by alexeygroshev** [comment]
Hi,

Here is the download link:
https://ufile.io/a5d381

**Comment by ondys** [comment]
The crash should be fixed in the master branch. The problem was that the obj file had texture coordinates defined only on a sub set of points, but in Draco, we currently require attributes to be used on all points. To solve this, the points with undefined texture coordinates are now using a dummy value. This can potentially hurt the compression a little bit, but at least the model can be processed.

**Comment by alexeygroshev** [comment]
It works now!
Thanks a lot
