### ISSUE TITLE
generate javascript code from c++ code

### ISSUE THREAD

**Issue by GumpXiaoli** [google/draco#534]
Hi Team,

In my project, i customize encoder and decoder in c++ code. Please help generate javascript code form my own modified c++ code.

Thanks!

**Comment by ram-sellamuthu** [comment]
I would like to have this feature too!

**Comment by FrankGalligan** [comment]
You should be able to change the c++ code and then run these [steps](https://github.com/google/draco#javascript-encoderdecoder) from README.md to create JavaScript and WASM encode and decode libraries.

If you are still having issues please reopen and post the specific issues.
