### ISSUE TITLE
PLY Decoder Can't Read Normals?

### ISSUE THREAD

**Issue by scashews** [google/draco#54]
It looks the the PLY decoder can't read normals? Just positions and colors? I get that custom properties aren't supported yet, but it seems like it should be able to at least read a built-in like normals.

**Comment by ondys** [comment]
Yes, our support for PLY files is currently rather limited at best. We are going to add support for other attributes over time. Normals should come soon, followed by texture coordinates and then generic attributes at later date (when we add support for custom metadata).

**Comment by ondys** [comment]
Support for normals has been added to the master branch.
