### ISSUE TITLE
Preserver sub meshes

### ISSUE THREAD

**Issue by lednhatkhanh** [google/draco#541]
I’m using draco to compress an `.obj` model and detect the sub-mesh name to apply different materials for them, draco only returns one big mesh, is there a way to accomplish this feature?
Thank you.

**Comment by n3c4** [comment]
Yes, you have to encode your model with `--metadata` flag (https://github.com/google/draco#metadata-api)

Also, I recommend to read these topics:
https://github.com/google/draco/issues/364
https://github.com/google/draco/issues/401

**Comment by lednhatkhanh** [comment]
@n3c4 I tried converting to `gltf` extension and then use `gltf-pipline` to compress it with `draco` and still get all the sub meshes, thank you for your help.
