### ISSUE TITLE
Support for pure data compression.

### ISSUE THREAD

**Issue by nxddsnc** [google/draco#546]
Hi,
We are trying to use draco to compress mesh, but we have our own 3d format. I have no idea of how Draco compresses data but is there any chance we can compress just the vertices/indices data instead of the entire 3d file?

**Comment by avzhatkin** [comment]
Draco can compress arbitrary collection of points with arbitrary point attributes (like position, color, some custom data) and point connectivity (aka indices).

**Comment by nxddsnc** [comment]
Thanks. I looked into the code and found the way.
