### ISSUE TITLE
Decoding problem in Android browsers

### ISSUE THREAD

**Issue by suopte** [google/draco#55]
I really appreciate the idea behind Draco, as it could greatly decrease the required bandwidth for downloading 3D models, which is especially important in case of mobile apps where bandwidth could be a tight bottleneck.
However testing the "three.js Renderer Example" on my Android 5.1 tablet I observed a strange issue with the decoding. I attached the screenshot showing the scrambled appearance of the 3D model. I checked it in both Firefox for Android (version 50.1.0) and Chrome for Android (55.0.2883.91), and found the same result. I also tried to visualize other three.js examples on this tablet to exclude the possibility of a three.js bug, however all other three.js models appeared well.

![screenshot_2017-02-05-18-00-13](https://cloud.githubusercontent.com/assets/1144015/22628350/c47738a8-ebd2-11e6-91cd-90e0c6868995.png)

Interestingly however on an older tablet with Android 4.4 but also with the latest version of Firefox and Chrome, there was no artifact at all, the above three.js example was visualized perfectly.
Could it be related to the Android version or the SoC? For me it does not seem to be a bug in Draco, however unfortunately it could undermine the usability of the library on mobile devices.

**Comment by ondys** [comment]
Thank you for the report. We will investigate the problem. I just tested it with Android 6.0.1 and latest version of Chrome and it worked as expected, but it is possible that there are some issues with other configurations.

**Comment by FrankGalligan** [comment]
Hello,

So I tried it on two devices with Android version 5.1.1 and Chrome version 55.0.2883.91 (Nexus 9 and 5). Both worked fine. We also tried it on android versions (4.4.4, 6.0.1, 7.0.0)  with the same Chrome version, and they all worked.

Maybe this is a bug specific to a device, like you mentioned. Could you pm me the device so we can check?

Thanks,
Frank

**Comment by suopte** [comment]
Hi,

Thanks for investigating this issue. Your findings suggests that this problem involve only a limited subset of Android devices which are good news anyway.
I sent the version number to the email address I found in one of your commits.

Best,
Bence

**Comment by FrankGalligan** [comment]
I'm closing this issue. If you are still having problems please re-open.
