### ISSUE TITLE
Segmentation Fault with inf_nan.obj

### ISSUE THREAD

**Issue by NathanBWaters** [google/draco#550]
I'm getting a seg fault when running the draco_encoder on `inf_nan.obj`.  This may be the expected behavior but it seems the [unit tests](https://github.com/google/draco/blob/c75a03b051877e45ee66093646ff405243c19f31/src/draco/io/obj_decoder_test.cc#L187) are able to compress and decompress `inf_nan.obj`.  My draco_encoder executable works with the other files like `test_nm.obj` and `bunny_norm.obj`. 

```
$ draco_encoder -i inf_nan.obj -o output.drc
Encoder options:
  Compression level = 7
  Positions: Quantization = 14 bits

Segmentation fault: 11
```

System: macOS Mojave

**Comment by FrankGalligan** [comment]
So the unit_tests are only testing the obj decoding. I can reproduce the seg fault but that is in the encoder.

**Comment by FrankGalligan** [comment]
This is faxed in release 1.3.6
