### ISSUE TITLE
Difference between GetAttributeByUniqueId and GetAttribute?

### ISSUE THREAD

**Issue by donmccurdy** [google/draco#554]
Both of these methods accept something that looks like an attribute ID, and in three.js r108 I mistakenly assumed that they were interchangeable, causing a bug: https://github.com/mrdoob/three.js/issues/17426. The fix involved using a different code path when a glTF file provides a attribute IDs, as opposed to a `.drc` file using default attribute ID mappings: https://github.com/mrdoob/three.js/pull/17501.

I don't think I quite understand the difference — are both cases necessary in that pull request, or is there a single way of getting an attribute that would work in both cases?

**Comment by FrankGalligan** [comment]
[GetAttributeId](https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/decoder_webidl_wrapper.h#L117)  and [GetAttributeByUniqueId](https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/decoder_webidl_wrapper.h#L132) are convenience functions.

Without those functions clients would have to search through all the attributes with [GetAttribute](https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/decoder_webidl_wrapper.h#L136) and store the attribute types and/or unique ids.

**Comment by donmccurdy** [comment]
Mostly my question is more general – what's the difference between an attribute ID and an attribute unique ID?

Without knowing that, I'm not sure which convenience function to use. I fixed a bug in https://github.com/mrdoob/three.js/pull/17501, but I still don't understand what that fix did. That makes me a little nervous about avoiding future regressions in three.js.
