### ISSUE TITLE
how to encode and decode from mesh by C++?

### ISSUE THREAD

**Issue by tatsuya-yokoda** [google/draco#560]
Hi. If possible would you tell me how to encode and decode from mesh by C++?
It seems that it has changed way to encode written on README.
First, I don't know how to create draco::mesh.

**Comment by FrankGalligan** [comment]
If you look here:
https://github.com/google/draco#c-decoder-api

This is pretty much all you need to do. In that example the encoded mesh is contained in the variable data.

Please reopen if you need something more specific.
