### ISSUE TITLE
[Unity] Error on import

### ISSUE THREAD

**Issue by Siccity** [google/draco#562]
Hello, just getting started with this plugin.

Directly after import in a fresh project i get this error:
```
Assets/Editor/DracoFileImporter.cs(33,7): error CS0246: The type or namespace name `DracoMeshLoader' could not be found. Are you missing an assembly reference?
```
![image](https://user-images.githubusercontent.com/6402525/66274313-916e6d00-e87d-11e9-9657-c456804d28bd.png)

Am I doing something wrong?

I tried with Unity 2017 and 2018, PC Standalone

**Comment by atteneder** [comment]
see #477 for a fix
also feel free to look at my much improved fork #540
