### ISSUE TITLE
Draco's binary schema

### ISSUE THREAD

**Issue by vpenades** [google/draco#563]
Could it be possible to write the binary schema of Draco file format?

It could greatly simplify draco's adoption by programming languages other than C..

The current binary schemas I know are:
- 010 Binary templates (proprietary)
- [Kaitai struct](https://github.com/kaitai-io/kaitai_struct)

**Comment by FrankGalligan** [comment]
Yes, that is what we tried to do with the [Draco bitstream](https://google.github.io/draco/spec/).

As well as another [bitstream ](https://github.com/KhronosGroup/glTF/pull/1721)in a different schema.

The issue is the bitstream does not fit nicely into a struct like structure.
