### ISSUE TITLE
Will Draco Compression/Decompression change the order of the triangles

### ISSUE THREAD

**Issue by BlackMojito** [google/draco#566]
Let’s say I have a vertex buffer which is a merged one as the meshes share the same material. I need to keep the original “range” for each VB before merge. The ranges can be described by a start vertex, vertex count, a start index and index count for example. So the only concern is whether doing Draco compression and Decompression will change the vertex order so that the range information becomes no longer valid?

**Comment by FrankGalligan** [comment]
Yes, Draco compression will change the order of the vertices
