### ISSUE TITLE
Query quantization bits in JavaScript API

### ISSUE THREAD

**Issue by lilleyse** [google/draco#573]
Is it possible to query the quantization bits used by an attribute without going through the process of skipping the attribute transform, initializing an `AttributeQuantizationTransform`, and getting the quantization bits from the transform?

Basically we want to decode to a float array if quantization bits is greater than 16, otherwise, decode to a uint16 array and dequantize in the shader. It's not clear if this is possible using the JavaScript API since we can't query the quantization bits until we have already called `SkipAttributeTransform` and initialized a `AttributeQuantizationTransform`.

Existing code looks something like this:
```js
var dracoDecoder = new draco.Decoder();
dracoDecoder.SkipAttributeTransform(draco[attributeType]);
var dracoAttribute = dracoDecoder.GetAttributeByUniqueId(dracoGeometry, compressedAttribute);
var transform = new draco.AttributeQuantizationTransform();
if (transform.InitFromAttribute(dracoAttribute)) {
    console.log(transform.quantization_bits());
}

**Comment by johnFJ** [comment]
> Is it possible to query the quantization bits used by an attribute without going through the process of skipping the attribute transform, initializing an `AttributeQuantizationTransform`, and getting the quantization bits from the transform?
> 
> Basically we want to decode to a float array if quantization bits is greater than 16, otherwise, decode to a uint16 array and dequantize in the shader. It's not clear if this is possible using the JavaScript API since we can't query the quantization bits until we have already called `SkipAttributeTransform` and initialized a `AttributeQuantizationTransform`.
> 
> Existing code looks something like this:
> 
> ```js
> var dracoDecoder = new draco.Decoder();
> dracoDecoder.SkipAttributeTransform(draco[attributeType]);
> var dracoAttribute = dracoDecoder.GetAttributeByUniqueId(dracoGeometry, compressedAttribute);
> var transform = new draco.AttributeQuantizationTransform();
> if (transform.InitFromAttribute(dracoAttribute)) {
>     console.log(transform.quantization_bits());
> }
> ```

**Comment by johnFJ** [comment]
#107

**Comment by ondys** [comment]
This workflow would require to get the quantization settings before the decoding step which is not really feasible for the current decoder design (quantization settings are not stored in any predefined byte position). I would recommend sending the quantization settings separately from the encoded data. This should allow you to implement the behavior that you want without modifying the decoder.
