### ISSUE TITLE
Possible to add metadata to faces?

### ISSUE THREAD

**Issue by zac92** [google/draco#577]
Hey,
i saw in the DracoEncoderModule that it is possible to add metadata to a mesh, 
but i need to add different metadata to every single face. Is their a way to do it?

Thank you
Zac

**Comment by FrankGalligan** [comment]
You could do this with a generic attribute (the compression will most likely be bad if it is unique for each face).

We do something like this for materials:
https://github.com/google/draco/blob/master/src/draco/io/obj_decoder.cc#L155
