### ISSUE TITLE
uv and uv2 disappear after compression.

### ISSUE THREAD

**Issue by DudduYum** [google/draco#58]
Basically when I encode obj model and decode it with javascript decoder I loose all uv coordinates. So it is impossible to add a texture to a model.

**Comment by ondys** [comment]
Can you please post an example of this problem? Draco encodes texture coordinates defined in .OBJ files and the example javascript decoder shows how to decode them as well.

**Comment by DudduYum** [comment]
I [link](http://stackoverflow.com/questions/42133752/draco-javascript-decodere-lose-uv-coordinates) you my question on stackoverflow

**Comment by ondys** [comment]
I just tried it on a simple model and the "uv" attribute was decoded correctly. 

1. Are you using the latest DRACOloader.js ? Support for texture coordinates has been added relatively recently. If you are using an older version, the uv coordinates would not be decoded.

2. If you are using the latest version, can you please share a sample .drc file (and if possible .obj as well) ?

**Comment by DudduYum** [comment]
You was right I had the old version.
