### ISSUE TITLE
can you make an installer for windows 10 

### ISSUE THREAD

**Issue by unholy182000** [google/draco#580]
Hello iam a 3d artist want to use this program for my project but i dont have any programming experience. Can you make an installer for this program for use in windows 10. Thank you.

**Comment by FrankGalligan** [comment]
I'm not sure how making an installer will help you out as this project is mostly a library.

There are some examples of using Draco within Unity here:
https://gitlab.com/atteneder/DracoUnity

And another good tool of using Draco in glTF files is here:
https://github.com/CesiumGS/gltf-pipeline

**Comment by Sandstedt** [comment]
@unholy182000 
Maybe this can help you or someone else:

Blender can export to glTF (at least in v 2.83) and comes with draco compression build in. You can find it in the export settings under Geometry.

**File** > **Export** > **glTF 2.0**. And to the right, expand **Geometry** and check **Compression**

So no need to build draco from scratch, and as Frank says, it's a library mean to be baked into other programs, not a program meant to be run as a GUI.
