### ISSUE TITLE
Draco 1.3.6 fails to compile with gcc < 5

### ISSUE THREAD

**Issue by SpaceIm** [google/draco#582]
With gcc-4.9:

```
src/draco/io/stdio_file_writer.cc:44:10: error: cannot bind 'std::unique_ptr<draco::StdioFileWriter>' lvalue to 'std::unique_ptr<draco::StdioFileWriter>&&'
   return file;
```

Can be fixed with std::move (eventually conditionnal preprocessing by checking gcc < 5 and clang < 3.9 I think).

It works with this patch:

```patch
--- a/src/draco/io/stdio_file_writer.cc
+++ b/src/draco/io/stdio_file_writer.cc
@@ -41,7 +41,12 @@ std::unique_ptr<FileWriterInterface> StdioFileWriter::Open(
     return nullptr;
   }
 
+#if (defined(__GNUC__) && (__GNUC___ < 5)) || \
+    (defined(__clang__) && (__clang_major__ < 3 || (__clang_major__ == 3 && __clang_minor__ < 9)))
+  return std::move(file);
+#else
   return file;
+#endif
 }
 
 bool StdioFileWriter::Write(const char *buffer, size_t size) {
```

**Comment by tomfinegan** [comment]
@SpaceIm Hopefully this new push helped.

Kind of a github fail as I didn't actually mean to directly land this without a test pass. Let me know if the patch helped.

**Comment by SpaceIm** [comment]
@tomfinegan I think that it doesn't matter in stdio_file_reader.cc, because "file" type is strictly identical to return type, while in stdio_file_writer.cc "file" is a unique_ptr to a derived type, which prevents copy ellision for non C++14 compilers.

**Comment by tomfinegan** [comment]
> @tomfinegan I think that it doesn't matter in stdio_file_reader.cc, because "file" type is strictly identical to return type, while in stdio_file_writer.cc "file" is a unique_ptr to a derived type, which prevents copy ellision for non C++14 compilers.

I can revert the change to the reader if it turns out to be unnecessary, but I don't have an environment readily available for testing ancient toolchains. If you could confirm whether the fix actually works and that the reader fix isn't needed I can close this issue and then revert the reader change.

**Comment by SpaceIm** [comment]
I can confirm that it works with gcc 4.9 without any fix on the reader.

**Comment by tomfinegan** [comment]
Thanks! I reverted the reader change. 

Closing this.
