### ISSUE TITLE
Does a npm version of the draco supports wasm?

### ISSUE THREAD

**Issue by yuhengh** [google/draco#588]
It's not clear in the document that if wasm is being used in the npm package. I don't see there's a wasm file being loaded so does it mean it's running the asm.js version? If so, is it possible to use wasm if available?

**Comment by FrankGalligan** [comment]
The current version (1.3.6) of the npm modules uses the asm.js versions. We can look into adding support for the wasm files.

**Comment by FrankGalligan** [comment]
Version 1.4.0 of the npm modules now use wasm instead of JavaScript.
