### ISSUE TITLE
Untextured triangles become textured

### ISSUE THREAD

**Issue by yvoronov-artec** [google/draco#59]
I have an OBJ file with some textured and some untextured triangles. Then I encode OBJ to DRC and decode it back. All untextured triangles become textured, which apparently is not what I want.

**Comment by ondys** [comment]
That's probably related to this [issue](https://github.com/google/draco/issues/53). Basically Draco currently requires attributes to be fully defined on all points. If some points on faces don't have texture coordinates defined, they are assigned with a default (0-index) value. Current solution would be to split the obj into two, where one uses the texture coordinates defined and one does not. We may add support for partially defined attributes later on, but it is currently not on our roadmap.

**Comment by yvoronov-artec** [comment]
Ok, I've got it.
