### ISSUE TITLE
JavaScript Pointcloud Support / Algorithm

### ISSUE THREAD

**Issue by haehn** [google/draco#590]
Hi all,

Do the JavaScript bindings support pointcloud compression/decompression yet?

Also, how does Draco compress point clouds? The spec does not tell much.

Thank you so much!

Best,
Daniel

**Comment by yuhengh** [comment]
I think so. Javascript specs are documented here
https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/draco_web_encoder.idl
https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/draco_web_decoder.idl
There's also an example in the npm module directory
https://github.com/google/draco/blob/master/javascript/npm/draco3d/draco_nodejs_example.js

**Comment by haehn** [comment]
Thank you, I will take a look!
