### ISSUE TITLE
Still have duplicate points after turn on ENABLE_DECODER_ATTRIBUTE_DEDUPLICATION in the CMakeList.txt

### ISSUE THREAD

**Issue by xtorker** [google/draco#591]
Hi, I am confused by the deduplication feature in your project.

What I expected is removing the duplicated points after quantization and the decompressed point cloud will have fewer points than the input point cloud.

But no matter I build the project with setting "ENABLE_DECODER_ATTRIBUTE_DEDUPLICATION" ON or OFF in the CMakeList.txt, I always get the same number of points in input/output point cloud.

Is there any way I can get fewer points in the output point cloud? Or did I just look into the wrong place for the setting?

My testing point cloud is a .ply file with only x, y, z coordinates data, no normals or other attributes.
I input a point cloud with 500k points, and I got the output point cloud with 500k points.
In the output point cloud, there are 491,147‬ duplicate points.

I have read similar issues and parts of source code on the decoder, but I only found "ENABLE_DECODER_ATTRIBUTE_DEDUPLICATION" will enable "FEATURE DRACO_ATTRIBUTE_INDICES_DEDUPLICATION_SUPPORTED" and "FEATURE DRACO_ATTRIBUTE_VALUES_DEDUPLICATION_SUPPORTED" on the decoder.
I think "FEATURE DRACO_ATTRIBUTE_INDICES_DEDUPLICATION_SUPPORTED" is what I need, but the results still negative.

Thanks in advance.

**Comment by Sheepsody** [comment]
Hi,
I have the same issue. Although the compression runs without any error, I still notice a de-duplication even with a small quantization size.
Thanks for your comprehension....

**Comment by ondys** [comment]
The name of the flag may be a bit confusing. ENABLE_DECODER_ATTRIBUTE_DEDUPLICATION is currently used only for deduplication of points on the input data (that is, when loading the data from .ply / .obj / etc). It currently does not affect duplicate points that were created because of quantization

**Comment by Sheepsody** [comment]
Thanks for your answer,
It indeed becomes clearer when looking at the source code.
Thus having duplicates in the encoded point cloud is something that should be expected ?

**Comment by ondys** [comment]
Sorry for the late reply, yes having duplicates in the encoded point cloud is to be expected.
