### ISSUE TITLE
Latest Draco for glTF does not work in IE11

### ISSUE THREAD

**Issue by bghgary** [google/draco#596]
It seems like the latest fallback version https://github.com/google/draco/blob/1.3.6/javascript/draco_decoder_gltf.js does not work with IE11.

I couldn't tell if this file was built with IE_COMPATIBLE or not. Is it supposed to be?

I tried building this myself to make sure IE_COMPATIBLE is on, but it still doesn't work. I ran the following CMake command:

```
cmake ../ -DCMAKE_TOOLCHAIN_FILE=<path>/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DIE_COMPATIBLE=ON -DBUILD_FOR_GLTF=ON
```

I'm using the latest emsdk version 1.39.11. The issue seems to be that the latest emscripten generates code that uses Promises, but they are not available in IE. Supposedly, this [PR](https://github.com/emscripten-core/emscripten/pull/10064) puts a polyfill for Promises, but I don't see it in the resulting js.

Am I missing something?

**Comment by tomfinegan** [comment]
Afaik the repo version of draco_decoder_gltf.js has never been built with -DIE_COMPATIBLE=1. 

Can you confirm that -s LEGACY_VM_SUPPORT=1 is present in build commands with your run? Run make VERBOSE=1 to see the output. If it is and the javascript is not working with IE11 it may be an emscripten issue. The draco side has never done anything more than set that flag to enable compatibility.

**Comment by bghgary** [comment]
> Can you confirm that -s LEGACY_VM_SUPPORT=1 is present in build commands with your run?

Yes, it seems to be present.
```
-DDRACO_ATTRIBUTE_INDICES_DEDUPLICATION_SUPPORTED -DDRACO_ATTRIBUTE_VALUES_DEDUPLICATION_SUPPORTED @CMakeFiles/draco_encoder.dir/includes_CXX.rsp -s LEGACY_VM_SUPPORT=1 -s WASM=0 -s PRECISE_F32=1 -s EXPORTED_RUNTIME_METHODS=[] -s NO_FILESYSTEM=1 -s MODULARIZE=1 -fno-omit-frame-pointer --memory-init-file 0 -Wno-almost-asm -s ALLOW_MEMORY_GROWTH=1  -DNDEBUG -O2   -std=gnu++11
```

I also suspect this is a emscripten issue, but I wanted to make sure I'm not doing something wrong first.

**Comment by bghgary** [comment]
I must have did something wrong before because now I have the polyfill in the generated output. Weird. Sorry for the spam.

**Comment by bghgary** [comment]
Would you consider adding IE_COMPATIBLE=1 for the fallback draco_decoder_gltf.js? It's not as useful without it. As far as I can tell, it doesn't make the js much bigger.

**Comment by MiiBond** [comment]
I agree with @bghgary. We need IE support as well so it would be great if the statically-hosted JS decoder worked on IE.
