### ISSUE TITLE
Directly loading Draco from string/ArrayBuffer (.drc embedded in file)

### ISSUE THREAD

**Issue by jliempt** [google/draco#597]
I am trying to create a new file format and want to incorporate Draco in it. Separating the file into different segments, I attain a variable that contains the Draco part as a string.

What I have tried is converting the string to an ArrayBuffer. I have (in an ugly way for quick testing) modified DRACOLoader.js to give my ArrayBuffer to decodeDracoFile, rather than the blob obtained from THREE.FileLoader.

However, this is not working as I am getting the following error: "THREE.DRACOLoader: Decoding failed: Failed to decode metadata."

One thing I have noticed is that my ArrayBuffer is of a smaller byteLength than the ArrayBuffer that THREE.FileLoader yields when loading the equivalent actual .drc file. Any clues on how to make this work?

Code snippet to create the ArrayBuffer:
```
  var drc = new ArrayBuffer(drc_s.length);

  var bufView = new Int8Array(drc);
  for (var i=0, strLen=drc_s.length; i<strLen; i++) {
    bufView[i] = drc_s.charCodeAt(i);
  }
```

Changed bit in DRACOLoader.js (1st argument for scope.decodeDracoFile):
```
    load: function(url, query, onLoad, onProgress, onError) {
        var scope = this;
        var loader = new THREE.FileLoader(scope.manager);
        loader.setPath(this.path);
        loader.setResponseType('arraybuffer');
        if (this.crossOrigin !== undefined) {
          loader.crossOrigin = this.crossOrigin;
        }
        loader.load(url, function(blob) {
            scope.decodeDracoFile(drc, onLoad, query);
        }, onProgress, onError);
    },
```

**Comment by guneshmunjal** [comment]
@ondys is this issue still open??

**Comment by ondys** [comment]
Based on my understanding this issue is not directly related to Draco but rather with preparing the data before it is passed to Draco (considering the buffer sizes are different). Unfortunately, we can't really provide help with general JS questions here (it's not really our expertise). I would suggest asking in a more appropriate forum where people may be able to help.
