### ISSUE TITLE
A error occurred when I try to open a .ply file using draco::ReadPointCloudFromFile.

### ISSUE THREAD

**Issue by guanguanboy** [google/draco#605]
I wrote a sample to encode ply files on windows 10, the code is like this.  

int main()
{
	std::unique_ptr<draco::PointCloud> pc;
	std::string input_filename = std::string("D:\\Code2020\\draco-1.3.6\\testdata\\bun_zipper.ply");
	auto maybe_pc = draco::ReadPointCloudFromFile(input_filename);
	if (!maybe_pc.ok()) {
		printf("Failed loading the input point cloud: %s.\n",
			maybe_pc.status().error_msg());
		return -1;
	}
...
}

A error occurred when I try to open a .ply file using draco::ReadPointCloudFromFile.
D:\Code2020\draco-1.3.6\src\draco\io\file_reader_factory.cc:41 (OpenReader): No file reader able to open input.
Failed loading the input point cloud: Unable to read input file..

**Comment by salvadorpg** [comment]
Hi! wonder if you manage to solve this? I am having the same issue.... Thanks!

**Comment by ferdymercury** [comment]
maybe related https://github.com/google/draco/issues/613

**Comment by FrankGalligan** [comment]
@guanguanboy You need to escape the '\' character when putting them in C strings. 

See [here](https://docs.microsoft.com/en-us/cpp/c-language/c-string-literals?view=msvc-160#:~:text=The%20single%20quotation%20mark%20('),as%20a%20line%2Dcontinuation%20character.) for more info.

**Comment by Darustc4** [comment]
#683 Check this out, its probably a problem when linking the library to your project.
