### ISSUE TITLE
Draco object disappears when moving too close

### ISSUE THREAD

**Issue by FabrizioDys** [google/draco#606]
Hi everybody,
I am using the simple Draco Decoding Object script you provided here in GitHub to have some decompressed draco meshes in my Unity Scene. The problem is, when I move too close to them through an FPS Controller the mesh disappears.

I already checked the clipping planes of the camera attached to the FPS Player, but the Near Plane is set as 0.01 so I believe that's not the problem.
Can someone help me out?

**Comment by Darustc4** [comment]
It disappears when the gameobject that holds the mesh goes out of the FOV, there is another separate script in the unity repository (https://gitlab.com/atteneder/DracoUnity) which does not have this problem, its under /Runtime/Scripts.

I hope this solves your problem.

**Comment by FrankGalligan** [comment]
Closing based on @Darustc4 comment.

**Comment by camroo29** [comment]
I am facing the same issue in Hololens. The model disappears with any movement of the HoloLens. Also not completely sure how to implement DracoMeshLoader.cs from the other repo. Would you please share some use cases?
