### ISSUE TITLE
Test building fails

### ISSUE THREAD

**Issue by hobu** [google/draco#61]
With a `googletest` directory above the `draco` clone as shown in CMakeLists.txt, when I configure with `-DENABLE_TESTS=ON`, I get a compiler error:

```
/Users/hobu/dev/git/draco/compression/mesh/mesh_edgebreaker_encoding_test.cc:23:10: fatal error:
      'mesh/mesh_are_equivalent.h' file not found
#include "mesh/mesh_are_equivalent.h"
```

**Comment by ondys** [comment]
Thanks for the report. The file is indeed missing in the public repo. We are going to fix this in the next update.

**Comment by ondys** [comment]
This should be fixed in the master branch
