### ISSUE TITLE
Try to encode and decode mesh in C++

### ISSUE THREAD

**Issue by zomanankasina** [google/draco#610]
Hi everyone,
I have a little problem when I try to add draco in my personal project.

When I build draco sources with main executable, it works very well. But when I try to put draco features in a separate library I have the following error :

draco/io/file_reader_factory.cc:41 (OpenReader): No file reader able to open input.

Can someone help me out?
Thank you very much.

**Comment by zomanankasina** [comment]
I cannot explain it but it works now.

**Comment by naxostech** [comment]
Hi zomanankasina,
I have the same problem (on Linux).
Did you change something in your code to make it work ?

Thanks in advance for your reply

**Comment by zomanankasina** [comment]
Hi naxostech,
I copied used draco sources and included it in our software. I wish I could find a more clever way.

**Comment by moshe-rabaev** [comment]
@naxostech Any luck I'm experiencing the same issue, thanks!

**Comment by moshe-rabaev** [comment]
The issue for me was that the mtl file and texture file had been renamed, so the obj file was referencing nothing and that caused this error.

Hope this helps someone else!

**Comment by naxostech** [comment]
Thanks for the information. I had no mtl when I tested, I'll try with one. I keep you posted.

**Comment by kho19** [comment]
Hi, 
I am having the same problem. 
@naxostech did you find a solution that doesn't involve copying the source code to your project? 
Thanks.

**Comment by Darustc4** [comment]
Same problem, how did you make the CMakeLists.txt to include the whole draco library sources? @zomanankasina

**Comment by zomanankasina** [comment]
I added ALL the sources, except of the *_test.cc

**Comment by Darustc4** [comment]
#683 Check this out, its probably a problem when linking the library to your project. This way you dont need to import all the sources.
