### ISSUE TITLE
Filesize limit

### ISSUE THREAD

**Issue by TimothieGeulin** [google/draco#611]
It seems that since reading a file involve using a vector, it is impossible to read a whole file bigger than the vector.max_size() in one go.
I work with really big point clouds so I tend to limit memory usage by using relatively small buffers and not reading the entirety of a file in one go.
So my question is: Is it possible to do that here? I didn't looked any further than the file reader so I don't know if ALL the datas are required before beginning the compression.
If that's not the case, do someone have any advice concerning that kind of problem?

**Comment by ondys** [comment]
The current version of the algorithm needs to load all data into a vector so it may not be suitable for extremely large models.
