### ISSUE TITLE
Error when reading PLY file from Rhinos

### ISSUE THREAD

**Issue by ferdymercury** [google/draco#613]
When opening this PLY file https://github.com/cnr-isti-vclab/meshlab/files/3330082/Box.ply.zip, I get an error in the console
```
Invalid header ('end_header' line not found!)
Invalid file
```

even if the end_header is there. Might be an issue with carriage return 0A (\r) vs 0D (\n) ?

![image](https://user-images.githubusercontent.com/10653970/85791010-29a7cd00-b6ff-11ea-93aa-5938bc37f185.png)

Related:
https://github.com/cnr-isti-vclab/meshlab/issues/463

**Comment by ferdymercury** [comment]
apparently the windows 3d viewer has same bug

**Comment by ferdymercury** [comment]
Also related:
https://developer.blender.org/T78278

It's because of different conventions in newline chars.

**Comment by FrankGalligan** [comment]
Fixed in 1.4.0

**Comment by ferdymercury** [comment]
Thanks!! Does it support now both versions of newlines?

See https://github.com/dranjan/python-plyfile
![image](https://user-images.githubusercontent.com/10653970/100926643-c42be980-34b1-11eb-9e8d-0c4a472efcf7.png)
