### ISSUE TITLE
Unity decode memory leak.

### ISSUE THREAD

**Issue by Darustc4** [google/draco#614]
Hello, as I was coding an application in Unity (2018.2.10f1 Personal 64b) that requires many draco files to be decoded for a extended period of time I noticed an unnatural increase of RAM usage, so I created this minimal code to test the problem.

```c#
public class RS_Feed_Manager : MonoBehaviour {

     NativeArray<byte> data;

        private void Update() {
            data = new NativeArray<byte>(File.ReadAllBytes("Assets/dracoSample.drc"), Allocator.Persistent);
            DracoMeshLoader dracoLoader = new DracoMeshLoader();
            GetComponent<MeshFilter>().mesh = dracoLoader.DecodeMeshSync(data);    // Memory leak when calling this function
            data.Dispose();
        }
}
```

If you comment out the line with the DecodeMeshSync call the memory leak stops. So I wonder if I'm using the provided code incorrectly or if there's actually a problem with it.
The code of said method is the following, as it is in the Unity repository:

```c#
     public Mesh DecodeMeshSync(NativeArray<byte> data) {

        Profiler.BeginSample("JobPrepare");
        var job = new DracoJob();

        job.data = data;
        job.result = new NativeArray<int>(1, defaultAllocator);
        job.outMesh = new NativeArray<IntPtr>(1, defaultAllocator);

        job.Run();
        Profiler.EndSample();

        int result = job.result[0];
        IntPtr dracoMesh = job.outMesh[0];

        job.result.Dispose();
        job.outMesh.Dispose();

        if (result <= 0) {
            Debug.LogError("Failed: Decoding error.");
            return null;
        }

        bool hasTexcoords;
        bool hasNormals;
        var mesh = CreateMesh(dracoMesh, out hasNormals, out hasTexcoords);

        if (!hasNormals) {
            mesh.RecalculateNormals();
        }
        if (hasTexcoords) {
            mesh.RecalculateTangents();
        }

        return mesh;
    }
```

Any help or ideas are appreciated.

**Comment by Darustc4** [comment]
After some research, I've discovered the problem isn't with Draco, it was with the way Unity handles meshes. 
Here is an article explaining this behavior and how to avoid memory leaks: https://nothkedev.blogspot.com/2018/08/procedurally-generated-meshes-in-unity.html

**Comment by camroo29** [comment]
How did you finally solve the problem?
