### ISSUE TITLE
point cloud compression algorithm

### ISSUE THREAD

**Issue by haehn** [google/draco#615]
Hello,

I read the Draco uses a KD-tree for point cloud compression. Are there details of the method available?

I also saw pointers to
* Schnabel: Octree-based Point-Cloud Compression
* Devillers: Geometric Compression for Interactive Transmission

Are these references correct and describe the algorithm? Is there any other paper available that I could take a look at?

Thank you so much!
Daniel

**Comment by ondys** [comment]
The most relevant paper seems to be this one:
https://hal.inria.fr/inria-00072743/document

The algorithm implemented in Draco does not follow the paper exactly and it contains many custom modifications but the overall approach should be comparable.
