### ISSUE TITLE
code 404, message File not found draco google

### ISSUE THREAD

**Issue by FrancescoMandru** [google/draco#616]
Hello, I'm following this tutorial for testing the capabilities of Draco:

(https://codelabs.developers.google.com/codelabs/draco-3d/index.html#4)

When I need to decode the file in the web browser I get this error message:

Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [08/Jul/2020 18:59:13] "GET /DracoDecode.html HTTP/1.1" 200 -
127.0.0.1 - - [08/Jul/2020 18:59:14] "GET /bunny.drc HTTP/1.1" 200 -
127.0.0.1 - - [08/Jul/2020 18:59:14] code 404, message File not found
127.0.0.1 - - [08/Jul/2020 18:59:14] "GET /favicon.ico HTTP/1.1" 404 -

Anyone know how to solve this issue? The file "bunny.drc" is in the same directory

Another question is that if I can decode the point-cloud without doing this kind of operation just by calling a function or something like that, I would like to build a c++ program that takes in input a pointcloud in the correct format, encode and decode it.

**Comment by wcochran** [comment]
Yeah .. this link does not exist:
https://rawgit.com/google/draco/master/javascript/draco_decoder.js
I tried replacing this with the provided draco_decoder.js but I think its interface has changed.

**Comment by FrankGalligan** [comment]
I updated the codelab. It should work now. Thanks for filing the issue.
