### ISSUE TITLE
Explain Draco

### ISSUE THREAD

**Issue by FrancescoMandru** [google/draco#618]
Is there someone who can explain or give all the resources available on how Draco works in detail? Like a sort of paper which currently does not exist.

**Comment by GovorovViva64** [comment]
https://google.github.io/draco/spec/

**Comment by FrankGalligan** [comment]
What @GovorovViva64 posted is probably the best we have. If you are looking for something more specific please reopen.

**Comment by FrancescoMandru** [comment]
I would like to read something like a "academic paper" where I can understand how Draco works, because looking at the entire source code trying to understand what Draco does is very hard to me.
