### ISSUE TITLE
Cannot compress *.gltf file to *.drc 

### ISSUE THREAD

**Issue by rib-pet** [google/draco#619]
`draco_encoder.exe -i 鑫源国际广场F、G栋.gltf -o xinyuanFG_Draco.drc
Failed loading the input mesh: Error decoding input..`

I am wondering whether it supports gltf format to drc format. Could you please specify the correct command line

**Comment by rib-pet** [comment]
On Contrary, I am using the gltf-pipleline. it is working and returns correct result.

![image](https://user-images.githubusercontent.com/37282473/88005057-f9efb780-cb3a-11ea-9c8a-1df40ba6c56b.png)
![image](https://user-images.githubusercontent.com/37282473/88005068-0542e300-cb3b-11ea-90a8-5b4096dbb340.png)

**Comment by donmccurdy** [comment]
glTF-Pipeline uses the Draco library to compress mesh/geometry data within glTF files. So the input is a glTF file, and the output is a (smaller) glTF file. If that's what you're trying to do, glTF-Pipeline is probably the right tool for the job.

**Comment by ondys** [comment]
As Don mentioned, glTF-Pipeline is probably what you want to use. .drc is a geometry only format that can't represent all properties of a .gltf scene.
