### ISSUE TITLE
Run Draco on gpu?

### ISSUE THREAD

**Issue by xudi1227** [google/draco#620]
Hi, 
Just wonder has anyone tried to run Draco on gpu? Any hint would be appreciated

**Comment by FrancescoMandru** [comment]
I would like to know if is it possible to do that

**Comment by ondys** [comment]
This repo contains only CPU implementation of the Draco decoder. A GPU decoder for the current [bitstream spec](https://google.github.io/draco/spec/) can be potentially written on the GPU but there are no plans to that in a near term future.
