### ISSUE TITLE
error C2248 when building draco using visual studio 2010

### ISSUE THREAD

**Issue by showintime** [google/draco#628]
in `status_or.h` line 77,when the type of `lhs` is `std::unique`, it sames like to use `std::unique_ptr<_Ty>::unique_ptr(const _Ty&)`,which is not define and not allowed.

**Comment by FrankGalligan** [comment]
The Draco code is dependent on C++11. Even if we can address this issue so it will work in VS2010, it will most likely break in other places of the code. I looked quick and there seems to be multiple C++11 features the Draco library currently relies on that VS2010 does not support.

This would be too much work to support a product [Microsoft does not support](https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing).
