### ISSUE TITLE
`MetadataBuilder.AddIntEntryArray()` missing in Draco JS API?

### ISSUE THREAD

**Issue by ibgreen** [google/draco#631]
I3S tiles (an OGC standard) requires support for [integer arrays in Draco metadata](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/compressedAttributes.cmn.md).

Clearly, JS API has support for decoding integer arrays from metadata
- https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/draco_web_decoder.idl#L182

However, support for encoding this type of metadata entries seems to be missing in the JS API?
- https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/draco_web_encoder.idl#L79

If this is true, it appears that standards-compliant I3S tiles can not be encoded in the Draco Javascript API (other existing encoders are not JS based as far as we know).

Is it possible to expose the missing API or are there any workarounds?

**Comment by FrankGalligan** [comment]
We are planning on making a new release this month. We will add this to the API.

**Comment by FrankGalligan** [comment]
Added in 1.4.0.

See https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/encoder_webidl_wrapper.h#L51
