### ISSUE TITLE
Applying materials to encoded mesh (.drc)

### ISSUE THREAD

**Issue by aeris170** [google/draco#639]
We are encoding an .obj file with material definitions stored in a .mtl file using draco_encoder command line tool (built with cmake and VS2017). The output file is a single .drc file. We use this file in combination with [DracoUnity](https://gitlab.com/atteneder/DracoUnity) however when we try to render the mesh in Unity, all the submeshes and the materials are gone. How can we apply the material definitions to the encoded mesh (or the mesh decoded by DracoUnity) ?

**Comment by FrankGalligan** [comment]
@atteneder Does https://github.com/atteneder/DracoUnity have an example of how to do this?

**Comment by atteneder** [comment]
Hi @aeris170 ,

Draco was not designed to solve this problem. It is a mesh compression library with no support for materials.

So you can either solve the material transform in a custom solution or use other existing, standard formats and tools. Here's my advice:

1. Convert your OBJs into [glTF](https://www.khronos.org/gltf/) files, which support full scenes with meshes, objects and materials (and more). It also supports/ uses Draco compression. Blender can do the conversion (make sure to check mesh compression when exporting).
Another side-benefit: glTF also supports more sophisticated material features than OBJ, like physically based rendering with metallic-roughness.
2. Use the [glTFast](https://github.com/atteneder/glTFast) Unity package for loading the glTF files. It is also maintained by me and uses/depends on DracoUnity.

hth,
Andi

**Comment by tomfinegan** [comment]
This appears to have been adequately answered. I'm going to close the issue: Please update this issue or file a new one if the topic requires further discussion.
