### ISSUE TITLE
Extra geometry

### ISSUE THREAD

**Issue by IluhaFR** [google/draco#640]
Hi. 
I have a  [model](https://drive.google.com/file/d/1HWcIxttW67IVz5XtXPOCeFI34qlmWbNh/view?usp=sharing).
I converted it by this [service](https://products.aspose.app/3d/conversion/obj-to-drc), the result of converting [here](https://drive.google.com/file/d/1eXvp9Z_mkj99vdt_R5Noh0mTVRyw_GGU/view?usp=sharing). But i has extra geometry after converting. This geometry isn't in default file. What is the problem?

**Comment by FrankGalligan** [comment]
I tired to download the source model to check with our tools but it seems to have been deleted.

**Comment by tomfinegan** [comment]
Closing due to lack of response. Please update the issue or file a new one.
