### ISSUE TITLE
Draco compression failing for some specific data

### ISSUE THREAD

**Issue by shakil0302** [google/draco#644]
[dna.zip](https://github.com/google/draco/files/5583540/dna.zip)

We extracted the positions and indices data and compressed with Draco. It returns status OK but fails to decompress. We debugged the decode code. The number of attributes, components per index and data type are all garbage. The encoding itself failed as we tried to do it in memory and data didn't took any intermediate form.

**Comment by FrankGalligan** [comment]
I converted dna.fbx to a gltf file using [fbxtogltf](https://github.com/facebookincubator/FBX2glTF). Then compressed the gltf file to a draco gltf file using [gltf-pipeline](https://github.com/CesiumGS/gltf-pipeline). Then rendered the Draco gltf file. It looked like some kind of DNA molecule.

So in general the geometry data can be compressed with Draco.

Could there be an issue with your encoding code?

Can you try saving your dna file as an obj or ply file and encoding with draco_encoder executable? That should be about the same loading fbx and encoding to draco in memory (Though my steps above also is about the same)

**Comment by tomfinegan** [comment]
Closed due to lack of response. @shakil0302: please respond to the above question, and we can reopen the issue to investigate further.
