### ISSUE TITLE
Segmentation Fault in encoding obj file

### ISSUE THREAD

**Issue by Center-Stage** [google/draco#651]
Hi, I am getting a segmentation fault in encoding a specific obj file. With most of the obj file I am getting the expected result but for the some obj files with format as attached gives segmentation fault. Following is the link to the obj file https://drive.google.com/file/d/1IKVBH5K3UARacJmjcAkoHO1Fomqawrzs/view?usp=sharing

**Comment by FrankGalligan** [comment]
Duplicate of #652
