### ISSUE TITLE
Encoder gives segmentation fault for some obj file

### ISSUE THREAD

**Issue by RahulJain7** [google/draco#652]
Hi, I am getting a segmentation fault in encoding a specific obj file. With most of the obj file I am getting the expected result but for the some obj files with format as attached gives segmentation fault. Following is the link to the obj file https://drive.google.com/file/d/1IKVBH5K3UARacJmjcAkoHO1Fomqawrzs/view?usp=sharing

**Comment by FrankGalligan** [comment]
Hi @RahulJain7,

I was able to encode [1.obj](https://drive.google.com/file/d/1IKVBH5K3UARacJmjcAkoHO1Fomqawrzs/view?usp=sharing) as decode the .drc file.

These are the steps I followed from a fresh checkout:
1. mkdir build_dir && cd build_dir
2. cmake ../ && make
3. ./draco_encoder -i ~/Downloads/1.obj -o temp.drc
4. /draco_decoder -i temp.drc -o temp.obj

I didn't get any segmentation fault. And I was able to view 1.obj and temp.obj and they both looked the same.

Can you provide the steps you did to cause the segmentation fault?

**Comment by tomfinegan** [comment]
Closed due to lack of response. @RahulJain7: please respond to the above question, and we can reopen the issue to investigate further.
