### ISSUE TITLE
Add complete listing of draco files on CDN to README

### ISSUE THREAD

**Issue by ibgreen** [google/draco#654]
In the process of upgrading loaders.gl to draco v1.4 (many thanks for the fix https://github.com/google/draco/issues/631 !!!), we are in the process of working through the customary tricky draco library loading issues ;)

Unless there is some documentation I am missing, it would be great if there could be a short explicit table listing the decoders in the following section: https://github.com/google/draco#wasm-and-javascript-decoders

In particular I can't find `draco_encoder.js` on the static CDN, and would really prefer to load all files the same way (supporting main thread, worker thread and Node.js loading of these libraries is quite tricky).

But it would also be good to e.g. have the `_gltf` decoder variants listed in the table. I remember seeing some discussion of the pros and cons of these in the past but I can't find it now.

**Comment by ibgreen** [comment]
Also is there any versioning on the https://www.gstatic.com/draco/v1/decoders/* URL?

Loading draco_decoder from the static URL I don't seem to get the new `AddIntEntryArray` function. I tried replacing v1 with v1.4 in the URL but no luck.

**Comment by ibgreen** [comment]
Poking around I am also finding a draco3dgltf module that seems to have node versions of the encoder/decoder!?! 

Are those the draco3d libraries that I should be loading when running on Node? Or are they just trimmed glTF-only versions that happen to be named `_nodejs`?

If these are to be used, could those files also be put on the gstatic CDN and added to the table in the documentation?

https://github.com/google/draco/blob/master/javascript/npm/draco3dgltf/draco3dgltf.js

```js

var createEncoderModule = require('./draco_encoder_gltf_nodejs');
var createDecoderModule = require('./draco_decoder_gltf_nodejs');

module.exports = {
  createEncoderModule,
  createDecoderModule
}
```

**Comment by tomfinegan** [comment]
@ibgreen: 

>  it would be great if there could be a short explicit table listing the decoders

The README will be updated with information about what's available on static hosting in our next release. 

> In particular I can't find draco_encoder.js on the static CDN

The encoders have not been added to static hosting.

> Are those the draco3d libraries that I should be loading when running on Node? Or are they just trimmed glTF-only versions that happen to be named _nodejs?

The files in the npm subdirectory are node packages intended for installation via npm. The files there have been copied there from the parent directory, and in some cases renamed. For example: 

- `javascript/npm/draco3d/draco_decoder_nodejs.js` is a renamed copy of `javascript/draco_wasm_wrapper.js`.
-  `javascript/npm/draco3dgltf/draco_decoder_gltf_nodejs.js` is a renamed copy of `javascript/draco_wasm_wrapper_gltf.js`

**Comment by ibgreen** [comment]
Thanks for clarification, this really helps. 

Would be nice if you added the encoders to static hosting for consistency. Until then we can include them in our own `@loader.gl/draco` npm module and load them via unpkg CDN.
