### ISSUE TITLE
draco1.4 - decodeDracoFile function does not work.

### ISSUE THREAD

**Issue by alitokur** [google/draco#655]
when i try to use decodeDracoFile it returns:

```
failed to asynchronously prepare wasm: TypeError: WebAssembly.instantiate(): Import #2 module="wasi_unstable" error: module is not an object or function
Uncaught (in promise) RuntimeError: abort(TypeError: WebAssembly.instantiate(): Import #2 module="wasi_unstable" error: module is not an object or function). Build with -s ASSERTIONS=1 for more info.
```
Is there any other decode function that uses bytearray(not url) as input?
edit:
problem is the decoder path:
'https://www.gstatic.com/draco/v1/decoders/'

**Comment by FrankGalligan** [comment]
@alitokur Sorry we are middle of changing our examples and documentation to use the versioned URLs.
