### ISSUE TITLE
Encoder gives segmentation fault

### ISSUE THREAD

**Issue by bianyunzhi95** [google/draco#669]
[segment2.zip](https://github.com/google/draco/files/5764750/segment2.zip)

Encoder 1.4.1 gives segmentation fault. (vector index out of range).
I would appreciate if you can post your testing executable file and build options if it works without segmentation fault.

**Comment by bianyunzhi95** [comment]
[small.zip](https://github.com/google/draco/files/5764878/small.zip)
This is the smallest model I could find which cause segment fault for you to debug.

**Comment by tomfinegan** [comment]
This no longer reproduces at repository HEAD. Closing the issue: please file a new one or update this one if it requires specific encoding settings to reproduce the reported crash.

Tested at repo hash: ee2c2578a170324bffef38cb8a3c2e60d89d5e87
