### ISSUE TITLE
Question: Compound point cloud attribute interpretation

### ISSUE THREAD

**Issue by abellgithub** [google/draco#678]
There are pre-defined point cloud attributes that can contain more than one actual value. For example, COLOR may contain a red value, green value, alpha value. I don't see any documentation describing the expected contents of such an attribute. Is there some way that a reader is supposed to know that such an attribute contains those values and the order of those values? Is this supposed to be stored in metadata? If COLOR, for instance, can contain any number of values with any particular meaning, what's the difference between COLOR and POSITION, for example?

**Comment by ondys** [comment]
You are correct that any attribute can contain any values and any format (e.g. POSITION attribute can by XY or XYZ, float32 or int32 or even anything else). In the end you can put any data into any attribute. There are two main reasons to use appropriate attribute types:
  1. It makes it easier for users to request a specific attribute on the decoder side.
  2. Some of the mesh compression algorithms use specialized encoders for specific attributes. E.g. we have specialized encoders for NORMAL or TEX_COORD attributes that in turn require the POSITION attribute. All these encoders have some requirements for the format of these attributes (e.g. XYZ for POSITIONS and NORMALS and UV for TEX_COORDS).
  
  For your COLOR example. I believe Draco currently doesn't have a specialized encoder for this attribute so you are free to put any values there (RGB or RGBA, etc..)

**Comment by abellgithub** [comment]
Thanks.

So the file reader needs metadata, in whatever form, in order to know the meaning of the decoded attributes. Is this seen as a deficiency? I would think specifying the meaning of data that make up each attribute would be valuable. It would mean that code like the following from the repo could be run with confidence.  This seems like a documentation issue. Is there any interest in creating documentation beyond what currently exists?

```
  if (color_att_id >= 0) {
    const auto *const attribute = in_point_cloud_->attribute(color_att_id);
    if (attribute->num_components() > 0) {
      out << "property " << GetAttributeDataType(color_att_id) << " red"
          << std::endl;
    }
    if (attribute->num_components() > 1) {
      out << "property " << GetAttributeDataType(color_att_id) << " green"
          << std::endl;
    }
    if (attribute->num_components() > 2) {
      out << "property " << GetAttributeDataType(color_att_id) << " blue"
          << std::endl;
    }
    if (attribute->num_components() > 3) {
      out << "property " << GetAttributeDataType(color_att_id) << " alpha"
          << std::endl;
    }
  }
  ```

**Comment by ondys** [comment]
I wouldn't say that you need metadata unless you expect to receive .drc files with different formats, nor do I see it as a deficiency. It really depends on each specific use case. Many of our users have full control over both encoder / decoder side so they just need to ensure both encoding and decoding formats match. Another common use of Draco is within the glTF format where the format of each attribute is defined by glTF attributes. 

If Draco prescribed some specific format for these attributes it would just limit many of the above listed use cases.

Improving our documentation is definitely something we want to do and we always welcome any community contributions in that regard.

**Comment by abellgithub** [comment]
Well I have to disagree a bit. Not having definitions for the attributes while at the same time providing special encoders that *assume* a certain definition seems contradictory.

**Comment by ondys** [comment]
The encoders do not really assume a format definition. The encoders will be used only if the format of the attribute matches the expected format. If not, a generic encoder is going to be used. I think we will have to agree to disagree on this one. We are always open to discussion but I don't think we are going to change our approach here. There are just too many users that use various formats for their attributes and any strict restrictions on our side would be too disruptive at this point. 

I would agree that we can improve our documentation to provide recommended formats for all attributes.
