### ISSUE TITLE
Global Module var in draco_decoder.js

### ISSUE THREAD

**Issue by edsilv** [google/draco#68]
Hi,

I created a PR adding DRACOLoader.js and draco_decoder.js to the three.js repository:

https://github.com/mrdoob/three.js/pull/10879

Please see @mrdoob's comments regarding the global `Module` var in draco_decoder.js. It's better to avoid polluting the global namespace if possible.

I also agree that it would be good if DRACOLoader.js were to be maintained within the three.js repo.

**Comment by jbaicoianu** [comment]
It looks like this library is built with Emscripten, which is where the global `Module` variable is coming from. Emscripten supports a couple arguments at compile time which lets you provide proper namespaced modules for compiled code.

The arguments to do what you want would be something like `-s MODULARIZE=1 -s EXPORT_NAME="'DRACO'"` - this will put the module definition in `window.DRACO` instead of `window.Module.`

**Comment by ondys** [comment]
Thanks for the report. We will replace `Module` with something more Draco specific,

**Comment by ondys** [comment]
We have just pushed a latest update to the master branch that contains changes to the javascript API.

As suggested by @jbaicoianu , we use the `MODULARIZE` and `EXPORT_NAME` flags.
This means that the whole Draco module needs to be exported through a function `DracoModule`, this function creates an instance of the module that has to be used for all the tasks that involved `Module` in the previous version. See our example apps for more details.

Let me know if this works for you, or if there are any other issues with the integration.

**Comment by ondys** [comment]
The THREE.js example has been updated according to comments from @mrdoob . `DracoModule` is now automatically instantiated in `DRACOLoader` which should make it easier to use/integrate.

**Comment by mrdoob** [comment]
I don't think `DracoLoader` should rely on these html elements... 😇 https://github.com/mrdoob/three.js/pull/10879/commits/4d4a569a9e79d91bc98bfe514d7d5eaa2f6b7b49

**Comment by ondys** [comment]
@mrdoob We moved the logging to console and we put it behind a verbosity settings that need to be explicitly enable.

**Comment by mrdoob** [comment]
Sweet!
