### ISSUE TITLE
fs dependency not found despite installing it

### ISSUE THREAD

**Issue by duncan-vrify** [google/draco#680]
Running into this error when installing `draco3dgltf` into my Vue project. Any ideas? I've run `npm install --save fs` after receiving this to no avail and tried removing my node_modules folder and package.lock and trying to re-run `npm install` but still seeing the issue.

```
 ERROR  Failed to compile with 1 errors                                                                                       friendly-errors 15:46:57

This dependency was not found:                                                                                                friendly-errors 15:46:57
                                                                                                                              friendly-errors 15:46:57
* fs in ./node_modules/draco3dgltf/draco_encoder_gltf_nodejs.js                                                               friendly-errors 15:46:57
                                                                                                                              friendly-errors 15:46:57
To install it, you can run: npm install --save fs
```

**Comment by tomfinegan** [comment]
This seems to be a Vue.js configuration issue. Google searches for "Vue.js missing fs" yield multiple potential fixes. Flipping this to invalid as it appears to be an issue unrelated to Draco.

This might be what you need: https://stackoverflow.com/questions/48710170/vuejs-cannot-resolve-module-fs
