### ISSUE TITLE
How to encode from istream? C++

### ISSUE THREAD

**Issue by Darustc4** [google/draco#683]
I was trying to encode a .PLY file to draco with the following code:

```cpp
        std::unique_ptr<draco::PointCloud> pc;
        draco::Mesh *mesh = nullptr;

        auto maybe_mesh = draco::ReadMeshFromFile(pathFilename, false);
        if (!maybe_mesh.ok()) {
            printf("Failed loading the input mesh: %s.\n", maybe_mesh.status().error_msg());
            throw std::exception();
        }

        mesh = maybe_mesh.value().get();
        pc = std::move(maybe_mesh).value();

        // Convert compression level to speed (that 0 = slowest, 10 = fastest).
        const int speed = 10 - dracCo;

        draco::Encoder encoder;
        encoder.SetAttributeQuantization(draco::GeometryAttribute::GENERIC, dracQu);
        encoder.SetSpeedOptions(speed, speed);

        // Save to file
        int res = EncodeMeshToFile(*mesh, name, &encoder);
        if(res == -1) std::cout << "Failed DRACO !\n";
```
But this code fails when checking the ok() method saying the file cannot be read, while the draco_encoder script has no problem reading it.
So I thought a quick workaround would be to encode a stream of data instead of telling the API to open the file for me. How do you do this?

**Comment by Darustc4** [comment]
1)
I´m building draco with the following commands:
```
cd ~;git clone https://github.com/google/draco.git;cd draco
mkdir build;cd build;cmake ../ -DCMAKE_BUILD_TYPE=release;sudo make -j install
```
Then I´m linking the library in a CMakeFiles like this:
```
cmake_minimum_required(VERSION 3.1.0)
project(testCam)

set(CMAKE_CXX_FLAGS_RELEASE "-O3")

include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
if(COMPILER_SUPPORTS_CXX11)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c11")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
    elseif(COMPILER_SUPPORTS_CXX0X)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
endif()

find_package(realsense2 REQUIRED)

add_executable(testcam ./testCam.cpp ./transmitter.cpp ./testCamUtilities.hpp)
include_directories(testcam ${ADDITIONAL_INCLUDE_DIRS})

target_link_libraries(testcam realsense2::realsense2)
[... more targets]
target_link_libraries(testcam draco)
target_link_libraries(testcam pthread)

include_directories(include ${realsense_INCLUDE_DIR})
target_include_directories(testcam PRIVATE ${realsense_INCLUDE_DIR})

set_target_properties (testcam PROPERTIES FOLDER Examples)
install(TARGETS testcam RUNTIME DESTINATION ~/)
```
I´ve also tried to link dracoenc, dracodec, draco_enc and draco_dec, but so far the only that has worked out is simply draco.

As for how I import the library to use the code above:
```
#include "draco/compression/encode.h"
#include "draco/core/cycle_timer.h"
#include "draco/io/file_utils.h"
#include "draco/io/mesh_io.h"
#include "draco/io/point_cloud_io.h"
```
Basically I copy pasted all the key code in https://github.com/google/draco/blob/master/src/draco/tools/draco_encoder.cc

--------

2) What I´m referring to with the draco_encoder is one of the standalone draco encoder and encoder command line executables [ https://github.com/google/draco/tree/master/src/draco/tools ].

As a workaround of the library version of draco failing with "draco/io/file_reader_factory.cc:41 (OpenReader): No file reader able to open input." I´ve been simply telling the OS to use the precompiled executables like this:
```
std::ostringstream dracoStream;
dracoStream << "draco_encoder -qg " << dracQu << " -cl " << dracCo << " -i " << plyName << " -o " << dracoName;
exec(dracoStream.str()); // This will execute a command on the OS
````
This works no problem, but since it lets the OS handle it like a separate process it´s hard to control and has unneeded overhead I need to remove.

**Comment by tomfinegan** [comment]
@Darustc4 Does changing the target_link_libraries() call for draco to the following help?

`target_link_libraries(testcam -Wl,--whole-archive draco -Wl,--no-whole-archive)`

The linker may be stripping out the self-registering classes FileReaderFactory uses to read inputs.

**Comment by Darustc4** [comment]
You absolute savior, that worked beautifully. Thanks.

There is multiple issues open and closed related to this problem, might want to link to this thread.

**Comment by tomfinegan** [comment]
To people looking in this issue for solutions for factory reported file I/O issues, the solution in https://github.com/google/draco/issues/683#issuecomment-785360878 will not work for all compilers and platforms. For MSVC[1] this may help, if you've setup your build in the same manner as @Darustc4:

`target_link_libraries(testcam /WHOLEARCHIVE:draco)`

I don't have a way to test this right now, but the clang/gcc options shown in my earlier comment certainly will not work when building with Visual Studio compilers.

**Comment by malleshamdasari** [comment]
On Mac, I had to use `-Wl,-force_load draco` instead of `whole-archive`

This is so ridiculous, I wasted 2 hours lol for this, the linker should take care of this :man-facepalming:
