### ISSUE TITLE
Output glb contains more vertex (+48%) with draco compression

### ISSUE THREAD

**Issue by Blocovin** [google/draco#684]
Hi,

We convert [this glb file](https://fromsmash.com/uS3iV4l51U-ct) with `gltf-pipeline -i file.glb -o output.glb -b -d`
And we got problem, output glb contains more vertex (+48%) than input glb.

Input glb => 7 932 745 vertex
Output glb => 11 744 221 vertex 

Does anyone have an explanation ?

**Comment by tomfinegan** [comment]
@Blocovin Can you share the file again? The link you provided has expired.

**Comment by Blocovin** [comment]
Sorry, i uploaded [the glb file](https://fromsmash.com/uS3iV4l51U-ct) again

**Comment by Blocovin** [comment]
Sorry for the issue duplication, we found answer: https://github.com/google/draco/issues/71

Another explanation (p15) : https://tuprints.ulb.tu-darmstadt.de/14189/1/vonBuelow-2017-BA.pdf

> Draco supports compressing vertex positions, colors, normals and texture coordinates but cannot encode non-manifold meshes without losing adjacency information. The loss of adjacency information is due to the inability of the used Edgebreaker algorithm to encode non-manifold meshes. To fix this issue, Draco copies vertices and its attributes on every non-manifold edge or vertex to ensure a 2-manifold mesh.
