### ISSUE TITLE
CORS issue with gstatic

### ISSUE THREAD

**Issue by repalash** [google/draco#695]
Getting the error when including the library file from `gstatic.com` as mentioned in the Readme.
```Access to XMLHttpRequest at 'https://gstatic.com/draco/versioned/decoders/1.4.1/draco_decoder.js' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

Edit: Works when loading from `www.gstatic.com`. Maybe it should be fixed in the Readme.

**Comment by tomfinegan** [comment]
Issues such as these, unfortunately, are beyond the scope of the Draco project, and not something that the project has any ability to control. CORS policies are typically in place to protect the host and/or user from potential security issues that can arise, for example, when including resources from multiple locations on a single page. The Mozilla docs[1] explaining CORS policies are a good place to start for gaining some insight into these issues. 

Regarding a README update: I'm extremely hesitant to add information regarding CORS policy circumvention to Draco documentation. It is not something that should be done without full knowledge of the consequences, and the Draco documentation isn't really the correct place for such information.

Perhaps a brief note that when developing using a localhost based http-server that it can be easy to run afoul of CORS policies when using the gstatic hosted Draco assets would be appropriate. However, information explaining how to circumvent the policies and reconfigure your development server are well outside of the realm of what belongs in the Draco README.

I'm open to suggestions as to what would have helped in your case, but the points I've considered thus far reduce to a quick note that CORS policy related issues are a possibility when developing using localhost. Would such a note have been useful in your case?

[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

**Comment by repalash** [comment]
Hello @tomfinegan, sorry I wasn't clear in my edit. 

In my case gstatic is blocking all requests to the root domain. So, I am able to load all the links starting with `https://www.gstatic.com` not from `https://gstatic.com`. Google may have some CORS bypass with www(not sure if that
s intentional).
It seems like the link in the Readme(under 1.4.1 changelog) https://gstatic.com/draco/versioned/decoders/1.4.1/draco_decoder.js has a typo and should be replaced with `https://www.gstatic.com/draco/versioned/decoders/1.4.1/draco_decoder.js`

**Comment by tomfinegan** [comment]
Oh, I see: that's an easy enough fix. I'll update the readme.
