### ISSUE TITLE
Module._free is not a function

### ISSUE THREAD

**Issue by tianjian-sky** [google/draco#696]
Hi,

I've built an draco webasemmbly encoder and decoder according to the Building.md these days, through which I've almost followed all the steps on it, but except the last step: 

`
$ java -jar closure.jar --compilation_level SIMPLE --js draco_decoder.js --js_output_file draco_wasm_wrapper.js
`

As when running it, the terminal would prompt "Error: Unable to access jarfile closure.jar", so I ignored the final step. Meanwhile it looks fine for me that I've successfully got two .wasm files, one draco_encoder.js, and one draco_decoder.js by doing the previous building steps.

After that I tried to replace the **draco npm package**'s draco_encoder_nodejs.js and draco_decoder_nodejs.js with the newly-built draco_encoder.js, draco_decoder.js , and then re-run the gltf-pipeline -d again. 

`
 gltf-pipeline -i main.gltf -o main.draco.gltf -d
`

But unfortunately the process was interrupted with exception:

`
TypeError: Module._free is not a function
    at Object.prepare (/usr/local/lib/node_modules/gltf-pipeline/node_modules/draco3d/draco_encoder.js:1420:22)
`

And after checking the draco_encoder.js source code, I found the error was caused by the missing of Module._free function in the draco_encode.js that i'v built,  when executing ensureCache.prepare().

`
	var ensureCache = {
			buffer: 0,
			size: 0,
			pos: 0,
			temps: [],
			needed: 0,
			prepare: function() {
				if (ensureCache.needed) {
					for (var i = 0; i < ensureCache.temps.length; i++) {
						Module["_free"](ensureCache.temps[i])
					}
					ensureCache.temps.length = 0;
					Module["_free"](ensureCache.buffer);
					ensureCache.buffer = 0;
					ensureCache.size += ensureCache.needed;
					ensureCache.needed = 0
				}
				if (!ensureCache.buffer) {
					ensureCache.size += 128;
					ensureCache.buffer = Module["_malloc"](ensureCache.size);
					assert(ensureCache.buffer)
				}
				ensureCache.pos = 0
			},
                       // ...
}
`

Do you know why this will happen, and please instruct how to solve it?

**Comment by tomfinegan** [comment]
> **so I ignored the final step.**

Generally speaking it is not advisable to skip steps in developer documentation. When building open source packages that have external tool dependencies it is imperative to follow _all_ of the instructions. 

You can download the closure compiler from the Maven repository[1]. The latest release[2] should be fine. Note that the file name will not actually be closure.jar: it's typically closure-compiler-vRELEASE-DATE.jar.

I'm marking this as invalid and closing it for now-- if problems persist after completing the final step of the build, or if the build is failing, please update the issue and we can delve into this further. 

[1] https://mvnrepository.com/artifact/com.google.javascript/closure-compiler/v20210302
[2] https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v20210302/closure-compiler-v20210302.jar

**Comment by tianjian-sky** [comment]
> Hi, i've finished final step. 

And the error still happens, though the build seems to be successful. 

I've attached my testcase and build folder for your reference. 

The testcase is basing on the Readme.md, section: "Javascript Encoder API". 

When it invokes "meshBuilder.AddFacesToMesh()", an exception will be thrown out.

`
TypeError: b._free is not a function
`
Here are my make commands: 
`
export EMSCRIPTEN=/Users/yutianjian/test/emscripten-main
`
`
cmake ../ -DCMAKE_TOOLCHAIN_FILE=/Users/yutianjian/test/emscripten-main/cmake/Modules/Platform/Emscripten.cmake -DDRACO_WASM=ON
`
`
make
`
`
java -jar closure-compiler.jar --compilation_level SIMPLE --js draco_encoder.js --js_output_file draco_encoder_nodejs.js
`
`
java -jar closure-compiler.jar --compilation_level SIMPLE --js draco_decoder.js --js_output_file draco_decoder_nodejs.js
`


Testcase: 
[testcase.zip](https://github.com/google/draco/files/6233426/testcase.zip)


Build folder:
[build.zip](https://github.com/google/draco/files/6233428/build.zip)

**Comment by chrbsg** [comment]
Emscripten _free now has to be exported when compiling e.g. `emcc -s 'EXPORTED_FUNCTIONS=["_free"]'`
