### ISSUE TITLE
flutter support

### ISSUE THREAD

**Issue by wasabia** [google/draco#699]
Hi
I want load .glb on Flutter App
maybe need dart:ffi support
but i have no idea, how to build

**Comment by tomfinegan** [comment]
@wasabia Draco does not provide a C API, and Dart does not support C++ interop per https://github.com/dart-lang/sdk/issues/42210. 

From your post I am unable to determine what you're trying to do. Please provide some more information: unless I'm not understanding the original post there isn't anything I can suggest.

**Comment by wasabia** [comment]
so
if we want use draco with flutter, maybe should wrapper draco with a flutter plugin?
use java kotlin or swift call draco library

but when i try build draco to a static library for android 
the result library .a file is 50MB, maybe it is too big for an app
if i just need decoder or encoder 
so what should i do...

**Comment by tomfinegan** [comment]
$ rm -rf ./* && cmake .. && make -j
[... snip ...]

$ ls -lh libdraco.a
-rw-r-----  1 tomfinegan primarygroup 3.8M Apr 21 20:24 libdraco.a

Are you building a debug library? Github master is producing a 3.8MB library in release mode.  On my system I see 81MB in debug mode.

**Comment by wasabia** [comment]
@ tomfinegan
Hi
Thanks

another question
if i just a Function like  just decode a .glb file to .gltf file

can i just implement a simple C function call draco C++ code
then export the C function
if this can build then dart can call this through dart ffi

i know little about c & c++

**Comment by tomfinegan** [comment]
@wasabia the Draco library does not provide support for conversion of gltf to glb (or the reverse). 

It sounds like that's all that you're attempting to use the library for, and since that's not something the library is able to do I'm going to close this issue. 

If you have some other purpose in mind please update this issue, or file a new one.
