### ISSUE TITLE
big glb compressed by draco have error while litte glb works well

### ISSUE THREAD

**Issue by Yes-Jumby** [google/draco#701]
when i get a glb files ,it is too big,so i use draco to compress it ,and get the compressed glb.
but when i load compressed glb in viewer ,here is the issue :
glb viewer link:https://gltf-viewer.donmccurdy.com/
![image](https://user-images.githubusercontent.com/51182133/116043945-e4e41e00-a6a2-11eb-8b91-f89d2b7aa340.png)

here is the compressed glb model(original glb is 539.9M ,and compressed glb 9.4M,and this has error in display):
https://github.com/Yes-Jumby/MyShareData/blob/main/youa_00035_compressed.glb.zip

here is the compressed glb model(original glb is 32.4M ,and compressed glb 1.3M,and this have no error):
https://github.com/Yes-Jumby/MyShareData/blob/main/car_compressed.glb.zip

The draco setting is just same:
		GLTFDracoOptions() :
			positionQuantizationBits(14),
			texCoordsQuantizationBits(12),
			normalsQuantizationBits(10),
			genericQuantizationBits(8),
			compressionLevel(7)

I need help,plz help me:)

**Comment by Yes-Jumby** [comment]
here is the unpressed glb files:
https://ecloud.baidu.com?t=b127feb7aebb9d99dce6018c8731cdd1

**Comment by donmccurdy** [comment]
Discussed in https://discourse.threejs.org/t/glb-comprssed-by-draco-load-failed-in-viewer-based-in-three-js/25698/6 — there seems to be a problem with the MeshSmith tool used to create this model; the output is not valid.

**Comment by ondys** [comment]
The file actually seems to be ok. I was able to transcode the compressed glb to an uncompressed one using our internal tools and the result looked fine. I think the issue may be with emscripten + memory.  Until recently the limit for emscripten memory was 2GB which may not be sufficient to decode this large model (decoder uses more space than size of the raw model). I just found out this article: https://v8.dev/blog/4gb-wasm-memory and we may be able to increase the limit to 4GB which may solve the issue for this model. I'll talk to the rest of the team and we will see what we can do about it.

**Comment by tomfinegan** [comment]
The Draco project provided javascript libraries are all built with ALLOW_MEMORY_GROWTH=1. This file appears to require more memory than the browser will allow a single instance of javascript to consume even with memory growth enabled. 

Closing this as it appears there's nothing that can be done from the Draco project side to address the issue.
