### ISSUE TITLE
Error Draco_decoder_nodejs.js Magic word and Unexpected token '<'

### ISSUE THREAD

**Issue by harrymelka** [google/draco#705]
Hey,

I have an issue with my drado_decoder I don't know why but since I reinstalled my mac, I have an issue with the display of my draco file.

The error I get is 
![Screenshot 2021-04-28 at 16 52 34](https://user-images.githubusercontent.com/4755048/116425201-6aea9b00-a842-11eb-9734-6693612fdff3.png)

I have replaced my old DRACOLoader with the newest version 1.4.1 but I am getting a crazy error

![Screenshot 2021-04-28 at 16 56 12](https://user-images.githubusercontent.com/4755048/116425583-aedda000-a842-11eb-9feb-8f0829886889.png)

I am checking from the network tab to understand where does this come from and I found that I was getting html page instead of the response that I had before when It was working.

is there anyone that had this issue ?

Thank you

-----
Config

draco3d: 1.3.6
three: 0.123.0
npm: 6.11.3
node: 12.12.0

**Comment by tomfinegan** [comment]
@harrymelka This actually isn't that crazy an error. When this happens it's usually because of a version mismatch in the compilers used. The reinstall of your mac is suspicious in this case: Are you certain you're using the same versions of tools that you used previously?

**Comment by harrymelka** [comment]
Yes I am. I use the same version of everything but it still doesn't work.
I try to install it with other version of node, v14 v16 but nothing works.

I managed to find in a previous commit a package-lock.json and try to fix this issue and now it's working 

thank you for your help
