### ISSUE TITLE
Duplicate vertices after compression/decompression

### ISSUE THREAD

**Issue by alexeygroshev** [google/draco#71]
Hello,

I am experiencing the following issue with draco compression.
I compressed and decompressed an object. After decompression I got the same number of vertices, but 72227 of them (out of 3024383) were duplicates of other vertices. Is this expected?

I got the same result when I used draco_encoder/draco_decoder and draco API directly.
The compression parameters I used are: qp=14, qt=14, method=1 (edge-breaker).

The original model is available here:
https://ufile.io/dc7eb

Thanks in advance

**Comment by ondys** [comment]
This can happen for non-manifold meshes where vertices on non-manifold edges are split into two (or more vertices). This is currently needed for efficient connectivity compression. If you are using C++ API you could potentially deduplicate the attribute values using `PointCloud::DeduplicateAttributeValues()`, but we don't do that by default as it is generally not needed. The method is currently not exposed in the Javascript API but we may add it there if demend.

**Comment by alexeygroshev** [comment]
Hi Ondrej,

Thanks for the quick response. Indeed I'm using the C++ API. After I tried PointCloud::DeduplicateAttributeValues() I got rid of the duplicate vertices. Also I noticed that the number of triangles in the mesh decreased - I guess degenerate triangles were also removed.
But I noticed another problem with the new mesh. There are:
- 20 faces with equal signature
- 31 edges incident to three or more faces

Those are serious inconsistencies and it takes rather significant time to wipe them out of the mesh of this size

**Comment by ondys** [comment]
Try to run `PointCloud::DeduplicatePointIds();` after you deduplicate the attribute values, hopefully it will help to remove some of the problems. As for the "31 edges incident to three or more faces", that sounds like non-manifold edges and they can be indeed introduced because of the deduplication step. The input model didn't have these problems? (I was assuming they were in the input because of the increased number of vertices)

**Comment by alexeygroshev** [comment]
Unfortunately, `PointCloud::DeduplicatePointIds()` didn't remove any more mesh defects.
No, the input model did not have any of these problems, you can check it yourself - there is a download link in my first post
