### ISSUE TITLE
Is it possible to enable glTF and point cloud support simultaneously?

### ISSUE THREAD

**Issue by andynines** [google/draco#719]
I'm working on an application that needs to use both Draco's glTF and point cloud compression capabilities. In the CMake below, it appears that these two capabilities are mutually exclusive. Is this intentional, or is there some way to use both features at once?

https://github.com/google/draco/blob/75b82f7b68c797b4e0ff5e73ca8a81e2db3db797/cmake/draco_options.cmake#L126-L134

**Comment by tomfinegan** [comment]
I'm not really sure what you're trying to do:

- GLTF support is node only and available in the draco3dgltf npm module.
- Point cloud support is available in the draco3d npm module. 

I am not certain how an application would be able to use both simultaneously, but I know next to nothing about node development.

Regarding the C++ library: there is no GLTF support present in libdraco itself. 

I might be able to help a bit more if you provide some more information about what you're building.

**Comment by andynines** [comment]
Thanks, and sorry for the confusion. I'm working on a C++ application which statically links to a build of the Draco library that selects the CMake build option `DRACO_GLTF`. My problem was that this build didn't support point cloud compression, and I'm adding a feature to the application that needs Draco's point cloud functionalities. If I selected the `DRACO_POINT_CLOUD_COMPRESSION` option, the above CMake snippet would ignore this selection.

I've since worked around the issue by selecting the CMake build options `DRACO_MESH_COMPRESSION`, `DRACO_STANDARD_EDGEBREAKER`, and `DRACO_POINT_CLOUD_COMPRESSION`. Doing so produces a Draco library build with all of my desired functionality. But if there's no need to shut off other functionality when `DRACO_GLTF` is selected, I'd be happy to make a quick PR that reorganizes the above CMake file's logic.

**Comment by emackey** [comment]
@tomfinegan I think the fix is to move `DRACO_POINT_CLOUD_COMPRESSION` (from line 132 in the post above) outside of the `else()` clause of `if(DRACO_GLTF)` (from line 126 in the post above).

There's no need to avoid the `DRACO_POINT_CLOUD_COMPRESSION` check if `DRACO_GLTF` happens to be set, right?

**Comment by tomfinegan** [comment]
The name of the DRACO_GLTF variable is a little confusing: it's really only for the draco3dgltf npm package. A variable name change would likely help out quite a bit. I'll take care of that upstream before the next release.

Point cloud support is a default feature of the C++ library:
https://github.com/google/draco/blob/75b82f7b68c797b4e0ff5e73ca8a81e2db3db797/cmake/draco_options.cmake#L55-L56

Turning DRACO_GLTF on at build time is not something you want when building Draco for a C++ application in the current release. GLTF integration is not present in the current release of the C++ Draco library. Enabling DRACO_GLTF will result in a limited version of the Draco library that supports only what is allowed in the draco3dgltf module.

**Comment by andynines** [comment]
Thanks for the explanation! I've obtained all of my desired functionality by building Draco with no options selected. I guess this issue is resolved.
