### ISSUE TITLE
invalid vertex normal after decode

### ISSUE THREAD

**Issue by ganibc** [google/draco#72]
Hi,

I did a quick test on encode and decode. It seems the vertex normal are invalid after decoding. All normals value are uniform.

Original data:
<img width="167" alt="screen shot 2017-03-06 at 9 38 22 am" src="https://cloud.githubusercontent.com/assets/1264707/23593965/afaf3fda-0250-11e7-882b-14e437e11e21.png">
Normals:

> vn 1 -0 0
> vn 1 -0 0
> vn 1 -0 0
> vn 1 0 0
> vn 0.707107 0.707107 0
> vn 0.707107 0.707107 0
> vn -1 0 -0
> vn -1 0 -0
> vn -1 0 -0
> vn -1 0 0
> vn 0.707106 -0.707108 0
> vn 0.707106 -0.707108 0
> vn 0 0 -1
> vn 0 0 -1
> vn 0 0 -1
> vn 0 0 -1
> vn 0 0 1
> vn 0 0 1
> vn 0 0 1
> vn 0 -0 1

Then I encode it to drc. And I encode back to obj.
<img width="133" alt="screen shot 2017-03-06 at 9 39 15 am" src="https://cloud.githubusercontent.com/assets/1264707/23593973/cbd463ca-0250-11e7-8cb5-568e29fbdd33.png">

> vn 1.000000 0.000000 0.000000
> vn 1.000000 0.000000 0.000000
> vn 1.000000 0.000000 0.000000
> vn 1.000000 0.000000 0.000000
> vn 1.000000 0.000000 0.000000
> vn 1.000000 0.000000 0.000000
> vn 1.000000 0.000000 0.000000
> vn 1.000000 0.000000 0.000000

Where should I look to fix this issue?
Thanks.

**Comment by ondys** [comment]
Can you please post the input .obj? It's hard to tell what went wrong by looking at the normals only.

**Comment by ganibc** [comment]
Attached is the obj file. I renamed it to .txt so I can attach it here.
[Simple.txt](https://github.com/google/draco/files/820164/Simple.txt)

**Comment by ondys** [comment]
The problem with the .obj is that the normal are not attached to the vertices.

e.g. the first face is defined as:
```
f 1 2 3
```

to use normals they need to be assigned to the faces as well, e.g. :
```
f 1//1 2//1 3//1
```
Here all corners on the face would use the same normal value.

See more on [wiki](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Vertex_Normal_Indices_Without_Texture_Coordinate_Indices)

**Comment by ganibc** [comment]
Ah, yes. That's correct. Thanks.
