### ISSUE TITLE
THREE.DRACOLoader: Decoding failed: Unknown minor version

### ISSUE THREAD

**Issue by liujiling1** [google/draco#725]
Uncaught (in promise) Error: THREE.DRACOLoader: Decoding failed: Unknown minor version.
    at THREE.DRACOLoader.convertDracoGeometryTo3JS (DRACOLoader.js:262)
    at THREE.DRACOLoader.decodeDracoFileInternal (DRACOLoader.js:144)
    at DRACOLoader.js:113

**Comment by tomfinegan** [comment]
Are you able to share the file that is causing this error?

**Comment by liujiling1** [comment]
ok

[g11.zip](https://github.com/google/draco/files/6827223/g11.zip)
