### ISSUE TITLE
Mac catalyst support 

### ISSUE THREAD

**Issue by PrashantKT** [google/draco#727]
I am not able to use this in Mac catalyst app , Is there any workaround

**Comment by tomfinegan** [comment]
@PrashantKT We'll need more information about what you're trying to do:

- What have you attempted?
- What error messages are appearing?

Draco is not an ipad application, but the library is usable on iOS devices when built and configured to run on them.

**Comment by tomfinegan** [comment]
Note that Draco and its examples run natively on Apple desktop and mobile devices-- according to its site Catalyst allows developers to "Create a version of your iPad app that users can run on a Mac device."

You would need to configure your project to use the native Draco library. Our team is not familiar with Catalyst-- you need to consult Apple's docs to learn how to integrate a third party library into your application when using Catalyst.
