### ISSUE TITLE
How to use this in iOS

### ISSUE THREAD

**Issue by PrashantKT** [google/draco#728]
It seems very silly but I am not able to find how to use in iOS 

I have generated the files from the command from the doc, So now I have **libdraco.a** , But I don't have any idea how to use this in to  the my  app , 

If any one have any sample app or any suggestion it would be great help 

Thanks in advance

**Comment by tomfinegan** [comment]
@PrashantKT the directions for building Draco in iOS configurations can be found in our BUILDING.md:
https://github.com/google/draco/blob/master/BUILDING.md#ios-builds

As noted at the end of the section you can use lipo to merge the target specific libraries into one fat library that includes all necessary targets. You would then add that library to your project and consult the example tools (draco_decoder and draco_encoder) to learn how to use the library in your own code.

**Comment by dganzella** [comment]
@tomfinegan I have the same issue . I was able to build the draco_encoder binary, but then how do I use it? shouldn it also come with a header file together?
