### ISSUE TITLE
Pointcloud Compression Very Slow for 64-bit-Timestamps

### ISSUE THREAD

**Issue by DecentBumpkin** [google/draco#730]
Dear Sir or Madam,

Hi, we have a point cloud, each point has its corresponding unix timestamps, so it is a uint64_t integer, and for those 131072 points there are roughly only 2048 to 2060 unique timestamps, some points sharing same stamp. 

We tried compressing an GENERIC attribute of uint64_t but turns out it is not compressed at all, the size increase is 8 bytes x 131072 = 1MB after adding timestamp, we realized that deduplication probably does not work for 64 bit unsigned integer attribute, and then we switched to a pair of uint32_t integers, still a GENERIC attribute, now the size is compressed, we are sure that deduplication happens for encoding, but the speed is super slow. It turns out in shannon entropy calculation a std::vector is resized "max_value" of reinterpret_casted uint32_t "symbols", which is potentially a very large number(e.g. 1256009119), iterating over such a large and mostly empty vector is slow. And that "max_value" becomes larger if the number of unique timestamps is smaller(the worst case happens for a cloud where 95% of points have timestamp of an uninitialized 0, and only 96 unique nonzero valid timestamps), and your computed "num_unique_symbols" is 24 in this case, out of a 1256009119-long vector. We have to change the std::vector<int> to unordered_map<uint32_t, int>. But this solution is very slow for compressing POSITION attribute, or other reasonably small vector (<100k elements?). Do you have any recommendations for our use case. 

Thank you very much.

**Comment by ondys** [comment]
As you noted, 64 bit integers are currently not supported for point cloud encoding. As for the speed of ComputeShannonEntropy, you may try to use an additional vector to store the unique values in the first loop:
```
  std::vector<int> symbol_frequencies(max_value + 1, 0);
  std::vector<int> unique_symbols;
  for (int i = 0; i < num_symbols; ++i) {
    if(symbol_frequencies[symbols[i]] == 0) {
      unique_symbols.push_back(symbols[i]);
    }
    ++symbol_frequencies[symbols[i]];
  }
```
the second loop can then be:
```
for (int i = 0; i < unique_symbols.size(); ++i) {
  int symbol_index = unique_symbols[i];
  // Compute required number of bits... 
}
```

This should work reasonably fast for both timestamps and positions with the cost of some extra memory.

**Comment by tomfinegan** [comment]
Closed due to inactivity. Please update this issue or file a new one if this topic requires further discussion.
