### ISSUE TITLE
Tests don't build: FATALgoogletest must be a sibling directory

### ISSUE THREAD

**Issue by yurivict** [google/draco#731]
I already have the package ```googletest-1.11.0``` installed, but tests expect googletest to be in a sibling directory?

Why ```googletest``` package isn't sufficient?

**Comment by tomfinegan** [comment]
As the error message states: googletest must be a sibling directory of draco for the test build to succeed. The build script looks in one place, and if the source is not there an error is reported. Draco can be built without DRACO_TESTS enabled if you are, for whatever reason, unable to put googletest in a sibling directory.

**Comment by yurivict** [comment]
Why do you need googletest sources when the package is available?
Is package not usable and sources are required instead?

**Comment by tomfinegan** [comment]
It's simply how the CMake build locates the sources. If you'd like it to work differently I'd be happy to review a PR.
