### ISSUE TITLE
Sub-object index lost on decompression

### ISSUE THREAD

**Issue by rvkennedy** [google/draco#733]
I am using C++ on both ends to compress, and decompress a mesh. Following the obj_decoder and obj_encoder code in the absence of any specific documentation, I encode sub-object information per-index as a uint32:

		draco::GeometryAttribute subObjectGeometryAttribute;
		subObjectGeometryAttribute.Init(draco::GeometryAttribute::GENERIC, nullptr, 1, draco::DT_UINT32, false, 4, 0);
		const int sub_obj_att_id_ = dracoMesh.AddAttribute(subObjectGeometryAttribute, false, numSubObjects);
		draco::PointAttribute* subObjectAttribute = dracoMesh.attribute(sub_obj_att_id_);
		compressedMesh.subMeshAttributeIndex= sub_obj_att_id_;
		for (uint32_t i=0;i<numSubObjects;i++)
		{
			const draco::AttributeValueIndex attributeValueIndex(i);
			subObjectAttribute->SetAttributeValue(attributeValueIndex,&i);
		}
		// Now assign the material index to points:
		int face_index = 0;
		uint32_t sub_obj_id_=0;
		for(const auto& primitive:sourceMesh.primitiveArrays)
		{
			const avs::Accessor& indicesAccessor = sourceMesh.accessors[primitive.indices_accessor];
			for(size_t i=0;i< indicesAccessor.count;i++)
			{
				const draco::PointIndex vert_id(face_index);
				subObjectAttribute->SetPointMapEntry(vert_id, draco::AttributeValueIndex(sub_obj_id_));
				face_index++;
			}
			sub_obj_id_++;
		}

On the decompression side, I do this to recover the sub-object index:

		for(uint32_t j=0;j<numFaces;j++)
		{
			const draco::Mesh::Face& face = dracoMesh.face(draco::FaceIndex(j));
			if (dracoSubMeshAttribute)
			{
				auto pointIndex = draco::PointIndex(face[0]);
				const draco::AttributeValueIndex submesh_index = dracoSubMeshAttribute->mapped_index(pointIndex);
				uint32_t submesh = 0;
				if (!dracoSubMeshAttribute->ConvertValue<uint32_t>(submesh_index, &submesh))
				{
					continue;
				}`

But submesh is always zero. I never get a nonzero value from this (although submesh_index has a wide range of values).
What is the intended method of encoding sub-object information? Why does the above not work to recover the value I encoded?

**Comment by ondys** [comment]
Since I can't really run the above code, I could only guess but some parts looks somehow suspicious. E.g.:
```
                         const draco::PointIndex vert_id(face_index);
			subObjectAttribute->SetPointMapEntry(vert_id, draco::AttributeValueIndex(sub_obj_id_));
```
In general converting face index into a point index is really not correct. To get a point index on a face one would have to do something like:
```
                         PointIndex pi = mesh->face(face_index)[0];   // Point index on the first corner of the face.
```
Note that each face has 3 corners and three different points so the value should be mapped to all three corners.

**Comment by tomfinegan** [comment]
Closed due to inactivity. Please update the issue or file a new one if further discussion is needed.
