### ISSUE TITLE
how to build draco shared lib

### ISSUE THREAD

**Issue by xiazhibin** [google/draco#739]
I use cmake to build draco and linked to a target lib, but it fails
```
add_library(example SHARED ${LIB_SOURCE_FILES})
````

```
# DRACO
ExternalProject_Add(Draco
  GIT_REPOSITORY https://github.com/google/draco.git
  GIT_TAG 1.3.4
  PREFIX draco
  INSTALL_DIR
  CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
        -DBUILD_FOR_GLTF=1
        -DBUILD_SHARED_LIBS=1
  UPDATE_DISCONNECTED 1
)
```

```
/usr/bin/ld: draco/lib/libdracoenc.a(point_attribute.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
draco/lib/libdracoenc.a: error adding symbols: Bad value

```

**Comment by tomfinegan** [comment]
The primary issue here is that you're using a very old version of Draco. This should "just work" in the current repository HEAD (and in 1.4.x).  I'm not certain what you're doing, but v1.3.4 is from August of 2018. That's ancient in Draco terms.

Explicitly enabling PIC would be the next step if you must use the 1.3.4 release:

https://cmake.org/cmake/help/latest/variable/CMAKE_POSITION_INDEPENDENT_CODE.html#variable:CMAKE_POSITION_INDEPENDENT_CODE

Add `-DCMAKE_POSITION_INDEPENDENT_CODE=1` to your `CMAKE_ARGS`. 

The shared library build was not well supported when 1.3.4 was released. I'm not certain that this error will be the only issue that needs to be addressed.

**Comment by xiazhibin** [comment]
@tomfinegan thanks!! shareobj is work on 1.3.4
I link `.a` but not `.so` file, so I make this mistake.
