### ISSUE TITLE
v1/decoders started throwing RuntimeError

### ISSUE THREAD

**Issue by ffdead** [google/draco#751]
Hello, an existing project started breaking since yesterday with the following error:

```
failed to asynchronously prepare wasm: TypeError: WebAssembly.instantiate(): Import #0 module="env" error: module is not 
an object or function
```
```
RuntimeError: abort(TypeError: import object field 'env' is not an Object). Build with -s ASSERTIONS=1 for more info.
```

Website: https://www.pluto.app/
No code changes have been made in the last 3 months. 

Experienced in:
* Chrome version 94.0.4606.81 (Official Build) (x86_64) 
* Firefox version 92.0 (64-bit)
* macOS Catalina version 10.15.7

Files affected:
https://www.gstatic.com/draco/v1/decoders/draco_wasm_wrapper.js
https://www.gstatic.com/draco/v1/decoders/draco_decoder.wasm

**Comment by tomfinegan** [comment]
@ffdead Should this repro by simply launching the site? It seems to be working at present. I have the same version of Chrome that you've reported.

Issues like this is why for the last few releases we've recommended using the versioned URLs. There was a release on Tuesday and the situation you're seeing could be caused by delayed gstatic propagation and/or edge caching, which only effects the unversioned (aka v1/decoders) URLs. 

To go back to the last release update your site to pull the files from 1.4.2. The filenames are the same, but they live here:
https://www.gstatic.com/draco/versioned/decoders/1.4.2/

To use the latest release:
https://www.gstatic.com/draco/versioned/decoders/1.4.3/

**Comment by donmccurdy** [comment]
> During QA of this project we had to disable draco for safari/iOS because the threejs loader would get stuck for some reason. Not sure if you ever heard that happening before?

I've heard a few reports similar to this from three.js users, but most of those reports have not been reproducible on my iOS devices. If you have examples to share please feel free to file an issue on three.js as well. One exception would be https://github.com/mrdoob/three.js/issues/22445 – using multiple DRACOLoader instances at the same time may cause issues (in addition to allocating more Web Workers than is good for performance and memory) so it's better to reuse the same DRACOLoader instance or dispose of old ones.

> Is there a likely reason why "old" models should break with the new version. Mostly wondering how to sync up blender export versions with the correct draco wasm.


Also see https://github.com/google/draco/issues/717 – I'm not quite sure what the relationship between normal Draco builds and "gltf" Draco builds is, or whether it matters for most users.

**Comment by driescroons** [comment]
Same issue here, but on windows. I was thinking about setting up a repo, but figured that the pmndrs market was probably having the same issue:
https://market.pmnd.rs/model/zombie-car

@donmccurdy does the model load on your device?

**Comment by ffdead** [comment]
I'm happy to report that this error has magically fixed itself, we haven't changed the website code and now the models load again 🤷 

> > During QA of this project we had to disable draco for safari/iOS because the threejs loader would get stuck for some reason. Not sure if you ever heard that happening before?
> 
> I've heard a few reports similar to this from three.js users, but most of those reports have not been reproducible on my iOS devices. If you have examples to share please feel free to file an issue on three.js as well. One exception would be [mrdoob/three.js#22445](https://github.com/mrdoob/three.js/issues/22445) – using multiple DRACOLoader instances at the same time may cause issues (in addition to allocating more Web Workers than is good for performance and memory) so it's better to reuse the same DRACOLoader instance or dispose of old ones.

@donmccurdy I keep running into this problem so I'll try to make something reproducible and share

**Comment by ffdead** [comment]
> mrdoob/three.js#22445

Actually, maybe this is related. We use `useGLTF` from `drei`, could it be that it creates a new DRACOLOader instance everytime we use the hook? https://github.com/pmndrs/drei/blob/master/src/core/useGLTF.tsx

**Comment by donmccurdy** [comment]
I've just started seeing a similar issue again. Filed a new issue at https://github.com/google/draco/issues/819.

**Comment by tomfinegan** [comment]
I suspect this is the same situation as previously: use the pinned decoders to avoid the issue.

Is this problem happening on pages pinned to the new releases?

**Comment by donmccurdy** [comment]
Not seeing the issue for pages pinned to specific releases — agreed it's likely the same cause.
