### ISSUE TITLE
generic data gets lost after compression and decompression

### ISSUE THREAD

**Issue by libing64** [google/draco#757]
```
./draco_encoder -point_cloud -i ../testdata/bun_zipper.ply

./draco_decoder -point_cloud -i ../testdata/bun_zipper.ply.drc 
```
After compression and decompression, property 'confidence' and 'intensity' in bun_zipper.ply gets lost.
How to compress and decompress these generic data like 'confidence'?

**Comment by ondys** [comment]
Our PlyDecoder doesn't read generic data from PLY (it only supports positions, normals and colors). We don't have any immediate plans to add support for generic data for PLY but we are open to community contributions.

**Comment by libing64** [comment]
@ondys Great thanks for your reply.
