### ISSUE TITLE
Incorrect install paths

### ISSUE THREAD

**Issue by jansol** [google/draco#764]
When given an absolute path for e.g. `CMAKE_INSTALL_LIBDIR`, cmake does NOT prepend `CMAKE_INSTALL_PREFIX`, that is only done for relative paths (see [the CMake manual](https://cmake.org/cmake/help/latest/command/install.html))

However path wrangling in `draco_install.cmake` always unconditionally prepends the prefix, leading to broken installs e.g. on [NixOS](https://github.com/NixOS/nixpkgs/pull/143782). Nix always passes absolute paths to cmake for the specific install directories, as they may have different prefixes in order to split large packages into smaller ones (such as having a separate package for documentation or data files).

**Comment by tomfinegan** [comment]
> When given an absolute path for e.g. CMAKE_INSTALL_LIBDIR, cmake does NOT prepend CMAKE_INSTALL_PREFIX, that > is only done for relative paths (see the CMake manual)

Can you cite the section of the manual that you're referring to? I took a quick look over the script, and just reread the CMAKE_INSTALL_PREFIX documentation. There is no mention of behavioral changes relating to absolute paths. The GNUInstallDirs documentation is pretty clear that CMAKE_INSTALL_LIBDIR is not absolute and is built using CMAKE_INSTALL_PREFIX. CMAKE_INSTALL_FULL_LIBDIR is absolute, but the CMAKE_INSTALL_LIBDIR is not. Specifying an absolute path as the value of that variable appears incorrect by my reading. 

The CMake install() code in Draco is ancient, and I see from looking at the documentation that things have changed, but the problem you're having downstream is clearly related to the behavior of Nix, which is not typical:

> Nix always passes absolute paths to cmake for the specific install directories.

CMAKE_INSTALL_LIBDIR, according to CMake docs, is a relative path ([GNUInstallDirs doc](https://cmake.org/cmake/help/v3.22/module/GNUInstallDirs.html)):

> CMAKE_INSTALL_\<dir\>

> Destination for files of a given type. This value may be passed to the DESTINATION options of install() commands for the 
> corresponding file type. It should typically be a path relative to the installation prefix so that it can be converted to an 
> absolute path in a relocatable way (see CMAKE_INSTALL_FULL_\<dir\>). However, an absolute path is also allowed.

**Comment by jansol** [comment]
My bad, the part I was thinking of is about the destination parameter to `install()` and it is described right in the intro section of [the page I linked](https://cmake.org/cmake/help/latest/command/install.html#introduction):

> If a relative path is given it is interpreted relative to the value of the CMAKE_INSTALL_PREFIX variable. The prefix can be relocated at install time using the DESTDIR mechanism explained in the CMAKE_INSTALL_PREFIX variable documentation.
>
> If an absolute path (with a leading slash or drive letter) is given it is used verbatim.

Draco is explicitly prepending the prefix to all of the paths, i.e.:
```
install(TARGETS draco_decoder DESTINATION "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_BINDIR}")
```
Whereas the same result would be obtained with simply:
```
install(TARGETS draco_decoder DESTINATION "${CMAKE_INSTALL_BINDIR}")
```

...except in the case where `CMAKE_INSTALL_BINDIR` is an absolute path, like with Nix, where the latter would also work the way it is intended. Not sure what the best way to generate the paths for the pkg-config and cmake config files is, though.

**Comment by tomfinegan** [comment]
@jansol Thank you for the PR. I haven't had a chance to look it over yet, but we'll try to get this pulled in for the next release.
