### ISSUE TITLE
Unknown geometry type when loading drc model via a URL

### ISSUE THREAD

**Issue by HAZARDU5** [google/draco#77]
I'm having an issue when I use `DRACOLoader.load()` to load a drc model from a URL. For some reason it finishes loading and attempts to run `DRACOLoader.decodeDracoFile()` against the blob data from the `bunny.drc` example, however the `geometryType` is not valid, so it throws a `THREE.DRACOLoader: Unknown geometry type` error.

See here: https://hazardu5.github.io/aframe-workshop/examples/07/finish/

Loading the drc via the `FileReader` class and `DRACOLoader.decodeDracoFile()` method in the [webgl_loader_draco.html](https://github.com/google/draco/blob/master/javascript/example/webgl_loader_draco.html) example works as expected. Using this example I can also load another OBJ file converted to DRC via the command line tool without issue (see https://hazardu5.github.io/aframe-workshop/examples/07/draco-example/)

Just wondering if there's some additional conversion that needs to happen to the model blob data before it gets processed by `DRACOLoader`?

**Comment by ondys** [comment]
I'm not sure if I understand your example correctly, but by looking at the console log, it seems that `data.src` is just the asset name / path (`assets/drc/bunny.drc`) and not the binary data itself (which is expected by  `DRACOLoader.decodeDracoFile()`)

**Comment by HAZARDU5** [comment]
Yeah so `data.src` (the URL) gets passed to `DRACOLoader.load()` which accepts a URL and loads the model from that URL and extracts the data from it, passing it to `DRACOLoader.decodeDracoFile()` which decodes it. I can see from the network activity that the file is definitely loaded from the URL, but it has the issue I've outlined above during `DRACOLoader.decodeDracoFile()`.

**Comment by ondys** [comment]
I indeed overlooked that, sorry for the confusion.

Nevertheless, I tried it with the `DRACOLoader.load()` method and I still couldn't reproduce the problem. What I did was actually a modification of our example where I used your asset path for testing, i.e.:

```
dracoLoader.load("https://hazardu5.github.io/aframe-workshop/examples/07/finish/assets/drc/bunny.drc", .....
```

This worked fine and loaded the model without any issues. If you hard-code the link in your code to the one above, do you still encounter the problem?

**Comment by HAZARDU5** [comment]
That works as expected with the hard-coded URL. I'll see if I can code a workaround to automatically detect relative paths and prepend the full URL to them so it works correctly.

**Comment by ondys** [comment]
ok, I'm glad that the full URL worked. Internally, the `DRACOLoader.load()` uses `THREE.FileLoader` that I'm not really familiar with, but you may ask people from THREE.js community why the relative URL did not work.

**Comment by HAZARDU5** [comment]
Cool I'll look into it. Closing this issue for now.
