### ISSUE TITLE
C++ loading decoded mesh vertices and indices

### ISSUE THREAD

**Issue by Leadwerks** [google/draco#771]
I'm having some trouble retrieving the vertex and indice data from a decoded mesh. The triangles don't seem to be using the right indices. They're not just flipped, they look like the wrong values. The loaded model was exported from Blender and reloads in Blender with no issues:

![oof](https://user-images.githubusercontent.com/108503/142256127-5e326063-4275-49cb-9f2e-8fc1d28415ff.jpg)

I think I have a misunderstanding of how to get the mesh data out of the draco::Mesh class:
```
Vec4 vector;
int tris = dmesh.value()->num_faces();
int verts = dmesh.value()->num_points();
mesh->vertices.resize(verts);
mesh->indices.reserve(tris*3);

//Load vertex positions
auto attr = dmesh.value()->GetNamedAttribute(draco::GeometryAttribute::POSITION);
if (attr == NULL) return false;
switch (attr->data_type())
{
case draco::DataType::DT_FLOAT32:
	if (attr->num_components() != 3)
	{
		Print("Error: Invalid number of components in compressed mesh position attribute");
		return false;
	}
	if (attr->byte_stride() > 16)
	{
		Print("Error: Attribute byte stride is too long");
		return false;
	}
	for (int v = 0; v < verts; v++)
	{
		attr->GetValue(draco::AttributeValueIndex(v), &vector.x);
		mesh->vertices[v].position.x = vector.x;
		mesh->vertices[v].position.y = vector.y;
		mesh->vertices[v].position.z = vector.z;
	}
	break;
default:
	Print("Error: Invalid data type in compressed mesh position attribute");
	return false;
	break;
}

//Load triangle indices
for (int t = 0; t < tris; ++t)
{
	mesh->indices.push_back(dmesh.value()->face(draco::FaceIndex(t))[0].value());
	mesh->indices.push_back(dmesh.value()->face(draco::FaceIndex(t))[1].value());
	mesh->indices.push_back(dmesh.value()->face(draco::FaceIndex(t))[2].value());
}
```

**Comment by ondys** [comment]
There is a difference between PointIndex and AttributeValueIndex. .. in general attribute value indices are used for unique values for a given attribute while point indices identify unique "points" or vertices of the mesh (e.g. a single spatial vertex can have multiple points when two or more corners attached to the vertex have different UV values).

Assuming you want to share the indices for all attributes (not only positions) a proper way to initialize the position for vertices would be:
```
        for (int v = 0; v < verts; v++)
	{
		attr->GetMappedValue(draco::PointIndex(v), &vector.x);
		mesh->vertices[v].position.x = vector.x;
		mesh->vertices[v].position.y = vector.y;
		mesh->vertices[v].position.z = vector.z;
	}
```

**Comment by Leadwerks** [comment]
Great, thank you. I was able to load this into our glTF loader and saver in one day.
