### ISSUE TITLE
Can Draco be Used for Dynamic Point Cloud objects Compression 

### ISSUE THREAD

**Issue by yaseenit** [google/draco#772]
I am not sure if Draco can compress dynamic point cloud objects, i.e. a streaming point cloud.  All the examples there target one static object. What if we need to compress a sequence of objects, for example, compress 3D LiDAR sensor streaming? There are some protocols from [MPEG-PCC](https://mpeg-pcc.org/index.php/software/), However, because of the lightweight and high performance of Darco, I would like to test it when compressing a streaming point cloud. I would appreciate any information you can provide.

**Comment by ondys** [comment]
Draco point cloud compression is designed for static point clouds. That being said, animated point clouds can be stored for example by using one dimension to represent time (Draco can handle points with an arbitrary number of dimensions). It wouldn't really work well for true streaming point clouds though (in which case separate time stamps would have to be encoded independently, loosing any benefit from temporal compression).
