### ISSUE TITLE
Add stl file format support to Draco.

### ISSUE THREAD

**Issue by yodew** [google/draco#773]

**Comment by yodew** [comment]
I need compress stl to drc,  but draco's command failed.  the error info is 
`Failed loading the input mesh: Error decoding input..`

so draco can support stl?  or someone can help me or give one tool to solve?   I coding by Python, so can use python tools or c++ tools

thanks

**Comment by ondys** [comment]
STL files are currently not supported by Draco. You would need to write a custom decoder to convert the STL to `draco::Mesh`

**Comment by yodew** [comment]
> STL files are currently not supported by Draco. You would need to write a custom decoder to convert the STL to `draco::Mesh`

will stl can be supported in the feature?

**Comment by yodew** [comment]
now I convert stl to ply by vtk, then compress to drc

**Comment by guneshmunjal** [comment]
@tomfinegan you have to write the code in c++
it will work.
make a repository of what you have made changes in the code i will see to it

**Comment by tomfinegan** [comment]
> make a repository of what you have made changes in the code i will see to it

I am not sure what you mean. 

I have done no work on this feature, and have no plans to at present. If someone were interested in adding the support to Draco I would be happy to look over a design, and review the code and additional tests, but at present this is merely a feature request marked as "help wanted".
