### ISSUE TITLE
How to encode and decode quantized meshes?

### ISSUE THREAD

**Issue by chaohuang** [google/draco#789]
I want to use Draco to encode and decode meshes that are already quantized, but just setting -qp=0 and -qt=0 doesn’t seem to work; Draco treats the integer values of positions and texture coordinates as floating points (please correct me if that’s not the case) and the resulting .drc files are quite large.

So is there a way for Draco to directly use the input positions and texture coordinates as quantized values and encode and decode them without the quantization step inside Draco?

Thanks.

**Comment by ondys** [comment]
I believe Draco can load .ply with integer coordinates. In that case, no quantization settings should be needed and the pre-quantized values would be compressed directly. If your input is .obj, Draco indeed treats the input values as floats which is expected by most users. You can potentially use C++ API directly where you can specify the data type of each attribute, but you would most likely have to still write your custom format loader.
