### ISSUE TITLE
MeshAttributeElementType information loss during encoding/decoding

### ISSUE THREAD

**Issue by neonglb** [google/draco#792]
I'm trying to add generic attributes with `MeshAttributeElementType` values different from `MESH_CORNER_ATTRIBUTE` (e.g. `MESH_FACE_ATTRIBUTE` ) via `mesh->SetAttributeElementType()`. I've noticed that this custom information seems to get lost either already during encoding or decoding. After writing and reading a mesh the element type of any attribute returned by `mesh->GetAttributeElementType()` is set to `MESH_CORNER_ATTRIBUTE`. Could this be related to a wrong encoder/decoder config?

**Comment by ondys** [comment]
As far as I can tell, the information is not really encoded, therefore not preserved during compression. It should be possible to reconstruct it after the decoding by going through all faces and checking if decoded attribute values are same for all corners of each face. If that's true for all faces, the type can be set to MESH_FACE_ATTRIBUTE.
