### ISSUE TITLE
Output drc file size 

### ISSUE THREAD

**Issue by Constantin2106** [google/draco#804]
Hi,

I use the draco encoder for CAD files.
Today I faced a problem that I can't explain. I used a mesh encoder for stl files and encoding parameters: quantization level = 26, and compression level = 3,4,5,7,9. As I expected, the largest file size was obtained with compression level = 3, size for compression level = 9 was smaller that for compression level = 3. But for some reason the smallest size was for compression level = 5, and not 9. The difference was up to 2 times. Could you explain this strange result in my opinion?

Thanks in advance

**Comment by ondys** [comment]
With cl=5 the encoder is using slightly different method for compressing connectivity. It in general works worse than the method used for higher compression levels but it is possible it performs better for your specific geometry. One possible suspect would be meshes that have highly irregular triangulations (e.g. a lot of vertices with high valences).
