### ISSUE TITLE
How does Draco handle the same vertex with different texture coordinates?

### ISSUE THREAD

**Issue by liqingzhaomingcheng** [google/draco#820]
I mean, if a vertex has two different texture coordinates, how does Draco determine the original connectivity between the two texture coordinates since it encodes the connectivity by vertex position.I'm sorry to bring this up, because I don't really understand how the code works.

**Comment by ondys** [comment]
In general, the base connectivity is encoded based on the position attribute  (vertex positions). Other attributes then can have different connectivities that are encoded as differences from the base "position" connectivity. Essentially the encoder encodes them as "seams" on the base connectivity (at most 1 bit per edge but it can be reduced a lot if the seams are infrequent). These seams are then used to decode attribute values for the specific attribute.

**Comment by liqingzhaomingcheng** [comment]
Thanks for your quick response. So draco encodes these "seams" at the encoder and then reconstructs the connectivity of attributes at the decoder. According to my understanding, for example, after decoding the connectivity of texture coordinates, should there be a corner table to generate its indices_map_, or it shares a corner table with position?

**Comment by ondys** [comment]
The other attributes use `MeshAttributeCornerTable` . It uses the base `CornerTable` from positions underneath but it also stores the "seams" that are used to modify calls to many of the corner table methods such as `Opposite()`, etc..

**Comment by liqingzhaomingcheng** [comment]
Got it, thank you very much!
