### ISSUE TITLE
Draco_transcoder_supported failed to generate

### ISSUE THREAD

**Issue by mqsnq996** [google/draco#827]
When I use CmakeGUI to generate draco_transcoder_supported, the warning "Error in configuration process, project files may be invalid" pops up, and the specific error message is: third_party/eigen/Eigen missing, run git submodule update --init
Call Stack (most recent call first)

**Comment by tomfinegan** [comment]
Have you tried doing as instructed by the error message? You cannot build Draco with DRACO_TRANSCODER_SUPPORTED enabled without Eigen. (or gulrak/filesystem, or TinyGLTF for that matter). There are instructions covering this in README.md and BUILDING.md.

I cannot provide assistance with use of the CMake GUI. I have no familiarity with it, and it is not necessary for configuration of Draco. At least as it comes to Draco, I strongly suggest avoiding the GUI and learning the 2 commands necessary to configure Draco in a terminal/command prompt:

1) Configure:
cmake <PATH TO DRACO HERE> <ARGS HERE>
i.e.
cmake /src/draco -DDRACO_TRANSCODER_SUPPORTED=ON

2) Build:
(FROM THE SAME DIRECTORY AS ABOVE)
cmake --build .

**Comment by mqsnq996** [comment]
Thanks, as a front-end programmer, I'm not familiar with how cpp projects are built, I'm trying to configure some eigen environments, hope it helps.
