### ISSUE TITLE
v1.5.2 not available on gstatic?

### ISSUE THREAD

**Issue by Ben-Mack** [google/draco#831]
These url return 404 not found, seem like v1.5.2 is not published to gstatic.
https://www.gstatic.com/draco/versioned/decoders/1.5.2/draco_decoder.js
https://www.gstatic.com/draco/versioned/decoders/1.5.2/with_asserts/draco_decoder.js

**Comment by tomfinegan** [comment]
Fixed the issue. The URLs for the versioned files should now work.
