### ISSUE TITLE
The  UV error  about texture

### ISSUE THREAD

**Issue by openforus** [google/draco#86]
when I load  texture and add material to model use draco_mesh_decoder.js ,the result as shown below the  texture's uv  in disorder.
the previous version which not Separate mesh and pointcloud is ok。

![image](https://cloud.githubusercontent.com/assets/18387798/24443159/0a64ab5e-1494-11e7-9ca0-57f950bff73d.png)

**Comment by openforus** [comment]
I've tested The current version you had Commited on Mar 29, 2017,also  have the some problem.

the old  version  not Handle Square but it's uv and texture is right（Very sorry  the upload slowly so give the link ）
 http://pan.baidu.com/s/1c1UbdG8
  
![Uploading cowtrue.jpg…]()

the latest version   , it's uv and texture is wrong
 http://pan.baidu.com/s/1kUAPWIN
 
![Uploading cowfalse.jpg…]()

the below is a cow model
 http://pan.baidu.com/s/1slvuViH

**Comment by ondys** [comment]
Can you try it with the latest javascript decoders that were just pushed to the master branch? Thanks!

**Comment by openforus** [comment]
ondys,
I have tried the latest javascript，it's uv is right now ,Thanks!
