### ISSUE TITLE
The vertex and index ordering is getting changed after decompression.

### ISSUE THREAD

**Issue by swomack** [google/draco#87]
So, i have a set of triangles (vertices and indices) which i have compressed with draco (by creating `draco::mesh` from those vertices and indices). I didn't remove any vertices or indices because at client side i want same amount of vertices and indices. My problem is, the vertex and index ordering is completely changed when i decompress it at the client side. 

Is it possible to compress it without changing the order?

**Comment by ondys** [comment]
You can try using sequential encoding method that preserves order of indices/faces.

`SetEncodingMethod(options, MESH_SEQUENTIAL_ENCODING);`'

Compression ratio is going to be significantly worse though. Our main focus has been so far on lossy compression that does not preserve order of points, which allows us to achieve biggest compression gains.
