### ISSUE TITLE
C++ API configs for lossless compression

### ISSUE THREAD

**Issue by zanazakaryaie** [google/draco#878]
Reading previous issues here, I found that the key config to achieve lossless compression is to set quantization to 0. So I use the following c++ code:

`
encoder.SetAttributeQuantization(draco::GeometryAttribute::POSITION, 0);
encoder.SetAttributeQuantization(draco::GeometryAttribute::NORMAL, 0);     encoder.SetAttributeQuantization(draco::GeometryAttribute::GENERIC, 0);      encoder.SetAttributeQuantization(draco::GeometryAttribute::TEX_COORD, 0);
encoder.SetSpeedOptions(0, 0);
`

Are there any other configs that I should set to make sure I will get a lossless compression? What about `encoder.SetEncodingMethod(draco::MESH_SEQUENTIAL_ENCODING);`? Can I use `MESH_EDGEBREAKER_ENCODING`? The latter gives me a smaller file size. It was mentioned somewhere that it has nothing to do with lossy or lossless compression. It's just about reordering the points and faces.

**Comment by ondys** [comment]
It depends how you define lossless compression. Turning off quantization ensures that the attribute values (positions, normals, etc) don't change (lossless). Edgebreaker vs sequential encoding mostly affects order of vertices / faces (sequential would be order preserving). Edgebreaker may also remove degenerate faces or isolated vertices.
