### ISSUE TITLE
CMake Error at CMakeLists.txt:2 (project):   No CMAKE_CXX_COMPILER could be found.

### ISSUE THREAD

**Issue by channing1986** [google/draco#88]
Hi guys, 

I am new with CMake. I am working on Windows10 with VS 2015. I have download  CMake 3.8.0-rc4 and I am using the CMake GUI to generate the solution. But the error shows like this:
The C compiler identification is unknown
The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.  

Any idea? 

Thanks. 

Changlin

**Comment by tomfinegan** [comment]
Are you able to compile C++ source code using the VS 2015 IDE? That error is expected when you have no C++ compiler installed-- it means CMake can't find one.

**Comment by channing1986** [comment]
yeah, that's my fault. After installing C++ compiler, it works.

Thanks.

**Comment by Jumabek** [comment]
@tomfinegan , I successfully compile programs with VS 2015, but when using cmake the error still persists.

Do you have other suggestion?

**Comment by tomfinegan** [comment]
@Jumabek: Please open a new issue, and include the following:

1) Your CMake command line.
2) All of the CMake output.
3) The following files (might not exist, but if present):
CMakeFiles/CMakeOutput.log
CMakeFiles/CMakeError.log

Thanks!

**Comment by Abhi-1725** [comment]
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_C_COMPILER could be found.

I am using VS 15.4.3 community 2017
Cmake version : 3.10.0 RC3 
 c++ programs can compile

**Comment by Abhi-1725** [comment]
Also this is one of the error that i have received :

CMake Error: The source directory "C:/Users/ada24/source/repos/glfw-3.2.1/glfw-3.2.1" does not appear to contain CMakeLists.txt.

i would like to know whether  i am supposed to write the script to for  a new CMakeLists.txt  file  according to the particular  c++ program.

**Comment by tomfinegan** [comment]
@Abhi-1725:

Please open a new issue and include following so I can help you:

1.  Your CMake command line.
2. All of the CMake output.
3. The following files (might not exist, but if present):
    CMakeFiles/CMakeOutput.log
    CMakeFiles/CMakeError.log

I'm unfamiliar with glfw. It appears to include CMake support. The error you've pasted into your comment means exactly what it says. There is no CMakeLists.txt file in the directory from your comment. Given that you've listed glfw-3.2.1 twice in the path passed to CMake I would hazard a guess that the CMakeLists.txt file is one directory above.
