### ISSUE TITLE
bug? uint16 data might be encoded to 24bits

### ISSUE THREAD

**Issue by MovingZ** [google/draco#881]
When I close prediction, func EncodeValues in SequentialIntegerAttributeEncoder will go into func ConvertSignedIntsToSymbols.
Then ConvertSignedIntsToSymbols will turn uint16 value like  63990 to 127980.
Then the uint16 attr will be encoded in 24 bits

**Comment by ondys** [comment]
I'm not sure if I understand the question correctly. The conversion is applied to symbols that result from prediction scheme and it may be applied even when the prediction scheme is turned off but in either case the resulting symbols are encoded using entropy coding so the number of bits used for encoding each value depends on the overall frequencies of the input symbol. What is more important, after decoding the value is going to be stored in uint16 attribute again, that is not affected by the compressed bitstream.
