### ISSUE TITLE
obj reader gets stuck when file has no new line at the end of file

### ISSUE THREAD

**Issue by mlenta** [google/draco#90]
Hello! I like DRACO very much. Thanks for this great lib.

Recently, I am reading DRACO code to construct an object reader supporting generic attributes compression. I found that if  input obj file is not end with new line, "draco_encoder" will be pending. The input obj file would be like [test2.obj](https://raw.githubusercontent.com/mlenta/reality/master/assets/test2.obj).

From my perspective, it may arise from the `SkipLine()` function in `parser_utils.cc`.
This function is called by `ParseDefinition()`, which is in `obj_decoder.cc`,
and it won't stop at the last line of file since it cannot meet any '\n'.

I am not sure whether you just don't want to support obj file that has no new line at the end of file or it is really a bug.

**Comment by ondys** [comment]
@mlenta Thanks for the report. Sounds like a bug to me. I'll look into it

**Comment by ondys** [comment]
The fix for the issue was pushed to the master branch. Please let us know if you still encounter any problems.
