### ISSUE TITLE
BUILD_SHARED_LIBS=OFF with unity build, builds DLL not static lib

### ISSUE THREAD

**Issue by SoylentGraham** [google/draco#904]
Apologies as I am an amatuer when it comes to cmake;

I am trying to build static libs to integrate draco into a project with a single dll.
On windows (although when I come to mac, I assume this will be much the same) I explicitly use `-DBUILD_SHARED_LIBS=OFF` which builds a static `.lib` for windows, but continues to build a `dracodec_unity.dll` as well 
`cmake ../ -DBUILD_SHARED_LIBS=OFF -DDRACO_UNITY_PLUGIN=ON -DCMAKE_BUILD_TYPE=Release -A x64 -DCMAKE_CONFIGURATION_TYPES=Releases`

I corrected this by manually changing this (line)[https://github.com/google/draco/blob/master/CMakeLists.txt#L1012]
```
if(DRACO_UNITY_PLUGIN)
    if(IOS)
      set(unity_decoder_lib_type STATIC)
    else()
      set(unity_decoder_lib_type MODULE)
    endif()
```
to `set(unity_decoder_lib_type STATIC)`

This works fine, and I can link to `draco.lib` and `dracodec_unity.lib`, everything works.

But I don't know how to integrate this option PROPERLY via cmake;

This seems to work, but I don't know if it's the correct way? (and I'd imagine, maybe this isn't the ideal default...)
```
if(DRACO_UNITY_PLUGIN)
    if(IOS)
      set(unity_decoder_lib_type STATIC)
    else(BUILD_SHARED_LIBS)
      set(unity_decoder_lib_type MODULE)
    else
      set(unity_decoder_lib_type STATIC)
    endif()
```

**Comment by SoylentGraham** [comment]
Perhaps this should have been an amatuer pull release, rather than an issue? :)

**Comment by tomfinegan** [comment]
Can you provide some more detail on what you're attempting to do? The Unity plugin is strictly intended for use within Unity, and the build settings are configured with that intent in mind. A static library build for non-iOS targets has never made sense, and without some information about what you're trying to do (beyond a vague reference in https://github.com/google/draco/issues/901 to atteneder/DracoUnity having changed).

**Comment by SoylentGraham** [comment]
Yeah as per #901 I use the C-API provided by the unity module/design for easy integration into something else. (rather than c++)

And now I'm building all my external dependencies statically (including draco) so I only have to distribute one DLL/framework/dylib/so (for win/ios/mac/android)

> A static library build for non-iOS targets has never made sense
I assume you mean this specifically for unity, not as a general "static libraries make no sense" :)

If this is a wont-fix, fine, I'll find some other way, or switch to using c++ interfaces, the C api was just far quicker/simpler for an initial implementation.

**Comment by SoylentGraham** [comment]
Even if "xyz makes no sense/hasnt been done before" I was just expecting the parameters to do what they described, and just assumed the default would be the usual setup, and specific parameters to still be adhered to
