### ISSUE TITLE
Issue with adding new object to gltf_encoder.cc

### ISSUE THREAD

**Issue by Yejneshwar** [google/draco#906]
I don't know if I am missing something but...

Adding an object to the class in `gltf_decoder.cc` builds and works.
When I try and add a new object to the file `gltf_encoder.cc` and build, I get the error

`draco_transcoder_lib.obj : error LNK2019: unresolved external symbol "public: class draco::Status __cdecl draco::GltfEncoder::NewFunc<class draco::Scene const *>(class draco::Scene const * const &,class std::basic_ostream<char,struct std::char_traits<char> > const *)" (??$NewFunc@PEBVScene@draco@@@GltfEncoder@draco@@QEAA?AVStatus@1@AEBQEBVScene@1@PEBV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z) referenced in function "public: class draco::Status __cdecl draco::DracoTranscoder::TranscodeBuffer(class draco::DecoderBuffer const &,class std::basic_ostream<char,struct std::char_traits<char> > *)" (?TranscodeBuffer@DracoTranscoder@draco@@QEAA?AVStatus@2@AEBVDecoderBuffer@2@PEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)`

`35>C:\Users\redacted\Desktop\draco\draco\build\Release\draco_transcoder.exe : fatal error LNK1120: 1 unresolved externals`

Defining the object in the file `gltf_encoder.h` builds and works 

### Info :
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.32.31329.0
-- The CXX compiler identification is MSVC 19.32.31329.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Python39/python.exe (found version "3.9.2")
--- Running combined CXX flags test, flags: /w44018;/w44146;/w44244;/w44267;/w44804
--- Passed combined CXX flags test
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/redacted/Desktop/draco/draco/build

**Comment by FrankGalligan** [comment]
You got a good amount of C++ coding issues in your code. But the biggest things to get your code to compile are:

1. Add a return statement to NewFunc()
2. You are trying to call what would like a static function which you have not defined. Change "this->GltfEncoder::NewFunc(&geometry, out_buffer);" to "NewFunc(&geometry, out_buffer);"
3. You are not instantiating NewFunc(). Add this to the bottom of gltf_encoder.cc "template Status GltfEncoder::NewFunc<Scene>(const Scene &geometry, const std::ostream *out_buffer);"

This should get it to compile, but I think there are other issues such as const non-const variables, which I don't think it will work for whatever you are trying to do.

**Comment by Yejneshwar** [comment]
Thank You!

Yep there were stuff from other things I had tried, pretty new to C++ so I had no idea templates had to be explicitly instantiated for libs. I removed the definition in the header and everything now works.
