### ISSUE TITLE
no 'webidl_binder.py' in 'tools' folder

### ISSUE THREAD

**Issue by ghorte** [google/draco#91]
Hello!
I am going to rebuild JavaScript Decoder. But there is no file called 'webidl_binder.py', which is specified in 'Makefile.emcc'. How should I get this file?

**Comment by ondys** [comment]
This would indicate that you either do not have emscripten sdk installed, or the path to emscripten sdk is not in your environment variables. `webidl_binder.py` is located within emscripten folder, we do not include it.

**Comment by mlenta** [comment]
Thank you~

**Comment by FrankGalligan** [comment]
I'm closing this issue. If you are still having problems please re-open.
