### ISSUE TITLE
open3d compatibility for mesh compression 

### ISSUE THREAD

**Issue by mdasari823** [google/draco#911]
Hi, I am trying to compress a mesh model created using open3d. I see the open3d mesh is not directly compatible with draco expected format. Did anyone try this already? 

There is an issue on Open3d repo here: https://github.com/isl-org/Open3D/issues/844, but it seems it is not complete.

**Comment by tomfinegan** [comment]
Draco requires PLY position data to be of type int32 or float32 as noted in the comments within the linked issue. There has been no change to Draco's PLY importer. In addition, normals are restricted to float32 and RGBA values are restricted to uint8.
