### ISSUE TITLE
missing  draco/compression/attributes/attributes_decoder_interface.h"file in build

### ISSUE THREAD

**Issue by Irvenae** [google/draco#912]
bazel-out/k8-fastbuild/bin/external/draco/draco/include/draco/compression/point_cloud/point_cloud_decoder.h:18:10: fatal error: draco/compression/attributes/attributes_decoder_interface.h: No such file or directory
   18 | #include "draco/compression/attributes/attributes_decoder_interface.h"

When adding 

"${draco_src_root}/compression/attributes/attributes_decoder_interface.h"

at L104 of CMakeLists.txt the build seems to work.

**Comment by tomfinegan** [comment]
Thanks for the report. You may actually be the first to attempt building Draco with Bazel.

**Comment by tomfinegan** [comment]
@Irvenae How are you setting up your Bazel build of Draco? I'm not familiar with setting up a Bazel build that runs a CMake build (or uses it for input), but I can put coverage in place if the setup isn't too complicated.

**Comment by Irvenae** [comment]
In the workspace file (of the bazel project) you download draco with an http_archive rule e.g.

http_archive(
        name = "draco",
        build_file = "//build_tools:draco.BUILD.bazel",
        sha256 = "7882a942a1da14a9ae9d557b1a3af7f44bdee7f5d42b745c4e474fb8b28d4e5e",
        strip_prefix = "draco-1.5.3",
        url = "https://github.com/google/draco/archive/1.5.3.tar.gz",
    )

as you can see you use the build_file argument to pass how it should be built.
That draco.BUILD.bazel file contains in our case

load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")
filegroup(
    name = "all_srcs",
    srcs = glob([
        "cmake/*",
        "src/**",
        "CMakeLists.txt",
    ]),
)
cmake(
    name = "draco",
    lib_source = ":all_srcs",
    generate_args = ["-GNinja"], // Probably not necessary in your case.
    cache_entries = {
        "CMAKE_BUILD_TYPE": "Release",
        "BUILD_SHARED_LIBS": "OFF",
    },
    copts = ["-fPIC"],
    out_static_libs = [
        "libdraco.a",
    ],
    target_compatible_with = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],
)
