### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by keainala** [google/draco#917]
/gltf2obj/gltf2obj-main/draco/src/draco/core/status_or.h:38:51: error: call to deleted constructor of 'std::unique_ptr<draco::Mesh, std::default_delete<draco::Mesh> >'
  StatusOr(const T &value) : status_(OkStatus()), value_(value) {}
/gcc/x86_64-redhat-linux/7.5.0/../../../../include/c++/7.5.0/bits/unique_ptr.h:383:7: note: function has been explicitly marked deleted here
      unique_ptr(const unique_ptr&) = delete;

**Comment by tomfinegan** [comment]
Please attach all the build output and your full configuration command.

**Comment by tomfinegan** [comment]
Closed due to lack of response. Please feel free to respond with the requested information, and I will reopen the issue.

**Comment by keainala** [comment]
i find the error
