### ISSUE TITLE
Options::Options() constructor is defined without a matching destructor

### ISSUE THREAD

**Issue by SergeyKorytnik** [google/draco#919]
At https://github.com/google/draco/blob/c0b57c1b6ec365a5e97f765deacb6b45ead104a3/src/draco/core/options.cc#L23
You can see the Options::Options() constructor is instantiated. As soon as constructor is here it would be great to instantiate the destructor as well. Just add 
```cpp
Options::~Options();
```
and the destructor declaration.

For example, It would help when DLL and application using it are compiled with different  Microsoft STL versions (slightly different debug iterators).  In other words the minor change will made a Draco dll more binary compatible.

**Comment by tomfinegan** [comment]
This will be fixed in the next release, which does not yet have a planned date. It has been fixed by removing the empty constructor, and then explicitly defaulting the Options constructor and destructor.

**Comment by SergeyKorytnik** [comment]
Defaulting constructor and destructor is great! Just do it in the options.cc and not in a header file!

**Comment by tomfinegan** [comment]
It's in the header file, as required. Besides that, how would one "= default" a constructor in a .cc file? How would that be useful to other modules that cannot see the definition?

Anyway, I think I'm misunderstanding the issue here. Defaulting a constructor outside the class declaration is an error, per clang:

> Out-of-line definition of 'Test' does not match any declaration in 'test::Test'clang(member_decl_does_not_match)

The internal version of Options now looks like this:

class Options {
  Options() = default;
  ~Options() = default;
...
};

**Comment by SergeyKorytnik** [comment]
See the fifth variant of default constructing at https://en.cppreference.com/w/cpp/language/default_constructor#:~:text=A%20default%20constructor%20is%20a,public%20default%20constructor%20is%20DefaultConstructible.
In header file
```cpp
class Options {
 public:
  Options();
  ~Options();
...
};
```
in options.cc:
```cpp
Options::Options()=default;
Options::~Options()=default;
```
It guarantees that both constructor and destructor are created at the library compile time. 
In turn it means better binary compatibility of the public API across different compiler versions/settings.

**Comment by tomfinegan** [comment]
I was not aware of the 5th form: thanks for that.

I need some more information on why this is necessary. Defaulting ctors/dtors with the common syntax is a very widely used pattern, and is used in multiple places within Draco.

What situation is this addressing? 

> In turn it means better binary compatibility of the public API across different compiler versions/settings.

Is there any information supporting this statement?

**Comment by SergeyKorytnik** [comment]
The Options problem happened because constructor and destructor were generated by different compiler versions with slightly different STL (Microsoft debug iterators).
Constructors/destructors dealing with STL objects (std::map in the Options class) are quite vulnerable to such discrepancies in build environments.

The situation is not a reason to make so many changes in multiple files. It's more like my own fault (not recompiling libraries when migrating to a new compiler/STL).
Sorry for spending your time.

P.S.:
I still think that for non trivial classes that contain STL members (exposed in a public API) it may have sense to define all constructors and destructors in c* files rather than in headers. If possible
