### ISSUE TITLE
How to use transcoder for .drc files

### ISSUE THREAD

**Issue by FarzanehGJ** [google/draco#926]
Hi,
I am working on streaming holograms. I want to encode, then transcode and finally decode files with draco.
I could successfully encode .ply file to .drc file and vise versa (decode .drc to .ply).
But midwhile I would like a transcoding as well. As I understood from the documentation the transcoder just support .glb and .gltf files. 
I was wondering how I can transcode .drc files as I got from encoder output and need for decoder input. 
Do I need to convert .drc to .glb before transcodding? Or there is any way that draco do it automaticaly?

encoder output (.drc) ----> Transcoder ----> decoder input (.drc)

**Comment by tomfinegan** [comment]
I'm not sure I understand this question.

> encoder output (.drc) ----> Transcoder ----> decoder input (.drc)

What is the transcoder step intended to achieve in this sequence?
