### ISSUE TITLE
New version released (0.10.0)

### ISSUE THREAD

**Issue by ondys** [google/draco#93]
We have just pushed a new version to the master branch. This release brings improved mesh compression and faster decoding in browser:

- On average 10% better compression of triangular meshes (up to 20% for purely spatial meshes without any extra attributes).
- Up to 2X faster decoding in browsers with our newly provided WebAssembly decoder.
  - Supported in most modern browsers including Chrome, Firefox, and Edge.
  - Decoder size is about 50% smaller compared to the javascript version.
- New version is backward compatible with 0.9.x encoders.
- Note that 0.10.0 is not forward compatible. I.e., files encoded with 0.10.0 cannot be decoded with 0.9.x decoders.

The previous version is still available in a newly created branch 0.9.1

Please let us know if you find any problems or bugs. Thanks!

**Comment by KindDragon** [comment]
Please set git tag(!) for 0.10.0 and better add this description directly to release https://github.com/google/draco/releases

Thank you
