### ISSUE TITLE
Is there any plan to support compressing for morph targets?

### ISSUE THREAD

**Issue by daemyung** [google/draco#930]
Currently I want to use draco to compress my model file. It looks like that draco doesn't support morph targets. Could you let me know the plan? Or it's out of spec on draco?

**Comment by ondys** [comment]
Not in the short term unless there is a sufficient demand from the community. Also note that morph targets are not covered in the KHR_draco_mesh_compression glTF extension and this morph targets compression would most likely require a new extension that would then have to be implemented by viewers such as three.js, etc.

**Comment by daemyung** [comment]
Thanks for your explanation. I hope draco supports morph target compression soon.
