### ISSUE TITLE
WebAssembly build and sample application in the roadmap?

### ISSUE THREAD

**Issue by j7th** [google/draco#94]
Hi, WebAssembly build and sample application in the roadmap?

**Comment by ondys** [comment]
We have just released version 0.10.0 that includes WebAssembly (see [release notes](https://github.com/google/draco/issues/93)) + a sample loader for THREE.js that uses it (see [here](https://github.com/google/draco/blob/master/javascript/example/webgl_loader_draco.html))

**Comment by j7th** [comment]
cool, thx!
