### ISSUE TITLE
JS Decoder API questions

### ISSUE THREAD

**Issue by yeliang0510** [google/draco#946]
I want to decompress and read the data through javascript

After decoder through javascript, I get a decoderModule.Mesh(). How can I read the points and face index

**Comment by tomfinegan** [comment]
I'm not really sure what you're attempting to do. You can walk the faces of a mesh using GetFaceFromMesh() on the decoder interface, and you can get the number of faces using the the num_faces accessor on the Mesh. 

The decoder interface is here:
https://github.com/google/draco/blob/master/src/draco/javascript/emscripten/decoder_webidl_wrapper.h

If you need further assistance please elaborate on what you're trying to do, and where things are going wrong.

**Comment by yeliang0510** [comment]
I have found a solution. I want to read the position and uv. I found the DracoLoader of Three.js and found that data can be read through GetAttributeDataArrayForAllPoints
