### ISSUE TITLE
point_cloud_decoder.h is part of DRACO_COMPRESSION_POINT_CLOUD and should not

### ISSUE THREAD

**Issue by mwestphal** [google/draco#956]
It looks like `point_cloud_decoder.h` is part of the DRACO_COMPRESSION_POINT_CLOUD, making the cmake options `DRACO_POINT_CLOUD_COMPRESSION` a must turn-on option. This looksn unexpected.

**Comment by tomfinegan** [comment]
`PointCloudDecoder` is used as a base class. This is noted in the source code:

From https://github.com/google/draco/blob/master/src/draco/compression/point_cloud/point_cloud_decoder.h#L26:

```
// Abstract base class for all point cloud and mesh decoders.
```

`DRACO_COMPRESSION_POINT_CLOUD` does not guard usage of the base class. It guards usage of PointCloudSequentialDecoder and PointCloudKdTreeDecoder. You can see this in the code: the CMake flag controls the definition of `DRACO_POINT_CLOUD_COMPRESSION_SUPPORTED` in the generated header `draco_features.h`.

I don't think there's any action needed here.
