### ISSUE TITLE
Build js decoder error "/usr/bin/env: python2: No such file or directory"

### ISSUE THREAD

**Issue by Ben-Mack** [google/draco#98]
Thanks for this fantastic project!

I cannot build the javascript decoder. Command `make -f Makefile.emcc` give this error:

> /usr/bin/env: python2: No such file or directory
make: *** [obj/javascript/emscripten/draco_glue_wrapper.o] Error 127

No file is edited yet, I'm just run that command right after downloaded this project. I'm using Win10 64bit, Emscripten 1.35.0, Python 2.7.5 (come with emscripten), `make` from `MinGW\msys\1.0\bin`

This is full report:

>K:\draco-master>set EMSCRIPTEN="C:\Program Files\Emscripten\emscripten\1.35.0" 
K:\draco-master>make -f Makefile.emcc
python "C:\Program Files\Emscripten\emscripten\1.35.0"/tools/webidl_binder.py javascript/emscripten/draco_web.idl glue
em++ -MMD -MP -DDRACO_MESH_COMPRESSION_SUPPORTED -DDRACO_STANDARD_EDGEBREAKER_SUPPORTED -DDRACO_PREDICTIVE_EDGEBREAKER_SUPPORTED -DDRACO_POINT_CLOUD_COMPRESSION_SUPPORTED -I../../ -I./ -std=c++11 -O3 -s NO_FILESYSTEM=1 -s ELIMINATE_DUPLICATE_FUNCTIONS=1 -s EXPORTED_RUNTIME_METHODS=[] -s PRECISE_F32=1 -s ALLOW_MEMORY_GROWTH=1 -s MODULARIZE=1 -s EXPORT_NAME="'DracoModule'" --memory-init-file 0 -Wno-sign-compare -fno-omit-frame-pointer javascript/emscripten/draco_glue_wrapper.cc -o obj/javascript/emscripten/draco_glue_wrapper.o
/usr/bin/env: python2: No such file or directory
make: *** [obj/javascript/emscripten/draco_glue_wrapper.o] Error 127

Does that mean I have to build Draco on Linux?

(This is the first time I build project with make, cMake so apologize for any noob question)

**Comment by ondys** [comment]
Thanks for the report. We will double check the windows workflow for Javascript decoders. From the log, it looks like python2 was not found. 

Note that all javascripts decoders are already provided in the `javascript/` folder so there is no need to build them yourself unless you made some changes to the source code.

**Comment by FrankGalligan** [comment]
I'm closing this issue. If you are still having problems please re-open.
