### ISSUE TITLE
WASM decoder module question

### ISSUE THREAD

**Issue by APIWT** [google/draco#984]
Hello!

I am attempting to use the WASM module to decode an OBJ file and encode it to a Draco mesh. Is this possible?

Currently, if I attempt to use the Decoder on a buffer that is an `.obj` file, it throws:
`Not a Draco file.`

I know with the command line utility I can pass `-i` with an `.obj` file, so I'm probably missing something obvious!

Thanks

**Comment by ondys** [comment]
WASM decoder is used only to decode draco files into a mesh / point cloud. We do not provide direct support for encoding obj to drc using JS/WASM but you may want to check our draco_encoder.wasm that can be used to encode any mesh into a draco file format. You would still have to load the obj and convert it into a draco mesh format though.
